### ISSUE TITLE
Добавить Бузард CAS для перевооружения

### ISSUE THREAD

**Issue by malashin** [ToxaBes/ADR-Spec-Ops#100]

**Comment by Noart537** [comment]
А его нет в наградной, его никак же не добыть обычным способом. Если только в награду добавлять.

**Comment by malashin** [comment]
Надо проверить есть ли у него для бомбометания камера при смене вооружения. У AA её нет.

**Comment by Noart537** [comment]
Там вроде специальной камеры нет для бомбометания, там появляется белый круг на илс-е.

**Comment by ToxaBes** [comment]
так нужно ставить CAS или нет?

**Comment by 12st** [comment]
Суть в том, что не появляется крестик куда должна упасть бомба(AA версия). Надо проверить будет ли он появляется если заменить на CAS и попробовать сменить вооружение.

**Comment by ToxaBes** [comment]
А зевсом не попробовать?

**Comment by ToxaBes** [comment]
Если есть возможность, выясните это сегодня, чтобы я успел применить.

**Comment by 12st** [comment]
CAS нельзя перевооружать, собственно по этому поводу и тикет

**Comment by malashin** [comment]
Сейчас проверяю. У меня и у CAS и у AA есть крестик куда упадет бомба.
