### ISSUE TITLE
Наградная техника на Tanoa

### ISSUE THREAD

**Issue by 12st** [ToxaBes/ADR-Spec-Ops#103]
Ввиду того, что на этом острове абсолютно другой рельеф предлагаю обсудить какие виды техники должны быть в наградной.

- Все танки станут менее эффективными поэтому они будут пылится на базе. Возможно стоит снизить шанс их выпадения

- Артиллерия и РСЗО также станут менее эффективными ввиду наличия большого количества гор, да и мало кто станет стрелять с неё прям с базы, также уменьшить шанс выпадения.

- С зенитками ситуация останется не изменой ввиду большой дальности действия. Воздух видно издалека, поэтому их наверно не стоит трогать.

- Так как бмп можно будет перевозить по воздуху, а также наличием множества островов до которых на танках не добраться, можно добавить усиленные версии камыша, маршала и моры.

- По той же причине можно добавить усиленные версии MRAP при этом уменьшить их количество на базе по умолчанию и заменить на вот эти(при условии, что они будут доступны всем, а не только обладателям DLC).
![ss_7763e9290a30a0a48af64d10e0b745cc31d48f24 1920x1080](https://cloud.githubusercontent.com/assets/18305023/15931070/b53afd8e-2e5e-11e6-9276-13e86a677883.jpg)

- На карте много воды и большинство островов можно расстреливать с катеров, поэтому стоит добавить усиленную версию штурмового катера.

- С выходом Apex станут доступны 2 вида БПА
Первый стоит добавить как наградную за допки, второй вроде как является облегчённой версией K-40 абабиль(CSAT) и возможно он вообще не нужен.
MQ-12 Falcon Drone
![ss_511401e11527c4df87d2809bdd2ab50f50199bed 1920x1080](https://cloud.githubusercontent.com/assets/18305023/15930953/22905e3e-2e5e-11e6-9450-169d0c9f921d.jpg)
KH-3A Fenghuang Drone
![ss_d426e4268b4e85c38f3d8b9673c388c99c5d76ab 1920x1080](https://cloud.githubusercontent.com/assets/18305023/15930968/351f477c-2e5e-11e6-9724-3ccfd2427948.jpg)

-  Станет доступен и вот этот вид техники.
V-44 X Blackfish
![ss_258630fabefc61b4645fa670f173376c9c7a5693 1920x1080](https://cloud.githubusercontent.com/assets/18305023/15931239/8af95038-2e5f-11e6-8d99-cfe7eb3bca98.jpg)
Y-32 Xi’an VTOL
![ss_05531cda09f9113d5a3afbbc88b0b69447557ac4 1920x1080](https://cloud.githubusercontent.com/assets/18305023/15931227/7cec9a4a-2e5f-11e6-9e79-53eb4e754a74.jpg)
Что с ними делать не очень понятно, с одной стороны они будут необходимы для переброски техники,а с другой у них намечается серьёзное вооружение
![toolwiz20166-9-16-32-51](https://cloud.githubusercontent.com/assets/18305023/15931307/dadd8ee8-2e5f-11e6-962f-18fc83cfe9d6.png)
И в таком случае они будут эквивалентны штурмовым вертолётам. Если на алтисе их бросать только в наградную, то на Tanoa вопрос об их вводе по умолчанию остаётся открытым

**Comment by malashin** [comment]
Сам остров доступен только обладателям экспаншена. Поэтому вопроса о его наличии у игрока нет.

VTOL самолеты имеют несколько типов. У НАТОвского будет три типа, гурзовой для техники, транспортный для пехоты, боевой с вооружением. Боевые могут быть наградными, транспортные можно ставить на базу.

**Comment by 12st** [comment]
@malashin Разве остров не будет доступен для всех?

**Comment by Horizon1959** [comment]
OMFG, беспилотная ударная вертушка, орудия AC-130 на оспрее, мутант МИ-24! 
![shut-up-and-take-my-money](https://cloud.githubusercontent.com/assets/17685328/15932081/f425fbbc-2e62-11e6-94d3-a7d2da611685.jpg)

**Comment by malashin** [comment]
https://arma3.com/apex

Все что указано на странице до пункта:

> PLATFORM UPDATES
> The Arma 3 Apex expansion is supported by major platform updates, 
> featuring a wide variety of new content, features, and enhancements.
> These platform updates also apply to the base game and are free for all owners of Arma 3.

Платное.

**Comment by ToxaBes** [comment]
Ну ничего, будем чередовать миссии Altis/Tanoa по четным/нечетным дням.

**Comment by kovt** [comment]
12-ый, ну зачем ты эти фотки выложил...? )) До этого совсем не хотел покупать ДЛС, теперь слюнки так потекли что уже сейчас хочу...))

**Comment by malashin** [comment]
У них одна из фишек бесплатных
Vehicle-in-Vehicle Transport – transport suitable vehicles across large distances inside larger vehicles

То есть перевозка техники в другой технике. Уже понятно, что VTOL есть грузовой. Интересно, что еще будет.

Странно, что не сделали больших лодок для перевозки техники.

**Comment by 12st** [comment]
Да тоже читал, но я не представляю как они это сделать собираются. Кроме хурона по сути никто и не может внутри себя технику перевозить

**Comment by malashin** [comment]
На Таноа добавил следующие награды.

```sqf
	["MQ-12 Falcon", "B_T_UAV_03_F"],
	["KH-3A Fenghuang", "O_T_UAV_04_CAS_F"],
	["V-44 X Blackfish", "B_T_VTOL_01_armed_F"],
	["Qilin", "O_T_LSV_02_armed_F"],
	["Y-32 Xi'an", "O_T_VTOL_02_vehicle_F"]
```

Все внедорожники, кроме варианта CSAT есть на базе. Blackfish на базе есть для перевозки техники. Пехотный я не ставил. Xian наградной тоже для техники.
