### ISSUE TITLE
Баг с БПЛА

### ISSUE THREAD

**Issue by kovt** [ToxaBes/ADR-Spec-Ops#104]
Нашел микро баг с БПА. Если у игрока терминал подключён к любому беспилотнику ,при этом сам игрок им не управляет, а просто бегает пехотинцем, то он не может взаимодействовать с VAS и арсеналом пока не отключит терминал от БПА. Жить конечно не мешает, но всё таки баг. ))

**Comment by Horizon1959** [comment]
Это не баг, а фича. защита от любителей затарится в арсенале на расстоянии. Отключайся от БПА перед работой с арсеналом.

**Comment by kovt** [comment]
Защита должна быть когда игрок подгоняет БПА и пытается через него затариться, а не когда он просто бегает. Ну в общем фича так фича.

**Comment by malashin** [comment]
Есть идея как это исправить. Задача не приоритетная.

**Comment by Horizon1959** [comment]
@malashin если поправите, то будет хорошо, пока можно пожить с такими неудобствами.

**Comment by kovt** [comment]
Да на самом деле неудобства собственно нет Всё равно если не отключиться от БПА и если тебя грохнут, то БПА заглючит. Так что для себя я уже давно выработал привычку сразу отключаться. Но поправить со временем надо.

**Comment by malashin** [comment]
Баг исправил. Нужно еще добавить в список БПА новые из Апекса.
