### ISSUE TITLE
Сервис техники

### ISSUE THREAD

**Issue by kovt** [ToxaBes/ADR-Spec-Ops#105]
Предлагаю добавить один сервис техники в районе Пароса. Объясню зачем, когда основа или допка ресается в районе Софии, сервис в радиусе 2-ух км отключается. И получается что ближайший это или база или в самом анусе южной части острова, т.е. около 15 км.....

И ещё баг с сервисом. Вчера была миссия Прерванный полёт. Появилась как раз около Софии. Сервис отключился, но на карте он всё равно был жёлтым, типо рабочим. Тем не менее когда я на него заехал на Страйдере, появилась надпись что то вроде "данный сервис предназначен только для наземной техники" и Страйдер не починился.Смущает не то что не было ремонта, а сама надпись... ))

**Comment by malashin** [comment]
Сервисы отключаться должны только при действующей основе. Допки ничего не отключают.

**Comment by 12st** [comment]
Ещ

**Comment by 12st** [comment]
Ещё несколько замечаний по поводу сервиса.

- Если поставить технику заряжаться и выйти со слота скрипт до конца не доработает и останется техника без топлива.

- Если отключится от БПА вовремя его заправки скрипт также не доработает.

- Были жалобы, что если в машине больше 2 человек с возможностью стрелять, то скрит не заряжает полностью(приходится перезаряжать 2-3 раза)

**Comment by kovt** [comment]
С БПА такого бага нет, я тебя 12-ый ввел в заблуждение. Вчера специально проверил, загнал на сервис, отключился, всё ОК.

**Comment by malashin** [comment]
На счет _"Этот сервис только для наземной техники"_, этой проблемы быть не должно. Если такая строка появилась то, либо это была не наземная техника, либо БПА.

На счет того, что @12st писал. Из техники можно выйти и все будет ок. Проблема скорее всего в локальности скрипта. Т.к. всё происходит на клиенте водителя, при наличии других игроков в технике для них перезарядка не происходит, хотя там вся машина перезаряжается. Если водитель вышел, то другие игроки мешают процессу скрипта, у них скорее всего приоритет на эту технику.

Нужно протестировать. Сейчас выход это запускать скрипт у всех игроков в данной технике.

**Comment by 12st** [comment]
Там суть такая, что если на сервис заезжают водитель и стрелок и есть какое нибудь 3 место вроде командира(пассажирки не влияют), то их БК уже не пополняет, причём и стрелка и командира.
