### ISSUE TITLE
Предложение: спецназ Viper на спецоперациях

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#106]
Предлагаю ввести на спецоперациях спецназ CSAT - отряды Viper, они выходят в Apex DLC. Они отлично вписываются в концепцию задач, не светятся в тепловизоре и обладают крутыми плюшками.

**Comment by malashin** [comment]
У них еще мега броня )

Если на их шмотки одеть крутой бронежилет, то реально терминатором становишься.

Я сейчас все задания портирую на новый остров. После того, как всё работать будет, буду новых юнитов ставить.

**Comment by Horizon1959** [comment]
Спецоперации имеют концепцию особо важных заданий, соответственно охрана у них должна быть на уровне. Можно попробовать малое количество отрядов заделать на основы.

**Comment by ToxaBes** [comment]
Хорошая идея,  можно на Таноа в спецоперациях заменить часть ботов на спецназ, а на основе высаживать спецназ при обороне.

**Comment by Horizon1959** [comment]
При обороне это будет слишком жестоко. Лучше пихать пару отрядов на основу и заменять ими ботов на спецоперациях.

**Comment by ToxaBes** [comment]
Оборона должна быть жестокой -  противник в попытке отбить позиции бросает в бой свои лучшие подразделения. На захвате основы они не нужны,  т. к. там есть свежие и уверенные в себе регулярные войска.

**Comment by Horizon1959** [comment]
@ToxaBes ну ок, будет круто.

**Comment by malashin** [comment]
Я пока их не добавлял на тестовый сервер. После портирования, нужно будет их отдельной группой посылать, а не просто ставить в пул возможных противников.

**Comment by malashin** [comment]
#115
