### ISSUE TITLE
Баг: вражеские элементы одежды на игроках

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#107]
Заметил сегодня игроков с рюкзаками hex и в шлемах CSAT.

**Comment by malashin** [comment]
Они не указаны в черном списке VAS. Можно от туда загружать сохранные профили, даже когда этих вещей нет в белом списке.

**Comment by Horizon1959** [comment]
@malashin т.к. отключены шестиугольники, то отличаем своих по форме. Если человек одет в форму и снаряжение противника, то может возникнуть неприятная ситуация, надо фиксить.

А есть ли другой скрипт на пополнение боеприпасов? VAS давно устарел и заглючил, но нам всё ещё нужно грузить ракеты, рюкзаки, беспилотники, боеприпасы и т.п.

**Comment by malashin** [comment]
Да это понятно, что это косяк. Я указал, где проблема кроется скорее всего. Сейчас не могу пофиксить, нужно классы одежды все собрать, чтобы их запретить.

Чтобы самому не забыть или другому кому исправить пишу сразу.

**Comment by Horizon1959** [comment]
@malashin ты меня не так понял. Я уточняю почему это плохо. Не горит особо в принципе.

**Comment by malashin** [comment]
Да тут и дураку понятно, что плохо ;)

**Comment by malashin** [comment]
На Таноа запретил. На Алтисе позже. Боюсь, вдруг, проблемы возникнут с новыми шмотками.

Нужно еще будет запретить партизанскую одежду и одежду синдиката.

**Comment by Horizon1959** [comment]
Оставьте одежду для наёмников, как у @12st.

**Comment by malashin** [comment]
В дальнейшем появятся партизаны, эта одежда будет у них.

**Comment by Horizon1959** [comment]
@malashin логично. Главное чтобы форма CSAT и AAF не была доступна.

**Comment by ToxaBes** [comment]
Да,  одежду партизан/синдиката уже можно запрещать для синих в рамках #RoadToПартизаны.

**Comment by malashin** [comment]
Нужно еще убрать их с допок.

**Comment by Horizon1959** [comment]
@malashin убрать бомжей с допок? Может быть просто определить их как батальоны нацистов, помогающих AAF?

**Comment by malashin** [comment]
Как партизаны будут своих от чужих отличать?

**Comment by Horizon1959** [comment]
@malashin хм, и то верно.

**Comment by ToxaBes** [comment]
С допок партизан убирать не надо,  это часть местных, которая продалась CSAT за пайку. Это добавит веселья синим - попытаться понять бот это иди игрок (длч опытных игроков труда не составит).

**Comment by Horizon1959** [comment]
@ToxaBes ну я и говорю - банды нацистов под видом добровольческих объединений.

**Comment by ToxaBes** [comment]
Причем тут нацизм? Это вообще из другой оперы. Часть ботов пошла туда из-за того что есть нечего,  часть - просто отбросы которым пофиг под каким флагом мародерить (наемники). У нас виртуальное будущее, 2035 год,  государства фактически трансформировались в корпорации,  война как способ ведения бизнеса,  вот это вот все.

**Comment by Horizon1959** [comment]
Ну я на канон ориентируюсь, там всё по сценарию с бандитами, партизанами, продавшейся власти, корумпированными войсками и двумя сильными политическими блоками.

**Comment by ToxaBes** [comment]
мы с тобой говорим об одном и том же разными словами.

**Comment by Horizon1959** [comment]
@ToxaBes ладно, всё ок:) Но мне кажется, что бомжей надо оставить, разнообразие всё-таки.

**Comment by Horizon1959** [comment]
Сейчас можно сохранить пресет с Таноа в ящик и загружаться на Алтисе. В виртуальном арсенале все новые вещи и оружие недоступны.

**Comment by ToxaBes** [comment]
Новые шмотки еще не прописывали.

**Comment by ToxaBes** [comment]
Баг пофикисл. Арсенал будем прописывать позже вместе с таблицей разрешенного оружия.

**Comment by Horizon1959** [comment]
И пофиксите уже хитрецов, которые загружают старые добрые РПС LBV от CSAT. Вчера меня спрашивали, кого считать противником и пришлось говорить, что противник одет не по форме NATO/CTRG.
Ещё вчера в ящике тыкал боеприпасы и там в списке появлялись SPAR16 и прочие ништяки из DLC Apex.
Кстати, сейчас арсенал стал открываться очень быстро, даже с моим мега-комплектом пресетов на каждый класс, сторону и карту. Может выпилите ящик к чертям собачьим?

**Comment by malashin** [comment]
Единственая причина почему VAS (Снаряжение) всё еще используется это то, что в нём можно взять вещи которые Арсенал не дает взять без определенной одетой вещи. Например чтобы загрузить машину ракетами для Титана из Арсенала, нужно быть ПТшником с Титаном.

Косяки вчерашние из-за того, что Тоха настройки VAS скопировал с Tanoa миссии. Это косяк.

**Comment by Horizon1959** [comment]
По сути нам надо загружать боеприпасы из ящика: ракеты и патроны. Может есть какой костыль типа скрипта, чтобы в ящике генерировались нужные предметы?
