### ISSUE TITLE
Переделать скрипт перепаковки магазинов

### ISSUE THREAD

**Issue by malashin** [ToxaBes/ADR-Spec-Ops#108]
Недавно убрал из скрипта анимацию, т.к. её не по назначению использовали. Сейчас мгновенно перепаковываются магазины. Нужно сделать задержу, если анимацию ставить, то продумать её ограничение.

**Comment by kovt** [comment]
Играл последние несколько дней любительскую миссию Побег с Таноа. Там есть скрипт перепаковки. Не много заморочный, но если привыкнуть то норм. При нажатии ctrl+R открывается окошко, и там перепаковываешь. Причём руками, а не как у нас было, тыкнул меню и всё само перепаковалось. Качни миссию, глянь, может и нам такой вариант подойдёт.

**Comment by Horizon1959** [comment]
Да, скрипт надо переделывать. Или делать анимацию как с починкой/лечением и добавлять полоску на экран или как предлагает @kovt .
Сейчас я вообще перезаряжаюсь как в бвтлфилде, абсолютно не следя за БК.

**Comment by malashin** [comment]
Переделал скрипт.

Процесс перепаковки теперь занимает время. Один переложенный патрон из одного магазина в другой 1 секунда (привет пулеметчикам). Когда таймер завершается (есть прогресс бар), обновляется инвентарь и две обоймы объединяются. Дальше процесс повторяется, пока все обоймы будут не перепакованы. Если начать двигаться в процессе, процесс прерывается, даже если поворачиваться на месте, можно только головой вертеть. Все уже перепакованные обоймы останутся, те что в данные момент перепаковывались останутся не перепаковыными, отдельно патроны не считаются в процессе.

Как вариант, можно еще увеличить время, чтобы во время боя никто не пытался этим страдать.

Во время перетаскивания раненных вызов скрипта отключен. Даже если скрипт сработает, то вернет в предыдущую анимацию передвижения раком после прерывания скрипта.

**Comment by malashin** [comment]
Исправил косяки, время в два раза увеличил. Две секунды на один патрон.

**Comment by Horizon1959** [comment]
Может быть я и докопался, но:

![photo_2016-06-22_23-28-19](https://cloud.githubusercontent.com/assets/17685328/16361084/81feb5e8-3b8b-11e6-8777-be47de2ae81c.jpg)

А вообще большое спасибо за переделку, этот скрипт был хуже любого чита или tactical hud.

**Comment by malashin** [comment]
Поставил этот скрипт
http://www.armaholic.com/page.php?id=19692

Старый убрал.

**Comment by Horizon1959** [comment]
@malashin на основной или в тестовый?

**Comment by malashin** [comment]
Везде. Основной обновится после возвращения @ToxaBes.

**Comment by Horizon1959** [comment]
@malashin 
![default](https://cloud.githubusercontent.com/assets/17685328/16520808/540d8862-3f9b-11e6-9729-349bc705d69b.jpg)

**Comment by malashin** [comment]
Нужно добавить вызов через экшнменю.

**Comment by Horizon1959** [comment]
@malashin хоткеи только оставьте.

**Comment by ToxaBes** [comment]
Скрипт не работает через Ctrl+R. Также нет экшна в меню. Этот скрипт тестировался в миссии?

**Comment by ToxaBes** [comment]
Исправил.
