### ISSUE TITLE
Изменение спецоперации "Желтый Туман"

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#11]
- [x] Добавить разрушаемость стен с помощью подрывных зарядов/сву.
- [x] Добавить стомпер с AT/AA titan внутри зоны спецоперации при успешном выполнении задания (вероятность 50%).

**Comment by 12st** [comment]
Появилась эта спец операция. 
1)2 подразделения появилось почти в упор к базе и побежали расстреливать игроков на базе.
2)Также если их убивать с техники аид наказывает, хотя до допки около 6 км. Один патруль появился примерно в 3 км и несколько игроков на них напоролись за что были наказаны аидом.
3)Зелёные стены требуют 3 подрывных пакета, что слишком много, никто столько не носит, однако падают с 2 пт ракет аламута

**Comment by ToxaBes** [comment]
>2 подразделения появилось почти в упор к базе и побежали расстреливать игроков на базе.

Арма чудит со спавном. Проверил код - нечего исправлять.

>Также если их убивать с техники аид наказывает, хотя до допки около 6 км. Один патруль появился примерно в 3 км и несколько игроков на них напоролись за что были наказаны аидом.

Исправил, теперь Аид будет наказывать если бот убит из технике в самой зоне. Если бот убит вне зоны - его проблемы, нефиг шастать

>Зелёные стены требуют 3 подрывных пакета, что слишком много, никто столько не носит, однако падают с 2 пт ракет аламута

Это стандартное поведение этих стен, им не менялся уровень урона. Попробуй использовать большое СВУ городского типа. Вообще, это хорошо что на стену надо 3 заряда - в этом случае вариант с десантом по-прежнему остается актуальным.
