### ISSUE TITLE
Сделать чтобы беруши выключались при выходе из техники

### ISSUE THREAD

**Issue by malashin** [ToxaBes/ADR-Spec-Ops#110]
+ Добавить беруши VTOL-ам.
+ Автоматически убиреть беруши после выхода из любой техники.

**Comment by Horizon1959** [comment]
А можно эти правки ещё и на Алтис внести? Недавно пострадал из-за берушей.

**Comment by malashin** [comment]
Они внесены на обе карты. После обновления миссии на сервере, будет всё ок.

**Comment by Horizon1959** [comment]
@malashin отлично, спасибо.
