### ISSUE TITLE
Добавить класс "Штурмовик"

### ISSUE THREAD

**Issue by malashin** [ToxaBes/ADR-Spec-Ops#111]
Убрать два слота медиков и поставить вместо них штурмовиков.

Только штурмовикам будут доступны AK-12, Type-115.

У AK-12 калибр 7.62. Самый мощный автомат.
У Type-115 .50 калибр под стволом. Урон как у снайперов, меткость до 500-600 метров отличная.

**Comment by 12st** [comment]
2 медика собираются убирать для слотов партизан.

**Comment by Horizon1959** [comment]
У нас сейчас 2 отделения и они слишком большие. Можно срезать по два медика и по одному пулемётчику, одному ракетчику. Пилотов можно на 1-2 подрезать, одновременно летающих  можно по пальцам пересчитать. 
Предлагаю штурмовиками ещё выдать MX SW, очень такое ударное оружие.

**Comment by ToxaBes** [comment]
Вы серьезно? Из-за 2х пушек добавлять целый класс? Так не пойдет. 
Это оружие можно сделеть наградным,  за что награда придумаем позже,  после введения партизан,  пока что это оружие будет отключено.

**Comment by Horizon1959** [comment]
@ToxaBes с Type 115 и его подствольным уберганом всё понятно, а зачем запрещать АК-12?

**Comment by ToxaBes** [comment]
Запрещать будем то что не подходит под текущие классы и мутить в награду. Если AK-12 вписывается в один из текущих классов, можно добавить его.

**Comment by Horizon1959** [comment]
@ToxaBes АК-12 отличная штурмовая винтовка, не вижу смысла её запрещать.
Вот Type 115 имеет подствольную пушку 50-го калибра, она позволяет работать по технике и убивает пехотинца с одного попадания на дистанции до 600 метров. Всем её выдавать точно нельзя.

**Comment by ToxaBes** [comment]
АК-12 - нужно будет решить каким именно из существующих классов она будет доступна.
