### ISSUE TITLE
Выбор заставки для Tanoa-миссии

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#113]
Мы с @malashin  не можем решить какой из двух логотипов выбрать.

1. вариант:
![adr_specops_tanoa_loading](https://cloud.githubusercontent.com/assets/3309152/16565908/3b06478e-4219-11e6-84f4-ac9bb976ca5b.jpg)

2. вариант:
![adr_specops_tanoa_loading2](https://cloud.githubusercontent.com/assets/3309152/16565912/42977072-4219-11e6-84b3-04aabae28bb4.jpg)

Вариант набравший большее количество голосов будет использован в миссии. Просьба обойтись без обсуждений в стиле я бы тут добавил/убрал взрывающийся вертолет (выбранное изображение будет доводится до ума по-мелочи). Достаточно написать первый или второй вариант.

**Comment by Horizon1959** [comment]
Второй ведь попса, я за первый.

**Comment by 12st** [comment]
Мне кажется первую картинку не видно будет, арма же пережмёт её и будет просто месиво из цветов. Я за вторую

**Comment by SHAH-500** [comment]
Хороши оба ! Но я выбираю вариант 2.

**Comment by Noart537** [comment]
вторая

**Comment by malashin** [comment]
Так это же вообще чужая картинка. Я думал, ты постановку кадра демонстрируешь, а не собираешь её ставить какая она есть.

По сути дела, все слова о том, что картинка показывает, что это та же самая миссия, но новый остров, улетают в трубу. Так как это картинка айдентика Arma Apex, но никак не нашей миссии.

**Comment by Horizon1959** [comment]
@malashin и я про то же. По сути это один чувак зазеркалированный. Картинку такую будут все сервера вешать, это ведь официальная обложка Apex.

**Comment by kovt** [comment]
Вторая картинка уже давно на половине серверов. Так что либо первая, либо что то другое.

**Comment by ToxaBes** [comment]
>Так это же вообще чужая картинка. Я думал, ты постановку кадра демонстрируешь, а не собираешь её ставить какая она есть.

@malashin - я пытался тебе демонстрировать постановку кадра, но ты не хочешь ее делать. Вместо этого ты сделал первый вариант, он меня не устраивает, он не похож по композиции на картинку для Алтиса, а это важно, т.к. это одна и та же миссия просто на разных картах. 
Т.к. я не художник, то просто взял примерно похожую композицию и слепил из нее то что я просил тебя сделать (2 бойца, слева и справа джунгли, по-центру "окно" с видом на что-то чтобы была композиция как для Алтиса). Нужна вот такая картинка:
![adr_specops_loading](https://cloud.githubusercontent.com/assets/3309152/16578374/cfa4669e-42a2-11e6-91ee-26281357d0ab.jpg)
только для Таноа:
![adr_specops_tanoa_loading2](https://cloud.githubusercontent.com/assets/3309152/16578407/0fe9efc6-42a3-11e6-9653-377dad584e0c.jpg)

Я был бы рад если вместо стандартной армовой картинки была наша, сделанная вручную, как для Алтиса, но я не художник и не могу ее сделать, а ты считаешь что первый вариант лучше.

**Comment by Horizon1959** [comment]
@ToxaBes ты хочешь одну картинку на две карты?

**Comment by ToxaBes** [comment]
Нет, я хочу чтобы все было по бренд буку. На каждую карту своя картинка с одной и той же композицией:
1. 2 бойца (на Таноа в новом камуфляже, на Алтисе в стандартном)
2. в левом и правом углу деревья/трава/камни (заполнение), специфичное для каждой карты.
3. по центру вид на что-то в перспективу, тоже специфичное для карты.
4. если в центре техника видна то должна быть использована техника специфичная для карты.

В итоге получается одна композиция в разном окружении. Потом например БИСы выпустят снежную карту, будет такая же композиция только слева и справа будет все в снегу, 2 бойца будут в маскхалатах и тд. 
Одна и та же миссия на разных картах = одна и та же композиция в разном фоновом окружении.

**Comment by malashin** [comment]
![img](http://i.imgur.com/RGdfHjk.jpg)

**Comment by Horizon1959** [comment]
@malashin 
![default](https://cloud.githubusercontent.com/assets/17685328/16594626/efd2eb42-42f3-11e6-8f85-d89f52ea5eef.jpg)

**Comment by ToxaBes** [comment]
@malashin - блин, вот можешь же, когда хочешь. То что надо! Я думаю никто не будет спорить что это вариант самый лучший из предложенных.
