### ISSUE TITLE
Устаревшее описание в разделе Информация на карте

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#114]
Часть описания миссий устарело в связи с их изменением но соответствующие разделы не были исправлены.

**Comment by Noart537** [comment]
Еще при выполнении доп.задания в конце текст " Можете возвращаться на базу или прямиком на основную миссию" (примерно так). Может лучше написать в место "прямиком на основную миссию" ---> "ожидайте дальнейших указаний"?

**Comment by ToxaBes** [comment]
Исправил.
