### ISSUE TITLE
Tanoa 0.0.2

### ISSUE THREAD

**Issue by malashin** [ToxaBes/ADR-Spec-Ops#115]
#### Основные задачи:
- [ ] Портировать спецоперацию "Конвой"
- [x] Переписать погоду под данный регион
- [x] Добавить гидроциклы
- [x] Добавить отделения Viper в основное задание
- [x] Сделать чтобы перепаковка не сбивала анимацию перетаски раненых
- [x] Запретить появление одной и той же основы два раза подряд
- [x] Анимация активации терминалов и заложников зависимая от позы игрока
- [x] Добавить отделения Viper в спецоперации
- [x] Очистка не убирает всё оружие с земли
- [x] Заменить циклы в ПВО и очистке базы
- [x] Добавить "WeaponHolderSimulated" в автоматическую очистку
- [x] Запретить шлемы CSAT
- [x] Добавить партизан
- [x] Добавить наградную для партизан
- [x] Портировать спецоперацию "Угон"
-  ~~Если основа на острове, то спавнить меньше брони и убрать вертолет~~
-  ~~Если на основе много леса, спавнить меньше брони, больше пехоты~~

**Comment by Horizon1959** [comment]
Не до конца убрали шмотки с мультикамом
![107410_20160713114303_1](https://cloud.githubusercontent.com/assets/17685328/16797192/0a14a3aa-48ef-11e6-925d-f6f98e0275e9.png)

**Comment by malashin** [comment]
Я когда делал, решил в головных уборах ничего не убирать за исключением камуфляжа противника. Т.к. тогда нужно будет и убирать кучу разных расцветок шлемов.

**Comment by ToxaBes** [comment]
Все этапы задачи сделаны? Я вижу кучу не поставленных чекбоксов в первом посте.

**Comment by malashin** [comment]
Это задачи на версию 0.0.2. Они не сделаны. Это открытая задача.

**Comment by Horizon1959** [comment]
А почему для SPAR-16S доступен только чёрный глушитель? Это BIS так сделали или вы?
![107410_20160713122735_1](https://cloud.githubusercontent.com/assets/17685328/16798551/46106b9a-48f5-11e6-9023-0068d0409b5b.png)

**Comment by malashin** [comment]
Так у БИСов. Ты смотри в игровом меню в виртуальном арсенале, есть ли там нужные шмотки или нет. У них там абсолютно всё разрешено.

**Comment by Horizon1959** [comment]
@malashin ок

**Comment by malashin** [comment]
Оказалось неудаляемые шмотки при очистке базы имеют класс "WeaponHolderSimulated". Раньше мы таких не встречали. До этого удаляли только "GroundWeaponHolder". Сейчас часть вещей с одним классом, часть с другим.

**Comment by malashin** [comment]
"GroundWeaponHolder" падает если игрок положил что-то на землю.
"WeaponHolderSimulated" падает если игрок умер или дисконектнулся.

**Comment by ToxaBes** [comment]
@malashin - ты вроде уже находил массив погодных данных недалеко от реального расположения острова. Можешь скинуть на почту? Займусь погодой.

**Comment by malashin** [comment]
http://rp5.md/Weather_archive_in_Nadi_(airport)

Обрати внимание, что световой день сократился. С 6 до 19 на Таноа.

**Comment by ToxaBes** [comment]
Понял, спасибо.

**Comment by Horizon1959** [comment]
Вчера столкнулись с багом, связанным с наградным БПА. В награду дали новый БПЛА CSAT (маленький такой, с четыремя ракетами), но подключиться к нему не удалось.

**Comment by malashin** [comment]
Дроны залочены так же как и вся наградная техника. Их сразу можно выбрать в терминале, но нельзя управлять. Через 300 секунд управлять можно.

**Comment by ToxaBes** [comment]
Погода готова.

**Comment by ToxaBes** [comment]
Предлагаю не делать следующие пункты:
- Если основа на острове, то спавнить меньше брони и убрать вертолет
- Если на основе много леса, спавнить меньше брони, больше пехоты

Вчера была основа на острове, очень даже неплохо получилось с вертолетом и ботов хватало.

**Comment by Horizon1959** [comment]
Если много леса, то лучше спавнить лёгкую технику типа мрапов и внедорожников, т.к. тяжёлая техника часто выходит из строя при такой обильной растительности. 
Без пилота, сбивающего вражескую авиацию на островах, добираться до места назначения очень нудно по причине внезапных взрывов лодок.

**Comment by ToxaBes** [comment]
>Если много леса, то лучше спавнить лёгкую технику типа мрапов и внедорожников, т.к. тяжёлая техника часто выходит из строя при такой обильной растительности. 

Не зависит от ратсительности - на Алтисе на ровном месте танки переворачиваются. 

>Без пилота, сбивающего вражескую авиацию на островах, добираться до места назначения очень нудно по причине внезапных взрывов лодок.

Я был тогда, никаких "внезапных" взрывов лодок не было. Ты знал что там касатка и все равно старался поближе подплыть. Высадка на 200м раньше решает проблему, что мы и сделали.

**Comment by Horizon1959** [comment]
@ToxaBes мы часто наблюдали, что боты врезались в зелёнку,  ломались и покидали машину.
Вчера я доезжал в то же место, просто не всегда везло, т.к. косатка то уходила вглубь, то подлетала ближе.

**Comment by ToxaBes** [comment]
>мы часто наблюдали, что боты врезались в зелёнку, ломались и покидали машину.

Это кривость движка, об этом я и пишу, что такая фигня и на Алтисе происходит, нет смысла из-за этого убирать технику. Это будет упрощением игры, что нам ни к чему.

**Comment by Horizon1959** [comment]
@ToxaBes ааа, я думал из-за зелёнки. BIS'ы кривее с каждым апдейтом.
