### ISSUE TITLE
Несколько идей

### ISSUE THREAD

**Issue by Noart537** [ToxaBes/ADR-Spec-Ops#116]
Вот парочка идей для сервера, у меня пока времени на них нет. Обсудите, нужно оно или нет.

1. Наградная техника уже находится на карте в нужных нам местах, но скрыта. При выполнении задания, случайная техника становится видимой. В этом случае маркер не нужен. Постоянные игроки уже будут знать в каких местах техника появляется.
2. Добавить поддержку для командиров. На базе устанавливается Артиллерия только с фугасными и дымовыми снарядами (можно еще лазерными), в ограждении как и зсу, закрыта для игроков, неубиваемая. Также создается модуль поддержки, и модуль запрашивающий поддержку. Синхронизируется с командирами и тригером, который будет определять условия запроса. Можно раз в 20-30 мин, не более 4-х выстрелов. Ну и т.д. 
2.1. Если нет пилотов, также можно сделать поддержку для сброса ящика с припасами. (виртуальную)
3. Ранговую систему привязанную к заработанным очкам, а в будущем, когда будет возможность сохранять в базу данных информацию, и усложнить зарабатывание званий. Звания же помогают пользоваться той-же поддержкой. Чем выше звание, тем разнообразнее поддержку можно вызывать. Или открывается новое вооружение в арсенале и т.д.  Главнокомандующий (администратор) может в ручную повышать звания отличившимся игрокам.

**Comment by Noart537** [comment]
Последнее лучше оставить на время, когда будет БД

**Comment by Horizon1959** [comment]
@Noart537 было мнение, что такие автоматические вещи убирают нужду в некоторых специалистах. Если бы у нас был уклон на тактику, то можно было бы дать командиру вызов ящика.
Тема с вооружением интересная, можно мутить дедовщину. Дедушки бегают с Type 115 и SPAR-16, а духи используют классические MX.

**Comment by malashin** [comment]
Первый пункт вообще не понял. Где стоит техника, что за нужные нам места? Что это дает?

Логика в том, что на наградной площадке, каждая техника появляется на уникальном для неё месте?

**Comment by Noart537** [comment]
да

**Comment by malashin** [comment]
Я смысла не вижу. Появляются новые проблемы, при этом не давая никаких плюсов.

Если место техники занято, то её нельзя будет спавнить, это дополнительные проверки. Для добавления новой техники, нужно постоянно выделять новые места, это ручная работа, трудности с портированием и т.д. При удалении техники из наградной, нужно отлавливать освободившиеся места.

**Comment by Noart537** [comment]
ты её на карте ставишь. самолеты в ангар, танки под тент. в любое место где хочешь чтобы она появилась. Изначально она там стоит на карте, при выполнении задания, появляется. Это можно применить только для вертопланов, т.к они большие и могут не влесть между маркерами

**Comment by Noart537** [comment]
это ещё дает возможность использовать только по одному типу ед. техники. (копий не будет). респавнится она сразу после уничтожения, и сразу скрывается. Да этот метод подходит только если хотите чтобы был только один оригинал. если нет, то тогда вычеркивайте эту идею

**Comment by ToxaBes** [comment]
1. >метод подходит только если хотите чтобы был только один оригинал

Да, хотим. Только я не уверен что мы будем перемещать места спавна дальше зоны наградной.
И @malashin задал правильный вопрос, что делать если место этой техники занято в момент спавна? Тут нужно будет еще продумать и решить стоит или нет. 

2. Отличная идея с артой. давать раз в 30 мин командиру отделения возможность ударить 4 выстрела артой (каким-нибудь простым боеприпасом) чтобы максимум можно было накрыть несколько ботов или серьезно повредить легкобронированную технику. Баланс это не нарушит.
Зенитку или танк такой артой не вынесешь. На время спецопераций/допок такая возможность отключается.

3. Ранговая система это интересно, но только если прогресс идет довольно медленно. Т.е. новая пушка за X килов с предыдущего оружия или Y часов игры с предыдущей пушкой (для меня примемлемо X=100ботов, Y=50часов). Вернемся к этому вопросу после партизан и endless game.

**Comment by Noart537** [comment]
4. Арт удар фугасами перед обороной в рандомные позиции в области миссии. Еще можно дымом наступающие войска прикрыть.

**Comment by ToxaBes** [comment]
4. Арт удар не имеет смысла. В подавляющем большинстве случаев все заканчивается у вышки/купола либо радиовышки (наблюдательные вышки) и там есть где спрятаться. Дым не вариант по двум причинам: 
1. мы не знаем с каких сторон остались синие на зоне и как правильно поставить дым
2. чтобы решить первый пункт нужно поставить много дыма то приведет к лагам, т.к. помимо него будет много чего происходить.

**Comment by Horizon1959** [comment]
Чуваки, добавьте на Алтис конвертоплан для транспортировки машин и пару Prowler. Народ кипятком ссыт от этих возможностей, нам ведь теперь не надо по 15 минут ждать пилотов на вертолёте.

**Comment by ToxaBes** [comment]
Машинки будут завтра. Конвертоплана не будет пока не решим вопрос с радаром.

**Comment by Horizon1959** [comment]
@ToxaBes а конвертоплан тоже нагибает чтоль? Я же не про боевой говорю, а транспортный.

**Comment by ToxaBes** [comment]
за 15 мин нашли базу партизан, за 5 мин с помощью конвертоплана скинули им на голову маршал полный синих.

**Comment by Horizon1959** [comment]
@ToxaBes а MRAP мы сейчас скинуть не можем или десант из Мохавка?

**Comment by ToxaBes** [comment]
MRAP-у партизаны с базовым оружием могут противостоять, маршалу - уже нет.

**Comment by Noart537** [comment]
Что если РПГ-7 партизанам дать с ограниченным кол-вом ракет?
--- офф топ
Антон, вечерком найди меня в тске, есть пару вопросов.

**Comment by Horizon1959** [comment]
@toxabes если MRAP красных с 40-мм автоматическим гранатомётом прижимает синих, то представляешь, что будет, если его скинуть к партизанам и укомплектовать медиком-инженером? Даже сейчас никто не едет щемить базу бомжей, т.к. это трата времени из-за возможности переноса базы. Достаточно штурмовых самолётов и БПА.

**Comment by ToxaBes** [comment]
Против MRAP-a есть варианты, против маршала - нет.

**Comment by ToxaBes** [comment]
>Что если РПГ-7 партизанам дать с ограниченным кол-вом ракет?

Будет как один из вариантов наградной. С самого начала у партизан нет никаких ПТ/ПВО средств.

>Антон, вечерком найди меня в тске,

Ок.

**Comment by ToxaBes** [comment]
Принятые идеи перенес в #124 . Ранговая система будет описан отдельно если решим ее вводить. Конвертоплан скорее всего будет на Алтисе вместо Мохавка. Этот тикет закрываю.

**Comment by Horizon1959** [comment]
Да, долой ненужные корыта, даёшь конвертоплан!
