### ISSUE TITLE
Тактический компас

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#117]
- [ ] добавить всем Тактический компас
- [ ] убрать отображение союзников на карте (сам игрок будет отображаться)
- [ ] добавить кураторы игрокам чтобы админ через Zeus мог видеть всех (нужно для быстрого отлова нарушителей)
- [ ] применить на Altis и Tanoa

**Comment by Horizon1959** [comment]
Круто! А что за тема про кураторов, как оно работает и что из себя представляет?

**Comment by ToxaBes** [comment]
>А что за тема про кураторов

тебе это не надо ) это для админов.

**Comment by Horizon1959** [comment]
@ToxaBes ну ок.

**Comment by malashin** [comment]
В релизной версии нет компаса.

**Comment by Horizon1959** [comment]
Они там совсем двинулись? Ну тогда отбой.
![are you kidding me](https://cloud.githubusercontent.com/assets/17685328/16756979/a3e47976-4811-11e6-8836-3e8629d1735d.png)

**Comment by ToxaBes** [comment]
Возможно добавят в следующих обновлениях.
