### ISSUE TITLE
Проблемы с появлением новых заданий

### ISSUE THREAD

**Issue by 12st** [ToxaBes/ADR-Spec-Ops#118]
Сегодня за день на алтисе столкнулся с 2 разными ошибками.
В первый раз после доп задания "Прерванный полёт" не появилась основа, причём триггер допки пропал, но сообщение об удачном завершении задания не прошло.
Второй раз выполнив основу появилась допка "Гроздья гнева", а через примерно 2-3 минуты появилась основа, причем там же где и предыдущая( и допка, и основа были полноценными).

**Comment by malashin** [comment]
Похоже на какой-то баг нового патча. Без какой-либо ошибки наши миссии начинают сходит с ума.

Я пока код пишу и тестирую, время от времени это встречаю, раза два такое было уже. При этом всё это локально и ошибку я бы сразу увидел. После рестарта всё нормально.

**Comment by ToxaBes** [comment]
В момент когда все перестает работать из консоли невозможно получить значение переменных (у меня так на выделенном сервере). Возможно опять поломали scriptDone.

**Comment by malashin** [comment]
У меня было так, что основа появилась на карте, а на ней ничего нет, ни объектов, ни противников. То есть до scriptDone он даже не успел дойти.

**Comment by ToxaBes** [comment]
Значит самый плохой вариант - баг в самом движке. Причем появляется через раз. В логах чисто. Ждем исправления от BIS-ов.

**Comment by malashin** [comment]
Плюс всё это у меня происходит в клиенте Винды. До релиза Apex такого не видел.

**Comment by ToxaBes** [comment]
Проверил логи запуска Таноа.
 5:00:33 Error: Sound volume expression: (speed factor[4, 1] * water)
 5:00:33 Error *: Type Array, expected Number,Not a Number,Expression

Т.е. уровень звука они рассчитывают умножая скорость на... воду. 
Надеюсь, что это просто опечатка и должно быть (speed factor[4, 1] * volume).

**Comment by malashin** [comment]
**water** скорее всего с этим связано:
https://community.bistudio.com/wiki/Ambient_Parameters
https://community.bistudio.com/wiki/Arma_3_Sound:_SoundControllers

Правда там именно **water** нет в Вики, есть **sea**.

**Comment by ToxaBes** [comment]
Ок, значит ошибка в том что нужно умножать на море а не на воду )

**Comment by malashin** [comment]
Кажется нашел в чем проблема была. В findSafePos когда прописывал фейлсейф позицию, её надо было указать в массиве, а не просто как одну позицию. Из-за этого при исчерпании 1000 рандомов и дохода до фейлсейфа появлялась ошибка и не возвращала никакую позицию. Не появлялись важные элементы задания и оно застрявало или пропускалось.

Как я уже говорил функция очень опасная. Сейчас  хорошо видно, что фейлы у неё не только с лодками в Рыбе-меч. Лучше её переписать и сделать логичный поиск, а не рандомы. Рандомов еще и на самом деле меньше 1000. Если рандом попадает за переделы минимального расстояния переданого в функцию, то это минус один рандом.

**Comment by Noart537** [comment]
Почему не сделайте просто маркеры с интересными местами? Штук 20-30 вполне хватит. Потом через 2-3 месяца можно переместить просто в новые места.

**Comment by malashin** [comment]
Как я уже писал. Проблема в функции которая используется повсеместно во многих местах миссии. Прописывать места для появления каждого юнита это не решение.

Я написал свои функции для поиска берега и для поиска места спауна Viper отделения. Работает всё отлично и скорость значительно выше чем я ожидал.

Массив маркеров это хардкодинг для отдельно взятого места. Нельзя потом портировать нормально, передать задачу другому и куча ручной работы. Сейчас две спецоперации так и не портированы потому, что в них огромное количество предопределеных позиций.

**Comment by Horizon1959** [comment]
Сейчас захватили КП, после подрыва вышки не было сообщения об уничтожении вышки. На точке не было пехоты и техники противника, даже авиации (точка была заспавнена до нашего прихода).

**Comment by ToxaBes** [comment]
Логи чистые, баг в дижке. Как это фикисть - хз пока.

**Comment by Horizon1959** [comment]
Не работает скрипт ПВО на базе. В общий чат про ПВО не пишет, нажатие кнопки эффекта не даёт.

**Comment by ToxaBes** [comment]
Похоже ошибка в переносе  сирены на Таноа. @malashin - добавь объект "Land_Loudspeakers_F" с именем "loudspeaker" и allowDamage=false куда-нибудь в центр базы.

Вот как добавлено на Алтисе:
https://github.com/ToxaBes/ADR-Spec-Ops/blob/da1f99483f739309c7af7581b1b98bf0c16892be/co30_ADR_Spec_Ops.Altis/mission.sqm#L10845

**Comment by malashin** [comment]
Я добавлял и тестировал.

Сейчас в миссии с гита нормально работает. Я не знаю, что на сервере.

**Comment by malashin** [comment]
Тут даже очистка базы не работает.

**Comment by ToxaBes** [comment]
https://github.com/ToxaBes/ADR-Spec-Ops/search?utf8=%E2%9C%93&q=loudspeaker

В mission.sqm для алтиса loudspeaker есть, для Таноа - нет.

**Comment by malashin** [comment]
https://github.com/ToxaBes/ADR-Spec-Ops/blob/master/co30_ADR_Spec_Ops.Tanoa/mission.sqm#L27917-L27956

**Comment by malashin** [comment]
Тут косяк не в этом. Он вообще remoteExec не делает такое ощущение. Ты в battlyeEye ничего не менял?

**Comment by malashin** [comment]
Походу это клиента косяк.

Я сейчас заходил не работ Зевс, вызов очистки и ПВО.

Перезагрузил клиент, зашел снова, всё работает.

**Comment by ToxaBes** [comment]
>Ты в battlyeEye ничего не менял?

Нет, не менял.

У меня такое чувство что обновление апекс добило движок армы и он периодически распадается. Отпадают различные части типа phisX, подсистема межсетевого взаиможействия (передача и синхронизация данных между клиентами) и тд. Т.к. это все внутри движка то до логов просто не доходит.

**Comment by 12st** [comment]
Получается с этим связано резкое падение графической подсистемы, резкие необоснованные скачки пинга у игроков и рассинхроны на ровном месте?

**Comment by ToxaBes** [comment]
Похоже что да.

**Comment by 12st** [comment]
Ну вроде и на Алтисе и на Таноа чередуется нормально. Таноа вчера проверили.

**Comment by ToxaBes** [comment]
Отлично. Остались проблемы с вызовом техники на базе партизан но это мелочи. Сегодня кстати тоже Таноа.
