### ISSUE TITLE
Мелкие косяки миссии на Таноа

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#119]
1. Очистка базы от мусора по ходу не убирает новые предметы
![107410_20160713105657_1](https://cloud.githubusercontent.com/assets/17685328/16795942/aadb912e-48e8-11e6-8500-7a4e2e57612f.png)
2. Появляются сообщения типа таких
![107410_20160713105602_1](https://cloud.githubusercontent.com/assets/17685328/16795960/c0136dc8-48e8-11e6-8ff9-46389e5175a2.png)

**Comment by malashin** [comment]
Первое уже давно заметил. Не понятно почему не удалят, в сингле с этим проблем нет. Разницы этого оружия от стандартного никакой нет.

Второе это косяк БИСов. На некоторые новые вещи иконки не находит. К миссии это отношения не имеет.

**Comment by Horizon1959** [comment]
Понял. Патчи каждый день по ходу будут.

**Comment by Horizon1959** [comment]
А куда дели чёрный Navid?
![107410_20160713111610_1](https://cloud.githubusercontent.com/assets/17685328/16796407/42b85cbe-48eb-11e6-908f-c9e605290e4f.png)

**Comment by malashin** [comment]
Черного никогда и не было.

**Comment by malashin** [comment]
Сюда пиши по Таноа #115. Эту тему закрываю.
