### ISSUE TITLE
Изменение спецоперации "Рыба-Меч"

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#12]
Добавить командный центр на берегу, атаковав который можно вынудить боевых пловцов прекратить выполнять основную задачу и выходить на берег защищая командный центр.

**Comment by 12st** [comment]
Боты всплывают при любом шорохе, будь то выстрел или вертушка.

**Comment by ToxaBes** [comment]
Наши боты реагируют на звуки (шум, выстрелы и тд). Т.к. большинство шума над поверхностью - то они устремляются туда. Пока ищу как запретить им отвлекаться на шум на поверхности.

**Comment by ToxaBes** [comment]
Единственный вариант - запретить некоторым ботам покидать позицию в любом случае. ТОгда хоть кто-то под водой останется. Будем тестить.

**Comment by malashin** [comment]
Как вариант можно ставить им вейпоинты в воде с поведением которое игнорирует врага, пока противника в воде или на берегу рядом не появится. Когда никого нет рядом, возвращаться в стандартное состояние игнорирующее противника.

**Comment by ToxaBes** [comment]
Там все плохо с определением что в воде а что нет.

**Comment by malashin** [comment]
Можно попробывать сравнивать высоту поверхности суши с поверхностью дна моря у объекта. Там много разных getPos есть. Если они отличаются, то он в воде. Летать они все равно не будут.

**Comment by malashin** [comment]
https://community.bistudio.com/wiki/isFlatEmpty
Здесь еще есть проверка на воду, сушу, берег.

**Comment by ToxaBes** [comment]
Ты немного не понял, я использую [BIS_fnc_ambientAnimCombat](https://github.com/ToxaBes/ADR-Spec-Ops/blob/master/co30_ADR_Spec_Ops.Altis/mission/side/missions/swordfish.sqf#L197) - чтобы их поведение было хоть немного адекватным под водой. Там нет возможности исключить шум от объектов на поверхности. Для армы это такой же противник и на него нужно реагировать.

**Comment by ToxaBes** [comment]
даже если я каким-то образу отловлю те объекты которые они считают противником и найду из них те кто над водой, и прикажу не реагировать на них то на следующем шаге проверки они опять их найдут.

**Comment by 12st** [comment]
3 раз подряд вижу как кп спавнится под водой или вообще не появляется. Боты появляются прям в воде в радиусе 4 км причём в разных местах, 2 раза офицера найти удалось, последний видел только ботов в воде.

**Comment by ToxaBes** [comment]
Есть проблема с определением места для спавна объектов, проблема в самой BIS-ской функции. Если за 1000 (или 10000) итераций место не найдено то возвращается безопасное место по-умолчанию. @malashin выяснил, что на Алтисе это перешеек нижнего острова, на Таноа - наша будущая ВПП. Также эта функция может выбрать место в воде не смотря на явный запрет использования воды как зоны поиска (баг в движке). 
Тут можно было добавить рекурсивную проверку в конце "если выбранная позиция не подходит то перевыбираем", но проблема в том что нет гарантии что в итоге арма найдет верную позицию. Получаем что спавн миссии может длится и 10 и 20 мин, что неприемлемо. 
Второй вариант - для каждой зоны спецоперации самому сделать массив из ~10 мест где могут появится лодки и кп. 
Продолжаем мониторить эту миссию, если проблема будет постоянно проявляться - будет делать второй вариант (долго делать зато будет работать).

**Comment by malashin** [comment]
Там в функции можно указать место по умочанию заместо стандартного. Для каждой точки можно указать одно место по умолчанию.

**Comment by ToxaBes** [comment]
И в итоге игроки быстро выучат эти места по-умолчанию и будут первым делом наведываться туда. Нужно больше чем одно место для каждой точки.

**Comment by malashin** [comment]
Шансы, что оно будет использованы крайне малы, если при тестировании всё сработало нормально.

**Comment by malashin** [comment]
Код функции, на всякий случай.
<details> 
  <summary>findSafePos</summary>
  ```sqf
  /*
   File: findSafePos.sqf
   Author: Joris-Jan van 't Land
  
   Description:
   Function to retrieve and dynamic position in the world according to several parameters.
  
   Parameter(s):
   _this select 0: center position (Array)
                       Note: passing [] (empty Array), the world's safePositionAnchor entry will be used.
   _this select 1: minimum distance from the center position (Number)
   _this select 2: maximum distance from the center position (Number)
                       Note: passing -1, the world's safePositionRadius entry will be used.
   _this select 3: minimum distance from the nearest object (Number)
   _this select 4: water mode (Number)
                       0: cannot be in water
                       1: can either be in water or not
                       2: must be in water
   _this select 5: maximum terrain gradient (average altitude difference in meters - Number)
   _this select 6: shore mode (Number):
                       0: does not have to be at a shore
                       1: must be at a shore
   _this select 7: (optional) blacklist (Array of Arrays):
                       (_this select 7) select X: Top-left and bottom-right coordinates of blacklisted area (Array)
   _this select 8: (optional) default positions (Array of Arrays):
                       (_this select 8) select 0: default position on land (Array)
                       (_this select 8) select 1: default position on water (Array)
   
   Returns:
   Coordinate array with a position solution.
   
   TODO:
   * Maybe allow passing several combinations of position, min and max dist ... so that you can 
   avoid several things?
   * Interpretation of minDist / maxDist is wrong. It's not true distance that is used. Too bad?
  */
  
  scopeName "main";
  
  private ["_pos", "_minDist", "_maxDist", "_objDist", "_waterMode", "_maxGradient", "_shoreMode", "_defaultPos", "_blacklist"];
  _pos = _this select 0;
  _minDist = _this select 1;
  _maxDist = _this select 2;
  _objDist = _this select 3;
  _waterMode = _this select 4;
  _maxGradient = _this select 5;
  _shoreMode = _this select 6;
  
  if (_shoreMode == 0) then {_shoreMode = false} else {_shoreMode = true};
  
  _blacklist = [];
  if ((count _this) > 7) then 
  {
   _blacklist = _this select 7;
  };
  
  _defaultPos = [];
  if ((count _this) > 8) then 
  {
   _defaultPos = _this select 8;
  };
  
  //See if default world values should be used.
  if ((count _pos) == 0) then 
  {
   _pos = getArray(configFile >> "CfgWorlds" >> worldName >> "safePositionAnchor");
  };
  if ((count _pos) == 0) exitWith {debugLog "Log: [findSafePos] No center position was passed!"; []}; //TODO: instead return defaults below.
  
  if (_maxDist == -1) then 
  {
   _maxDist = getNumber(configFile >> "CfgWorlds" >> worldName >> "safePositionRadius");
  };
  
  //TODO: Validate parameters.
  
  private ["_newPos", "_posX", "_posY"];
  _newPos = [];
  _posX = _pos select 0;
  _posY = _pos select 1;
  
  
  //Limit the amount of attempts at finding a good location.
  private ["_attempts"];
  _attempts = 0;
  while {_attempts < 1000} do
  {
   private ["_newX", "_newY", "_testPos"];
   _newX = _posX + (_maxDist - (random (_maxDist * 2)));
   _newY = _posY + (_maxDist - (random (_maxDist * 2)));
   _testPos = [_newX, _newY];
  
   //Blacklist check.
   //TODO: Do not use function when the blacklist is empty?
   if (!([_testPos, _blacklist] call BIS_fnc_isPosBlacklisted)) then
   {
           if ((_pos distance _testPos) >= _minDist) then
           {
               if (!((count (_testPos isFlatEmpty [_objDist, 0, _maxGradient, _objDist max 5, _waterMode, _shoreMode, objNull])) == 0)) then 
               {
                   _newPos = _testPos;
                   breakTo "main";
               };
           };
   };
  
   _attempts = _attempts + 1;
  };
  
  //No position was found, use defaults.
  if ((count _newPos) == 0) then
  {
   if (_waterMode == 0) then
   {
       if ((count _defaultPos) > 0) then 
       {
           _newPos = _defaultPos select 0;
       } 
       else 
       {
           //Use world Armory default position:
           _newPos = getArray(configFile >> "CfgWorlds" >> worldName >> "Armory" >> "positionStart");
       };
   }
   else
   {
       if ((count _defaultPos) > 1) then 
       {
           _newPos = _defaultPos select 1;
       } 
       else 
       {
           //Use world Armory default water position:
           _newPos = getArray(configFile >> "CfgWorlds" >> worldName >> "Armory" >> "positionStartWater");
       };
   };
  };
  
  if ((count _newPos) == 0) then 
  {
   //Still nothing was found, use world center positions.
   _newPos = getArray(configFile >> "CfgWorlds" >> worldName >> "centerPosition");
  };
  
  _newPos
  ```
</details>

Эти парматры у нас не указаны, они пустыми массивами становятся в итоге.
**"positionStart"
"positionStartWater"**

Это и есть куда кидается позиция сейчас.
**"centerPosition"**

**Comment by ToxaBes** [comment]
Эм, у меня при тестировании не разу не было проблем, а при написании я запускал ее раз 200 наверное, а на в мультиплеере раз за разом бывает косяк. У нас некоторые (не буду показывать пальцем) фразы на фарси выучили чтобы понимать кого заметил противник, неужели такие игроки не выучат 10 мест которые нужно смотреть на берегу в первую очередь?

Да я в курсе про опциональный параметр. Проблема  втом что он позволяет задать одно из мест по умолчанию, нам надо примерно по 10 мест на кажду точку. Т.е. нам нужно добавить проверку после findSafePos - если полученное место в воде - взять новое место рандомом из массива мест по-умолчанию для этой точки (~10шт в массиве). Тогда будет разнообразие.

**Comment by malashin** [comment]
Ну тогда можно без проверки вставить в дополнительный параметр рандомно выбраную позицию из твоего десятка.

Проблема в том, что это может произойти везде где эта функция используется, не только в этой миссии.

**Comment by ToxaBes** [comment]
>Проблема в том, что это может произойти везде где эта функция используется, не только в этой миссии.

именно так, причем чаще всего в зонах где суша переходит в воду (берег).

**Comment by malashin** [comment]
Тут логичнее будет свою функцию написать чем места каждый раз указывать.

**Comment by ToxaBes** [comment]
Свою функцию поиска пятна с заданным градиентом поверхности в заданном радиусе?

**Comment by malashin** [comment]
Да. Поиск места вообще сложнее будет. Но поиск берега для лодок простая функция. По часовой стрелке проверяешь все места в радиусе, увеличиваешь радиус, ищешь снова и т.д. Накопил так несколько мест и выбрал рандомом одно. Это логичнее чем 1000 рандомов делать.

**Comment by ToxaBes** [comment]
Ты серьезно считаешь что поиск нужного градиента проще написать самому? )

**Comment by malashin** [comment]
Градиент ищется через команду isFlatEmpty, команду движка игры. Она же и используется в функции bis_fnc_findSafePos. Нас isFlatEmpty устраивает, не устраивает функция в которой она применяется.

**Comment by ToxaBes** [comment]
Т.е. это будет быстрее чем выбрать 1 значение из массива?

**Comment by malashin** [comment]
Ты хочешь на все применения bis_fnc_findSafePos в миссии прописать по десять мест на каждую точку задания? И при этом не хочешь чтобы игроки эти места могли запомнить?

Это несколько сотен точек указанных в ручную.

**Comment by ToxaBes** [comment]
Нет, проблема в bis_fnc_findSafePos в определении координат именно на берегу. У нас в миссии места на берегу ищутся только для лодок в спецоперации рыба-меч. Всего 24 мест появления точки. На каждую точку прописать например 8 мест, это 24*8 = 192 координат забить в массив. Это займет 1.5-2 часа времени и обеспечит достаточное разнообразие в купе с bis_fnc_findSafePos. Т.е. мы оставляем bis_fnc_findSafePos, в конце берем ее результат, если он не на берегу - берем рандомно из массива для этой точки. Нет необходимости вообще избавляться от bis_fnc_findSafePos во всей миссии.

**Comment by malashin** [comment]
Проблема в поиске места 1000 рандомами. Любое использование функции потенциально опасно и кинет объекты нам на базу. Нужно, либо менять функцию, либо фейлсейф позиция функции должна быть центром поиска во всех случаях её применения.

Поиск берега 1000 рандомами в радиусе не оптимальный вариант поиска, объяснять, я думаю, не надо это. А при условии, что ты его всё равно хочешь делать, то о чем тогда был разговор по поводу быстродействия выбора одного значения из массива?

Если так волнует производительность операции производимой раз в час при создании задания, то быстрее найти возможные места алгоритмом и сделать из этого массив из которого всегда будут выбираться значения, чем делать это вручную.

**Comment by ToxaBes** [comment]
Суть в следующем - ищем через bis_fnc_findSafePos + добавляем fallback method в виде массива с выбранными координатами. Нас устраивает скорость работы bis_fnc_findSafePos, нас не устраивают НЕКОТОРЫЕ результирующие значения которые появляются ИНОГДА. Для таких случаев применяется fallback (грубо говоря подстраховка). 
Можно конечно написать небольшой скрипт который для каждой точки найдет 8-10 мест на берегу, запишет в массив и отметит на карте с подписанными координатами для проверки (займет минут 20). Но я предпочитаю такое делать вручную т.к. в этом случае я могу выбрать наиболее "интересные места" на местности: ложбины на берегу, камни, кусты, русла рек и тд.

**Comment by ToxaBes** [comment]
>Любое использование функции потенциально опасно и кинет объекты нам на базу.

Не кинет объекты а вернет координаты. После этого мы и делает проверку и при необходимости используем fallback. В подавляющем большинстве случаев функция косячит при работе с береговой зоной которая у нас используется только для поиска мест для лодок.

**Comment by malashin** [comment]
Написал функцию для Таноа. Из десяти запусков задания, на поиск максимум тратилось 0.1 секунда. Все позиции рандомны.

**Comment by malashin** [comment]
Во все BIS_fnc_findSafePos прописал центр самого поиска как фейлсейф, лучше он туда кидать будет, чем в другой конец карты.

Делал только на Таноа, так как ты не захотел это менять.

Регулярка
```sqf
(\[(\w+),.*)(\] call BIS_fnc_findSafePos;$)
$1, [], $2$3
```

**Comment by ToxaBes** [comment]
Если ты уже написал функцию, применил на Таноа и она решает проблему, то применяй и на Алтис чтобы было одинаково. Не вижу смысла делать по-своему только ради того чтобы было по-своему.
