### ISSUE TITLE
Новые предложения

### ISSUE THREAD

**Issue by SHAH500** [ToxaBes/ADR-Spec-Ops#120]
1 При включении систем ПВО, включить тревожное звуковое сопровождение (для антуража)
2 При входе партизан на базу синих, иметь возможность через лептоп включить тревогу на базе, для информирования союзников не знающих об этом.
3 Для командира отделения, сделать доступным арт удар 1 раз в пол часа например.

**Comment by ToxaBes** [comment]
1. Сделаем если найдем соответствующий звук в стандартной библиотеке Армы.
2. Сделаем если найдем соответствующий звук в стандартной библиотеке Армы. Помимо это на 5 или 10 мин будет появляться усиленная охрана периметра (автоматические турели и стационарные пулеметы).
3. Эту идею ранее предложил @Noart537 , обсуждение [тут](https://github.com/ToxaBes/ADR-Spec-Ops/issues/116)

**Comment by malashin** [comment]
Звук тревоги есть. Я его ставил в Желтый туман.

Не понял, только как глобально кинуть его в в нужное место на карте, просто кидал его каждому игроку в радиусе. То есть это не очень правильная реализация, т.к. не центрального объекта и отдаление от него не делает звук тише.

**Comment by ToxaBes** [comment]
Пункты 1 и 2 готовы. Третий пункт сделаю позже в рамках #116
