### ISSUE TITLE
Новые баги

### ISSUE THREAD

**Issue by 12st** [ToxaBes/ADR-Spec-Ops#121]
- Синие не видят маркеры своей базы(арсенал\бронетехника\сервис техники и т.д).

- Раненых не видит никто, нет отображения как на карте так и визуально у медиков.

- Периодически пропадает экстренный канал, обычно пропадает при смерти, возвращаясь при следующей.

- Враждующие стороны видят метраж до вражеских медиков(Баг или фича?).

- При наведении вражеского игрока на воздушную технику нет никаких оповещений у пилотов(Единичный случай или косяк бисов?)

- Партизаны имеют сторону AAF, однако существует доп задание "Пусковые установки", противником на которой является как раз AAF. Учитывая, что зевсовые боты зелёных партизан не атакуют, следовательно и на допке тоже не будут.

- Партизаны видят оповещения о включении ПВО и обороны базы.

**Comment by malashin** [comment]
> Партизаны имеют сторону AAF, однако существует доп задание "Пусковые установки", противником на которой является как раз AAF. Учитывая, что зевсовые боты зелёных партизан не атакуют, следовательно и на допке тоже не будут.

На допках все боты имеют красную сторону. То, что они выглядят как зеленые не значит, что они зеленые. ;)

**Comment by ToxaBes** [comment]
>Синие не видят маркеры своей базы(арсенал\бронетехника\сервис техники и т.д).

Fixed.

>Раненых не видит никто, нет отображения как на карте так и визуально у медиков.

Fixed. Нужно потестить т.к. есть второй вариант решения.

>Периодически пропадает экстренный канал, обычно пропадает при смерти, возвращаясь при следующей.

Fixed.

>Враждующие стороны видят метраж до вражеских медиков(Баг или фича?).

Fixed.

>При наведении вражеского игрока на воздушную технику нет никаких оповещений у пилотов(Единичный случай или косяк бисов?)

Косяк БИСов.

>Партизаны имеют сторону AAF, однако существует доп задание "Пусковые установки", противником на которой является как раз AAF. Учитывая, что зевсовые боты зелёных партизан не атакуют, следовательно и на допке тоже не будут.

На допках все "зеленые" - "красные".

>Партизаны видят оповещения о включении ПВО и обороны базы.

У нас пока общий канал в этом плане т.к. слишком много сообщений которые должны видеть обе стороны.
