### ISSUE TITLE
Дичайшие рассинхроны и кик BattleEye

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#122]
После вечернего рестарта на Таноа у некоторых стало дико рассинхронить и лично меня кикает BattleEye.

**Comment by 12st** [comment]
Решилось перезапуском миссии.

**Comment by Horizon1959** [comment]
@12st не решилось, позже продолжилось.

**Comment by 12st** [comment]
Я зашёл у всех всё нормально было.

**Comment by Horizon1959** [comment]
Ок, завтра-послезавтра понаблюдаю.

**Comment by malashin** [comment]
Как вариант, стоит проверить работают ли в это время вызовы из лэптопов на базе.

Если они не работают, значит не работает remoteExec на клиенте. Он же делается каждые пять минут для синхронизации с БД.

**Comment by ToxaBes** [comment]
Я вчера зашел - потестил, все норм. Поспрашивал остальных, проблемы были только у тех кто в мск регионе, возможно лагало то направление сети.
