### ISSUE TITLE
Беруши для пилотов

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#123]
Беруши не включаются автоматом в самолётах, таких как бузард, вайпаут и неофорн. Приходится вручную тыкать.

**Comment by malashin** [comment]
Я поэтому и спрашивал только ли в вертолетах делать

**Comment by 12st** [comment]
Кстати, есть ли возможность включить беруши в БПА? Инженеры жалуются на звук дартера.

**Comment by ToxaBes** [comment]
затем игроки попросят беруши на постоянной основе т.к. звук выстрелов стрелкового оружия раздражает ). Давайте добавим в самолеты и беспилотники.

**Comment by 12st** [comment]
А это с самого начала просят)

**Comment by ToxaBes** [comment]
и я ошибся, это не баг. Беруши просто не были добавлены в самолеты/беспилотники.

**Comment by ToxaBes** [comment]
>А это с самого начала просят)

Для этих модно посоветовать только убрать вообще звук в игре.

**Comment by Horizon1959** [comment]
В БПА действительно нужны беруши, гудит сильно и мозг сверлит. В IRL это делать можно.

**Comment by malashin** [comment]
Самолеты добавил. С БПА сложнее, т.к. при подключении ты видишь экшны БПА, а не игрока. То есть их нужно добавлять к БПА при подключении.

**Comment by malashin** [comment]
Для БПА не очень оптимальный алгоритм. У авиации проверка идет по эвенту посадки в технику. Т.к. при присоединении к БПА эвент хэндлера нет, то сделал постоянный цикл у инженеров. Каждые пять секунд идет проверка, камера на БПА или нет. Если на БПА, то приглушается звук и добавляются экшны вставки, вытаскивания беруш. Каждые 5 секунд идет проверка ушла ли камера с этого БПА, если да, то убираются экшны и приглушенния звука.
