### ISSUE TITLE
Добавить поддержку для командиров отделений

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#124]
1) Создается модуль поддержки арт огнем, только с фугасными и дымовыми снарядами (можно еще управляемыми) и модуль запрашивающий поддержку. Синхронизируется с командирами и тригером, который будет определять условия запроса. Раз в 30 мин, не более 4-х выстрелов. 

2) Если нет пилотов, доступна поддержка для сброса ящика с припасами один раз в 60 мин. Если пилоты появляются на сервере - поддержка недоступна.

**Comment by 12st** [comment]
Лазерные или управляемые? Просто это два разных типа боеприпасов. Лазерные сами наводятся на технику в небольшом радиусе. Управляемые наводятся по лазеру пехоты или БПА.

**Comment by ToxaBes** [comment]
Спасибо за уточнение, исправил. Я имел ввиду наводящиеся по подсветке пехоты или БПА.

**Comment by Horizon1959** [comment]
Может сократить время вызова ящика до 30-45 минут? 60 много.

**Comment by ToxaBes** [comment]
60 норм, это 1 основа + 1 допка в среднем. Как раз хватает боеприпасов.

**Comment by Horizon1959** [comment]
@ToxaBes мне всегда казалось, что точку берут за 30-40 минут.

**Comment by 12st** [comment]
@Horizon1959 По разному. Иногда за 15 минут с поддержкой авиации и арты, а иногда по 1.5 часа берут, 150 раз помирая на точке.

**Comment by Horizon1959** [comment]
@ToxaBes @12st тогда да, пойдёт 60 минут.
