### ISSUE TITLE
Наградная партизан

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#128]
- [x] разделение сообщений по сторонам
- [x] награда партизан не спавнится в зону наградной а доступна для вызова так же как и машины на базе
- [x] на основе партизаны получают награду за каждое из 2х выполненных действий. Если началась оборона, то ее держат синие

Cохранение данных между рестартами будет в v0.0.8
Список наград для партизан будет добавлен позже.

**Comment by 12st** [comment]
В таком случае придётся продумывать награду для синих. И у партизан проблема, придётся как-то прятать наградную технику после использования или добавить скрипт который будет "паковать" технику обратно в ящик.

**Comment by 12st** [comment]
Также у партизан два вида награды, вооружение и техника. Просто рандомом выдавать? Или вооружение за основу, техника за допку?

**Comment by ToxaBes** [comment]
>В таком случае придётся продумывать награду для синих.

Зачем?

>И у партизан проблема, придётся как-то прятать наградную технику после использования

Нет проблемы, если вызвали то используйте до победного. Никакой паковки обратно и тд.

>Также у партизан два вида награды, вооружение и техника. Просто рандомом выдавать?

Да, просто рандом из списка.

**Comment by 12st** [comment]
Что давать синим в награду за основу?

**Comment by malashin** [comment]
Стоит вызов техники спрятать в отдельное подменю, как это с админскими инструментами сделано.

**Comment by ToxaBes** [comment]
>Стоит вызов техники спрятать в отдельное подменю, как это с админскими инструментами сделано.

Отличная идея, так и сделаю. И для наградной отдельное подменю.

**Comment by ToxaBes** [comment]
Подменю можно сделать только через commanding menu, а оно не позволяет добавлять появление экшна при условии (игрок ближе Х метров определенной стороны). Поэтому пока оставляем через addAction.

**Comment by ToxaBes** [comment]
Составил список наградной для партизан:
1) Ящик с базовым оружием синих (Box_T_NATO_Wps_F)
2) Ящик с базовым оружием красных (Box_T_East_Wps_F)
3) Ящик с базовым оружием синдиката (Box_Syndicate_Wps_F)
4) Ящик с базовыми боеприпасами красных (Box_T_East_Ammo_F)
5) Ящик с базовыми боеприпасами синдиката (Box_Syndicate_Ammo_F)
6) Ящик со взрывчаткой СВУ (Box_IED_Exp_F)
7) Ящик со взрывчаткой красных (Box_East_AmmoOrd_F)
8) Ящик с гранатометами синдиката (Box_Syndicate_WpsLaunch_F)
9) Ящик с гранатами красных (Box_East_Grenades_F)
10) Ящик с основным оружием синих (Box_NATO_Wps_F)
11) Ящик с основным оружием красных (Box_IND_Wps_F)
12) Ящик с основными боеприпасами синих (Box_NATO_Ammo_F)
13) Ящик с основными боеприпасами красных (Box_East_Ammo_F)
14) Ящик со специальным оружием синих (Box_T_NATO_WpsSpecial_F)
15) Ящик со специальным оружием партизан (Box_IND_WpsSpecial_F)
16) Ящик со специальным оружием красных (Box_T_East_WpsSpecial_F)
17) Ящик с припасами синих (C_T_supplyCrate_F)
18) Ящик с припасами красных (O_supplyCrate_F)
19) Ящик с припасами партизан (IG_supplyCrate_F)
20) Ящик поддержки синих (Box_NATO_Support_F)
21) Ящик поддержки красных (Box_East_Support_F)
22) Ящик поддержки партизан (Box_IND_Support_F)
23) Пусковые установки синих (Box_NATO_WpsLaunch_F)
24) Пусковые установки красных (Box_East_WpsLaunch_F)
25) Пусковые установки партизан (Box_IND_WpsLaunch_F) 
26) Ящик со снаряжением синих (Box_NATO_Equip_F)
27) Ящик со снаряжением красных (Box_CSAT_Equip_F)
28) Ящик со снаряжением партизан (Box_AAF_Equip_F)
29) Ящик с формой партизан (Box_AAF_Uniforms_F)
30) Вертолет M900 (C_Heli_Light_01_civil_F)
31) Спортивный хэтчбек (C_Hatchback_01_sport_F)
32) Самолет Caesar BTT (C_Plane_Civil_01_F)
32) Дартер AR-2 (I_UAV_01_F)
33) Стомпер с гранатометом (I_UGV_01_rcws_F)
34) Вертолет Хеллкет с оружием (I_Heli_light_03_F)
35) Страйдер с пулеметом (I_MRAP_03_hmg_F)
36) Миномет (I_G_Mortar_01_F)
37) Ифрит с пулеметом (O_T_MRAP_02_hmg_ghex_F)
38) Вертолет Pawnee (B_Heli_Light_01_armed_F)
39) Беспилотник KH-3A Fenghuang (O_T_UAV_04_CAS_F)
40) Беспилотник MQ-12 Falcon (B_T_UAV_03_F)

**Comment by malashin** [comment]
Не забывай, что для БПА нужен зеленый терминал. Самолеты и БПЛА бесполезны если будут появляться на базе Партизан, а не ВПП.

**Comment by malashin** [comment]
> Подменю можно сделать только через commanding menu, а оно не позволяет добавлять появление экшна при условии (игрок ближе Х метров определенной стороны). Поэтому пока оставляем через addAction.

Можно на ящике сделать вызов подменю. Он поменяет локальную переменную у игрока. Когда переменная true, то видно нужные экшны на ящике, когда false видно все остальные. Все экшны уже будут висеть на ящике с этой переменной в условии.

**Comment by ToxaBes** [comment]
>Не забывай, что для БПА нужен зеленый терминал. Самолеты и БПЛА бесполезны если будут появляться на базе Партизан, а не ВПП.

Можно спавнить на дороге вблизи базы 

> Он поменяет локальную переменную у игрока. Когда переменная true, то видно нужные экшны на ящике, когда false видно все остальные. Все экшны уже будут висеть на ящике с этой переменной в условии.

Так все равно экшены на ящике. Возможно есть смысл сделать свой контрол, в котором будет список доступной техники для вызова.

**Comment by ToxaBes** [comment]
мда, попробовал взлетать с дорог - 50%. Как вариант, можно выбирать ближайший от партизан пустой аэродром.

**Comment by 12st** [comment]
Как вариант поставить на каждом аэродроме ящик и от туда вызывать воздушную технику, а партизаны уже сами решат где спавнить.

**Comment by malashin** [comment]
> Так все равно экшены на ящике.

При активации экшна в него передается тот, кто его активировал.
