### ISSUE TITLE
Добавить еще 70 мест для Базы партизан

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#129]
Нужно добить количество мест для базы до 100 шт как на Алтисе. Я сегодня еще поищу глухие места, в том числе и на островах.

**Comment by malashin** [comment]
Я когда их искал, решил ограничиться главным островом. Даже если у них лодки будут, пешком же они не будут топать по острову с берега.

**Comment by malashin** [comment]
А южный остров с мостом, из-за единственного прохода с него достаточно убог в ПвП сценарии.

**Comment by ToxaBes** [comment]
попробую с островами, потестим и если все будет плохо - оставим только базы на главном острове. Но я думаю все будет ок - есть задумки.
