### ISSUE TITLE
Отображение БПА на карте

### ISSUE THREAD

**Issue by 12st** [ToxaBes/ADR-Spec-Ops#131]
На новых БПА вместо AI отображается имя бота.
![20160807232614_1](https://cloud.githubusercontent.com/assets/18305023/17465095/8370f472-5cf6-11e6-99f9-47122828251b.jpg)

**Comment by malashin** [comment]
Сделал ботам имена [AI], косяк с +1 в конце так и останется, т.к. это не стандартные AI для дронов, как в редакторе. Как сделать стандартных я не понял.

На Алтис добавил наградную с Апекса.
