### ISSUE TITLE
Не работают внутриигровые каналы

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#132]

**Comment by Horizon1959** [comment]
Известно что-нибудь про внутриигровые каналы? Это BIS накосячили или сломалось что-то в сценарии?

**Comment by 12st** [comment]
@Horizon1959  Учитывая, что на остальных серверах такой проблемы нет, косяк где-то у нас.

**Comment by ToxaBes** [comment]
Косяк может быть в 3-х местах:
1. в самой миссии
2. в настройках server.cfg или server.arma3profile
3. в версии самой армы под linux

**Comment by Horizon1959** [comment]
@ToxaBes помню у @malashin были такие проблемы на линуксе, может он помнит что там?

**Comment by ToxaBes** [comment]
Можно попробовать определить методом исключения. Если есть возможность, запустите миссию локально, подключитесь и под запись попробуйте сказать что-нибудь в зеленый канал. Потом проиграйте запись.
Если голос будет на записи, то пункт 1 исключаем.
Если голоса не слышно, то исключаем пункты 2 и 3.

**Comment by Horizon1959** [comment]
@ToxaBes просто миссию в сетевой игре запускать?

**Comment by ToxaBes** [comment]
да, затем зайти за синих и потестить голосовой канал.

**Comment by Horizon1959** [comment]
@ToxaBes ок, сегодня попробую.

**Comment by ToxaBes** [comment]
@Horizon1959  - спасибо за тест. Дело точно не в файле миссии.

**Comment by ToxaBes** [comment]
Пофиксил. Видимо одно из последних обновлений предполагало что рано или поздно система перезагрузится. А у меня линукс, месяцами работает. Короче ребут полечил.
