### ISSUE TITLE
Камера арсенала

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#133]
Игроки при использовании арсенала в большинстве случаев видят задницу прапора. С этим надо что-то делать.
![20160810014425_1](https://cloud.githubusercontent.com/assets/3309152/17630602/a2bad9ee-60c8-11e6-989f-2b97c3090667.jpg)

**Comment by Noart537** [comment]
И ещё добавьте в арсенал ракеты от РПГ-7
