### ISSUE TITLE
Правки арсенала

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#136]
Вчера зашёл на Алтис за пилота, при выборе Vermin в арсенале, не смог загрузить магазины, в списке боеприпасов было пусто. Есть жалобы на РПГ-7 с такой же ситуацией.

**Comment by ToxaBes** [comment]
Исправлено сегодня в #133

**Comment by Horizon1959** [comment]
Отлично.
