### ISSUE TITLE
Перенос наградных вещей в снаряжение

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#137]
Нужно попробовать следующее: если у партизан выпала награда в виде вещей, а не техники, то при ее вызове из списка доступных наград добавлять не ящиком на землю, а загружать все вещи в снаряжение ящика-базы. Нужно убедится что в него  можно засунуть бесконечное количество  вещей.
Также у партизан в награде может быть ящик с формой противника, нужно предусмотреть возможность выложить форму с ящика на землю и одеть через пункт меню.

**Comment by Noart537** [comment]
На сколько я знаю, в ящик, скриптом можно запихать сколько угодно всего. Но взяв от туда что-либо, обратно не положить. т.к. не будет места.

**Comment by malashin** [comment]
Если в контейнере несколько форм лежит, одеваем первую или извращаться с выбором?

**Comment by ToxaBes** [comment]
>Если в контейнере несколько форм лежит, одеваем первую или извращаться с выбором?

Игрок сам выкидывает нужную форму на землю и потом одевает.

**Comment by malashin** [comment]
Под контейнером я имел в виду GroundWeaponHolder. В нем может быть несколько форм. В итоге сейчас берет первую в контейнере которая начинается с "U_O_" или "U_C_", т.е. CSAT и Civilian. Скрипт кривой достаточно, т.к. удалить один объект из контейнера нельзя, только все сразу. Если в этом GroundWeaponHolder будет лежать контейнер с вещами внутри, типа рюкзака, то вещи эти пропадут. Вещи эти можно достать пройдя по всем контейнерам внутри через everyContainer, собрав массивы всех типов вещей и распихав в новый GroundWeaponHolder, но я решил забить на это. Смотрю только на шмот внутри юниформ которую одеваем и которая одета на игроке.

**Comment by ToxaBes** [comment]
А что вернет cursorObject? сам контейнер или форму?
Если возвращает контейнер то не заморачивайся - бери первую, как есть сейчас.
