### ISSUE TITLE
Радар

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#138]
Этой проблеме уже больше 5 лет. Т.к. у нас есть PvP то нужно как-то отлавливать и убирать пустую технику на радаре (серый квадратик "empty"). 
![arma3radartargettypes](https://cloud.githubusercontent.com/assets/3309152/17644145/a106fef6-6187-11e6-8be3-78003c82f803.png)

**Comment by Horizon1959** [comment]
Плюсую, её вроде нет, но на радаре тонна серых квадратов.

**Comment by ToxaBes** [comment]
Полностью скрыть серые квадратики без изменений в движке невозможно. Поэтому мы скроем их иначе - с завтрашнего дня на обеих картах появляется гражданское население, примерно десяток машин. Убийство гражданского - 5 минут клетки. Если убийство было с беспилотника - смерть беспилотника.

**Comment by Horizon1959** [comment]
А эти неприкасаемые будут респавнится?

**Comment by ToxaBes** [comment]
Конечно. Но я оставил синим лазейку что с этим можно делать: можно делать досмотр/облаву, сбивать машинам колеса - они будут останавливаться, водитель будет выходить. Т.е. можно, потратив какое-то время, обездвижить все машины в районе (если встать на пути у бота он начнет тормозить), затем поискать в этом районе базу либо партизан. После чего перейти в следующий район и тд.
Партизаны не могут использовать машины ботов и не могут ездить с ними пассажирами. 
Я думаю, опытные игроки быстро научатся распознавать кто есть кто по поведению, но тотального геноцида авиацией уже не будет.
