### ISSUE TITLE
Беруши для пилотов

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#14]
Авто включение при заходе в кабину. Возможность переключения в меню действий.

**Comment by Horizon1959** [comment]
Во многом я именно из-за шума не сажусь в вертолёты, фича была бы очень полезной. Сейчас всё равно люди включают карту и отдаляют её, звук пропадает, а игрок не видит окружающий мир.

**Comment by malashin** [comment]
Беруши только в вертолетах нужны?

**Comment by ToxaBes** [comment]
да

**Comment by malashin** [comment]
Сделал так, чтобы при входе в вертолет беруши сами вставлялись и вытаскивались после выхода. При этом всё время в экшн меню можно вставить/вытащить беруши независимо от техники.

**Comment by malashin** [comment]
Громкость снижается в два раза. Без беруш 1, с берушами 0.5. Если нужно еще тише сделать, то пишите.

**Comment by ToxaBes** [comment]
Ты сделал для все техники? Не только для пилотов вертов?

**Comment by malashin** [comment]
Вообще у всех игроков всегда доступно это действие в экшн меню, даже пешком. Но при посадке в вертолет беруши сами вставляются и убираются после высадки.

**Comment by ToxaBes** [comment]
а пешком-то зачем? Добавь проверку
```sqf
if (vehice player != player) then {
   //показываем в меню беруши
};
```

**Comment by malashin** [comment]
Как вариант если ты стоишь рядом с вертолетом или громкой техникой.

В принципе, смысла не так уж и много. Но большинство подобных скриптов просто дают действие в экшн меню. Я это дело оставил, но добавил автоматизацию для вертолетов.

Сделать только внутри техники?

**Comment by ToxaBes** [comment]
да

**Comment by ToxaBes** [comment]
и по автоматическому включению - нужно его сделать только для шумной техники: самолеты/вертолеты. В остальной технике включение только вручную (на самом деле беруши вназемной техники вообще не нужны - там нет такого шума, но если сделал то пусть будет).

**Comment by malashin** [comment]
Я сделал для всех вертолетов, т.к. изначально и спрашивал, только для нужно сделать или нет. Самолеты добавить не проблема.

Экш я оставил у пехов, чтобы симулировать наличие беруш, которые ты если хочешь можешь одеть, т.к. они у тебя в инвентаре лежат.

Сегодня сделаю только в технике экш виден чтобы был и самолеты добавлю в автоматику.

**Comment by ToxaBes** [comment]
Стоп стоп )
Если сделал только в вертолетах то так и оставляй - все верно. Видимо мне нужно было более детально сформулировать задачу.
Беруши в данном случае не затычки для ушей, а большие наушники, поэтому беруши работают только внутри вертолета. Для пилота он включаются автоматически, остальные кто в вертолеты - могут включить их вручную. При выходе из вертолета они автоматически выключаются.

**Comment by malashin** [comment]
Да лучше у всех сразу это делать, а не только у пилота. Проблемы как раз у пассажиров. У меня, как у человека постоянно летающего на вертолете, звук и так тихий стоит и мне беруши не нужны, на самом деле.

Сейчас у всех игроков севших в вертолет воткнутся беруши. При выходе из него они уберутся.

Помимо этого у всех игроков всегда доступен экшн беруш в любой момент не зависимо от техники. Я это переделаю и будет он виден только в технике.

**Comment by ToxaBes** [comment]
Ок, если экшн беруш будет доступен только в технике то согласен.

**Comment by ToxaBes** [comment]
Спасибо.

**Comment by 12st** [comment]
Беруши не включаются автоматом в самолётах, таких как бузард, вайпаут и неофорн. Приходится вручную тыкать.

**Comment by ToxaBes** [comment]
Лучше создать отдельный тике и пометить его багом. Поправил -> #123
