### ISSUE TITLE
Type-115 c .50cal

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#141]
Это оружие у синих должно быть доступно только пехотным снайперам, сейчас оно доступно всем кроме пилотов.

**Comment by 12st** [comment]
Недавно попробовал и ужаснулся, дальше 300 м стрелять стало практически нереально, разброс просто адовый. Правда она также эффективно выносит модули на технике, но станет ли пехотный снайпер её брать при наличии более мощного и удобного вооружения? Может стоит вернуть обратно всем классам или например командиру?

**Comment by Horizon1959** [comment]
Попадаю на 500 метров, уничтожает пеха сразу. Её лучше оставить пехотным снайперами.

**Comment by ToxaBes** [comment]
Подвтерждаю, на 500-600м ваншотит без проблем.

**Comment by 12st** [comment]
Ваншотит, но у неё довольно таки низкая скорость пули, по движущимся целям не постреляешь, к тому же при стрельбе по статичной цели, порой приходится делать по 3-4 выстрела, просто не попадает,пули уводит в сторону. К тому же нет возможности установить глушитель на доп ствол, все в округе сразу узнают где ты. И в итоге получается, что на дистанции в 500 м намного легче использовать любую 7.62 снайперку или если важен ваншот лучше подойдёт тяжёлая DMR из DLC. 

Однако данный ствол раскрывает свой потенциал именно  на дистанции до 300 м(дистанция обычного штурмовика. но никак не снайпера), дальше стрелять просто перерасход бк. Чтобы снести колесо с техники нужно 4 попадания, у 7.62 винтовок 5-6 однако со вторых намного легче. Адекватный снайпер не станет её брать при наличии более эффективного оружия(если мы не преследуем цель сделать из пех снайпера обычного штурмовика), получается у нас просто один никому не нужный ствол. Побегал один раз и забыл. Поэтому стоит разрешить использовать его хотя бы командиру.
P.S. Изменения после последних патчей, видимо порезали данный ствол увеличив ему разброс, уменьшив скорость полёта пули и уменьшив урон по технике.

**Comment by Horizon1959** [comment]
@12st марксмен действует в составе подразделения, тоже участвует в штурме. На практике марксмен с Type 115 не перерасходует БК, а ещё может помочь огнём 6,5. Даже ASP-1 Kir не стоит выдавать всем подряд.
Командиру нужны не модные пушки, а средства тактики. Сейчас в арме этих самых средств мало.

**Comment by 12st** [comment]
Сейчас на сервере такая ситуация, что часть вооружения не используется либо 1-2 человека  на весь сервер. 
MX SW
ASP-1 Kir
MXM
Type-115

**Comment by ToxaBes** [comment]
>Сейчас на сервере такая ситуация, что часть вооружения не используется либо 1-2 человека на весь сервер. 

Учитывая что на сервере в среднем не больше 10 чел в день, это нормально. Это из той же серии что и предложение разрешить всем ASP-1 Kir. У нас разделение: хочешь снайперские и специальные (ASP, Type-115) винтовки - заходи за пехотного снайпера. Хочешь anti-material rifles - заходи за снайпера.

**Comment by Horizon1959** [comment]
Опыт раздачи точного и сильного вооружения имел печальные последствия. Часть вооружения не используется из-за его устаревания или личных предпочтений синих.
