### ISSUE TITLE
Допка Угон

### ISSUE THREAD

**Issue by kovt** [ToxaBes/ADR-Spec-Ops#142]
Сегодня выполнял доп миссию Угон. На сервере был один, убил всех, сел в вертолёт, отлетел на километр, появляется табличка, "доп.миссия провалена, партизаны выполнили её раньше." После чего появилась надпись "доп задание выполнено" Награду не дали.

**Comment by Horizon1959** [comment]
@kovt  
![default](https://cloud.githubusercontent.com/assets/17685328/17701110/2906c00c-63d1-11e6-9e62-c4fa43e3873a.jpg)

**Comment by ToxaBes** [comment]
Спасибо, разберемся.
