### ISSUE TITLE
Лодочная станция

### ISSUE THREAD

**Issue by kovt** [ToxaBes/ADR-Spec-Ops#143]
Думаю имеет смысл убрать возможность респа миссий на лодочной станции, той что на северо-востоке от базы. Раньше это было не актуально так как не было обороны базы. Сегодня там реснулась основа, а за ней (после выполнения основы) допка. В итоге наши стационарные пулемётчики поубивали большую часть ботов. 
Лично мне не мешает. Тикет создал просто для информации.

**Comment by 12st** [comment]
Она там как раз таки и нужна. С другой стороны острова оплывать очень долго. А вот то, что стационары выкашивают это уже проблема.

**Comment by kovt** [comment]
Я не имел ввиду Лодочную станцию убрать. )) Она нужна, безусловно. Просто сделать так что бы миссии прям на ней не появлялись.

**Comment by ToxaBes** [comment]
Это на Таноа или на Алтисе?

**Comment by kovt** [comment]
На Алтисе.
