### ISSUE TITLE
Предложение по медицине.

### ISSUE THREAD

**Issue by Noart537** [ToxaBes/ADR-Spec-Ops#144]
Когда медик начинает лечить раненого игрока, то время, которое видит раненый игрок (300 сек), останавливается.

**Comment by Noart537** [comment]
![107410_20160819184252_1](https://cloud.githubusercontent.com/assets/8770445/17812346/1b3b7802-6640-11e6-8da3-1ac0f5d0c65b.png)

**Comment by malashin** [comment]
Я об этом давно думал уже. Так как задачи другие стояли, а этот функционал не так просто реализовать, решил не делать.

Но сделать, конечно, стоит в будущем.

**Comment by Horizon1959** [comment]
А в чём проблема?

**Comment by malashin** [comment]
Да сделать можно.

Сейчас логика такая, что идет проверка по ```(время смерти + 300) < время сервера``` каждую секунду. Решение попроще это добавлять секунду к этому времени во время лечения, но на мой взгляд это костыль какой-то. По идее должно быть ```300 - 1``` каждую секунду, если игрока лечат, то не вычитать. Проблема в том, что это не будет реальная секунда, а что-то очень близкое к ней и нужно переписать логику скрипта.

**Comment by Noart537** [comment]
Медик начинает лечить, переменная _h = true; А в цикле со временем доавить условие if (_h) then {sleep 5}; Получится так?

**Comment by Noart537** [comment]
Еще одна сложная вещь. Чем больше времени прошло с мосента ранения, тем дольше лечение. (в разумных пределах)

**Comment by ToxaBes** [comment]
Давайте подытожим:

1. При лечении таймер у игрока останавливается
2. Если с момента ранения прошло больше минуты то время лечения увеличивается на 5 сек каждую следующую минуту. Т.е. лечение на четвертой минуте займет на 15 сек больше времени чем в пределах первой минуты.

Таймер который использует системное время: https://community.bistudio.com/wiki/uiSleep

**Comment by ToxaBes** [comment]
@malashin и @Noart537 - у Вас есть возможность заняться этим тикетом?

**Comment by malashin** [comment]
У меня пока времени нет и на Арму я забил.

Может и возьмусь, но не в ближайшее время.

**Comment by ToxaBes** [comment]
Ясно, жаль. Если решишь вернуться, напиши - я восстановлю твой доступ.

**Comment by ToxaBes** [comment]
Готово, нужно будет потестить на сервере.
