### ISSUE TITLE
Рисование на карте

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#145]
БИСы добавили возможность рисования пенисов на карте, но забыли добавить возможность отключения этой полезнейшей вещи. Пока что мы можем пофиксить это двумя способами:

1. Прикрутить к арме PDA (Penis Detection Alghoritm): http://pda-pro.net/
2. Раз в десяток секунд проверять все полигональные маркеры на карте и удалять те которые поставлены не в зеленом (групповом) или желтом (транспортном) каналах.

**Comment by ToxaBes** [comment]
Пока сделал второй вариант. Всех проблем это не решает т.к. есть возможность рисования в 2х каналах, также можно рисовать точками, но это хоть как-то ограничит залетных художников.

**Comment by Horizon1959** [comment]
Спасибо Тоха, мы очень ценим твою заботу и защиту нас от пенисов. Теперь мы без тим спика и командира отделения не можем ставить метки пилотам через синий канал и координировать действия. Ты ещё запрети людям разговаривать об алкоголе, прикрути распознавалку слов, описывающих всё с алкоголем. Это как закон о нецензурной лексике, от которого в РФ лучше не стало с культурой общения, зато все нормальные матные слова запретили в искусстве.
Раньше у нас и без рисования на карте неадекваты спамили маркерами, но мы успешно сами всё регулировали.
![107410_2015-07-28_00002](https://cloud.githubusercontent.com/assets/17685328/17871237/5b4dca8c-68c3-11e6-8009-925be98f4845.png)

**Comment by ToxaBes** [comment]
> Теперь мы без тим спика и командира отделения не можем ставить метки пилотам через синий канал

В любой канал можно ставить все остальные типы маркеров, точки, кружочки, крестики и т.д. Ограничения только по линиям (ctrl+left mouse button). 

Если вот прям горит нарисовать что-нибудь пилоту - сделай это линией если ты с ним в одной вертушке, либо укажи другим типом маркера. Многие злоупотребляют этими линиями - обводят каждую высоту на основе вместо расстановки точек, рисуют на карте маршрут движения для каждого транспорта и т.д. Надоело.

**Comment by ToxaBes** [comment]
>Ты ещё запрети людям разговаривать об алкоголе, прикрути распознавалку слов, описывающих всё с алкоголем.

Это уже не моя проблема - в общий канал ТС больше не захожу, т.к. голова гудит - информации об игре ноль, а шуму и гаму как на базаре.

**Comment by malashin** [comment]
Смысла не вижу в этом. Даже если вдруг где-то что появится оскорбительное (ни разу этого не видел), то любой игрок может удалить это с карты.

Какая разница обвели высоту или точку поставили? Делают то, что быстрее и удобнее делается. Маршрут обычно один.

**Comment by ToxaBes** [comment]
>Даже если вдруг где-то что появится оскорбительное, то любой игрок может удалить это с карты.

Т.е. вместо того чтобы играть надо сидеть и вытирать с карты мусор? Ты не видел как SHAH вместо того чтобы играть - сидел и исправлял похабства на лету. Зашло несколько новеньких, кто из них рисует неизвестно.

>Какая разница обвели высоту или точку поставили? 

Ты видимо не встречал еще ситуацию когда метку просто не видно из-за обилия линий на карте. Карта это не детская раскраска, она должна быть читабельна. Несколько линий по делу это ок, но не вся карта исчерченная крест-накрест где уже не понять что по делу, а что нет.

**Comment by Horizon1959** [comment]
Богемия реализовала фичу, которую требовали команды годами - просто и удобно рисовать на карте маршруты, ключевые объекты, т.е. работать как с настоящей картой. Вместо этого мы опять должны по пол часа царапать-тыкать маркеры, выбирая цвет, вид картиночки (а стрелку-то не повернёшь, как в ACE моде).
Я наблюдал как вредитель гадил, но продолжалось это недолго, ему надоело. Тут вопрос в анонимности художника, можно ли как-то вычислить. кто это рисует?

**Comment by ToxaBes** [comment]
>Богемия реализовала фичу, которую требовали команды годами

Как по мне, линии нафиг не нужны. Точек достаточно. Но фиг с ним, добавили и добавили, но сделать ее неотключаемой - это надо быть полным идиотом.

О чем вы вообще, у нас паблик сервер. Я не хочу видеть такое в глобальных каналах, вы хотите?:
![20160531024446_1_zpsmezljwg8](https://cloud.githubusercontent.com/assets/3309152/17893949/3dad5c08-6950-11e6-8ccc-f47b4ce25f90.jpg)

>Можно ли как-то вычислить. кто это рисует?

Можно но оч. гемморно, т.к. придется выводить имя нарисовавшего радом с линией что еще больше захламит карту.  К тому же это фигня будет все больше нагружать сервер после запуска.
Проще оставить художества только в групповом, транспортном и оперативном каналах, что я и сделал.

**Comment by Horizon1959** [comment]
@ToxaBes вообще выпиющий случай, их много стало? Вон я же тоже скрин кидал, но это было до рисования. Может тогда ещё придумаешь что-нибудь с разбрасыванием техники на базе неадекватами?

**Comment by 12st** [comment]
@Horizon1959 на скриншоте не наш сервер.

**Comment by Horizon1959** [comment]
@ToxaBes @ToxaBes а на моём скриншоте TG2. если это не наш сервер, то в чём вообще проблема?

**Comment by ToxaBes** [comment]
У меня не осталось скриншота когда Шах закрашивал похабства, поэтому я взял скриншот с офф. I&A сервера, на миссии которого основана наша миссия, чтобы показать что я имею ввиду.  В том случае было тоже самое. Тогда я сохранил себе в todo разобраться с линиями в глобальных каналах. Руки дошли - разобрался.

**Comment by malashin** [comment]
Как вариант, можно админам добавить в инструменты временное отображение имен тех, кто нарисовал. Баны можно будет раздавать. Проблема в том, что храниться _id, а не _uid. При дисконекте толку от него ноль, если не записывать игроков в массив или базу.

**Comment by ToxaBes** [comment]
Проблема в том что можно выводить на карту или в лог только в сам момент рисования. В лог бесполезно т.к. там не понятна что за линия, на карту - перегрузка карты не нужной инфой в большинстве случаев.

Внимательно прочитайте еще раз: я ограничил рисование линий **ТОЛЬКО В ГЛОБАЛЬНЫХ КАНАЛАХ**. В остальных по-прежнему можно рисовать.

**Comment by Horizon1959** [comment]
@ToxaBes сначала глобальные, потом групповые, потом транспортные. Мы уже научены новыми демократическими законами про интернеты. Тут нужно не взять а запретить, а придумать, как это предотвращать или как наказывать хотя бы. Просто так взять и запретить - людоедство какое-то.

**Comment by malashin** [comment]
https://community.bistudio.com/wiki/allMapMarkers

Хранит _id игрока. Если заносить в массив имя и гуид каждого игрока при коннекте напротив _id. То в любое время админ сможет вызвать скрипт из Инструментов. У него на карте рядом с рисоваными маркерами появятся локальные маркеры с именами игроков, видимые только админу. Через секунд 10 удалять их.

**Comment by ToxaBes** [comment]
>Тут нужно не взять и запретить, а придумать, как это предотвращать или как наказывать хотя бы.

На данный момент решения, которое бы быстро работало - нет.

>Хранит _id игрока. Если заносить в массив имя и гуид каждого игрока при коннекте напротив _id. 

Я в курсе этого решения - с его помощью можно выводить на карту имя того кто писал. Вот только выводить на карту не вариант - захламляет. В идеале, выводить tooltip при выделении линии, но такого вроде тоже арма не позволяет.

**Comment by malashin** [comment]
Я же написал, что видеть будет только админ в течении 10 секунд.

**Comment by ToxaBes** [comment]
Тут есть вопрос реализации, ты сразу хочешь выводить на 10 сек? Или сделать в виде админ утилиты? Если сразу то не имеет смысла т.к. через 10 сек пропадет, админ может не увидеть или его может не быть на сервере. Если админской утилитой, то AllMapMarkers вернет тебе массив значений вида 
```
_USER_DEFINED #12345/1/2/3
```
формат:
```
_USER_DEFINED #<PlayerID>/<MarkerID>/<ChannelID>
```
где <MarkerID> - порядковый номер маркера, а не его идентификатор, т.е. по нему ты не обратишься. В  этом случае в массив нужно сохранять не только данные юзера но и эту строку маркера, а затем заново в цикле пробегать по всем маркерам чтобы найти маркер с этой строкой.
Прежде чем рассуждать об этом дальше, приведи мне примеры почему игрокам нужно рисовать линиями в глобальных каналах.

**Comment by Horizon1959** [comment]
@ToxaBes в глобальных каналах можно рисовать маршруты обхода для отрядов, помечать пилотам целые области для высадки (маркер в данном случае полная жопа, так как пилот должен видеть в какой области ему нужно работать, а не ориентироваться на абстрактную точку). В конце концов это быстрый способ отметить предполагаемую область обстрела или источника стрельбы для взаимодействия между подразделениями, а ещё рисовалка позволяет задать векторы атаки.

**Comment by ToxaBes** [comment]
>рисовать маршруты обхода для отрядов

можно рисовать своему отряду в зеленый канал. Соседнему отряду будет рисовать его командир. Либо рисуй им точку на месте встречи.

>помечать пилотам целые области для высадки (маркер в данном случае полная жопа, так как пилот должен видеть в какой области ему нужно работать, а не ориентироваться на абстрактную точку).

рисуй линии пилотам в оперативный канал, либо если в вертушке находишься - в транспортный

>В конце концов это быстрый способ отметить предполагаемую область обстрела или источника стрельбы для взаимодействия между подразделениями, а ещё рисовалка позволяет задать векторы атаки.

В конце концов у нас у синих 2 пехотных отряда, у каждого есть свой командир который и должен рисовать на карте. Хочешь командовать - ок, иди на слот командира и командуй, а не бегай медиком или еще кем. Также играя за партизан несколько раз спасался видя как меня обводят линией в глобальном канале )

**Comment by Horizon1959** [comment]
@ToxaBes у нас не хватает людей, чтобы всегда было два командира отделения. Мы не можем и пару полноценных ударных групп наскрести.
В оперативный канал может рисовать только командир отделения, опять же, проблема в онлайне. Если ты не в вертушке, то указать пилоту нормальную зону высадки ты уже не можешь.
У партизан классы совмещены, у нас же сейчас тупо не хватает людей для формирования двух полноценных ударных групп, т.к. с этими модными каналами нам нужны как минимум:

1. командир отделения
2. медик
3. медик
4. инженер
5. пулемётчик/пехотный снайпер - любой стрелок, который может быть ранен

Если же мы при наличии партизан не собираем две ударные группы, то зелёные спокойно захватывают первый объект, который находится дальше основного замеса, а затем сидят и ждут захват второго объекта синими, чтобы нажать кнопку на первом. Дальше идёт автоматический слив.

А вообще получается, что люди всё равно будут наблюдать пенисы, но в зелёном/жёлтом канале, т.е. проблему пенисов это не решает, но позволяет зелёным не наблюдать это чудо?

**Comment by ToxaBes** [comment]
>у нас не хватает людей, чтобы всегда было два командира отделения. Мы не можем и пару полноценных ударных групп наскрести.

Заходите в одну группу. 

>Если ты не в вертушке, то указать пилоту нормальную зону высадки ты уже не можешь.

Используй точки, Люк.

>А вообще получается, что люди всё равно будут наблюдать пенисы, но в зелёном/жёлтом канале

Это психология, если школьник не может рисовать на весь сервер - он сдуется.

>Если же мы при наличии партизан не собираем две ударные группы, то зелёные спокойно захватывают первый объект

Эм, зеленых редко больше 1-2 чел. Думаешь, просто захватить в 1-2 лица купол или вышку?

Вообще, я тебе сейчас отвечаю как одному из признаных командиров на сервере. Не хватает л/с? Ищи, агитируй, собирай отряд.

**Comment by Horizon1959** [comment]
@toxabes Зайти в одну группу тоже не вариант, т.к. у нас остаётся один оператор БПА/механик-подрывник вне отряда, что усложняет коммуникацию без тим спика и те же обозначения зон. Бывает, что и второй снайпер оказывается во втором отряде.
Точки не позволяют выделить целую область (если ими не затыкать её, что очень долго и глупо). Пилотам теперь намного понятнее, когда им рисуют область высадки, у них от этого больше свободы действий и пехота всегда знает, где их высадят.
Психология современного школьника-дегенерата не ставит славу или троллинг во главу кайфа, сейчас они просто хотят нагадить. Вымирание говна под дверь людям как смысл жизни.
По зелёным всё проще: они все опытные и даже один-два зелёных могут взять пустой объект, пока вся пехота противника ушла от него к синим. Это отлично было показано на подводной миссии лично тобой. 
По личному составу всё сложнее. У меня достаточное количество людей, но они никогда не могут одновременно зайти, 4-6 человек точно есть.  Чтобы вытащить людей всем скопом, нужно серьёзное мероприятие, согласование (у всех разные часовые пояса, личная жизнь и возможности), а это для обычного 3-4 часового замеса не подходит, скорее для тушняка.

Тут или систему отрядов надо переделывать или количество классов в отряде. Или спокойно позволить игрокам самим регулировать художества, как это было с маркерами, где дегенераты писали всякие гадости и буквально спамили такой пакостью, но никто не жаловался и спокойно разгребали всю эту помойку. Что уж говорить, недавно мы видели бардак на базе, но я скоординировал субботник и мы прибрались за пару-тройку минут.

**Comment by ToxaBes** [comment]
Я тебя услышал. Пока оставлю как есть, посмотрим. Если будет много жалоб, уберу ограничение.

**Comment by Horizon1959** [comment]
@ToxaBes спасибо. Если действительно тот ад, что выше будет часто, то лучше ограничить, но пока мы справляемся и без автоматической модерации.

**Comment by ToxaBes** [comment]
Добавил синий канал в разрешенные, теперь линии в синем канале будут видны всей стороне.

**Comment by 12st** [comment]
Теперь когда стало видно кто именно ставит метки, может стоит вернуть линии во все каналы?

**Comment by Horizon1959** [comment]
@12st сейчас ещё и новая система меток, привязанных к каналам.
