### ISSUE TITLE
Предложение по переработке основы

### ISSUE THREAD

**Issue by SooNDooCK71** [ToxaBes/ADR-Spec-Ops#148]
вначале : на карте нет ни чего , нет союзников , нет тригеров , игрока видно только при наличии gps или терминала бпа . информация о противнике появляется в письменном виде (скажем "враг замечен в пяти километрах на восток от сирты").воздуха изначально нет , вызывают его с вышки при обнаружении противника , время подлёта скажем 3 минуты , воздух злой , добивает даже покинутую технику , но бк ограничен , как только отстреливает , уходит на дозаправку , скажем на 10 мин . отпадает необходимость возить кучу стационаров , есть возможность переждать . т.к зачастую игроков бывает мало необходимо ввести возможность "стэлс" прохождения . полезно и для синих и для партизан . для этого на основе должны находиться не две ключевых точки (вышка,кп) ,а три : кп , вышка , узел связи . на кп вышка военного склада , на которой 3 терминала . штаб военного склада , в котором офицер ( сюжет-ахантерос ) без оружия . охрана греки , незначительная . для выполнения синим нужно подорвать терминалы одним зарядом .убить офицера . партизанам напротив нужно взломать каждый терминал и допросить офицера . тем самым каждый выполняет свою задачу и кто быстрее . кп окружён большими полевыми укреплениями . вокруг кп на значительном расстоянии , для возможности скрытного прохождения , 4 бункера (маленьких) под камуфлированным брезентом для техники со стационарами ( греки) и патруль из двух страйдеров с вооружением . вышку , считаю , нужно менять на вышку (land_communication_f) + рлс(маленькая) , т.к. стандартную легко обнаружить из за размеров .новая вышка: вышка , рлс , 2 бункера(маленьких) под брезентом и склад военных грузов с терминалами внутри . охрана греки .  вокруг вышки  4 дос(шестиугольных) на знач. расст. для прохождения синим необходимо взорвать терминалы зарядом , вышку+рлс подрыв.пакетом . партизанам необходимо взломать 3 терминала . взорвать вышку при желании лишить противника воздушной поддержки . НОВИНКА : узел связи - спутниковая антенна , спутниковый телефон ,терминал с оператором бпа(возможность партизан захватить дартер) под палаткой с ик маскировкой . рядом дос(большое)с пехотой и дос(шестиугольное) с пехотой .возможно стомпер. находится на ЗНАЧИТЕЛЬНОМ удалении от кп и вышки и является приоритетной , но не ключевой целью . ФУНКЦИИ : при объявлении тревоги вызывает подкрепление csat .скажем после тревоги в течении минуты нужно убить оператора бпа , тогда покрепления не будет , если этого не сделать через 3 минуты на точку прибывает колонна : 3 грузовика с пехотой , 2 ифрита , камыш , марид , зенитка , танк . возможно появляется поддержка арты . грузовики сразу разъезжаются по трем целям обороны . для прохождения синим необходимо убить оператора , подорвать зарядом терминал . партизанам убить оператора , взломать терминал . ДЛЯ СТЭЛСА : необходимо вихрем ворваться на кп , выполнить необходимые действия и успеть уйти до подхода подкрепления . необходимо что бы все позиции противника были замаскерованны  . вокруг должны действовать 4 полных отделения viper и 4 снайперских группы ( замена патрулей) при объявлении тревоги они начинают движение к точке обнаружения противника . ПАРТИЗАНЫ . очень не понравилась возможность пополнять бк любого оружия арсеналом . необходимо исключить эту возможность , а бк пополнять за счёт взлома терминалов . скажем каждый терминал ящик . так же можно сделать и с каждой допкой и тогда обе фракции смогут завершить миссию , а можно и пакостить . надеюсь что нибудь из предложенного понравится

**Comment by 12st** [comment]
Предложения интересные, но если всё это вводит получится совсем другой режим, а не то, что у нас есть. Легче сделать заново всю миссию, чем добавлять всё в таком виде сюда.
Стелс в арме тяжело реализуем, и НЕ криво его сделать тяжело.На счёт вышки, можно добавить просто ещё один вариант как ты и описал. Дозаправка штурмовиков тоже вещь тяжело реализуемая, боты не умеют сажать самолёты на доп аэродромы, как вариант раз в 10 минут просто удалять его на какое-то время. Подкрепления уже предлагали сделать #50 , от идеи отказались из-за того, что оборону часто проваливали, возможно стоит вернутся к обсуждению этого. 
P.S. читать было трудно)

**Comment by SooNDooCK71** [comment]
не совсем верно раскрыл мысль про воздух , но ты меня понял и подправил . читать трудно , потому что максимально сжато писал ))) так то нужно и скрины из редактора делать , чтоб люди видели , когда читали , а не додумывали

**Comment by SooNDooCK71** [comment]
и по сути это не подкрепление , а основная группа противника

**Comment by SooNDooCK71** [comment]
просто при определённом прохождении можно избежать её появления . как раз когда играют один-два человека

**Comment by 12st** [comment]
На счёт разделения целей для партизан и синих, такое предлагал сделать горизонт. Суть тут такая, например синим нужно уничтожить вышку, а партизанам передать с помощью неё что-то. Синим не захватить кп, а уничтожить. Это добавило бы конфликт интересов и каждая сторона пыталась сделать быстрее другой.

**Comment by SooNDooCK71** [comment]
вот об этом и речь , если партизаны , сейчас , захватывают кп , туда уже смысла ехать нет , а если сделать разделение задач , то всем работы хватит .

**Comment by 12st** [comment]
@SooNDooCK71 В данном контексте это получается подкрепление, которое вызывается по событию, с возможностью его отмены.

**Comment by Horizon1959** [comment]
@SooNDooCK71 штурмовик на основе давно больная тема. Если его убрать, то будет совсем легко, если оставить, то без пилотов сделать с ним что-то весьма сложно и нудно. Сейчас с этим легче, т.к. не всегда появляется самолёт противника.

Тактику стелса против ботов не получится применять, у них мозги электронные, хитрые.

На счёт задач я уже озвучивал свои мысли: партизанам и войскам синих должны выдаваться разные задачи, но эти задачи должны пересекаться между собой, чтобы образовался конфликт. К тому же, задач должно быть больше двух, и награды должны выдаваться обеим сторонам в зависимости от сложности выполненной задачи и с учётом количества выполненных задач.

Подкрепления=нагрузка на сервер. Но в то же время у нас банальный тир, т.к. свежие силы противнику не поступают. Можно было бы спавнить подкрепления от штаба противника при наличии линии снабжения, которую в свою очередь надо отрезать (линии снабжения были в Arma 2). Но тогда и должен быть передовой аванпост с волновым спавном синих.

**Comment by SooNDooCK71** [comment]
да , но изначально на точке должны находиться незначительные силы . скажем 30 процентов от того что имеется сейчас . опять же тоха говорил что мы редко когда находим всех ботов с точки . так вот таким образом можно собрать тоже число , но на более ограниченном пространстве . кто хочет фана , идет напролом и воюет со всем что есть , кто хочет меньше умирать -находит скрытные пути и воюет минут 5 , а потом пытается скрыться . вобщем  мысль высказал )

**Comment by ToxaBes** [comment]
@SooNDooCK71 - отличный поток сознания ) но если осилить прочтение то все по делу.

>вначале : на карте нет ни чего , нет союзников , нет тригеров , игрока видно только при наличии gps или терминала бпа . информация о противнике появляется в письменном виде (скажем "враг замечен в пяти километрах на восток от сирты").

Идея не для этой миссии. Я реализую ее в другой миссии, там вначале у тебя еще и оружия в 50% не будет, вообще...

>ДЛЯ СТЭЛСА : необходимо вихрем ворваться на кп

Эм, так стелс или вихрем? Сделать стелс в арме очень сложно, у меня есть идея, но она не для данной миссии.

>если партизаны , сейчас , захватывают кп , туда уже смысла ехать нет , а если сделать разделение задач , то всем работы хватит .

Нет смысла делать разделения задачи например по КП. Если партизаны должны передать что-то, а синие захватить, то что мешает и тем и другим по-очереди это сделать. Кто тогда выиграл? А?
Суть в конкуренции - кто первый сделает задачу тот и молодец.

>очень не понравилась возможность пополнять бк любого оружия арсеналом

Так работает сам арсенал. Решение только в убирании арсенала для партизан, что даст свои минусы (гемор с базовым доступным шмотом).

Из всего написанного видно две вещи:

1) ты хочешь новых допок/спецопераций пусть и на основе т.к. старые приелись. 
2) ты хочешь больше хардкора т.к текущй уровень сложности уже не устраивает

Даже если сделать все то что ты написал (а это займет довольно много времени) то нововведений хватит на месяц-другой. 
Поэтому мы пойдем немного другим путем. В следующий версии миссии будет режим [endless game](https://github.com/ToxaBes/ADR-Spec-Ops/issues/74) который и разбавит "приевшийся" захват точки, а "хардкорные" вещи я потихоньку внедряю в другую, пока что приватную миссию "EasyGame".

**Comment by SooNDooCK71** [comment]
"стелс" заключается в том , что бы обойти патрули и другие две точки , которые по сути лишь мешают выполнить задачу , не подняв тревогу , потом за 4 минуты убить/допросить офицера , подорвать/взломать терминалы и успеть уйти от подкрепления . дальше , суть конкуренции между партизанами и синими заключается в том что если они не успеют на кп , то синие подорвут терминалы и убьют офицера , тем самым оставят партизан без ништяков .а партизаны бомжи и выхода у них два : кидаться на амбразуру или ждать пока не зайдут синие и не атаковать их . в любом случае если синие зашли раньше партизаны провалили миссию , а если партизаны зашли раньше , то могут устроить засаду , минировать , ведь всё равно точку кому то закрывать надо . но и закрыть они её тоже могут выполнив задачи синих . и последнее )) хардкор должен быть вменяемым , а не доводить до истерик )))я больше не за хардкор , а за приближение к реализму , поэтому бесконечный бк у воздуха меня не очень радует , мины вокруг всей вышки , ведь как то надо её обслуживать , закрытая забором допка желтый туман , ведь как то они туда зашли и т.д . я просто хочу вернуть большую часть игроков , при этом режим пвп мне нравится , вот поэтому считаю и нужно найти золотую середину , чтобы каждый смог с удовольствием отдыхать после работы . опять же не понимаю игроков , которые кричали о том что бесит когда боты убивают сквозь траву , очень меткие , живучие , так вам дали равного противника , который тоже не видит , устаёт , промахивается , ошибается , всё равно слились

**Comment by ToxaBes** [comment]
>суть конкуренции между партизанами и синими заключается в том что если они не успеют на кп , то синие подорвут терминалы и убьют офицера , тем самым оставят партизан без ништяков 

Можно сделать так что если синие захватили КП/Бункер то через 5 мин ящики с оружием на КП исчезают. 

>поэтому бесконечный бк у воздуха меня не очень радует

Ну считай что там куча ящиков с БК. У синих это не проблема. Проблема только у арсенала партизан, я еще думаю что с ним делать.

>мины вокруг всей вышки , ведь как то надо её обслуживать

Есть карта прохода в поле, по улитке. У синих и партизан такой карты нет.

>закрытая забором допка желтый туман , ведь как то они туда зашли

Вер-то-лет. Грузовыми притащили грузы, маленьким привезли охрану.

> я просто хочу вернуть большую часть игроков

Для этого достаточно сделать 2 вещи:
1. Вернуть вид от 3го лица
2. Убрать ограничения по оружию
(Но в таком виде сервре не будет нужен уже мне)

>опять же не понимаю игроков , которые кричали о том что бесит когда боты убивают сквозь траву , очень меткие , живучие , так вам дали равного противника , который тоже не видит , устаёт , промахивается , ошибается , всё равно слились

Ну во-первых, не у всех есть достаточно времени чтобы играть постоянно, тем самым получая скилл и чувствуя себя комфортно в сложном режиме. А во-вторых люди очень часто представляют себя лучше и опытнее чем они есть на самом деле, в итоге реальность оказывается болезненной и они уходят куда попроще. Это нормально. Многие просто хотят расслабится после рабочего дня часик другой не заморачиваясь.

**Comment by SooNDooCK71** [comment]
со всем согласен кроме одного , воздух должен "исчезать" для пополнения бк и дозаправки горючего , наши пилоты ведь не таскают на крыльях буззарда канистры и ящики )))это придаст мобильности и синим и зелёным , но не сильно упростит игру . опять же это только моё мнение )) к сожалению без постоянно занятых 8-9 слотов игроков новые заходить не будут , а новые , пусть даже по началу не опытные , это фан . и менять что то нужно , вспомни , основной приток начался из за того что пошли отличия от второго tehgama , и админ слушал пожелания )))))

**Comment by Horizon1959** [comment]
@SooNDooCK71 Игроки все на месте. Малый процент не играет в арму вообще, по причине усталости от всей концепции игры или из-за смены обстановки IRL (рождение ребёнка, дедлайн на работе, командировка).
Если нужен хороший годный замес, то надо мутить мероприятия по выходным. Для мероприятий требуется продумать концепцию, сценарий, подготовить карту, оповестить людей и скоординировать их. Если собрать людей я и могу, то вот с организацией сценария и карты надо шаманить другим людям, т.к. у меня лично не хватает знаний и личного времени для освоения скриптов в редакторе и опыта построений Зевс-миссий.
Читал о тусовках на имиджбордах, которые договариваются о мероприятиях, качают аддоны и рубятся в pvp с участием Зевса. Но у них pvp, нагрузка не такая сильная, как с ботами.

**Comment by ToxaBes** [comment]
Добавил то что подходит по по концепции сервера в  #149

**Comment by ToxaBes** [comment]
Данный тикет закрываю, все что отсюда взято перенес в 149й.
