### ISSUE TITLE
Блокирование рампы и бортовых пулеметов пилотами

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#15]
- [x] По-умолчанию рампа заблокирована. Изменение через меню действий.
- [x] По-умолчанию бортовые пулеметы заблокированы. Изменение через меню действий.

**Comment by Horizon1959** [comment]
Пилоты сильно бесятся от стрельбы в вертолёте и открытия рампы, тут вводить фичу надо 100%.

**Comment by malashin** [comment]
Хурон и Гостхок который на базе появляются, теперь с выключенными по умолчанию бортовыми пулеметами (включить их может только пилот).

Рампы вертолетов может открывать/закрывать только пилот, у других игроков появится сообщение "Данное действие доступно только пилоту". Снятие блокировки пилотом решил пока не делать, смысла не вижу.

Убрать стандартное действие открытия/закрытия рампы из меню действий нельзя, только если в конфиге менять значения.

Само это действие называется "UserType". Может с чем-то еще пересечься, т.к. название уж больно общее, но при тестировании я не нашел таких.

**Comment by ToxaBes** [comment]
спасибо,  сегодня применю на сервер.

**Comment by 12st** [comment]
Нужно добавить блокировку рампы в новые самолёты.

**Comment by malashin** [comment]
А есть какие-то с этим проблемы? В них и так только пилоты могут открывать рампу. Всё что измениться это то, что второй пилот не сможет её открыть.
