### ISSUE TITLE
Недоступные предметы в виртуальном арсенале

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#150]
Переделывал комплекты снаряжения, обнаружил, что на миссии Алтиса нет возможности выбрать цвета глушителя для MX, доступен только чёрный. Если зелёный здесь не нужен, то песочный вписался бы в самый раз.

this addPrimaryWeaponItem "muzzle_snds_H_snd_F"

![107410_20160902233553_1](https://cloud.githubusercontent.com/assets/17685328/18217573/3eee7688-7166-11e6-9489-24d2e7ce517b.png)

![107410_20160902234601_1](https://cloud.githubusercontent.com/assets/17685328/18217785/7175e770-7167-11e6-893e-ac0a489b64d7.png)

**Comment by Horizon1959** [comment]
На Таноа прицел LRPS Hex не удаляется скриптом при игре за инженера.
![107410_20160903155342_1](https://cloud.githubusercontent.com/assets/17685328/18224921/be1a3c84-71ee-11e6-80ba-85b8b621aa26.png)

**Comment by ToxaBes** [comment]
Спасибо, поправлю.

**Comment by Horizon1959** [comment]
Добавьте ещё пожалуйста в раздел рюкзаков вещмешок MTP, его сейчас нет. На Таноа он не нужен.

![107410_20160904153713_1](https://cloud.githubusercontent.com/assets/17685328/18231029/c18adff0-72b5-11e6-9747-4d9a905c2471.png)

**Comment by ToxaBes** [comment]
Пофиксил.
