### ISSUE TITLE
Дальность прорисовки БПА

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#151]
Сейчас прорисовка БПА подстраивается по пехотинца, т.е. если пехотинец просто открыл терминал - максимум 3000 метров, если же он сел в мащину - 5000 метров, в авиацию - 6000 метров. Можно ли сделать в меню прорисовки отдельную шкалу для БПА?

**Comment by 12st** [comment]
Если сесть в машину и выставить прорисовку на 5 км, то и в бпа тоже будет 5 км.

**Comment by Horizon1959** [comment]
@12st я про это и говорю. Если ты пешком открыл терминал и подключился к БП-авиации, то почему у неё прорисовка пехоты?

**Comment by 12st** [comment]
Арма работает так, что ты берёшь ботов внутри бпа под контроль, поэтому прорисовка зависит от твоей в данный момент.

**Comment by Horizon1959** [comment]
@12st спасибо кэп, но у RF есть отдельная шкала прорисовки БПА на скрипте.

**Comment by Noart537** [comment]
https://github.com/ToxaBes/ADR-Spec-Ops/blob/master/co30_ADR_Spec_Ops.Tanoa/scripts/taw_vd/fn_updateViewDistance.sqf
Первый case

 case (!(EQUAL(SEL(UAVControl getConnectedUAV player,1),""))): {
		setViewDistance tawvd_drone;
		_dist = tawvd_drone;
	};

**Comment by Noart537** [comment]
Проще так.
[taw_vd.zip](https://github.com/ToxaBes/ADR-Spec-Ops/files/453807/taw_vd.zip)

**Comment by Noart537** [comment]
Если хотите могу заняться.

**Comment by ToxaBes** [comment]
Хотим, занимайся.

**Comment by Noart537** [comment]
![107410_20160906215833_1](https://cloud.githubusercontent.com/assets/8770445/18283124/3e8806e0-747d-11e6-9888-ae58de92c42f.png)
![107410_20160906215932_1](https://cloud.githubusercontent.com/assets/8770445/18283126/40e44138-747d-11e6-920a-ac685562a126.png)

**Comment by Horizon1959** [comment]
БПЛА - беспилотный летательный аппарат, у нас же БПА. Докопался:)

**Comment by Noart537** [comment]
Летательные тоже есть)

**Comment by Horizon1959** [comment]
@Noart537 чтобы путаницы не было, надо писать БПА, а то будут думать, что это не касается стомпера.

**Comment by Noart537** [comment]
Если подумать, то стомперу 6 км не нужны) он стреляет же на 1500 м.

**Comment by Horizon1959** [comment]
@Noart537 нужны для наблюдения за противником и отслеживания авиации.

**Comment by Noart537** [comment]
Скрипт, обновил. Если надо Антон сделает как надо ;)

**Comment by ToxaBes** [comment]
Эм, ты просто взял и затер предыдущий скрипт? Молодчина ) Цветокоррекция и прочие изменения видимо были дотационными. Суть задачи была не скопипастить скрипт а посмотреть как там сделана одна полоска для БПА и сделать ее у нас. Сохранение тоже не нужно.

**Comment by Noart537** [comment]
Да, вышла новая версия скрипта, я подумал будет лучше обновить полностью.

**Comment by ToxaBes** [comment]
В новой версии скрипта нет наших изменениий и она содержит в 2 раза больше файлов только из-за фичи сохранения пресетов которая нам не нужна. Из-за это раздувать миссиию и затирать то что уже есть считаю нелогичным. Коммит отменил.

**Comment by Noart537** [comment]
Цветокоррекцию не увидел, думал что там стандартный стоит с техгама2 с изменениями по дальности прорисовки. Завтра в старый доблавлю тогда БПЛА строку.

**Comment by Horizon1959** [comment]
@ToxaBes а ведь фича сохранения набор дистанций крутая. Любой инженер может матерясь рассказывать, как для воздуха и пешего штурма всё время меняет прорисовку ради  нескольких FPS.

**Comment by ToxaBes** [comment]
> @ToxaBes а ведь фича сохранения набор дистанций крутая.

Если ты чуть над ней поразмыслишь то поймешь что она бесполезна. Тебе все равно надо открыть диалог, открыть список сохраненных пресетов, выбрать нужный пресет и нажать загрузить. Действий столько же, если не больше как просто открыть диалог и изменить прорисовку.

>как для воздуха и пешего штурма всё время меняет прорисовку ради нескольких FPS

Это отдельные ползунки, один раз выставил и забыл. С появлением ползунка для БПА еще проще будет. Различные наборы прорисовок просто нафиг не нужны никто постоянно не меняет их.

**Comment by 12st** [comment]
Разная прорисовка для разных целей. Бывает когда часто пересаживаешься с вертолёта на самолёт и обратно, приходится менять прорисовку. Не знаю как у остальных, но у меня пролагивает во время изменения прорисовки и нужную не всегда удаётся поймать с первого раза.

**Comment by Horizon1959** [comment]
@12st @ToxaBes мне всё время приходится менять прорисовку как в настройках игры, так и в скрипте. Каждый раз мотать полоски туда-сюда - долго и ещё подвисает игра. Очень часто из-за такой фигни мою машину жгли.

**Comment by ToxaBes** [comment]
Посчитайте количество действий например при загрузке нужного пресета и при выставлении полоски Авиация вручную. И это, покажите мне на скрине кнопку "Загрузить".

Из-за третьестепенной фичи добавлять то количество кода которое было в коммите у Noart-a считаю нецелесообразным.

**Comment by Horizon1959** [comment]
Сейчас:

1. Нажимаем escape
2. нажимаем левой кнопкой мыши "настройки"
3. нажимаем левой кнопкой мыши "видео"
4. нажимаем левой кнопкой мыши "прорисовка"
5. выделяем левой кнопкой мыши значение
6. нажимаем backspace для удаления значения
7. нажимаем цифру
8. нажимаем цифру
9. нажимаем цифру
10. нажимаем цифру
11. нажимаем левой кнопкой мыши "прорисовка объектов"
12. выделяем левой кнопкой мыши значение
13. нажимаем backspace для удаления значения
14. нажимаем цифру
15. нажимаем цифру
16. нажимаем цифру
17. нажимаем цифру
18. нажимаем левой кнопкой мыши "ок"
19. нажимаем левой кнопкой мыши "продолжить" в меню паузы
20. крутим колёсико колёсико мыши
21. выбирается прорисовка
22. нажимаем пробел для вызова меню прорисовки
23. нажимаем левая кнопка мыши для движения ползунка пешей прорисовки
24. скроллится пешая прорисовка
25. нажимаем левая кнопка мыши для движения ползунка прорисовки машин
26. скроллится прорисовка машин
27. нажимаем левая кнопка мыши для движения ползунка прорисовки авиации
28. скроллится прорисовка авиации
29. обязательно один пролаг при скролле ползунка
30. нажимаем левой кнопкой мыши "закрыть"

Можно сократить количество тыканий мышкой, убрать лишнее движение ползунков. Ведь чем меньше рутины и действий, тем лучше, разве нет? Мне, как сисадмину, непонятно, почему нужно выполнять столько действий вместо автоматизации значительной части этих тыков и движений мышью. Неужели нельзя сократить количество кода? Неужели он будет так сильно вредить миссии?

**Comment by ToxaBes** [comment]
>[30 действий]
>Мне, как сисадмину, непонятно, почему нужно выполнять столько действий вместо автоматизации значительной части этих тыков и движений мышью.

Мне, как тимлиду, непонятно зачем сисдамин делает 30 действий там где можно сделать 5-8.
Также непонятно какое отношение к обсуждаемому скрипту имеют действия в меню игры, а это первые 19 пунктов, которые новый скрипт никак не убирает.

1. крутим колёсико колёсико мыши и выбираем прорисовку
2. нажимаем пробел для вызова меню прорисовки
3. нажимаем левая кнопка мыши для движения ползунка прорисовки, например, авиации
4. скроллится прорисовка авиации с лагами или без
5. нажимаем левой кнопкой мыши "закрыть"

Загрузка сохраненного пресета займет те же самые 5-6 действий. Такая "автоматизация" не дает никаких преимуществ, только раздутие миссии.

Ну и чтобы тебе было понятнее, объясню тебе на языке сисадминов: в данном случае делать загрузку пресетов для 3х ползунков все равно что соединять _вторым_ кабелем два уже соединенных неуправляемых свитча.

**Comment by Horizon1959** [comment]
@toxabes я тебя понял
