### ISSUE TITLE
Командирский ящик с боеприпасами

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#152]
Могу составить список предметов для командирского ящика, который вызывается через меню действий при игре за командира отделения.
Можно ли туда поместить больше предметов, чем вмещает ящик? Влияет ли это на вес, влияет ли это на лётные характеристики ящика?

**Comment by ToxaBes** [comment]
Нужно будет 2 списка, для Алтиса и для Таноа. Больше предметов можно поместить, но сильно увеличивать количество всего не стоит из-за летных характеристик и реализма. Придерживайся примерно того количества что есть сейчас +/-

**Comment by ToxaBes** [comment]
@Horizon1959 - как продвигаются дела со списком?

**Comment by Horizon1959** [comment]
Я на неделю выпал из онлайн, если сегодня-завтра свет дадут, то выложу.

**Comment by ToxaBes** [comment]
>если сегодня-завтра свет дадут, то выложу

Ох, вы держитесь там, всего доброго и хорошего настроения...
Я не тороплю, просто пингую.

**Comment by Horizon1959** [comment]
Свет пока не запилил, но есть три розетки с вожделенным электричеством. Так что выкладываю.
Алтис:

> _cargo addItemCargoGlobal ["FirstAidKit", 40]
_cargo addMagazineCargoGlobal ["30Rnd_762x39_Mag_Tracer_Green_F", 30];
_cargo addMagazineCargoGlobal ["30Rnd_65x39_caseless_mag_Tracer", 30];
_cargo addMagazineCargoGlobal ["30Rnd_65x39_caseless_mag_Tracer	", 10];
_cargo addMagazineCargoGlobal ["30Rnd_556x45_Stanag_Tracer_Red", 40];
_cargo addMagazineCargoGlobal ["130Rnd_338_Mag", 6];
_cargo addMagazineCargoGlobal ["150Rnd_93x64_Mag", 6];
_cargo addMagazineCargoGlobal ["200Rnd_65x39_cased_Box_Tracer", 6];
_cargo addMagazineCargoGlobal ["100Rnd_65x39_caseless_mag_Tracer", 15];
_cargo addMagazineCargoGlobal ["200Rnd_556x45_Box_Red_F", 10];
_cargo addMagazineCargoGlobal ["150Rnd_556x45_Drum_Mag_Tracer_F", 15];
_cargo addMagazineCargoGlobal ["10Rnd_50BW_Mag_F", 15];
_cargo addMagazineCargoGlobal ["10Rnd_93x64_DMR_05_Mag", 15];
_cargo addMagazineCargoGlobal ["10Rnd_338_Mag", 15];
_cargo addMagazineCargoGlobal ["20Rnd_762x51_Mag", 20];
_cargo addMagazineCargoGlobal ["20Rnd_650x39_Cased_Mag_F", 20];
_cargo addMagazineCargoGlobal ["SmokeShellBlue", 40];
_cargo addMagazineCargoGlobal ["B_IR_Grenade", 10];
_cargo addMagazineCargoGlobal ["HandGrenade", 10];
_cargo addMagazineCargoGlobal ["1Rnd_HE_Grenade_shell", 10];
_cargo addMagazineCargoGlobal ["3Rnd_HE_Grenade_shell", 10];
_cargo addMagazineCargoGlobal ["Titan_AA", 6];
_cargo addMagazineCargoGlobal ["Titan_AT", 6];
_cargo addMagazineCargoGlobal ["RPG32_F", 8];
_cargo addMagazineCargoGlobal ["NLAW_F", 4];
_cargo addMagazineCargoGlobal ["IEDUrbanBig_Remote_Mag", 2];
_cargo addMagazineCargoGlobal ["SatchelCharge_Remote_Mag", 2];
_cargo addMagazineCargoGlobal ["SLAMDirectionalMine_Wire_Mag", 4];
_cargo addMagazineCargoGlobal ["APERSBoundingMine_Range_Mag", 6];
_cargo addBackpackCargoGlobal ["B_Kitbag_mcamo_Eng", 2];
_cargo addBackpackCargoGlobal ["B_TacticalPack_mcamo", 2];
_cargo addBackpackCargoGlobal ["B_AssaultPack_mcamo", 2];
_cargo addItemCargoGlobal ["Medikit", 2]
_cargo addItemCargoGlobal ["ToolKit", 2]
_cargo addWeaponCargoGlobal ["arifle_MX_F",2];
_cargo addWeaponCargoGlobal ["arifle_SPAR_01_snd_F",2];
_cargo addItemCargoGlobal ["muzzle_snds_H_snd_F", 2]
_cargo addItemCargoGlobal ["muzzle_snds_m_snd_F", 2]
_cargo addItemCargoGlobal ["acc_pointer_IR", 2]
_cargo addItemCargoGlobal ["bipod_01_F_snd", 2]
_cargo addItemCargoGlobal ["optic_ERCO_snd_F", 2]
_cargo addItemCargoGlobal ["optic_Hamr", 2]

Таноа:

> _cargo addItemCargoGlobal ["FirstAidKit", 40]
_cargo addMagazineCargoGlobal ["30Rnd_762x39_Mag_Tracer_Green_F", 30];
_cargo addMagazineCargoGlobal ["30Rnd_65x39_caseless_mag_Tracer", 30];
_cargo addMagazineCargoGlobal ["30Rnd_65x39_caseless_mag_Tracer	", 10];
_cargo addMagazineCargoGlobal ["30Rnd_556x45_Stanag_Tracer_Red", 40];
_cargo addMagazineCargoGlobal ["130Rnd_338_Mag", 6];
_cargo addMagazineCargoGlobal ["150Rnd_93x64_Mag", 6];
_cargo addMagazineCargoGlobal ["200Rnd_65x39_cased_Box_Tracer", 6];
_cargo addMagazineCargoGlobal ["100Rnd_65x39_caseless_mag_Tracer", 15];
_cargo addMagazineCargoGlobal ["200Rnd_556x45_Box_Red_F", 10];
_cargo addMagazineCargoGlobal ["150Rnd_556x45_Drum_Mag_Tracer_F", 15];
_cargo addMagazineCargoGlobal ["10Rnd_50BW_Mag_F", 15];
_cargo addMagazineCargoGlobal ["10Rnd_93x64_DMR_05_Mag", 15];
_cargo addMagazineCargoGlobal ["10Rnd_338_Mag", 15];
_cargo addMagazineCargoGlobal ["20Rnd_762x51_Mag", 20];
_cargo addMagazineCargoGlobal ["20Rnd_650x39_Cased_Mag_F", 20];
_cargo addMagazineCargoGlobal ["SmokeShellBlue", 40];
_cargo addMagazineCargoGlobal ["B_IR_Grenade", 10];
_cargo addMagazineCargoGlobal ["HandGrenade", 10];
_cargo addMagazineCargoGlobal ["1Rnd_HE_Grenade_shell", 10];
_cargo addMagazineCargoGlobal ["3Rnd_HE_Grenade_shell", 10];
_cargo addMagazineCargoGlobal ["Titan_AA", 6];
_cargo addMagazineCargoGlobal ["Titan_AT", 6];
_cargo addMagazineCargoGlobal ["RPG32_F", 8];
_cargo addMagazineCargoGlobal ["NLAW_F", 4];
_cargo addMagazineCargoGlobal ["IEDUrbanBig_Remote_Mag", 2];
_cargo addMagazineCargoGlobal ["SatchelCharge_Remote_Mag", 2];
_cargo addMagazineCargoGlobal ["SLAMDirectionalMine_Wire_Mag", 4];
_cargo addMagazineCargoGlobal ["APERSBoundingMine_Range_Mag", 6];
_cargo addBackpackCargoGlobal ["B_Kitbag_mcamo_Eng", 2];
_cargo addBackpackCargoGlobal ["B_TacticalPack_mcamo", 2];
_cargo addBackpackCargoGlobal ["B_AssaultPack_mcamo", 2];
_cargo addItemCargoGlobal ["Medikit", 2]
_cargo addItemCargoGlobal ["ToolKit", 2]
_cargo addWeaponCargoGlobal ["arifle_MX_F",2];
_cargo addWeaponCargoGlobal ["arifle_SPAR_01_snd_F",2];
_cargo addItemCargoGlobal ["muzzle_snds_H_snd_F", 2]
_cargo addItemCargoGlobal ["muzzle_snds_m_snd_F", 2]
_cargo addItemCargoGlobal ["acc_pointer_IR", 2]
_cargo addItemCargoGlobal ["bipod_01_F_snd", 2]
_cargo addItemCargoGlobal ["optic_ERCO_snd_F", 2]
_cargo addItemCargoGlobal ["optic_Hamr", 2]

Ничего лишнего нет, всё по делу и утаскивается даже самым маленьким вертолётом.

**Comment by ToxaBes** [comment]
Спасибо! Сегодня применю.

**Comment by 12st** [comment]
Смущает один момент, прицел ERCO на алтисе. Хоть сейчас все имеют доступ к любым предметам из дополнения, но это могут в любой момент пофиксить. Может сразу подстраховаться?

**Comment by Horizon1959** [comment]
@12st этот прицел заточен под использование винтовок SPAR-16, зачем его удалять? Он даже правильного цвета.

**Comment by 12st** [comment]
@Horizon1959 Я не прошу удалять. Я говорю, что нет альтернативного прицела для людей без DLC.

**Comment by ToxaBes** [comment]
@12st поднял правильный вопрос (RCO прицел на алтисе для тех у кого нет APEX).

И еще момент, наверное надо будет добавить экшн уничтожения ящика. Т.е. синие вызвали ящик - налутались - уничтожили его. А то ведь партизаны тоже видят дым в небе и могут подождать пока синие налутаются и уйдут.

**Comment by Horizon1959** [comment]
@12st:
`_cargo addItemCargoGlobal ["optic_Hamr_khk_F", 2];`

![image](https://cloud.githubusercontent.com/assets/17685328/18474334/3dc94e24-79ca-11e6-8e67-4d7b61a5e902.png)

**Comment by ToxaBes** [comment]
@Horizon1959 - вопросов больше не имею.

**Comment by Horizon1959** [comment]
@ToxaBes уничтожить ящик можно взрывчаткой, если ты ему конечно god mode не включил. благо взрывчатки достаточно.

**Comment by Horizon1959** [comment]
Любители не покупать DLC всё равно ведь не могут попасть на Таноа?

**Comment by ToxaBes** [comment]
Включил - а то с приземлением у него бывают проблемы. Он исчезает сам через 15 мин но не сидеть же около него и караулить.

**Comment by ToxaBes** [comment]
>Любители не покупать DLC всё равно ведь не могут попасть на Таноа?

ну это пока )

**Comment by 12st** [comment]
@Horizon1959 Могут, наш сервер один из таких.

**Comment by ToxaBes** [comment]
ну вот )

**Comment by Horizon1959** [comment]
@ToxaBes @12st т.е. жадина заходит на Таноа, а из ящика не может натянуть зелёный RCO?

**Comment by 12st** [comment]
@Horizon1959 Пиратская версия полностью совпадает с лицензионной, владелец такой копии просто рискует глобал бан словить.

**Comment by ToxaBes** [comment]
так может просто добавить
```sqf
_cargo addItemCargoGlobal ["optic_Hamr", 2];
```
а?

**Comment by Horizon1959** [comment]
@ToxaBes хотелось всё красиво сделать, чтоб цвета совпадали. Ну если критично, то мутите `optic_Hamr` вместо `optic_Hamr_khk_F` .

**Comment by ToxaBes** [comment]
зачем вместо если можно вместе.

**Comment by Horizon1959** [comment]
@ToxaBes ну и ладно, будет 6 прицелов:)

**Comment by ToxaBes** [comment]
я вообще не понимаю зачем там прицелы так что двумя больше, двумя меньше )
