### ISSUE TITLE
Аванпост у основного задания

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#153]
После обсуждения с @Horizon1959 появилась мысль изменить ситуацию когда основа на другом конце острова и после каждого респауна нужно ехать/летать на основу через всю карту. В реале же делают небольшие базы/аванпосты для переброски л/с ближе к РБД, может пора и нам такое сделать, но мобильные КШМ, телепорты и halo jump нам не подходят.

Идея в следующем: если основа дальше 3км от базы синих то в 200-600м от границы основы появляется небольшой аванпост красных.
Если синие не хотят каждый раз тащится с базы - в первую очередь они захватывают аванпост. В этом случае они могут выбирать где ресаться, на основной базе или на аванпосте. Этот же аванпост могут захватывать партизаны и уничтожить. Если аванпост захвачен синими то там появляется минимальная охрана (пара стационаров).

Цель синих - сделать себе доп точку респа рядом с основой.
Цель партизан - уничтожить аванпост чтобы синие дольше добирались до основы. 
Также обе стороны могут забить на этот аванпост и выполнять задачи как обычно.

Описание аванпоста: укрепления (разные варианты) с посадочной площадкой для вертов и 4-5 квадриками. На аванпосте не будет ни арсенала ни ящиков со снаряжением. 
Особенность респа на аванпосте: респаун производится волнами, раз в 1 мин. <- не уверен, нужно ли это.

Данный вариант оставит необходимыми пилотов грузовых вертушек как в начале основы так и после захвата аванпоста - таскать боеприпасы либо л/с который реснулся на базу к арсеналу.

Давайте обсудим, есть ли смысл делать такую вещь, плюсы/минусы.

**Comment by malashin** [comment]
Не фанат обездоливания пилотов. Учитывая большое количество медиков, возить людей практически и не требуется.

Скорее всего на аванпосте нужен какой-то транспорт, на 4 квадроциклах все могут не уехать. Да и добираться в боевую точку на квадроциклах как-то странно, как минимум.

Можно захват аванпоста ограничить тем, что синие должны доставить грузовик на аванпост, а не просто прилететь на вертушке и постоять там минуту. Это усложнит процесс, даст выбор, либо быстро на основу прилететь, либо медленно ехать на грузовике и захватить новый респ. Зеленые смогут минировать подъезд к аванпосту.

**Comment by Horizon1959** [comment]
Мне кажется, что минимальное удаление основы от базы для появления аванпоста должно быть не менее 5-ти км. Аванпост не должен быть заменой базы, но иногда должен избавлять от ненужной траты времени на дорогу до основы.
Аванпост должен иметь опцию захвата, но не уничтожения. Это ещё один повод для столкновения партизан с регулярной армией, ведь иногда намного выгоднее респавниться у точки, чем ехать по 10-15 минут с риском взорваться из-за авиаподдержки противника.
Аванпост может представлять из себя пару вышек, какие-то ограждения, вертолётную площадку, барьеры. Образцы можно поглядеть в композициях Ares Mod или скачав пресеты для редактора на armaholic или steam workshop. На аванпосте можно сделать сильно ограниченный арсенал или ящик, в котором спавнится минимальный пыщ-пыщ. Т.е. если ты почти всех завалил и в куполе осталась пара ботов, то тебе хватит какой-нибудь простой винтовки, чтобы закончить миссию. Это не значит, что нужно туда пихать оружейный магазин.
На аванпосте может быть простой транспорт, вмещающий много людей, но он не должен организовывать бронезащиту и не должен иметь вооружение. Для этих задач сейчас отлично подходит Prowler или Qilin. У зелёных может спавниться газель.
Волна спавна должна быть фиксированной, т.е. ты можешь при нажатии кнопки респавна прождать 30 секунд, а можешь и несколько минут. Таким образом получается не бесконечный спавн одиночного мяса, а появление группы, которая вместе может выдвинуться на точку.

Если использовать данные особенности создания аванпоста, то пехота, используя передовую базу, будет очень сильно зависима от союзной авиации: пехоте понадобится техника, боеприпасы, оружие и снаряжение. Сейчас пилот может отвезти гружёную до отказа пехоту на основу и сидеть скучать на базе. Если сыграть на лени игроков при респавне, то пилоты будут носиться до основы как угорелые, что хоть систему заявок им поднимай. Вся техника, которая может доставляться по воздуху, слабо бронирована и быстро горит на поле боя, заставляя возить её до победного конца, этакое военное общество потребления.

**Comment by ToxaBes** [comment]
>Не фанат обездоливания пилотов.

Я тоже, но в данном случае потери минимальны. Пилоты по-прежнему возят л/с на зоны высадки до того как взяли аванпост, возят после взятия на другу сторону зоны если нужно зайти оттуда, возят боеприпасы с базы (на аванпосте нет арсенала), возят новых игроков с базы и тех кто реснулся на базе чтобы взять что-то арсенале, возят на допки и тд.
Суть не в обездоливании пилотов а в сокращении поездок на машине по 15 км. Это удовольствие для партизан.

>Можно захват аванпоста ограничить тем, что синие должны доставить грузовик на аванпост, а не просто прилететь на вертушке и постоять там минуту.

Ну тупо прилететь и постоять минуту не получится - собьют, он же кишит красными, придется высаживаться в отделении и штурмовать/погибать/ресаться на базе/лететь. Аванпост будет посложнее КП/Бункера в плане взятия.

Идея с грузовиком мне не очень нравится, т.к. нужно ехать, а не лететь на верте, ты же сам против обездоливания пилотов. Также этот грузовик очень уязвим для вражеской авиации пока едет.

>Грузовик можно специальный сделать с долгим респауном на базе синих. Если потеряли грузовик, то придется долго ждать новый.

Ненужное усложнение, тут суть в возможности получения близкого места респа для синих а не создания доп. основы.

**Comment by ToxaBes** [comment]
>Мне кажется, что минимальное удаление основы от базы для появления аванпоста должно быть не менее 5-ти км. Аванпост не должен быть заменой базы, но иногда должен избавлять от ненужной траты времени на дорогу до основы.

да, можно 5 км. Заменой базы не будет.

>Аванпост должен иметь опцию захвата, но не уничтожения. Это ещё один повод для столкновения партизан с регулярной армией, ведь иногда намного выгоднее респавниться у точки, чем ехать по 10-15 минут с риском взорваться из-за авиаподдержки противника.

Партизаны могут уничтожить аванпост, синие - нет. Синие могут ресаться на аванпосте, партизаны - нет. После захвата у синими на аванпосте появляется минимальная охрана по типу как на базе + подход к "ящику/терминалу" уничтожения базы можно минировать.

>Аванпост может представлять из себя пару вышек, какие-то ограждения, вертолётную площадку, барьеры. Образцы можно поглядеть в композициях Ares Mod или скачав пресеты для редактора на armaholic или steam workshop. 

Все уже есть.

>На аванпосте можно сделать сильно ограниченный арсенал или ящик, в котором спавнится минимальный пыщ-пыщ. Т.е. если ты почти всех завалил и в куполе осталась пара ботов, то тебе хватит какой-нибудь простой винтовки, чтобы закончить миссию. Это не значит, что нужно туда пихать оружейный магазин.

Нет, главное отличие аванпоста от базы - там нет арсенала/ящика. Откуда на вражеском аванпосте винтовки/боеприпасы синих. Если кончились патроны - попроси у товарищей или возьми катибу у бота. После захвата базы синие могут попросить своих пилотов привезти БК либо командир отделения может вызвать поддержку припасами (ящик на парашюте).

>На аванпосте может быть простой транспорт, вмещающий много людей, но он не должен организовывать бронезащиту и не должен иметь вооружение. Для этих задач сейчас отлично подходит Prowler или Qilin. У зелёных может спавниться газель.

Только квадрики и то просто на всякий. Аванпост у границы зоны БД, куда ехать? На аламут/титан? Зеленым там ничего не надо тк они там ресаться не смогут. Единственный смысл зеленым лезть на аванпост - уничтожить его чтобы синие не спавнились рядом с основой.

>Волна спавна должна быть фиксированной, т.е. ты можешь при нажатии кнопки респавна прождать 30 секунд, а можешь и несколько минут. Таким образом получается не бесконечный спавн одиночного мяса, а появление группы, которая вместе может выдвинуться на точку.

Период волны 1 мин. Кто в течении этой минуты нажал респавн, тот и реснется в конце минуты.

>Если использовать данные особенности создания аванпоста, то пехота, используя передовую базу, будет очень сильно зависима от союзной авиации: пехоте понадобится техника, боеприпасы, оружие и снаряжение. Сейчас пилот может отвезти гружёную до отказа пехоту на основу и сидеть скучать на базе. Если сыграть на лени игроков при респавне, то пилоты будут носиться до основы как угорелые, что хоть систему заявок им поднимай. Вся техника, которая может доставляться по воздуху, слабо бронирована и быстро горит на поле боя, заставляя возить её до победного конца, этакое военное общество потребления.

На то и расчет что т.к. аванпост по факту просто точка доп респа а не база, а также то что часть БК игроки израсходуют на взятие аванпоста - пилоты по-прежнему будут очень нужны.

**Comment by Horizon1959** [comment]
> Нет, главное отличие аванпоста от базы - там нет арсенала/ящика. Откуда на вражеском аванпосте винтовки/боеприпасы синих. Если кончились патроны - попроси у товарищей или возьми катибу у бота. После захвата базы синие могут попросить своих пилотов привезти БК либо командир отделения может вызвать поддержку припасами (ящик на парашюте).

Хорошо, согласен. Нужно больше нагрузки пилотам.

В целом взгляд верный, плюсую.

**Comment by ToxaBes** [comment]
Прикрутил аванпост на Алтис и Таноа. 
Из изменений:

>для появления аванпоста должно быть не менее 5-ти км

Потестил с 5км, 4км, 3км, 2.5км. Остановился на 2.5км, как на самом оптимальном, особенно это оправдано на Таноа. Пока тестим так, потом посмотрим.

>Волна спавна должна быть фиксированной, т.е. ты можешь при нажатии кнопки респавна прождать 30 секунд, а можешь и несколько минут.

Тестил волну с периодами 1, 2 и 3 минуты. 2 и 3 минуты - слишком долго, особенно если до этого 10 минут лежал ждал медика.  А 1 минута просто не имеет смысла т.к. среднее время ожидания получается 25-35 сек. У нас сейчас процесс респа занимает 10 сек. Из-за 15-25 дополнительных  секунд ожидания добавлять в миссию глобальный счетчик который будет синхронизировать время респа (и давать доп нагрузку) смысла не вижу. В нашем режиме игры эти секунды ни на что в итоге не повлияют.

**Comment by Horizon1959** [comment]
@toxabes не понял, т.е. теперь просто нажимаешь респаун и появляется на аванпост без ожидания?

**Comment by ToxaBes** [comment]
Если аванпост захвачен то и синих появляется на экране смерти доп кнопка "На аванпост" (экран смерти был немного изменен). По нажатию все также как при респауне на базу: черный экран и таймер ожидания 10 сек. После чего черный экран исчезает и ты на аванпосте.

**Comment by Horizon1959** [comment]
Потестили:

- аванпост спавнится (на Алтисе точно)
- респавн работает, кнопки доступны
- квадроциклы респавнятся
- подрыв аванпоста партизанами работает

Баги:

- после подрыва аванпоста квадроциклы продолжают спавнится

Замечания:

- когда партизан тыкнул ноутбук для подрыва аванпоста, то не было сообщения о подрыве для зелёных
- у синих сообщение не очень понятное: "Лучше поторопиться, скоро тут всё взлетит на воздух. У вас полторы минуты, чтобы уйти". Зачем торопиться, что взлетит - не ясно.

Вообще не очень понимаю, зачем там РЛС и странный бетонный заборчик. Может переделать композицию? Пара вышек из досок, блоки с песком, укрепления из мешков, не?

**Comment by ToxaBes** [comment]
Спасибо за тест. Баги и замечания исправлю.

>Вообще не очень понимаю, зачем там РЛС и странный бетонный заборчик.

1. Для заметности. Изначально аванпост был меньше и примерно такой как ты описал. Но найти его можно было только зевсом, слишком незаметным он был. Белый бетонный забор и РЛС делают его хоть как-то заметным т.к. он не отображается на карте.
2. Для безопасности. Часто аванпост появляется совсем рядом с границей зоны и находится около маршрута патрулирования зениток/ифритов. Бетонный забор спасает.

**Comment by Horizon1959** [comment]
@ToxaBes а большие блоки с песком не спасут? Такой лагерь с маскировочной сеткой мы всегда спалим, вся разведка идёт квадракоптером.

**Comment by ToxaBes** [comment]
>а большие блоки с песком не спасут?

Неа, сплеш от выстрела зенитки накрывает только так. Только высокий бетонный забор спасает - чтобы не залетало.

>Такой лагерь с маскировочной сеткой мы всегда спалим, вся разведка идёт квадракоптером.

Ты не рассматриваешь ситуацию когда на сервере нет инженера. В этом случае игроки могут найти аванпост поднявшись на возвышенность с помощью бинокля.

**Comment by Horizon1959** [comment]
@ToxaBes не бывает таких ситуаций, ну не лезем без разведки с воздуха.
А отсутствие респавна охраны - это баг или фича?

**Comment by ToxaBes** [comment]
Ты не находишься 24 часа в сутки на сервере.

**Comment by ToxaBes** [comment]
>А отсутствие респавна охраны - это баг или фича?

Фича
