### ISSUE TITLE
Ошибка в скрипте при захвате

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#154]
При захвате партизанами бункера либо КП, при условии что вышка еще не уничтожена проявляется следующая ошибка:
![20160911193222_1](https://cloud.githubusercontent.com/assets/3309152/18419084/4c4f8824-785c-11e6-8f73-a57329b2673f.jpg)

Влияет только на сообщение о полученной награде для партизан, сама награда дается без ошибок.

**Comment by malashin** [comment]
Нужно вместо ```==``` ставить ```isEqualTo```. При сравнении разных типов ```==``` дает ошибку. В данном случае ```false == resistance```.

**Comment by ToxaBes** [comment]
О, спасибо! Привык к мягкой типизации в другом ЯП. Совсем забыл что арма не может приводить сложные типы данных к одному виду перед сравнением. Сегодня исправлю.
