### ISSUE TITLE
Зона посадки вертолетов

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#155]
На данный момент зона посадки вертолетов на Таноа не используется. Нужно ее убрать и разместить посадочную разметку перед основным ангаром без каких либо ограждений.

**Comment by Horizon1959** [comment]
А посадочные огни не приведут к авариям?

**Comment by ToxaBes** [comment]
Нет, колеса техники и лыжи вертолетов проходят сквозь них.

**Comment by Horizon1959** [comment]
@ToxaBes понял
