### ISSUE TITLE
Баг снаряжения: доступен предмет противника

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#156]
На Таноа можно подобрать полевой ранец раскраски "зелёный hex". Камуфляжный рисунок противника, надо добавить в запрещалку.

**Comment by ToxaBes** [comment]
Спасибо, исправим.

**Comment by ToxaBes** [comment]
проверил - исправлять нечего. В арсенале рюкзак недоступен,а с тушек ботов синие могут любые рюкзаки и жилеты брать.
