### ISSUE TITLE
Сохранение данных между рестартами

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#157]
Нужно сохранять наградную технику как синих так и партизан чтобы она была доступна после перезагрузок либо в следующий день этой же карты.

**Comment by Horizon1959** [comment]
А не приведёт ли это к дикому накоплению техники? Вот у нас стоит косатка изо дня в день, что с ней делать?

**Comment by ToxaBes** [comment]
Нет, у нас каждая новая техника будет выдаваться из того чего еще нет в списке наградной. Если уже все есть в списке то награда будет заменять существующую в списке технику того же типа.
Если техника выехала/вылетела с зоны наградной - она исключается из списка и при рестарте будет утеряна.

**Comment by Horizon1959** [comment]
@ToxaBes а если эту вывезенную технику поставить на место?

**Comment by ToxaBes** [comment]
В этом случае я еще не решил лучше. Можно возвращать ее в список либо нет.

**Comment by Horizon1959** [comment]
Если техника не будет дублироваться, то можно её возвращать, почему бы и нет. В конце концов нормальная регулярная армия просто так свою технику в рабочем состоянии не бросает.

**Comment by ToxaBes** [comment]
логично, если такой техники нет в списке - будем возвращать.

**Comment by ToxaBes** [comment]
Последние тесты показали что сохранение наградной и снаряжения будет делать бессмысленным соревнование в захвате точек между синими и партизанами. Этот тикет пока закрываю - будем смотреть дальше.
