### ISSUE TITLE
Буксировка техники стропами

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#16]
Техника большего или равного тоннажа может буксировать поврежденную технику. Управление через меню действий.

**Comment by Horizon1959** [comment]
Будут использоваться стропы как у вертолётов? Не будет ли техника при буксировке летать и прыгать?

**Comment by ToxaBes** [comment]
Нет, будет ездить по земле )

**Comment by Horizon1959** [comment]
@ToxaBes типа как раньше танки приклеивались к дну вертолёта?

**Comment by ToxaBes** [comment]
Не совсем, со стороны выглядит так как будто одна машина тащит волоком на тросе вторую. Это нужно для 2х вещей:
1. сдернуть застрявшую машину с камней/отбойника без повреждения.
2. отбуксировать машину с поврежденными колесами до сервиса техники.

**Comment by Horizon1959** [comment]
@ToxaBes прикольно. Как запилишь - зови тестить, я много катаюсь.
