### ISSUE TITLE
БПА Дартер

### ISSUE THREAD

**Issue by kovt** [ToxaBes/ADR-Spec-Ops#160]
Нужно поставить два-три Дартера на базе, с возможностью респавна. Думаю имеет смысл поставить их не в ангаре с остальными, а где нибудь рядом, с боку или сзади, что бы не выводить их руками постоянно из ангара (но это не принципиально). Только нужно не забыть продумать их уничтожение после израсходования заряда/горючки, так как они не падают, а садятся и это не позволит им респавнится на базе.

**Comment by Horizon1959** [comment]
Подробнее и точнее:

Фича №1:

Надо сделать на базе спавн 3-ёх дартеров с временем респа примерно 30-60 секунд. Желательно в самых неиспользуемых местах и на открытых площадках (не думаю, что вражеская авиация будет охотится на этих карапузов). Если же во время тестирования авиация будет слетаться на них, как мухи на говно, то придётся пихать их под навес.

Для чего это надо:

- 	убрать рутину с взятием рюкзаков с дартером и их установку
- 	позволить вызывать дартеры с базы без необходимости присутствия на базе игроков
- 	убрать необходимость спавнить сразу кучу дартеров на базе
- 	не засорять основные места тусовки игроков на базе

Почему это надо:

БПА - очень глючная штука в сетевой игре, их поведение может заглючить в любой момент (закономерности выявить не удалось). Глюк выражается в потере управления или контроля над БПА (error: no venicle), дартер например, начинает вращаться и кружить. Из-за этого приходится спавнить сразу много дартеров, чтобы исправный заменял поехавшего без потери времени.
Из-за данной особенности, приходится спанвить не меньше 12-ти дартеров, 4-е штуки отправлять на точку, а остальных рядом с точкой в запас (даём команду на приземление). Если сделать спавн дартеров, то необходимость в больших количествах дартеров отпадает, т.к. они будут равномерно тянуться от базы в сторону точки.

Как предотвратить злоупотребление дартерами:

- 	сделать ограничение на дартеры в 12 штук (4-е на точке, 5 про запас у зоны боевых действий, 3 на базе)
- 	при достижении лимита, новые дартеры не должны спавнится
- 	при попытке собрать дартер из рюкзака, дартер не должен затирать уже действующие квадрокоптеры и должен или удаляться или вообще не создаваться. Вводить ограничение на ношение рюкзака не разумно.

Фича №2:

Надо сделать автоматическое уничтожение дартера, если у него заканчивается АКБ.

Для чего это надо:

- 	убрать рутину с отслеживанием запаса энергии АКБ дартера
- 	убрать ситуации с расходом АКБ дартера и его автоматическим приземлением

Почему это надо:

Если дартер остался висеть в воздухе, то у него расходуется АКБ и если АКБ будет израсходован, то дартер садится/мягко падает и остаётся так лежать до тех пор, пока его не уничтожат (т.е. никогда). Если запиливать лимит дартеров и их спавн, то такая ситуация может привести ещё к большей рутине. Чтобы такого не произошло, нужно чтобы дартер после израходования энергии АКБ, взрывался или затирался с карты (взрыв будет круче, однозначно).

**Comment by kovt** [comment]
Книги писать не пробовал? ))

**Comment by Horizon1959** [comment]
@kovt не интересует.

**Comment by ToxaBes** [comment]
Итак, вот что получилось:

* Инженером доступно макс. 8 дартеров одномоментно. (не спешите ругаться, читайте дальше)
* Рюкзаков с дартерами в арсенале больше нет (также терпите, и читайте дальше)
* Дартеры вызываются из контекстного меню инженерами. Т.е. мотнул колесом мыши, выбрал "Вызвать AR-2 Дартер" - дартер появился на базе в районе зоны наградной.
* Инженеры могу вызывать дартеры откуда угодно и когда угодно. После вызова дартер сразу доступен в терминале управления.
* При достижении лимита инженер видит сообщение о том что достигнул лимит дартеров.
* Как только дартеров стало меньше лимита - инженер может сразу вызвать новые.
* В лимит не входят дартер который появляется на основе и дартеры из спецоперации угон.
* В вызванных дартерах есть проверка каждую минуту - если топлива меньше 5% он уничтожается.

Пока считаю данные вариант оптимальным. Теперь можно ругаться.

**Comment by Horizon1959** [comment]
@ToxaBes вполне ничего так решение, посмотрим как оно будет работать на практике.

**Comment by Horizon1959** [comment]
@ToxaBes дартер появляется неизвестно где. Судя по виду с камеры - на дне морском.

![107410_20160925150132_1](https://cloud.githubusercontent.com/assets/17685328/18815184/7c52819a-8331-11e6-9ce6-87dfc2cc2be0.png)

**Comment by ToxaBes** [comment]
Ага, скорее всего по координатам [0,0,0] - сбоит функция поиска свободного места. Это единичный случай?

**Comment by Horizon1959** [comment]
@ToxaBes ни разу за день не заспавнилось где надо.

**Comment by ToxaBes** [comment]
Пофиксил. Проблема была только на Таноа.

**Comment by Horizon1959** [comment]
@SooNDooCK71 говорит, что спавн дартеров работает через раз. Завтра буду проверять лично.

**Comment by ToxaBes** [comment]
Проблема та же что и с кастомными каналами. Иногда, после возрождения арма не добавляет экшн на вызов дартера как и не добавляет каналы. Лечится возрождением. В коде ошибок нет.

**Comment by Horizon1959** [comment]
@ToxaBes ок, понял.
