### ISSUE TITLE
Неактуальное условие при выборе спавна доп. задания.

### ISSUE THREAD

**Issue by Noart537** [ToxaBes/ADR-Spec-Ops#161]
Антон глянь код. Условие выбора места для дополнительных заданий. 
Возможно это условие не актуально. Оно почти в каждом доп. задании.

https://github.com/ToxaBes/ADR-Spec-Ops/blob/master/co30_ADR_Spec_Ops.Tanoa/mission/side/missions/secureChopper.sqf#L31

**Comment by ToxaBes** [comment]
Да, оно уже неактуально. Спасибо, поправлю.
