### ISSUE TITLE
Система Аид

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#162]
Нужно проверить, работает ли Аид на спецоперациях.

**Comment by 12st** [comment]
Проверка на технику внутри триггера работает через раз, бывает на протяжении всей допки люди катаются, а бывает, что срабатывает с большой задержкой. На убийства с техники работает всегда.

**Comment by ToxaBes** [comment]
Исправил то что можно было. Дальше все от армы зависит.
