### ISSUE TITLE
Убийства с дартеров

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#163]
В 1.64 вроде пофиксили убийства с дартеров - теперь возвращает оператора а не дартер. Нужно будет потестить.

**Comment by Horizon1959** [comment]
@ToxaBes не понял, кто кого и куда возвращает?

**Comment by malashin** [comment]
@Horizon1959 

> Tweaked: Players shooting with drones are now considered the initiators of the shots

**Comment by Horizon1959** [comment]
@malashin т.е. мне фраги будут идти, а не Джону в грейхоке?

**Comment by malashin** [comment]
Скорее всего, да. И наказать за тимкилл или стрельбу где не положено проще в плане программирования. Поэтому это и интересно.

**Comment by Horizon1959** [comment]
@ToxaBes @malashin круто, сегодня буду гонять (если заработает арсенал и экшен меню), проверю всё.

**Comment by ToxaBes** [comment]
>если заработает арсенал и экшен меню

Уже работает. Вчера с Агларон тестили.

Появилась новая проблема с рюкзаками: периодически при попытке перетащить рюкзак в технику он оказывается на земле. При попытке забрать рюкзак, он также оказывается на земле причем его копия со всем содержимым остается в технике. Проявляется не всегда. Тестил на охотнике.

**Comment by ToxaBes** [comment]
Потестили с сундуком. При убийстве с беспилотника в системном чате пишется правильный ник но наказать по прежнему можно только бота сидящего внутри беспилотника. При наказании бота беспилотник уничтожается. Тикет закрываю до следующей попытки БИСов пофиксить это.
