### ISSUE TITLE
Доработка AI

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#164]
Нужно будет попробовать улучшить взаимодействие AI:
- ~~пулеметчики ведут огонь на подавление~~
- ~~весь отряд чаще использует укрытия~~
- ~~бойцы не стоят тупо на открытом месте, а атакуют либо занимают укрытие~~
- ~~при близком контакте закидывают гранатами~~

~~На Таноа нужно сделать более быструю потерю цели если игрок в джунглях/высокой траве.~~

**Comment by ToxaBes** [comment]
У нас боты действуют отдельными группами. Несмотря на то что тактика внутри группы находится на хорошем уровне, взаимодействие между группами налажено очень слабо. Пора вводить вражеского командующего на основное задание. Разместить его внутри КП. Пока он жив, вся информация о противнике будет передаваться между командирами всех групп, что надеюсь повысит групповую тактику ботов.

**Comment by Noart537** [comment]
(К пятничному обсуждению) Что если от уровня базы будет зависеть точность ботов? (Общее от синих и зеленых). Берем только точность, остальное как есть. Тогда партизанам можно на 1-м уровне давать пистолеты и ПП, а то они совсем не используются.

**Comment by ToxaBes** [comment]
>Что если от уровня базы будет зависеть точность ботов?

Офигенная идея. Мне нравится. Как вариант модно сделать так:

* Точность и интеллект ботов будут зависить от только развития базы синих, партизаны могут немного и пострадать в случае чего
* Партизанам на первом уровне оставляем пистолеты и ПП, на втором уровне то что есть сейчас

**Comment by ToxaBes** [comment]
Добавил ботам тактики, перепрошил мозги. Они теперь умнички (даже пытаются медленно летящие вертолеты сбивать аламутом и подрывают дома в которых засел противник).

**Comment by Horizon1959** [comment]
@ToxaBes Не понял, ботинки теперь из шайтан-трубы в окна палят? Или посылают муджахида на встречу с Всевышним?

**Comment by ToxaBes** [comment]
Не буду ничего расписывать, пусть будет приятным сюрпризом.

**Comment by 12st** [comment]
Ждём ботов, которые будут вскрывать танки голыми руками)

**Comment by ToxaBes** [comment]
>Ждём ботов, которые будут вскрывать танки голыми руками)

Пара забавных случаев со вчерашнего теста:

1. засел в доме с пулеметом, окружили со всех сторон. Боты начали подавляющим огнем загонять меня в угол дома на втором этаже. После того как загнали - подрывник подбежал к углу этого дома, поставил заряд, отбежал и подорвал вместе со мной.

2. перестреливался с ботом, у него закончились патроны. Вместо того чтобы вытащить пистолет он метнулся назад за угол дома, полутал павшего товарища на предмет магазинов, вернулся и продолжил бой.

3. вынес стрелка в зенитке и перестал на нее обращать внимание. А зря. Пробегающий мимо бот запрыгнул на стрелка развернул башню и накидал мне.

Так что не голыми руками конечно, но подползти и поставить заряд уже должны смочь.

**Comment by ToxaBes** [comment]
мне кстати пришлось снизить некоторые параметры, а то каждая осада дома заканчивалась его физическим сносом...
