### ISSUE TITLE
Update 1.64

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#165]
Эти дебилы поломали арсенал. Также не работают ВСЕ экшены по колесу мыши.

**Comment by ToxaBes** [comment]
Пофиксил. Ошибка была в комбинации первого и восьмого параметров переменной ShowHUD в description.ext. Также мы потеряли прелоад арсенала но это не критично.

**Comment by Horizon1959** [comment]
Эти дебилы сломали радар:
![107410_20160923192207_1](https://cloud.githubusercontent.com/assets/17685328/18793381/2ca71ecc-81c3-11e6-8216-efbfb7565792.png)

**Comment by Horizon1959** [comment]
Теперь можно спалить, кто оставил метки:
![107410_20160923193103_1](https://cloud.githubusercontent.com/assets/17685328/18793638/5612c792-81c4-11e6-8106-3a4e17c1cf6f.png)

**Comment by ToxaBes** [comment]
Радар пофиксили своими силами. Метки это ок.

**Comment by Horizon1959** [comment]
Не работает вызов модулей для вертолётов на Таноа:
![107410_20160923205527_1](https://cloud.githubusercontent.com/assets/17685328/18796037/1df0162e-81d0-11e6-8c44-3c0832573d68.png)

**Comment by Horizon1959** [comment]
Периодически пропадют экшен-меню.

**Comment by Horizon1959** [comment]
На Таноа доступна форма MTP и CTRG (Алтис, коричневая).

**Comment by 12st** [comment]
Полностью отсутствует командирское меню.

**Comment by ToxaBes** [comment]
>Не работает вызов модулей для вертолётов на Таноа

Работает, при условии что ты пилот.

**Comment by ToxaBes** [comment]
>На Таноа доступна форма MTP и CTRG (Алтис, коричневая).

Не смог повторить фокус. Скорее всего через снаряжение как-то получалось. Теперь снаряжения нет )

>Полностью отсутствует командирское меню.

Fixed.

**Comment by 12st** [comment]
Не отображаются члены отряда в командирском меню.

**Comment by ToxaBes** [comment]
>Не отображаются члены отряда в командирском меню.

Это не баг, это вроде закрыто с некоторыми возможностями командирки.
