### ISSUE TITLE
Допилить ограничения арсенала

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#168]
Сейчас многие вещи можно снять с ботов и успешно носить, но в арсенале их взять нельзя (РПС LBV например).

@Noart537 Noart спавнил рюкзаки с дартерами, @SooNDooCK71 их сохранял и успешно загружал.

Ещё на Таноа вижу вот такую картину:
![107410_20160925183748_1](https://cloud.githubusercontent.com/assets/17685328/18816312/8910f998-834f-11e6-8f28-8b567465f4c0.png)

**Comment by ToxaBes** [comment]
Баг проявляется только на Таноа?

**Comment by Horizon1959** [comment]
@ToxaBes на Алтисе тестить будем завтра. На Таноа я свои пресеты с MTP и серым CTRG не могу загрузить.

**Comment by ToxaBes** [comment]
Еще косяки связанные с арсеналом:
1. Партизаны могут грузить пресеты.
2. Все могу грузить рукзаки с БПЛА.

Похоже что все эти косяки из-за того что перестал работать прелоад арсенала.

**Comment by Horizon1959** [comment]
@ToxaBes 
![default](https://cloud.githubusercontent.com/assets/17685328/18844250/390f4496-8425-11e6-8262-d0105a9622b9.jpg)

**Comment by malashin** [comment]
Ошибок никаких нет в логах?

**Comment by ToxaBes** [comment]
Нет. Если включить прелоад арсенала при загрузке игрока то выдает ошибку из самой функции bis_fnc_arsenal.

**Comment by ToxaBes** [comment]
1. Партизаны могут грузить пресеты - fixed
2. Все могут грузить рукзаки с БПЛА - fixed
3. Синие могут снимать жилеты/рюкзаки с ботов и носить - нужен большой список отдельно по жилетам, отдельно по рюкзакам того что нельзя носить (отдельно для Алтиса, отдельно для Таноа).

**Comment by ToxaBes** [comment]
Жилеты и рюкзаки противника добавил.

**Comment by Horizon1959** [comment]
@ToxaBes можешь мне дать список подразделений, которые задействованы в обоих миссиях? Т.е. огневая группа, стрелковое отделение и т.п. Буду тестить локально.

**Comment by ToxaBes** [comment]
Да практически все подразделения используются (красные+зеленые). Я добавил все по списку из https://community.bistudio.com/wiki/Arma_3_CfgWeapons_Equipment что принадлежит красным и зеленым по жилетам и рюкзакам, а потом исключил то что мы все-таки разрешаем (некоторые рюкзаки красных в нашей расцветке и т.д. - т.е. то что доступно в арсенале).

Что я не делал - разграничение формы синих между Алтисом и Таноа. Нужно 2 списка Форма/Жилеты/Рюкзаки того что нельзя носить на Алтисе и что нельзя носить на Таноа.

Т.е. если мы запрещаем форму синих в MTP расцветке на Таноа то она должна быть в списке для Таноа.

**Comment by Horizon1959** [comment]
@toxabes сегодня протестирую локально всю эту тему с собирательстаом формы противника.
Списки разграничения формы между Алтисом и Таноа постараюсь намутить до понедельника, если меня не упекут в командировку.
Ещё надо разрешить лётные комбинезоны только пилотам, они вроде обеспечивают защиту по принципу формы CSAT.

**Comment by ToxaBes** [comment]
>Списки разграничения формы между Алтисом и Таноа постараюсь намутить до понедельника

Меня до 24го не будет, так что не торопись.

**Comment by ToxaBes** [comment]
РПС CSAT уже запрещен

**Comment by ToxaBes** [comment]
Тут вообще большой вопрос, а надо ли вообще запрещать жилеты и рюкзаки противника если они не в расцветке противника?

**Comment by Horizon1959** [comment]
> Тут вообще большой вопрос, а надо ли вообще запрещать жилеты и рюкзаки противника если они не в расцветке противника?

@ToxaBes вот я про это и клоню. По сути всё это нужно, чтобы не было путаницы между сторонами.

**Comment by ToxaBes** [comment]
В данный момент путаницы нет и можно разрешать. Но. Я планирую убирать метки своих с карты и оставлять их только на GPS (т.к. пока тактического компаса нет и не предвидится то вместо него будет gps). В этом случае нужен строгий дресскод для синих.

**Comment by Horizon1959** [comment]
@ToxaBes если точнее, то путаница возникает по следующим параметрам:

- общая цветовая гамма
- форма и габариты снаряжения
- камуфляжный рисунок.

Меня смущают рюкзаки противника, которые мы используем. Они попадают под второй пункт путаницы, но в то же время очень нравятся людям на сервере. Заставлять всех переходить на рюкзаки NATO как-то совсем жёстко.

Если нужна модель дресс-кода, то тут я номер один, самый модный пацан на сервере. Так что накатаю список MTP/CTRG для каждой карты. 

> Я планирую убирать метки своих с карты и оставлять их только на GPS (т.к. пока тактического компаса нет и не предвидится то вместо него будет gps).

Можно подробнее? Что будет выпилено?

**Comment by ToxaBes** [comment]
>Можно подробнее? Что будет выпилено?

В планах убрать метки игрока и союзников на карте. Оставить их на GPS.

**Comment by Horizon1959** [comment]
@ToxaBes маркеры на карте и пенисы оставлять будете?

**Comment by ToxaBes** [comment]
да

**Comment by Horizon1959** [comment]
@ToxaBes ок.

**Comment by Horizon1959** [comment]
@ToxaBes открой тикет, а то искать его долго. 
Провёл инвентаризацию арсенала у прапора на Алтисе, провёл тесты по забору снаряжения трупов CSAT (коричневые/серые) и AAF. Результаты записал в [таблицу ](https://docs.google.com/spreadsheets/d/1eGELvu46JyLDQI3YaO8iP4Xvl8jz-r4TFT8ob8A1AG4/edit?usp=sharing)(внизу переключение листов, на Таноа будет запись завтра).

**Comment by Horizon1959** [comment]
@ToxaBes обновил таблицу, теперь с корректировками на Таноа. После того, как всё будет допилено, полностью протестирую подбор вражеского снаряжения, оружия, приспособлений с трупов противника. Например обнаружилось, что один из юнитов китайцев таскает Kir и любой класс может его взять и таскать.
И ещё: - [таблица](https://community.bistudio.com/wiki/Arma_3_CfgWeapons_Equipment) имеет устаревшие ID, я же брал из редактора напрямую.

**Comment by ToxaBes** [comment]
Спасибо, буду резать.

**Comment by Horizon1959** [comment]
О как:)
![image](https://cloud.githubusercontent.com/assets/17685328/19223048/7b351fa0-8e6e-11e6-8c89-92be27d60f48.png)

**Comment by ToxaBes** [comment]
Готово, проверь как будет время. Все замечания оформляй в новый тикет. Этот закрываю.

**Comment by Horizon1959** [comment]
@ToxaBes ок.
