### ISSUE TITLE
Ограничение на слот пилота

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#170]
За слот пилота может зайти любой игрок отыгравший не меньше 2х часов на сервере. Время считается со времен ввода часов для партизан, т.е. все постоянные игроки давно перешагнули этот лимит.

**Comment by Horizon1959** [comment]
@ToxaBes 

![default](https://cloud.githubusercontent.com/assets/17685328/19163095/337e665c-8c03-11e6-81bd-db923fbffc22.jpg)
