### ISSUE TITLE
Дипломатия

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#172]
Т.к. у нас возможна дипломатия между регулярной армией и партизанами необходимо придумать как игрокам узнавать текущий статус, а также как заключать и разрывать союзы. Что-то типа голосовалки?

Если текущий статус фракций - война, то все остается как есть сейчас.
Если текущий статус фракций - мир, то:
1. Фракции видят друг друга на GPS.
2. что-то еще?

**Comment by 12st** [comment]
Для начала надо реализовать механизм смены статуса. Голосование или админ переключает? Просто надо сразу исключить такие моменты когда один человек хочет воевать, а остальные нет.

**Comment by ToxaBes** [comment]
>Голосование или админ переключает? 

Точно не админ. Голосование сторон либо как-то еще.

**Comment by ToxaBes** [comment]
Период голосования - раз в 30 мин, не чаще чтобы спама не было.

**Comment by Horizon1959** [comment]
Если на сервере и дальше будет атмосфера тусовки с голосовой связью, то можно устроить демократическую голосовалку. Если раскручивать сервак и иметь регулярную текучку, то нужно усложнять систему.

**Comment by ToxaBes** [comment]
Механизм должен быть простым и понятным. Примерные требования:
1. Любой игрок может инициировать голосование в своей фракции по изменению статуса.
2. После этого  в течении 30 мин никто из фракции не может стартовать новое голосование.
3. Результат  голосование определяется простым большинством.
4. Время на принятие решения 1 минута. Грубо говоря  в меню можно вызвать форму с кнопками мир/война. Эта форма доступна в течении минуты. Не нажал ничего - слил голос.
5. Голосование проходит параллельно по двум фракциям. Если в обоих фракциях большинство за мир - то статус меняется на мир. Если в хоть одна фракции большинство за войну - статус меняется на войну.
6. Минимального порога нет. Для голосования достаточно по одному голосу с каждой стороны.

**Comment by Horizon1959** [comment]
@ToxaBes это всё официальщина, что на счёт механики? Остаётся шанс внезапного удара в спину?

**Comment by ToxaBes** [comment]
конечно.

**Comment by ToxaBes** [comment]
Как ни крути - ничего не мешает фракциям договориться о мире, а потом кто быстрее предаст и   расстреляет в спину.  Возможно есть смысл пересмотреть всю это логику и сделать проще и понятнее. У партизан нет проблем с идентификацией синих, т.к. они всегда в форме регулярной армии. Это синим нужно отличать партизан от армии противника в случае если между фракциями мир.
Как вариант, можно сделать такой механизм: каждый партизан в экшн меню имеет возможность вкл/выкл свое отображение на GPS синих. Договорились о мире - каждый партизан нажал вкл. Случалась подстава - нажали выкл.

**Comment by Horizon1959** [comment]
@ToxaBes запили так, как считаешь нужным. Сейчас отношение синих к зелёным такое, как у РФ к оппозиционерам в Сирии, поэтому вся дипломатия носит чисто информативный характер.

**Comment by ToxaBes** [comment]
Готово, надо будет протестить в мультиплеере.
Партизаны в меню могут переключать статус между фракциями перемирие/война:
* При перемирии обе стороны видят друг друга на GPS
* Каждый партизан переключает свой собственный статус и не может делать это чаще чем 1 раз в 5 мин

**Comment by ToxaBes** [comment]
Нужно перенести переключатель на ящик партизан.

**Comment by ToxaBes** [comment]
Готово.
