### ISSUE TITLE
Рюкзаки ПТ

### ISSUE THREAD

**Issue by 12st** [ToxaBes/ADR-Spec-Ops#173]
С трупов нельзя брать рюкзаки нато на Таноа, причём брать не могут только ПТ(требует подтверждения)

**Comment by ToxaBes** [comment]
Можно скриншот рюкзака который нельзя взять?

**Comment by 12st** [comment]
пытались почти все стандартные для таноа у ботов

**Comment by ToxaBes** [comment]
Пофиксил. Такая же проблема была и на Алтисе.
