### ISSUE TITLE
Доработки по дресс-коду NATO

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#174]
Полностью протестировал последние изменения в миссии, включая оружие и его обвес. Таблицу переделал в более понятный вид, снабдил почти все позиции актуальным ID с кавычками и запятой. Думаю, что это окончательный вариант (если конечно BIS внезапно не запилят пурпурные глушители или не поменяет ID предметов в очередной раз).
Основная идея в том, что у синих есть два подразделения: основная пехота и спецназ CTRG.
Алтис:
- пехота - MTP
- CTRG - коричневый камуфляж CTRG

Таноа:
- пехота - тропики
- CTRG  - зеленый камуфляж CTRG.

Короче: на Алтисе пехота и спецназ бегают в цветах зелёно-коричневых оттенков, на Таноа - только в зелёных и цвета говна (коричневый на Таноа вообще не вариант). Никаких предметов с окраской противника (CSAT, AAF, FIA, бандиты, бомжи и т.п.) быть в распоряжении синих не должно, за исключением ситуаций типа оружия с отсутствием альтернативного окраса .

Таблица поделена на два листа, [ссылка](https://docs.google.com/spreadsheets/d/1eGELvu46JyLDQI3YaO8iP4Xvl8jz-r4TFT8ob8A1AG4/edit?usp=sharing).

**Comment by Horizon1959** [comment]
@ToxaBes если на эту хурму много времени уйдёт, то можете мне рассказать, как всё это запилить самостоятельно, мне не в лом.

**Comment by ToxaBes** [comment]
@Horizon1959 - спасибо за тесты и обновления. Я по приезду сам сделаю, объяснять что где менять выйдет дольше. По названиям -  у редактора есть косяк: он добавляет в id ненужный префикс который указывает на тип вещи.  Например,  для жилетов "Vest_",  для оружия "Weapon_" итд. Можно оставить как есть,  я сам по ходу исправлений обрежу. 
Последнее в чем нужно убедится - что на обоих картах есть все оружие.  Например,  аламут - он в расцветке противника должен быть на алтисе (коричневый) тк не бывает аламута в расцветке нато или черного аламута.  Т. е.  оружие должно быть доступно в разрешенном цвете или в черном. Если ни того ни другого нет то в ближайшем похожем из доступных цветов.

**Comment by Horizon1959** [comment]
@ToxaBes с оружием только в цвете противника всё посмотрел, всё на месте.

**Comment by ToxaBes** [comment]
отлично.
