### ISSUE TITLE
Наполнение транспорта припасами

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#175]
У нас давно не менялось наполнение грузового отсека транспортных средств. Сейчас там мало кому нужные магазины MX, ракеты PCML, куча бесполезных 40 мм дымовых гранат и прочий мусор. Предлагаю переделать стандартный комплект для машин, стоящих на базе (в разумных пределах). Могу оформить всё самостоятельно.

**Comment by ToxaBes** [comment]
Мы не регулируем наполнение машин - это базовый комплект  который добавляет сама арма. Я не хочу превращать технику в мобильные "арсеналы" (и отбирать работу у пилотов),  поэтому думаю либо оставить все как есть,  либо удалить все кроме 4х аптечек.

**Comment by Horizon1959** [comment]
@ToxaBes я не говорю снаряжать машины по самое небалуй, а всего лишь убрать оттуда базовый мусор и добавить немного магазинов обычных штурмовых винтовок. Запихивать туда ракеты и склады с гуманитарной помощью  по умолчанию не нужно. Пилоты тащат крупные партии на безопасные позиции, а машина может помочь в плане экстренной помощи, когда пилот скидывает её с воздуха.
Часто наблюдаю ситуацию, когда приезжает подкрепление на машине, но пехота на поле боя не может взять припасы из-за их отсутствия.

**Comment by ToxaBes** [comment]
Немного это по 2-4 магазина для 3-4 основных винтовок + дымы,  гранаты и аптечки.  Сюда не вхрдят патроны к снайперкам,  ракеты к титанам и т.д. Составь примерный вариант -  обсудим.

**Comment by Horizon1959** [comment]
@ToxaBes вот примерно что нужно намутить, пояснение ниже:
Магазин STANAG, 30 патр. 6,5 мм - 3 шт.
Магазин STANAG, 30 патр. (красные) 6,5 мм - 3 шт.
Запасной магазин на 30 трас. патронов 7,62 (зеленые) - 3 шт.
Магазин на 30 трас. патронов 7,62 (зеленые) - 3 шт.
Магазин на 30 станд. трас. патронов 5,56 мм (красные) - 4 шт.
Магазин на 30 патронов 5.56 с трассирующими пулями (красными) - 4 шт.
Дымовая шашка (синяя) - 16 шт.
Осколочная граната РГО - 4 шт.
Перевязочный пакет - 8 шт.
Подрывной пакет - 1 шт.
Штурмовой ранец (черный) - 1 шт.

Расчёт идёт на 4 человека, т.к. с текущим онлайном и тактикой это оптимальное количество человек на машину. 2-4 магазина на 4 человека с нашими ботами-терминаторами очень мало: на дистанции ≈500 метров из MX уходит на бота около 3-8 попаданий; в ближнем бою у SPAR 16 на одного бота уходит около 10-15 патронов. Соответственно боеприпасы делятся на 4 человека и этого хватит, чтобы протянуть, не шикуя, в самой плохой ситуации и дождаться подвоза припасов пилотом.
Ранец и подрывной пакет нужны, когда носитель взрывчатки теряет её армейским способом, уж очень неприятная ситуация и каждый раз в таком случае жалеем, что нет припасов в машине.

**Comment by ToxaBes** [comment]
Слишком много всего. Никаких подрывных пакетов - есть на кп. Никаких рюкзаков и трасеров. Я против такого упрощения. То что есть нужно переирать базовы состав снаряжения в охотнике например,  не увеличивая количества вещей.  Например, оставить текущее количество дымов но поменять их на синие,  убрать оружие и высорелы к гранатомету но добавить патроны 7.62 и один коробо для легкого пулемета и т. д.

**Comment by ToxaBes** [comment]
Про потерю подрывного пакета -  в этом есть часть геймплея: потеряли или забыли пакет на базе взять,  идите штурмуйте КП,  там есть пакет,  либо ждите посылку с базы. Потеряли пакет с КП - возвращайтесь на КП там несколько пакетов.

**Comment by Horizon1959** [comment]
@ToxaBes по пакету согласен (честно, я забыл, что он есть на КП). По припасам всё немного проще. Смотри:
Охотник сейчас:
![hunter](https://cloud.githubusercontent.com/assets/17685328/19598152/e9a91cb6-97a1-11e6-8dfd-d98917d15028.jpg)

- 2 штурмовые винтовки MX с эффективной дальностью до 800 метров
- 10 перевязочных пакетов
- 16 магазинов по 30 патронов для MX
- 6 магазинов по 100 патронов для пулемёта MX 
- 10 ручных гранат
- куча 40-мм говна
- 2 ракеты PCML

Страйдер сейчас:
![strider](https://cloud.githubusercontent.com/assets/17685328/19598728/fe2b666e-97a4-11e6-9ae3-65d3c3651947.jpg)

- 2 штурмовые винтовки Mk20 с эффективной дальностью до 500 метров
- 16 магазинов по 30 патронов для всего классического натовского стрелкового оружия
- 3 короба по 200 патронов под Mk200
- 10 ручных гранат
- куча 40-мм говна
- 2 ракеты PCML

Праулер сейчас:
![prowler](https://cloud.githubusercontent.com/assets/17685328/19598853/b9b5e878-97a5-11e6-8aed-7b6ac0e49840.jpg)

- 2 штурмовые винтовки MX с эффективной дальностью до 800 метров
- 10 перевязочных пакетов
- 16 магазинов по 30 патронов для MX
- 6 магазинов по 100 патронов для пулемёта MX 
- 10 ручных гранат
- куча 40-мм говна
- 2 ракеты PCML

С такими припасами отряд NATO может выкосить половину основы, а партизаны могут порешить всю основу, да ещё и на спецоперацию останется. Делают ли игроки это сейчас, используя машину как арсенал? Облегчает ли это задачу? Нет, не облегчает. Получается, что никто не использует машины как передвижной арсенал, если самостоятельно не запихивают туда припасы.

Я предлагаю актуализировать боеприпасы под текущие нужды, но не в таких количествах, как это есть сейчас. Машину нужно сделать не коробкой с припасами, а маленьким НЗ на случай если что-то пойдёт через задницу.

Самое актуальное и лёгкое, что сейчас нужно - магазины 6.5x39, 7.62x39, 5.56x45, дымы, медпакеты. Пулемётные ленты, или пулемётные магазины (можно вставлять и по 30 патронов в лёгкие пулемёты) не нужны, такую тяжесть пусть лучше возят пилоты в ящиках. Снайперам припасы вообще не нужны, т.к. они меткие стрелки и экономят БК до следующей поставки.

**Comment by ToxaBes** [comment]
Вроде раньше было меньше снаряги в транспорте - упустил я этот момент. Давай  возьмем за основу твой вариант,  только без рюкзаков/зарядов а вместо трасеров добавим магазины под другие нужные калибры. Нужен вариант при котором машины не являются лакомыми кусками для партизан.

**Comment by 12st** [comment]
@ToxaBes Всегда так было, года 1.5 так точно.

**Comment by ToxaBes** [comment]
ну я немного слоупок в таких деталях.

**Comment by Horizon1959** [comment]
@ToxaBes остальные боеприпасы не нужны, это даст дополнительный стимул иметь пилота в команде. Даже я сел за штурвал утюга, чтобы скидывать машины с припасами. Трассеры можно оставить, т.к. приемуществ они не дают, а в pvp вообще неприемлимы. Взрывчатку с рюкзаком в принципе можно не толкать, на КП же есть.

Кстати, @ToxaBes , ты ещё не видел что внутри Пантеры лежит, бгг.

**Comment by ToxaBes** [comment]
Начал делать и понял что нужно 2 списока:
1) MRAPы - уменьшенное количество всех предметов
2) Бронетехника - стандартное количество предметов к которому пришли + доп предметы, возможно пара выстрелов к Аламуту/PCML

@Horizon1959 - составь пожалуйста списки согласно тому что обсудили.

**Comment by Horizon1959** [comment]
@toxabes ок.

**Comment by Horizon1959** [comment]
MRAP и LSV:

Магазин STANAG, 30 патр. 6,5 мм - 3 шт.
Магазин STANAG, 30 патр. (красные) 6,5 мм - 3 шт.
Запасной магазин на 30 трас. патронов 7,62 (зеленые) - 3 шт.
Магазин на 30 трас. патронов 7,62 (зеленые) - 3 шт.
Магазин на 30 станд. трас. патронов 5,56 мм (красные) - 4 шт.
Магазин на 30 патронов 5.56 с трассирующими пулями (красными) - 4 шт.
Дымовая шашка (синяя) - 16 шт.
Осколочная граната РГО - 4 шт.
Перевязочный пакет - 8 шт.

Крупная техника:

Магазин STANAG, 30 патр. 6,5 мм - 3 шт.
Магазин STANAG, 30 патр. (красные) 6,5 мм - 3 шт.
Запасной магазин на 30 трас. патронов 7,62 (зеленые) - 3 шт.
Магазин на 30 трас. патронов 7,62 (зеленые) - 3 шт.
Магазин на 30 станд. трас. патронов 5,56 мм (красные) - 4 шт.
Магазин на 30 патронов 5.56 с трассирующими пулями (красными) - 4 шт.
Дымовая шашка (синяя) - 16 шт.
Осколочная граната РГО - 4 шт.
Перевязочный пакет - 8 шт.
ПТ выстрел РПГ-42 - 2 шт.
ПТ выстрел PCML - 2 шт.

Думаю, что этого достаточно.

**Comment by ToxaBes** [comment]
Подходит, ничего лишнего. А для Таноа?

**Comment by Horizon1959** [comment]
@ToxaBes это универсальный список, т.к. синие используют в основном MX, АК и SPAR-16.

**Comment by ToxaBes** [comment]
Хм, а разве синие не используют калибр 5.8 (винтовки с апекса)?

**Comment by Horizon1959** [comment]
@ToxaBes у синих чудные винтовки китайцев не пользуются популярностью. Раньше был по сути один стандарт, сейчас их уже три. Вот под самые используемые и надо ориентироваться, а любители экзотики и так переживут.

**Comment by ToxaBes** [comment]
ок.
