### ISSUE TITLE
Не уничтожаются дартеры без топлива

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#176]
Вчера, на Таноа, обнаружил сидящий на земле дартер без топлива, он стоял там больше 30-ти минут. Скрипт по их очистке в таких случаях работает вообще?

**Comment by ToxaBes** [comment]
Это значит что он посажен вручную/по команде и у него больше 10% топлива. В этом случае скрипт не убирает его и это правильное поведение. Скрипт проверяет уровнь топлива  а не положение дартера.

**Comment by Horizon1959** [comment]
@ToxaBes ок, но ведь у него не было топлива - полный ноль.

**Comment by ToxaBes** [comment]
Взлететь не мог из-за ЭМИ после ядерного удара например.

**Comment by Horizon1959** [comment]
@ToxaBes ядерки и РЭБ не было, точно помню.

**Comment by ToxaBes** [comment]
Нужно попробовать повторить баг -  поставить дартер на высоте и подождать.

**Comment by Horizon1959** [comment]
@ToxaBes сейчас зайду, поставлю один дартер в воздух. Заодно узнаю сколько времени они могут держаться на одном АКБ.

**Comment by Horizon1959** [comment]
@ToxaBes на Алтисе всё ок, буду тестить на Таноа завтра.

**Comment by Horizon1959** [comment]
Засёк. Сейчас на Таноа осталось в живых несколько дартеров с топливом ниже 5%, но я успешно их гоняю туда-сюда.

**Comment by Horizon1959** [comment]
Осталось 4-е из 8-ми дартеров. Как только батарейка села, они резко теряли высоту, а потом плавно садились на землю. На терминале пишет, что они повреждены, на интерфейсе при ручном управлении повреждений нет.

**Comment by Horizon1959** [comment]
@ToxaBes ещё один момент.  Ломаные квадрокоптеры всё ещё на месте, но я могу вызвать ещё 8 штук.

**Comment by ToxaBes** [comment]
Дартер считается уничтоженным,  поэтому исключен из прлверки. То что он физически остался целым - глюк армы.

**Comment by Horizon1959** [comment]
@ToxaBes понятно.
