### ISSUE TITLE
Стрельба НАРами осуществляется пилотом

### ISSUE THREAD

**Issue by Noart537** [ToxaBes/ADR-Spec-Ops#177]
Возможность стрельбы НАРами пилотом Каймана, а не стрелком. Пилотом удобней стрелять НАРами, чем говорить стрелку, когда стрелять.

Добавить в fn_SMhintSUCCESS.sqf

```sqf
	if (_reward isKindOf "O_Heli_Attack_02_black_F") then {
		_reward removeMagazineTurret ["38Rnd_80mm_rockets", [0]];
		_reward removeWeaponTurret ["rockets_Skyfire", [0]];
		_reward addMagazineTurret ["38Rnd_80mm_rockets", [-1]];
		_reward addWeaponTurret ["rockets_Skyfire", [-1]];
	};
```

**Comment by Horizon1959** [comment]
@Noart537 оно надо вообще? У нас всегда кайман летает со стрелком.

**Comment by Noart537** [comment]
Пилоту хоть скучать не придется, а тоже поработает. Смотрите сами, я лишь предложил, ваше дело отказаться =)

**Comment by 12st** [comment]
Надо, т.к. пилоту намного легче самому направлять ракеты, а не говорить стрелку в какие моменты стрелять или надеяться, что стрелок сам будет попадать.
А когда летаешь в одиночку там вообще хоть с пушки стрелять можно, так, что это именно для 2 человек фича.

**Comment by ToxaBes** [comment]
В каймане не спроста сделано разделение по вооружению.  Кайман сам по себе - имба с кучей вооружения. У него всего два сдерживающих фактора: лотерея при посадке и необходимость второго пилота для задействования всего вооржения, т.е. нужен экипаж который может играть командно что бывает довольно редко и это плюс. Я против создания имб для одиночек. 
Также тут будет нарушение баланса - у нас 4 слота пилота, сейчас получается 2 пилота на кайман и еще 2 боевых верта или верт +самолет.  Итого макс 3 боевых авиа-единиц. Если сделать второго пилота в каймане ненужным то получится что у синих одновременно дрступно 4 боевых авиа-единиц,  тк второй пилот пойдет на свой верт или начнет возить пехоту. 
На самом деле у нас дикий дисбаланс по пилотам до которого у меня еще не дошли руки. В текущем виде нам нужно 2-3 слота пилотов,  не больше.  У нас сейчас 4, пока это не критично тк 4 слота сразу заняты практически никогда.

**Comment by 12st** [comment]
@ToxaBes В данном случае мы даём пилоту возможность стрелять неуправляемыми ракетами даже если в вертолёте есть стрелок. Без стрелка пилот имеет доступ ко всему вооружению, но не может наводить ПТ ракеты на цель. То есть одиночных пилотов это не затронет никак, совсем.

**Comment by ToxaBes** [comment]
Представьте ситуацию: заходит опытный пилот,  например @12st , и садиться в кайман в котором сделано то что вы предлагаете. Какова вероятность того что он возьмет с собой второго пилота? Если округлить до целого то это 0%  т. к. смысла больше в нем нет.

**Comment by 12st** [comment]
Я и сейчас так могу сделать.

**Comment by ToxaBes** [comment]
Но ты останешься без НАРов, так?

**Comment by 12st** [comment]
Нет, всё вооружение будет на месте.

**Comment by ToxaBes** [comment]
Хм,  это плохо. Я предлагаю наоборот сделать разделение чтобы кайман был эффективен только при 2х пилотах.  Например,  первый пилот имеет только НАРы и ловушки. Второй пилот все остальное. Или как-то иначе распределить вооружениечтобы брать второго пилота имело большой смысл. Это как с танком - можно в одно лицо ездить и скакать между водителем/стрелком, а можно взять стрелка и действовать более эффективно.

**Comment by 12st** [comment]
Одному летать не эффективно, пушка смотрит только в одну сторону, наводить её тяжело, отсутствует тепловизор, ПТ ракеты превращаются в неуправляемые. Всё это заставляет подлетать в упор, а долго при таком раскладе не полетаешь.

**Comment by 12st** [comment]
Тут кстати и предлагают дать возможность пилоту стрелять нурсами, когда есть стрелок, а одиночных пилотов на каймане нет, это просто не имеет смысла. Просто побаловаться пару раз не более.

**Comment by ToxaBes** [comment]
Ты знаешь,  я могу судить о том как это только с ваших слов,  поиому что сам не пилот.  Мне главное чтобы со вторым пилотом кайман становился гораздо эффективнее.  Например,  эиу же проблему решили в батлфилде.  Там насколько я помню управляемые ракеты и ик ловушки только у второго пилота. Может нам сделать доступным все вооружение обоим пилотам но ловушки оставить только второму пилоту? 
Мне всегда казалось что один пилот на каймане оч даже эффективен.

**Comment by ToxaBes** [comment]
кажется я начал понимать ) 
когда есть второй стрелок -  первому скучно,  так?  Что ему доступно в этом случае?

**Comment by 12st** [comment]
В батле у пилота неуправляемые ракеты и контр меры, у стрелка всё остальное. В арме у пилота только ловушки и ничего больше, тут предлагают добавить ему неуправляемые.

**Comment by Horizon1959** [comment]
Вы лучше не мудрите, сейчас и так всё ок. Главное оружие каймана - ПТУР и пушка, для них нужен стрелок. Главная идея экипажа в машине - разделение обязанностей.

**Comment by ToxaBes** [comment]
Если у первого пилота только ловушки при наличии второго пилота то разрешить ему НАРы - логично. С этого надо было начинать объяснение -  я ж не пилот. 
@Noart537 - спасибо за предложение,  а @12st  -  за разъяснения. Так и сделаем.

**Comment by 12st** [comment]
@ToxaBes Если есть стрелок доступны только ловушки, если нет стрелка доступно ручное управление огнём. То есть имеем пушку которая будет смотреть только в одну сторону, ПТ ракеты без возможности авто наведения и нурсы. Я так понял тебя смутило, что пилот при отсутствии стрелка сможет оставаться эффективным, но на деле это не так. Убрать это мы не сможем  т.к. так работает арма, да и смысла это не имеет.

**Comment by ToxaBes** [comment]
Да,  я думал что в одиночку пилот имеет все возможности второго пилота.
