### ISSUE TITLE
Сбой счётчика дартеров

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#178]
Сегодня на Таноа запустил свои 8 дартеров, после был вылет игры (BIS ушлёпки). когда снова зашёл, смог вызвать ещё 8 дартеров,  предыдущие поддавались контролю, но вели себя странно. Отправил их на убой, но по ходу в схеме какой-то косяк.

**Comment by ToxaBes** [comment]
В схеме нет косяка, это косяк дартеров из той же серии что и невозможность подключения к дартеру если оператор убит. В коде миссии это не пофиксить.

**Comment by Horizon1959** [comment]
Ок:)
