### ISSUE TITLE
Ящики с боеприпасами

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#18]
- [ ] Добавить вариант пустого ящика, чтобы игроки могли сложить туда свое снаряжение перед десантированием
- [ ] Рассмотреть и применить предложенный Горизонтом вариант (Supply_h_ap.sqf):

- уменьшил количество магазинов с обычными пулями и увеличил количество магазинов с трассирующими
- заменил зелёные трассирующие у 5.56 на красные
- увеличил количество магазинов под MX SW
- добавил 4 подрывных заряда
- убрал мини-гранаты
- количество дымовых гранат увеличил до 16
- гранаты под Аламут сделал по 6 на ПТ/ПП
- увеличил число ракет под титан ПТ/ПВО до 12
- увеличил количество медпакетов до 30
- увеличил количество аптечек и инструментов до 2
- заменил рюкзаки на их раскраску в МТР (мультикам)

```sqf
_cargo addMagazineCargoGlobal ["30Rnd_556x45_Stanag", 5];
_cargo addMagazineCargoGlobal ["30Rnd_556x45_Stanag_Tracer_Red", 15];
_cargo addMagazineCargoGlobal ["20Rnd_556x45_UW_mag", 10]; 
_cargo addMagazineCargoGlobal ["30Rnd_65x39_caseless_green", 5]; 
_cargo addMagazineCargoGlobal ["30Rnd_65x39_case+less_green_mag_Tracer", 15]; 
_cargo addMagazineCargoGlobal ["5Rnd_127x108_APDS_Mag", 15]; 
_cargo addMagazineCargoGlobal ["7Rnd_408_Mag", 15]; 
_cargo addMagazineCargoGlobal ["10Rnd_93x64_DMR_05_Mag", 20]; 
_cargo addMagazineCargoGlobal ["10Rnd_127x54_Mag", 20]; 
_cargo addMagazineCargoGlobal ["10Rnd_338_Mag", 20]; 
_cargo addMagazineCargoGlobal ["20Rnd_762x51_Mag", 20]; 
_cargo addMagazineCargoGlobal ["10Rnd_762x54_Mag", 20]; 
_cargo addMagazineCargoGlobal ["30Rnd_65x39_caseless_mag", 5];
_cargo addMagazineCargoGlobal ["30Rnd_65x39_caseless_mag_Tracer", 25]; 
_cargo addMagazineCargoGlobal ["100Rnd_65x39_caseless_mag_Tracer", 15]; 
_cargo addMagazineCargoGlobal ["150Rnd_762x54_Box_Tracer", 10]; 
_cargo addMagazineCargoGlobal ["200Rnd_65x39_cased_Box_Tracer", 10]; 
_cargo addMagazineCargoGlobal ["150Rnd_93x64_Mag", 10]; 
_cargo addMagazineCargoGlobal ["130Rnd_338_Mag", 10]; 
_cargo addMagazineCargoGlobal ["SatchelCharge_Remote_Mag", 2];
_cargo addMagazineCargoGlobal ["DemoCharge_Remote_Mag", 4]; 
_cargo addMagazineCargoGlobal ["HandGrenade", 6]; 
_cargo addMagazineCargoGlobal ["SmokeShell", 16]; 
_cargo addMagazineCargoGlobal ["SmokeShellGreen", 16]; 
_cargo addMagazineCargoGlobal ["SmokeShellBlue", 16]; 
_cargo addMagazineCargoGlobal ["1Rnd_HE_Grenade_shell", 16]; 
_cargo addMagazineCargoGlobal ["RPG32_HE_F", 6]; 
_cargo addMagazineCargoGlobal ["RPG32_F", 6]; 
_cargo addMagazineCargoGlobal ["Titan_AT", 12]; 
_cargo addMagazineCargoGlobal ["Titan_AA", 12];
_cargo addMagazineCargoGlobal ["Laserbatteries", 5];
_cargo addItemCargoGlobal ["FirstAidKit", 30]; 
_cargo addItemCargoGlobal ["Medikit", 2]; 
_cargo addItemCargoGlobal ["ToolKit", 2]; 
_cargo addBackpackCargoGlobal ["B_AssaultPack_mcamo", 2];
_cargo addBackpackCargoGlobal ["B_Kitbag_mcamo_Eng", 2];
```

**Comment by AlexVDem** [comment]
Пустой ящик думаю никому не нужен. Поскольку я таскал технику много раз и часто просил туда складывать припасы, так вот это делали только единицы. Проще тогда страйдер подцепить, а не ящик, на нем хоть ездить можно.

**Comment by Horizon1959** [comment]
@AlexVDem пустой ящик нужен десантникам, т.к. они лишаются своих рюкзаков при высадке.

**Comment by AlexVDem** [comment]
Да я не против, тем более что это не займет много времени чтобы сделать, пара строк кода в макросе респа контейнеров. Просто врятли кто будет этим пользоваться. Десант сейчас проще в страйдер посадить и туда же накидать барахла.

**Comment by malashin** [comment]
Как будет загружаться пустой ящик? Кто-то будет бегать или на машине ездить от арсенала к ящику и загружать?

Не думаю, что пилот возьмется отвезти пустой ящик к арсеналу. При этом вызвать загруженный ящик некоторое время будет нельзя и пилот будет простаивать и ждать загрузки ящика.

То есть придется ставить рядом арсенал для загрузки ящиков.

---

Как вариант можно не делать пустой ящик, а дать подобным ящикам экшн на первую минуту их существования и любой игрок может подойти, выбрать экшн и убрать всё из ящика. Но кто-то сможет троллить и специально разгружать ящики пока пилот их цепляет.

**Comment by ToxaBes** [comment]
Так, похоже вы не совсем поняли концепцию пустого ящика. Он нужен для того чтобы игроки скинули в него свои рюкзаки и одели парашюты. Т.е. алгоритм такой:
1. пилот вызывает пустой ящик и идет запускать вертушку
2. игроки подъезжают к ящику на квадриках и скидывают свои рюкзаки (медики, снайперы - все)
3. затем берут парашюты и садятся в вертушку (или уже из вертушки парашюты берут)
4. пилот цепляет ящик и летит  в точку выброски
5. игроки десантируются + пилот отцепляет ящик
6. при приземлении игроки находят ящик, разбирают свои рюкзаки и идут в бой

в таком виде мы получим хоть какое-то приближение к реальному десантированию.

**Comment by ToxaBes** [comment]
>Десант сейчас проще в страйдер посадить

Давай, посади мне в страйдер группу из 10 чел )

Похоже что единственный кто пока понял о чем я говорю - Горизонт.

**Comment by malashin** [comment]
Самое веселое будет найти свой рюкзак из десятка одинаковых.

**Comment by ToxaBes** [comment]
Ну это не такая большая проблема )  Не у всех они одинаковые, а у одинаковых не все одного цвета.

**Comment by malashin** [comment]
Да 100% начнется нытье по поводу того, что у кого-то рюкзак забрали и поиски обидчика. ;)

**Comment by ToxaBes** [comment]
Ну на первом все же основной костяк давно не новички, к тому же зачем например пулеметчику забирать рюкзак медика или снайпера?

**Comment by AlexVDem** [comment]
Да я же говорю, что я не вижу препятствий это сделать, просто и смысла особого не вижу, учитывая то, что сейчас на сервере максимум 10 человек на пике, а висреднем 5-6, и десант там редкость. 
Кстати, удивлен что народу мало стало, я тут заходил на сервера EUTW, там ажиотаж на 4х серверах по 60 чел на каждом не редкость. Правда и режим у них PvP, может в этом дело. Надоело всем ботов крошить (мне кстати тоже), хочется против реального противника на нормальном сервере, без аддонов, ты радио и прочих заморочек с правилами.

**Comment by ToxaBes** [comment]
>просто и смысла особого не вижу

Я например тоже не представляю чтобы ты этим пользовался. Насколько я помню ты играешь либо пилотом вертолета, либо снайпером и для тебя фича бесполезна, но ты не один - есть другие котором эта фича пригодится.  

>то сейчас на сервере максимум 10 человек на пике, а в среднем 5-6

И поэтому не надо ничего делать? Мы делаем миссию в первую очередь для себя.

>Надоело всем ботов крошить (мне кстати тоже), хочется против реального противника на нормальном сервере

Ну дык никто же не держит, каждый выбирает по своим интересам, просто зачем тут флудить? 
Если есть желание порассуждать о том что "раньше деревья были зеленее" или "а вот на EUTW или еще где" - велкам на форум, создай тему и вперед. Тут мы обсуждаем только задачу. Без флуда. Обсуждение закрываю.

**Comment by Noart537** [comment]
Можете со второго взять скрипт ящиков, там правда через switch. Скомпановал в пару файлов.  Работает стабильно. Если не сбрасывать одновременно 2 ящика. Можете через if сделать, но задержки в работе switch не замечал. 

Там еще нужно добавить удаление модуля через 10 мин. (или на усмотрение)

**Comment by ToxaBes** [comment]
@Noart537 - спасибо, я планировал применить твой скрипт по ящикам со второго сервера когда руки дойдут до этой задачи, но @malashin ее взял на себя.

@malashin  - если не сложно, когда будешь делать эту задачу, примени последние изменения Noarta по ящикам со второго сервера.

**Comment by malashin** [comment]
@ToxaBes посмотрю. Можно в один файл объединить даже.

По поводу набору боеприпасов от Горизонта комментариев нет? Применяем как первом посте написано?

**Comment by ToxaBes** [comment]
>Можно в один файл объединить даже.

Как посчитаешь нужным.

>Применяем как первом посте написано?

Да, это уже сбалансированный вариант. Попробуем его и потестим.

**Comment by malashin** [comment]
Переделал всё.

- Добавлен пустой ящик.
- Содержимое ящика с боеприпасами от @Horizon1959.
- Добавлен контейнер с боеприпасами. Такой же как и ящик, только тяжелее и больше патронов в нём.
- Ящик можно вызвать только раз в 60 секунд.
- Если в зоне ящиков при вызове нового уже есть ящики, то они удаляются.
- Более реалистично цепляется парашут и сносится ветром. Нужно заново привыкать его бросать.
- После приземления ящика на землю, через 15 минут он удаляется.

---

@Horizon1959 нужно просмотреть набор боеприпасов в контейнере. Возможно, есть варианты получше.

```sqf
_cargo addMagazineCargoGlobal ["30Rnd_556x45_Stanag", 14];
_cargo addMagazineCargoGlobal ["30Rnd_556x45_Stanag_Tracer_Red", 14];
_cargo addMagazineCargoGlobal ["20Rnd_556x45_UW_mag", 14];
_cargo addMagazineCargoGlobal ["30Rnd_65x39_caseless_mag", 14];
_cargo addMagazineCargoGlobal ["30Rnd_65x39_caseless_green", 14];
_cargo addMagazineCargoGlobal ["30Rnd_65x39_caseless_green_mag_Tracer", 14];
_cargo addMagazineCargoGlobal ["5Rnd_127x108_APDS_Mag", 20];
_cargo addMagazineCargoGlobal ["7Rnd_408_Mag", 20];
_cargo addMagazineCargoGlobal ["10Rnd_93x64_DMR_05_Mag", 14];
_cargo addMagazineCargoGlobal ["10Rnd_127x54_Mag", 14];
_cargo addMagazineCargoGlobal ["10Rnd_338_Mag", 14];
_cargo addMagazineCargoGlobal ["20Rnd_762x51_Mag", 14];
_cargo addMagazineCargoGlobal ["10Rnd_762x54_Mag", 14];
_cargo addMagazineCargoGlobal ["30Rnd_65x39_caseless_mag_Tracer", 21];
_cargo addMagazineCargoGlobal ["100Rnd_65x39_caseless_mag_Tracer", 15];
_cargo addMagazineCargoGlobal ["150Rnd_762x54_Box_Tracer", 15];
_cargo addMagazineCargoGlobal ["200Rnd_65x39_cased_Box_Tracer", 15];
_cargo addMagazineCargoGlobal ["150Rnd_93x64_Mag", 15];
_cargo addMagazineCargoGlobal ["130Rnd_338_Mag", 15];
_cargo addMagazineCargoGlobal ["SatchelCharge_Remote_Mag", 5];
_cargo addMagazineCargoGlobal ["DemoCharge_Remote_Mag", 5];
_cargo addMagazineCargoGlobal ["HandGrenade", 24];
_cargo addMagazineCargoGlobal ["SmokeShell", 24];
_cargo addMagazineCargoGlobal ["SmokeShellGreen", 24];
_cargo addMagazineCargoGlobal ["SmokeShellBlue", 24];
_cargo addMagazineCargoGlobal ["1Rnd_HE_Grenade_shell", 24];
_cargo addMagazineCargoGlobal ["3Rnd_HE_Grenade_shell", 8];
_cargo addMagazineCargoGlobal ["RPG32_HE_F", 10];
_cargo addMagazineCargoGlobal ["RPG32_F", 10];
_cargo addMagazineCargoGlobal ["NLAW_F", 10];
_cargo addMagazineCargoGlobal ["Titan_AT", 7];
_cargo addMagazineCargoGlobal ["Titan_AA", 7];
_cargo addMagazineCargoGlobal ["Laserbatteries", 10];
_cargo addItemCargoGlobal ["FirstAidKit", 20];
_cargo addItemCargoGlobal ["Medikit", 2];
_cargo addItemCargoGlobal ["ToolKit", 2];
_cargo addItemCargoGlobal ["NVGoggles", 5];
_cargo addItemCargoGlobal ["Laserdesignator", 2];
_cargo addBackpackCargoGlobal ["B_AssaultPack_mcamo", 2];
_cargo addBackpackCargoGlobal ["B_Kitbag_mcamo_Eng", 2];
_cargo addBackpackCargoGlobal ["B_UAV_01_backpack_F", 2];
```

**Comment by ToxaBes** [comment]
Вот и потестим, сейчас применю на сервер.
