### ISSUE TITLE
Администрирование при отсутствии карты

### ISSUE THREAD

**Issue by 12st** [ToxaBes/ADR-Spec-Ops#180]
Сегодня на сервер набежало много незнакомого народа, естественно не все вели себя адекватно. Столкнулся с проблемой, что я банально не могу отследить, что делает человек. Объясню на примере пилота, если раньше, чтобы понять насколько хорошо летает человек можно было просто взглянуть на карту, то теперь приходится зевсом летать за ним, чтобы понять сбивают его или он сам падает, причем если он уже улетел с базы приходится чуть ли ни по всей карте его искать. Предлагаю ввести зевс куратора на игроков, либо в инструментах добавить возможность отображения игроков на карте.

**Comment by Horizon1959** [comment]
@12st секундочку, а разве Васянам не запретили летать, если они не ниграют 2 часа? Разве за бой вертолётов их не закидывает в обезьянник? Сегодня с утра сидел до обеда, никого не было. Чего это наплыв пошёл?

**Comment by 12st** [comment]
Видимо некоторых я не видел, они могут летать, да и пример с пилотом на то и пример.
![toolwiz201610-26-16-47-20](https://cloud.githubusercontent.com/assets/18305023/19728478/2928de1e-9b9c-11e6-92f3-2adc95012e68.png)

**Comment by ToxaBes** [comment]
@12st - Набежали с сервера отстрел в основном, я тоже удивился и промониторил. Кураторы добавлены всем игрокам: https://github.com/ToxaBes/ADR-Spec-Ops/blob/master/co30_ADR_Spec_Ops.Altis/initPlayerLocal.sqf#L219-L222 

Горизонт прав, у нас есть ограничение на 2 часа отыгрыша на сервере для слота пилота. Из списка например у Yahoo около 40 наигранных часов, он может летать.

**Comment by 12st** [comment]
@ToxaBes Погоди оно уже введено или просто прописано и ждёт своего часа?

**Comment by ToxaBes** [comment]
Уже введено, т.е. все у кого со времени ввода партизан больше 2х часов отыграно могут летать.

**Comment by 12st** [comment]
Я про куратора.

**Comment by ToxaBes** [comment]
Кураторы давно прописаны, но после обновлений движка Арма запрещает с ними что-либо делать тк это живые игроки. Возможно имеет смысл сделать админскую утилиту "Наблюдение" > "Выберите игрока" > камера летает за ним сверху сзади в 20м.

**Comment by 12st** [comment]
Странно, когда куратор на игроков включён они должны отображаться в списке справа, но такого нет и не было.

**Comment by ToxaBes** [comment]
Да, такого давно нет, после одного из обновлений в мультиплеере перестали работать кураторы на живых игроков. Если повесить куратора на бота или другой объект - все работает.

**Comment by 12st** [comment]
Когда спавнишь технику через зевс и в неё садится игрок, то всё работает.

**Comment by ToxaBes** [comment]
Потому что куратор висит на технике и отображает ее effective commander. Просто живого игрока давно не показывает - BISы ввели такое ограничение в мультиплеере.

**Comment by malashin** [comment]
@ToxaBes попробуй этот код в консоли от сервера запустить и посмотри добавятся ли игроки Зевсу или нет. Судя по Вики он работает только от лица сервера, а у нас сейчас в initPlayerLocal.sqf.
```sqf
{_x addCuratorEditableObjects [(allPlayers - entities "HeadlessClient_F"), false];} forEach allCurators;
```

Можно что-то подобное поставить в итоге на сервере, если сработает вариант выше. Нужно еще проверить сбрасывается или это после смерти игрока. Если нет, то можно только на коннекте это делать, а не в лупе.
```sqf
if (isServer) then {
 [] spawn {
  while {true} do {
   {
    _x addCuratorEditableObjects [(allPlayers - entities "HeadlessClient_F"), false];
    sleep 60;
   } forEach allCurators; 
  };
 }; 
};
```

**Comment by ToxaBes** [comment]
При выполнении на сервере игроки появляются в левой колонке. Если игрок перезаходит, то он исчезает из списка. @malashin - спасибо за подсказку, буду делать.
