### ISSUE TITLE
Обновить контейнер и ящик с боеприпасами

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#181]
1. Сейчас в контейнере и ящике (по вызову пилота) нет оружия и обвеса (хотя вроде оно там должно быть). Надо туда положить следующее:
- MX (разные цвета для Таноа и Алтиса) - 2 шт.
- SPAR-16 (разные цвета для Таноа и Алтиса) - 2 шт.
- RCO (разные цвета для Таноа и Алтиса) - 2 шт.
- ERCO (разные цвета для Таноа и Алтиса) - 2 шт.
- Глушитель 6,5 мм (разные цвета для Таноа и Алтиса) - 2 шт.
- Глушитель 5,56 мм (разные цвета для Таноа и Алтиса) - 2 шт.
- Сошка НАТО (разные цвета для Таноа и Алтиса) - 2 шт.
1. Нужно обновить рюкзаки в ящиках на Таноа, т.к. они в окрасе MTP. Нужно заменить их на аналогичные в каком-нибудь другом разрешённом цвете
2. В ящиках 2 рюкзака-дартера, думаю они там больше не нужны.

**Comment by ToxaBes** [comment]
Я против того чтобы добавлять туда оружие и обвес для него. Оружие нужно брать на базе, оно не клинит и не ломается, тоже самое с обвесом.
Рюкзаки поправлю, дартеры - выкину.

**Comment by Horizon1959** [comment]
@ToxaBes Т.к. это главный канал поставок, то лучше туда включить стандартные штурмовые винтовки. Бывает так, что ситуация резко меняется и какой-нибудь пулемётчик или снайпер хватает  оружие из ящика и работает как обычный стрелок. Или лучше заставить людей страдать, отправив их мародёрить дрель-катибу с трупа?

**Comment by ToxaBes** [comment]
>Или лучше заставить людей страдать

this.

Хороший снайпер или пулеметчик в любой ситуации останется хорошим оператором. Тут критерий - человек, а не оружие.

**Comment by malashin** [comment]
Украду тикет.

С 27-го октября в dev ветке.

> Tweaked: The CRV-6E Bobcat and Mi-290 Taru supply variants now also have a near infinite supply of ammunition, fuel and repair resources, just like the other supply vehicles in the game

Стоит после патча обратить внимание на это. Раньше мы лимитировали для того, чтобы ограничить бесконечную перезарядку.

**Comment by ToxaBes** [comment]
А любом случае есть смысл оставить наши лимиты, т.к. даже если они и уменьшили количество боеприпасов - их все равно может быть слишком много. Патч покажет.

**Comment by 12st** [comment]
Тут имеется ввиду, что теперь бобкэт и вертолётные модули будут иметь почти бесконечный запас как сейчас у машин. У нас нет ограничения на бобкет, а после патча возможно придётся пересмотреть на вертолётные модули.

**Comment by ToxaBes** [comment]
Точно, неправильно прочитал. Будем проверять после патча.

**Comment by Horizon1959** [comment]
@ToxaBes ок, тогда боль и страдания.

Я не понял, что там хотят бисы намутить? Неограниченный ресурс бобкета и прочих ништяков?

**Comment by 12st** [comment]
@Horizon1959 да, неограниченный запас бк, топлива, ремонта.

**Comment by Horizon1959** [comment]
@ToxaBes тогда надо будет озадачиться этим вопросом. Текущая система лимитов на сервере очень хороша.

**Comment by ToxaBes** [comment]
* оружие и обвес не добавлял
* цвет рюкзаков на Таноа поменял
* рюкзаки с дартерами убрал
* бобкет будем фиксить в отдельном тикете когда его поломают
