### ISSUE TITLE
Переделать квадроциклы на аванпосте

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#183]
Нужно переделать текущую систему квадроциклов на аванпосте. Сейчас их 4 штуки и часто они не респавнятся (где-то теряются или глючат). Предлагаю сделать вызов квадроциклов через терминал, но с условиями, что они не будут пропадать по типу квадроциклов на базе.

Вообще нужно подумать, как можно организовать такой простенький транспорт, чтобы он затирался не заставляя синих страдать. Часто при безлюдности точки мы едем на нём вплоть до центра триггера, на время бросая, а потом садимся на него вновь.

**Comment by ToxaBes** [comment]
>но с условиями, что они не будут пропадать по типу квадроциклов на базе

Не пойдет. Они должны пропадать иначе синие уехав один раз на всех квадриках и погибнув во второй раз пойдут пешком, т.к. вызывать кучу квадриков я не дам (нагрузка на сервер).
Как вариант, можно сделать так: вызов через меню, макс. количество квадриков: 4. Если около него нет игроков в радиусе 100м - он исчезает.

**Comment by Horizon1959** [comment]
@ToxaBes ты меня немного не так понял, я вот имел ввиду именно такую мысль, которую ты сейчас выдал. Давай 150 метров радиус и будет самое оно.

**Comment by ToxaBes** [comment]
ок
