### ISSUE TITLE
Актуализировать награды синих за выполнение задач

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#184]
Сейчас у зелёных большой набор бонусов, у синих же в роли награды выступает наградная техника, да ещё и только за дополнительные миссии.

Предлагаю эту ситуацию изменить и выдавать награды за обе миссии, но с разной значимостью. Например за основную миссию должны выдавать какую-нибудь пехотную машину, а за спецоперацию - специальную. Попутно надо убрать надоевшие и устаревшие машины типа Моры, Горгоны и т.п.

В принципе могу сам разложить что и как, но у меня нет полной картины по наградам синих. Если есть идеи по наградам кроме техники, то валяйте.

P.S. Касатку лучше не трогать, а то господин Банка сильно расстроится.

**Comment by ToxaBes** [comment]
>Сейчас у зелёных большой набор бонусов

Неа, по сравнению с наградами синих партизанские награды вообще ни о чем - в основном ящики с вооружением. Из самого крутого - хеллкет и беспилотник-вертолет которые выпадают крайне редко. В итоге партизанксие награды в большинстве своем бесполезны, т.к. чтобы ее заработать надо налутаться на поле боя, а если налутался - то зачем тебе ящик со снаряжением партизан например?

>Предлагаю эту ситуацию изменить и выдавать награды за обе миссии

Нет, будет слишком много наград.

>Попутно надо убрать надоевшие и устаревшие машины типа Моры, Горгоны и т.п.

Нет, кому-то надоело, а кто-то будет рад пополнению парка бронетехники.

Менять награды не будем, менять механизм выдачи наград тоже не будем. Будем добавлять варианты наград как для синих так и для зеленых.

Например для зеленых очень не хватает следующих вещей:

1. Мобильный постановщик электронных помех (пикап с тарелкой) - блокирует частоты управления беспилотниками синих в радиусе до 2 км. Беспилотники теряют управление и падают. Наземные БПА просто останавливаются и не реагируют на подключение.

2. Техничка с ПВО средством (пикап с стационарным ПВО титаном) - стационарный титан снять с технички нельзя (приварена).

3. Техничка с ПТ средством (пикап со стационарным ПТ титаном) - стационарный титан снять с технички нельзя (приварена).

4. Техничка с гранатометом (пикап со стационарным гранатометом) - гранатомет также приварен.

5. Аванпост зеленых - грузовик, который можно привезти в нужное место и "разложить" в палаточный лагерь (4 палатки, костер, небольшая антенна для связи). Дает доп. точку возрождения партизанам. Аванпост можно разложить только один раз - где поставили там и будет стоять. Пока аванпост цел - партизаны не могут вызвать новый аванпост из списка наград даже если уже заработали его. Синие могут уничтожить аванпост - достаточно одной бомбы с беспилотника или пары гранат по палаткам.

Предлагайте свои варианты для синих и зеленых.

**Comment by Horizon1959** [comment]
> Неа, по сравнению с наградами синих партизанские награды вообще ни о чем - в основном ящики с вооружением. Из самого крутого - хеллкет и беспилотник-вертолет которые выпадают крайне редко. В итоге партизанксие награды в большинстве своем бесполезны, т.к. чтобы ее заработать надо налутаться на поле боя, а если налутался - то зачем тебе ящик со снаряжением партизан например?

@ToxaBes это к тебе вопрос. Может ящик и гуманитарная помощь станут резко нужны, если партизаны будут терять награбленное после смерти, а?:) В компенсацию можно им всякие Mk200  отдать, M14 и шайтан-трубу (всё по канону). 

> Нет, будет слишком много наград.

@ToxaBes погляди сколько за вечер при онлайне около 10-ти человек будет наградной. Не больше двух. 

> Нет, кому-то надоело, а кто-то будет рад пополнению парка бронетехники.

@ToxaBes  Найди этих людей. Банка с касаткой не в счёт, т.к. он всё равно дохнет на взлёте или в течении 10-ти минут, да и существенного вреда никому не причиняет.

> Менять награды не будем, менять механизм выдачи наград тоже не будем. Будем добавлять варианты наград как для синих так и для зеленых.

@ToxaBes как раз-таки все эти новые награды мы не увидим. Я вертолёт-беспилотник видел только один раз вообще. новый БПА-самолёт красных видел два раза. Из-за большого списка бесполезной техники ничего хорошего и актуального синие не видят. От части это из-за того, что время работы по точкам увеличилось из-за сложности миссий и низкого онлайна.

- БТР/БМП дохнет при штурме сразу и не несёт КПД, т.к. у нас боты, да ещё и партизаны в лесу сидят
- Меркава-серию и танки никто  теперь не использует (кроме заблудших васянов), т.к. медленная и понерфленная
- Ударная авиация не используется, т.к. все пилоты уже давно не летают, а после апекса с поля боя в летуна летит 5-8 ракет одновременно. Юзать её в конце, когда нет противника, скучно и бесполезно.
- Экзотические мариды с нурсами и килины с пулемётами тоже контингент брать не хочет по причине их уязвимости и малого толка (пешком безопаснее)

- Например для зеленых очень не хватает следующих вещей:

@ToxaBes контингент сказал, что зелёным нужно ещё добавить губозакатывающую машину. Если серьёзно, то нужно не добавлять ящик с бонусами, а выдавать в пользование новое оружие прямо в арсенале, как например это было раньше в end game. Или каким-нибудь другим образом.

На счёт аванпоста зелёных - вещь клёвая, однозначно. Глушилка БПА без средств её обнаружения - зло похуже тепловизоров на морде лица, т.к. на данный момент БПА - это единственное эффективное средство противодействию спецназовцам-зелёным, которые в течении 30-ти минут получают лучшее снаряжение, оружие и могут выполнять сразу кучу задач даже вдвоём, что недоступно синим.

**Comment by 12st** [comment]
Для того чтобы зелёным были нужны ящики нужно просто не пополнять бк в непотраченых магазинах при смерти.

**Comment by 12st** [comment]
Можно раскидать технику по допкам, например за Радар дают только самолёты, за заложников пехотную технику, за прототип, прототип того вертолёта который там стоит и так далее. Тогда люди сразу будут знать, что выпадет и будет меньше случаев когда подряд выпадает одно и тоже.

**Comment by ToxaBes** [comment]
@Horizon1959 :
>если партизаны будут терять награбленное после респавна

Собирался это добавить в 9м релизе ну ладно, оформляй отдельным тикетом в этот релиз. Только сделаем так - если партизан один, то все остается как сейчас потому-то вылечить на месте некому. Если партизан больше одного то при респавне появляются пустыми.

> В компенсацию можно им всякие Mk200 отдать, M14 и шайтан-трубу (всё по канону).

Нет, партизаны должны постоянно чувствовать боль и превозмогать.

> нужно не добавлять ящик с бонусами, а выдавать в пользование новое оружие прямо в арсенале, как например это было раньше в end game

Если засунуть в арсенал то это 1) геморно реализовать , 2) оружие будет бесконечным. Ящики хороши тем что: 1) ограниченное количество всего, 2) заспавненый ящик видно - демаскирует и 3) при переносе базы ящики остаются на месте.

>Глушилка БПА без средств её обнаружения - зло похуже тепловизоров на морде лица

Глушилка выпадает редко, можно сделать так что она работате только когда стоит на месте, а при ее включении будет круг на карте  примерно 2км радиусом и в нем будет где-то глушилка стоять. Т.е. пока ее не выключат будет ясно что а) она там и включена, б) туда лететь не стоит.

>которые в течении 30-ти минут получают лучшее снаряжение, оружие и могут выполнять сразу кучу задач даже вдвоём, что недоступно синим.

Смешно читать о превосходстве партизан. Лучшее оружие и броники у синих (мы их и берем если находим), народу больше у синих, т.е. вы должны в разы эффективнее выполнять задачи. Мне кажется тут вопрос организации/командования.

@12st :
>Для того чтобы зелёным были нужны ящики нужно просто не пополнять бк в непотраченых магазинах при смерти.

Согласен. Добавь отдельным тикетом.

>Можно раскидать технику по допкам

Допок + Спецопераций  у нас 14 штук. Получится примерно каждой допке своя награда. Я против этого т.к начнется следующее: за одну допку будут рвать жилы тк будут знать что что-то релаьно нужное. Другую будут сливать тк награда фигня.

**Comment by 12st** [comment]
Можно сделать так, что в каждой допке будет определённый набор техники(в разных допках техника может повторятся, но не будет полностью копировать)

**Comment by 12st** [comment]
И к слову допки не проваливают намеренно со времён тг 2, у нас они не надоедают и обычно всем интересны.

**Comment by ToxaBes** [comment]
>Можно сделать так, что в каждой допке будет определённый набор техники(в разных допках техника может повторятся, но не будет полностью копировать)

В таком случае теряется смысл разделения. Можно сделать проще - оч. часто "рандом" в арме берет значения из начала и середины списка. Мы можем подвинуть редкие и интересные позиции наверх. И пока что-то нет предложений по новой награде для синих.

**Comment by Horizon1959** [comment]
> Нет, партизаны должны постоянно чувствовать боль и превозмогать.

@ToxaBes Сейчас основная идея партизан - собирательство, т.к. за 30 минут можно надыбать такой комплект, что синих можно нагибать очень сильно. Как только собирательство прекратится, то с текущей снарягой начнутся не только боль и страдания, но ещё ад и Израиль. Предлагаю добавить в арсенал зелёным на старте тактические жилеты, пулемёт Mk200 и винтовку Mk14.  Много ты с этим не навоюешь, но в то же время ускоришь переход от собирательства к полноценным боевым действиям. Как только идея собирательства отпадёт, то люди привыкнут не бегать и мародёрить, а воевать с чем есть, дополняя основное снаряжение партизан вещами с трупов. Взгляни на партизан в кампании "Восточный ветер", где главному герою выдают группу в управление. Вот если осуществить такие шаги, то они будут действительно похожи на партизан, а не опергруппу CSAT.

> Если засунуть в арсенал то это 1) геморно реализовать , 2) оружие будет бесконечным. Ящики хороши тем что: 1) ограниченное количество всего, 2) заспавненый ящик видно - демаскирует и 3) при переносе базы ящики остаются на месте.

@ToxaBes Ок, если это геморно, то лучше оставить как есть.

> Глушилка выпадает редко, можно сделать так что она работате только когда стоит на месте, а при ее включении будет круг на карте примерно 2км радиусом и в нем будет где-то глушилка стоять. Т.е. пока ее не выключат будет ясно что а) она там и включена, б) туда лететь не стоит.

@ToxaBes ты имеешь ввиду зону, обозначенную на карте?

> Смешно читать о превосходстве партизан. Лучшее оружие и броники у синих (мы их и берем если находим), народу больше у синих, т.е. вы должны в разы эффективнее выполнять задачи. Мне кажется тут вопрос организации/командования.

@ToxaBes Абсолютно не так. Лучшего оружия не существует, а вот самое защищённое снаряжение у красных (броники им не нужны). На эту тему тебе телегу может прогнать @12st .

 То, что синих больше, не значит. что это является превосходством, т.к. не все передвигаются в подразделении, а ещё у каждого свой набор задач (да-да, не все из нас могут поднимать, таскать снайперские винтовки, пулемёты, моднейшие прицелы, ЛЦУ с тепловизором и ракетные установки). На деле выходит, что активных стрелков мало, т.к. нам обязательно нужны специалисты поддержки, без которых стрелки мало что могут. Количество ≠ эффективность. 

Ещё добавлю. что арма 3 затачивалась как поле боя малых пехотных групп, и большое количество людей тут только вредит (партизан мало и в этом их главный козырь, они почти всегда могут пройти незаметно и более мобильны). Организация и командование тут мало решают, т.к. у нас ребята опытные и автономные, единственное, что нужно - периодически матерится.

Вернусь к началу треда: что будем делать с наградной техникой? Нужна ли она в нынешнем виде, если её очень редко берут? Может замутить другой тип наград? Я провёл опрос контингента и они все видеть уже не могут слеммеры, горгоны и прочий мусор, люди хотят видеть тактические, а не ударно-сгорающие машины. 

К слову, основной потребитель бронетехники (сюрприз!) - инженер. Инженеров можно пересчитать по пальцам.

**Comment by ToxaBes** [comment]
>тактические жилеты, пулемёт Mk200 и винтовку Mk14

Этим ты сократишь собирательство до первого бота с ARCO или DMS прицелом. Нельзя такое давать. Основная идя партизан у нас - выживание и выполнение задач используя все возможные ресурсы. Собирательство - часть этого.

>ты имеешь ввиду зону, обозначенную на карте?

Да, как только глушилку включили - на карте появился круг радиусом 2км, глушилка где-то внутри круга - не по центру. Выключили - круг исчез.

> а вот самое защищённое снаряжение у красных (броники им не нужны). На эту тему тебе телегу может прогнать @12st .

Нет, самое защищенное снаряжение это когда на форму красных одеваешь тяжелый жилет синих. Но для этого надо из trg/mk20 убить и того и другого. 

>То, что синих больше, не значит. что это является превосходством

Даже если половина будет слушаться командира это уже сила против 1-2 партизан. Один единственный хороший инженер синих подняв беспилотники может нагибать партизан очень жестко, тоже самое с хорошим пилотом. Хороший командир с горсткой бойцов будет гонять партизан ссаными тряпками по всей карте. Что мешает из тех кто хочет играть командно выделить небольшую группу охотников за партизанами которые будут либо активно охотится либо прикрывать основную группу на задании мне не понятно. Не хотите устраивать контрпартизанские действия - страдайте. То что партизаны сильнее синих - глупость. Пока партизаны держаться только за счет своей тактики и отсутствия контрпартизанских действий. Как только начинаются контрпартизанские действия - все, для партизан хорошая жизнь заканчивается.

>люди хотят видеть тактические, а не ударно-сгорающие машины.

Тактической машина становится в умелых руках, в неумелых - ударно-сгорающей. Про какие "тактические" машины ты говоришь?

**Comment by Horizon1959** [comment]
@ToxaBes не всегда беспилотниками можно что-то сделать (особенно в джунглях). К тому же оператор должен сидеть на пятой точке, будучи немобильным.

Пилоту же нужен нормальный самолёт, да и вообще его моментально сбивают по причине армии синхронно стреляющих ботов (такая жопа началась перед апексом). Охотники на партизан явление редкое, т.к. людей сейчас не хватает. А партизаны сейчас сильнее потому что простым зерг рашем они получают лучшее снаряжение и являются универсальными солдатами, когда синим нужно иметь отделение для выполнения всех необходимых задач.

Пока партизаны держатся только из-за универсальности, лучшего снаряжения полученного зерг рашем, разгильдяйства любителей гидрокостюмов и касаток. Полноценные контрпартизанские действия попробуем после запила тикета о собирательстве.

По машинам всё проще в стопицот раз (я как заклятый мехвод скажу): ни один танк и БТР/БМП в арме не может стать тактическим, т.к. он не может быть приспособлен для разных задач, его задача только одна: идти в грубую атаку. Все его манёвры сопровождаются низкой скоростью, малой тягой, большими габаритами, дичайшим шумом. 

Тактические единицы - это MRAP, LSV, беспилотники типа дартера, стомпера, MQ-12 Falcon. Тактической единицей мог бы быть хитрый инструмент или средство. Про что-то новое у синих пока говорить рано (пока не появится стабильный онлайн около 3-ёх партизан и хотябы 10-ти синих одновременно), нужно хотя бы убрать бесполезный хлам, который не вяжется с текущим точечным геймплеем.

Ещё раз, но короче: наградная техника в нынешнем виде - это наследие Tehgam 2, где тактики было минимум, а грубой силы максимум. В текущем виде награды синих - это огромный тяжёлый топор варвара, а в нынешней обстановке нужен нейрохирургический инструмент.

**Comment by 12st** [comment]
Пилоту нужен джойстик, без него с постоянно включённым теплаком летать невозможно(а именно так и вычисляют партизан), у нас таких пилотов не больше 5, а которые к тому же умеют и хотят летать ещё меньше.

**Comment by ToxaBes** [comment]
>А партизаны сейчас сильнее потому что простым зерг рашем они получают лучшее снаряжение и являются универсальными солдатами, когда синим нужно иметь отделение для выполнения всех необходимых задач.

Никакого зерг раша. То что ты называешь зерг рашем - использование огня и маневра. Зерг раш идет в основном у одиночек со стороны синих. Партизаны сильнее потому что играют командно, они просто вынуждены иначе постоянно будут ездить с базы, а у синих разброд и шатание в половине команды.

Дальше, с чего ты решил что партизаны могут выполнять все задачи? Партизаны все время выбирают между хорошей (тяжелой) снайперкой с кучей патронов или  катибой с подрывными пакетами/минами или аламутом, между хорошим (тяжелым) пулеметом и ПТ или ПВО титаном и т.д. Партизаны имеют ту же выносливость и просто физически не могут перекрыть все классы.
Это мифы выдумываемые синими. Сколько раз нас убивал воздух потому что партизаны взли ПТ титан а не ПВО просто не сосчитать (и наоборот). Сколько раз нужен был ремкоплект который был выброшен ради подрывного заряда для вышки и тд. Перечислять можно долго, но суть в том что сейчас синим хватает людей чтобы нагибать партизан но не хватает командного взаимодействия. Это орг. проблема которую скриптами не решить.

По наградной - убирать позиции я не собираюсь т.к. надоело/не надоело - это субъективные суждения. Изменить порядок в списке, сделать что-то более часто выпадаемым, добавить что-то новое - предлагайте конкретику. 

Из того что предложено сейчас:
MRAP, LSV, - у вас и так их полная база.
беспилотники типа дартера - 8 штук и так есть
стомпера - 1шт на алтисе, 2шт на таноа более чем достаточно
MQ-12 Falcon - вот его логично подвинуть повыше в списке или прописать 2 раза чтобы чаще выпадал.

**Comment by ToxaBes** [comment]
ИЗ мрапов можно разе что добавить ифрит с пулеметом/гранатометом. ТОлько желательно перекрасить его в черный например, чтобы синие могли свой ифрит отличить (заодно перекрасить всю наградную которая в камуфляже противника).

**Comment by Noart537** [comment]
Для Горгоны\Камыша можно сделать альтернативное вооружение. Можно им добавить возможность менять вооружение (как это сделано с буззардом и хелкатом). Камыш немного похож на ЗУ "Вулкан", а горгона на зенитную машинку из батлы (тот-же вулкан, только на колесах).
1. Наземное: (стандартное вооружение) Пушка(бб,оф), пулемет, 2 птура 
2. Зенитное: для пушки что-нибудь скорострельное и фугасное (например от самолета пушку) и 2 ракеты земля-воздух. 
Тем самым мы можем гибко менять назначение любой техники, для нужд пехоты. 
Шанс, что она будет стоять не нужной на базе уменьшится.

**Comment by Horizon1959** [comment]
@ToxaBes ещё раз повторюсь: из-за мусора в наградной у меня нет полного списка техники и видим мы только ненужное фуфло. Можно хоть 125 мм пушку засунуть на Камыш, но он действительно будет не нужен по причине смены целей на точках (мы теперь не выкашиваем всех, а выполняем конкретные задачи, а это заставляет маневрировать и не лезть на рожон). Опыт модного Марида с нурсами показал, что никто с ботами не будет лезть в бой на таких машинах. 

По ощущениям не хватает авиации типа самолётов-штурмовиков, бонусных ударных беспилотников, возможно ифритов с оружием и праулеров с пулемётами (на Алтисе). Нам всё время выпадают БМП/БТР и танки. 

Полемика про зелёные vs синие заходит в тупик, нужно будет её обсуждать после запила обнуления лута при респавне и обкатки этой правки. Пока что синие баттхёртят из-за того, что все зелёные медики и могут быстро перестраиваться из задачи в задачу. Дополнительно на это влияет снаряжение противника типа вайперов (с теплаками на морде лица).

**Comment by ToxaBes** [comment]
Список текущей наградной на Алтисе: https://github.com/ToxaBes/ADR-Spec-Ops/blob/master/co30_ADR_Spec_Ops.Altis/functions/fn_SMhintSUCCESS.sqf#L5-L27

Все что кажется тебе интересным находится в конце списка и потому выпадает редко.

**Comment by ToxaBes** [comment]
@Noart - перевооружение наземной техники это интересно но пока бесполезно, т.к. синие уезжая на технике в зону БД обратно уже не возвращаются )

**Comment by ToxaBes** [comment]
>Пока что синие баттхёртят из-за того, что все зелёные медики и могут быстро перестраиваться из задачи в задачу.

У синих тоже есть медики, они могут одеть броникии и тд. Почему ты упорно игнорируешь следующие факты:
1) синих больше и они имеют лучшее вооружение и тяжелую броню с самого начаа
2) синие могут перезаходить на другие слоты подстраиваясь под задачу
3) обычно база партизан находится минимум в 2 раза дальше от зоны БД чем база синих и единственное средство доставки - либо перенос базы раз в 15-20 мин с рандомным шансом оказаться ближе, или машина/лодка. В то время как у синих есть вертолеты для транспортировки.

Как вообще влияет что партизан  является медиком если партизан например один против 5-10 синих? Сам себя он не реснет, максимум - подлечит до 100%, но расплата за это - тягать с собой большую аптечку. Я скоро видео выложу как в одиночку можно вынести радиовышку быстрее синих с первого раза (одной жизни).

**Comment by ToxaBes** [comment]
Вот мы скоро будем обнулять шмотки партизан при возрождении. Я уверен что недовольство синих  никуда не денется. И что дальше? Оставлять партизанам только пистолеты с одной обоймой? Может не в этом проблема?

**Comment by 12st** [comment]
При грамотном использовании слот партизана даёт большую эффективность, по сравнению с любым слотом синих, так как имеет возможность сменить специальность прямо в бою. В этом их главное преимущество.

**Comment by ToxaBes** [comment]
Что нивелируется количеством синих и их техникой.

**Comment by ToxaBes** [comment]
Почему все сравнивают слот на слот партизан vs слот синих? При том что игра обычно идет слот партизан vs 5-10 слотов синих.

**Comment by Horizon1959** [comment]
@ToxaBes ты делал статистику. Есть стата по онлайну за последние 4 месяца?

**Comment by ToxaBes** [comment]
http://mon.tehgam.com/?s=1  выбери за 1 мес.

**Comment by ToxaBes** [comment]
онлайн есть вечером, 8-10 чел макс, из них макс 1-2 - партизаны.

**Comment by 12st** [comment]
Обычно с этим одним слотом воюет не больше 5 слотов, а часто и вовсе один человек. Все остальные просто выкашивают ботов и им немножко пофиг на одного партизана они пришли ботов  помесить, а не в ПвП играть. Да, часто бывает так, что тот один кричит, что-то вроде "тревога, партизаны!" и остальные помогают тому одному его прикончить и сразу же возвращаются обратно к своим делам, но именно выслеживает всего один. Партизаны в свою очередь постоянно охотятся за синими, даже если их приоритет подрыв вышки например. Отсюда и сравнение слотов как один на один.

**Comment by ToxaBes** [comment]
Я уже писал что если синие не хотят заниматься контрпартизанскими действиями - то это их проблемы, а не партизан. И дело тут не в мифическом перевесе партизан, а в нежелании синих. 
Если синие не хотят воевать - они могут предложить мир, партизаны практически всегда соглашаются. Но лично я давно таких предложений не слышал. Наоборот, когда я предлагаю мир - мне говорят, нет воюем. Вы там определитесь сначала, хотите воевать или нет - решите совместно.

**Comment by 12st** [comment]
Что даёт синим убийство партизан? Это не приоритетная цель, никакой награды за это нет. Синие получают лишь уверенность в том. что в ближайшее время никто не захватит вместо них приоритетную цель, вот и всё. Довольно таки слабая мотивация. Партизаны по идее вообще никак не мешают большей части народу, ну убьют их на лишний 1-2 раза не беда, доедем попробуем ещё, вот и воюют в итоге 1-2 человека. У зелёных в свою очередь весь смысл выкосить синих, для получения хорошего снаряжения.

**Comment by Horizon1959** [comment]
@ToxaBes статут посмотрю позже, пока работы много. Давайте в этом треде закончим полемику и продолжим беседу о технике. Говорить будем после запила фичи про обнуление снаряги партизан.

Список техники посмотрю позже, распишу что да как подробно по каждой единице.

**Comment by ToxaBes** [comment]
Последний раз накину на вентиллятор немного:

Контрпартизанские действия это не обязательно охота на партизан или поиск с беспилотников. Часто достаточно смотреть по сторонам и в тыл периодически, а не только вперед. Сколько раз я брал купол тупо идя за синими и не стреляя в них (обычно последних синих кладут у входа во внутренний купол, не важно сколько у них медиков). 
В последнее время синие догадались минировать вход в купол - это контрпартизанские действия которые реально работают. Затем они стали минировать второй вход в купол - тоже усложнило жизнь партизанам (особенно когда ты один). Затем они стали ставить стомпер около аванпоста/минировать вход в аванпост - тоже отличное решение. 
Я просто хочу показать что контрпартизанские действия могут быть простыми и не отнимать кучу времени.

>Что даёт синим убийство партизан?

Что дает синим убийство ботов на основе? никакой награды за это нет. Тоже самое дает - удовлетворение.

>У зелёных в свою очередь весь смысл выкосить синих, для получения хорошего снаряжения.

Нафиг надо, еще пристрелят и опять с базы ехать. Достаточно пройтись там где прошли синие. Иногда ради фана устраиваю "охоту", но в большинстве случаев не вступаю в бой, достаточно знать где они и куда идут. Ты не представляешь как близко бывает партизаны отираются рядом с синими когда они входят гуськом на основу....

>Давайте в этом треде закончим полемику

оке.

**Comment by Horizon1959** [comment]
@ToxaBes ты не забывай, синие как русские - долго разгоняются, но потом сносят всё и не могут остановиться. Чтобы никому потом не было неприятно, лучше мутить превентивные решения, которые помогут настроить правильный ассиметричный баланс. До зелёных всем вместе получилось отстроить тщательный баланс, где все зависели друг от друга и в одиночку было невероятно сложно и долго что-то сделать. Я не зря предлагаю корректировки, т.к. потом это поможет избежать экстренных решений по нерфу кого-либо.

**Comment by ToxaBes** [comment]
Изменения в наградной не заставят синих смотреть по сторонам.

**Comment by ToxaBes** [comment]
Результат напишу позже отдельным тикетом.
