### ISSUE TITLE
Отменить сохранение награбленного у партизан при респавне

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#186]
Нужно отменить сохранение награбленного снаряжения зелёных при респавне на базе/аванпосте. Исключением должна быть ситуация, когда на сервере только один зелёный.

Попутно предлагаю одевать их во что-то стандартное (с самым примитивом), чтобы недопустить ситуации. когда зелёный спавнится прямо перед врагом и даже не может отстреляться, пока не затарится в арсенале.

**Comment by ToxaBes** [comment]
>зелёный спавнится прямо перед врагом и даже не может отстреляться, пока не затарится в арсенале.

Нет, оставим такой вариант - мне понравилось. Партизан в любом случае может успеть нажать эвакуацию базы и реснутся в новом месте.

Также можно сделать партизанский схрон - маленькая палатка которую может ставить партизан в любом месте. Одновременно не может быть больше 4х схронов. Установленный схрон невозможно собрать и перенести, только уничтожить (действием в меню). В эту палатку можно сгружать награбленное которое не нужно прямо сейчас, но у нее ограниченная вместимость. Схроны отмечаются на карте у партизан.

**Comment by Horizon1959** [comment]
@Toxabes ок, мусье знает толк в извращениях. Схроны - хорошая штука.

**Comment by IteronUA** [comment]
После введения удаления шмоток после смерти, партизанам будет необходимо сосредоточиться на добычи оружия и припасов, для этого предлагаю добавить скрипт который позволяет игрокам переносить ящики с припасами, а так же загружать их в машины (видел такой скрип у Тарги на сервере, никаких модов для этого не нужно). Алгоритм действия такой: партизаны приезжают на точку с пустым ящиком попутно набивая его припасами с убитых ботов или КП, грузят ящик в машину и пытаются довезти нажитое добро в целости на базу/схрон.
Раз уж заговорили об удалении шмота, предлагаю убрать возможность  брать патроны к  оружию из арсенала партизан (кроме патронов к мк20, ТРГ, АКСУ), пусть пользуются ограниченным боезапасом который успели вывезти с точки.

**Comment by 12st** [comment]
@IteronUA Арма работает так, что если у тебя есть доступ к арсеналу и магазины к какому либо оружию(не важно есть такие боеприпасы в арсенале или нет), то тебе будет доступно бесконечное количество этих магазинов. Скорее всего убрать это не получится.

**Comment by IteronUA** [comment]
Тогда можно убрать сам арсенал и поставить обычный ящик с большим запасом патронов 5.56

**Comment by ToxaBes** [comment]
>предлагаю добавить скрипт который позволяет игрокам переносить ящики с припасами, а так же загружать их в машины

Зачем грузить все в ящик, а потом ящик в машину если можно сразу грузить в машину и везти на базу/схрон?

>предлагаю убрать возможность брать патроны к оружию из арсенала партизан

Я бы с радостью, но это косяк в логике работы арсенала. Он добавляет все что есть у игрока в сам арсенал иначе то чего нет в арсенале - удалится. Если убирать арсенал то придется слишком много вещей прописывать/отслеживать чтобы были в ящике (аптечки/gps/терминал бпла/одежда/жилетки/шапки/очки/итд). Пока оставляем арсенал - считаем что у партизан есть кустарное производтсво БК и обвеса к оружию. Ничего другого надюпать не получится.

**Comment by IteronUA** [comment]
> Зачем грузить все в ящик, а потом ящик в машину если можно сразу грузить в машину и везти на базу/схрон?

Потому что так будет удобней, представь если по пути на машину нападут или она сломается, ты никак не сможешь быстро выгрузить припасы и спрятать их или перегрузить в другую машину, за то время пока ты будешь пытаться её разгрузить и тебя и припасы уничтожат.

**Comment by Horizon1959** [comment]
@IteronUA дело говорит. Ящики для мародёров дико круты.

**Comment by ToxaBes** [comment]
Возможно есть смысл сделать схрон в виде ящика, ане палатки, т.е. можно вызвать пустой ящик, загрузить в машину, налутать ящик, привезти его куда-нить и оставить на земле. Не боольше 4х ящиков одновременно. Но тогда схроны будут мобильными - их можно будет перевозить в другие места, а это облегчение жизни партизан.

**Comment by Horizon1959** [comment]
@ToxaBes @IteronUA 
![2](https://cloud.githubusercontent.com/assets/17685328/19857996/d9847b68-9f90-11e6-840e-9fbf696e8ab1.jpg)

**Comment by malashin** [comment]
Судя по всему можно будет Арсенал поправить. Он вызывается через функцию, можно свою написать.

Не тестировал, но уже видно, что можно убрать автоматическое добавление патронов к оружию при его выборе (выбрал титан, в рюкзак упали ракеты). Так же в него загружаются все обоймы на игроке, кроме тех, что уже в оружии. Можно сравнивать их со списком и разрешать только нужные нам.

**Comment by Horizon1959** [comment]
@malashin , 
![default](https://cloud.githubusercontent.com/assets/17685328/19860396/983956ac-9f99-11e6-8efd-c1e8ff5a2625.jpg)

**Comment by ToxaBes** [comment]
@malashin - ага, можно скопировать всю функцию, дать ей другое имя и изменять в ней что хочешь. А потом поседеть пытаясь поддерживать свой вариант арсенала, т.к. бисы его периодически перетряхивают.

**Comment by ToxaBes** [comment]
Был предложен лучший вариант - оставлять налутанное при возрождении но убрать виртуальный арсенал у партизан. Т.е. наклепать боеприпасов не получится. + Ящики/схроны которые появляются с вызванной машиной.

**Comment by IteronUA** [comment]
По поводу скрипта по переносу ящиков, скорее всего это делается через команду: attachTo. К примеру: box attachTo [player, [0, 1, 1] ]; 
При срабатывании скрипта считаю нужно так же ограничить скорость передвижения с бега на боевой шаг.

**Comment by ToxaBes** [comment]
Спасибо, да через эту команду. Я как раз заканчиваю написание и тестирую. Сегодня постараюсь применить.

**Comment by ToxaBes** [comment]
* У партизан убран арсенал, налутанное остается при возрождении.
* В вызываемой технике партизан появились ящик. Его можно выгружать/загружать в машину, а также перетаскивать. Одна техника - один ящик.
* Ящик не бездонный - стандартный из под гранатометов синдиката. Засунуть большую кучу добра в один ящик не получится.
* Ящик можно оставлять под кустом - скрипт очистки его не трогает
* Ящик уничтожается очередью из любого оружия партизан
* На карте ящик никак не отмечается, сделать точную метку на карте - забота партизан
* Если у игрока нет доплнения Apex - ему не выпадет калаш у партизан (на всякий случай, а то арма любит удалять такое оружие из рук периодически)
* В ящике партизан на базе только набор для подводного плавания и несколько аптечек

**Comment by ToxaBes** [comment]
ящики не работают как надо в MP.

**Comment by ToxaBes** [comment]
Пофиксил, но выгрузка ящика с вызванной лодки похожа на игру в русскую рулетку автоматическим пистолетом. Будьте аккуратны.
