### ISSUE TITLE
Отключить режим тепловизора для авиации синих

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#187]
Ибо жирно.

**Comment by Horizon1959** [comment]
Чо, нервы сдают?

**Comment by 12st** [comment]
Сколько человек на сервере его используют? Ещё раз повторюсь, без джойстика с теплака целиться невозможно.

**Comment by Horizon1959** [comment]
Я говорил, что надо сделать комфортно всем. Если запретить теплаки на авиации, то синие найдут другой метод.

**Comment by ToxaBes** [comment]
Причем тут нервы? Если вы не поняли то мы с зедом тупо садились в машину и выезжали раз за разом чтобы пока 12st отвлекался на наше уничтожение вторая группа (Noart и Keiz) постарались выполить спецоперацию или провалить ее (помешать синим выполнить ее) - что они с успехом и сделали. 
Судя по вою в чате нервы сдали у синих после набега партизан на их базу.

Теперь о тепловидении - мы не можем влиять на радар тк арма не позволяет, поэтому обнаружение машин останется как есть (убирать радар с авиации вообще - не вариант). Но взамен мы обрежем теплак который даст хоть какой-то шанс партизанам разбежаться из подбитой машины. Авиация не должна работать так точно по одиночным пехотинцам.

Да и еще, все кто считают что партизаны сильнее синих предлагаю зайти за слот партизан и попробовать, только мне сообщите - я зайду синих. Самолет и беспилотники использовать не буду.

**Comment by ToxaBes** [comment]
@12st - проверь пожалуйста.
