### ISSUE TITLE
Усилить охрану базы синих

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#188]
Часть охраны тупит и ее в целом недостаточно чтобы перекрыть все подходы. Нужно удвоить (примерно) охрану и заменить тех которые тупят.

**Comment by Noart537** [comment]
Попробуй объединить всю охрану в одну группу. Возможно с командиром они будут поживее реагировать. 
Состояние группе 
```_group setBehaviour "COMBAT"; ```
В init пехоте (чтобы не двигались с места.
```this disableai "move";```

**Comment by ToxaBes** [comment]
Они все в одной группе.

**Comment by ToxaBes** [comment]
На Таноа охраны достаточно - при мне выкосили наступающее отделение противника с основы расположенной рядом. Когда пытался проехать - по мне даже грейхоки из ангара ракетами стрелять начали. Проблема осталась на Алтисе.

**Comment by ToxaBes** [comment]
Теперь на Алтисе 20 стационаров охраны, на Таноа - 15. Глючные стационары исправил. Дополнительные стационары прикрывают наиболее часто используемые партизанами вектора атаки (в том числе и в портах). Также добавил на Алтисе партизанские лодки разбросанные по побережью (как на Таноа) и заменил у синих пару надувных лодок на RHIB.
