### ISSUE TITLE
Добавить ночное видение авиации синих

### ISSUE THREAD

**Issue by Vilein** [ToxaBes/ADR-Spec-Ops#189]
> Но взамен мы обрежем теплак который даст хоть какой-то шанс партизанам разбежаться из подбитой машины

Шанс, а не гарантию сделать это в тёмное время суток.

**Comment by ToxaBes** [comment]
Ночное видение у пилотов есть - шлем пилота либо надетый ПНВ.

**Comment by 12st** [comment]
В многофункциональной камере остался только обычный режим, ПНВ там не работает в не зависимости от того есть он у пилота или нет.

**Comment by ToxaBes** [comment]
Я наверное не совсем понимаю что такое многофункциональная камера и как ее включить. У самолетов я отключил только термовидение, ночное не трогал. Также попробовал со шлемом пилота и с пнв отдельно в самолете включать ночной режим - работает.

**Comment by Vilein** [comment]
1 вид из кабины
![20161107150225_1](https://cloud.githubusercontent.com/assets/23302923/20057249/a13abb26-a4fb-11e6-84a6-745da505de32.jpg)

2 камера теплак
(машина и пех рядом)
![20161107150235_1](https://cloud.githubusercontent.com/assets/23302923/20057253/aaaba3d2-a4fb-11e6-9dff-2aec034e544e.jpg)

3 камера без теплака
(свет фар)
![20161107150228_1](https://cloud.githubusercontent.com/assets/23302923/20057259/b17c08fa-a4fb-11e6-84ea-be24016193ba.jpg)

как Двенадцатый уже написал, у вспомогательной камеры ночного видения нет, то есть увидеть пехоту с высоты 600 - 1000 метров ночью мне представляется слабо возможным.
ПНВ на оптике пилоту необходим.

**Comment by ToxaBes** [comment]
Я тестил только "1 вид из кабины" из поста @Vilein . Ночной режим пилоту однозначно нужен иначе партизаны разбегутся по карте как тараканы. Подскажите как переключиться на эту многофункциональную камеру - буду разбираться.

**Comment by Vilein** [comment]
настройки, общие, многофункциональная камера, по умаолчанию ctrl+пкм

**Comment by ToxaBes** [comment]
Понял, спасибо. Сегодня вечером посмотрю.

**Comment by ToxaBes** [comment]
Арма не дает возможности без модов добавлять vision modes в targeting pod (кусок дартера присобаченый к самолету, через камеру которого вы и смотрите), только убирать. Поэтому сделал так: с 8 вечера до 4 утра терморежим разрешен у воздушной техники там где он есть по-умолчанию. Днем терморежим не работает. Беспилотники отдельный класс - у них терморежим на постоянной основе (пока не трогал - там посмотрим).
Это позволит ночью использовать терморежим вместо режима ночного видения. Т.к. ночь у нас длится 1 час реального времени то партизаны потерпят.
