### ISSUE TITLE
Добавить появление имен при наведении

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#19]
При "наведении" оружия на игрока в пределах ~20-40м можно выводить его ник.

**Comment by Noart537** [comment]
На малой дальности 10-20м. Думаю будет позелно знать, что за чудо стоит перед тобой. :) Чтобы не смотреть на карту.

---
(На усмотрение) Сделай по времени опрос в игре. И проси игроков ставить + или - в чат. В логах потом найдешь результаты. Так ты будешь знать, что думают игроки о тех вопросах, которые тебя интересуют.

**Comment by ToxaBes** [comment]
Как вариант, 10м - видно четко, 20м - полупрозрачная индикация.
По голосованию - сначала надо узнать как его делать в чате в автоматическом режиме ) 
Я пока просто в самой игре спрашиваю у тех кто играет отзывы/предложения/замечания для того чтобы иметь хоть какую-то обратную связь.

**Comment by Horizon1959** [comment]
Дичайше полезная возможность, т.к. в реальном мире видны морды и комплекция людей, а тут у нас набор одинаковых клонов-штурмовиков с немного различающимися мордами. Процесс игры не облегчает, но с такой возможностью убирается рутинный геморрой в виде открывания карты. В пределах 20 метров вполне хватает.
В дополнение круто было бы видеть классы игроков с ником (в виде пиктограмм).

**Comment by ToxaBes** [comment]
Ники игроков добавлю. Про пиктограммы подумаю, не уверен что есть нормальный вывод графики (с выводом текста все ок).

**Comment by malashin** [comment]
Сейчас имена после 1.58 есть свои в Арме и не надо ничего делать? Я этот момент не тестировал.

Иконки классов можно добавить если мы свое решение будем делать, а не встроенное использовать.

**Comment by Horizon1959** [comment]
@malashin т.е. в стоковой арме теперь имена светятся над головами?

**Comment by malashin** [comment]
В конфигах сервера появились новые настройки
```sqf
friendlyTags = 1;  // Friendly name tags (0 = never, 1 = limited distance, 2 = always)
enemyTags = 0;     // Enemy name tags    (0 = never, 1 = limited distance, 2 = always)

//Parameters that affect the Limited distance choice for Group Indicators, Friendly Name Tags, Enemy Name Tags and Detected Mines.
//They determine on which distance the indicators are fully visible and how many more meters it takes until the indicator fades-out completely.
fadeDistanceStart = 40.0;
fadeDistanceSpan = 10.0;
```
Нужно проверить устраивает ли нас их реализация.

**Comment by ToxaBes** [comment]
friendlyTags = 1; <- работает

не работает:
fadeDistanceStart = 40.0;
fadeDistanceSpan = 10.0;
