### ISSUE TITLE
Отключить режим тепловизора у TWS и Nightstalker, и добавить их в арсенал.

### ISSUE THREAD

**Issue by Vilein** [ToxaBes/ADR-Spec-Ops#190]
Надоедает постоянно менять прицел для дальних дистанций из за смены времени суток. Иметь универсальный прицел для дня и ночи гораздо удобнее.

**Comment by ToxaBes** [comment]
* оба прицела имеют большую кратность увелиения что делает их доступными только для снайперов
* Nightstalker прицел имеет **неотключаемый** радар который подсвечивает противника если хоть1 пиксел его виден на экране. То есть ты противника не заметил а прицел показал черточки. Также если противника вообще не видно и он находится за кустами/деревьями - это не преграда для прицела. Я каогда-то даже видио запиливал какой он читерский.
* У TWS насколько я помню неотключаемый терморежим т.к. он основной у него.

Поэтому эти прицелы были удалены.
