### ISSUE TITLE
Изменения в авиации синих

### ISSUE THREAD

**Issue by Vilein** [ToxaBes/ADR-Spec-Ops#191]
пару дней назад на сервере произошёл инцидент приведший к нерфу тепловизора у авиации.
немного математики.

   игра шла примерно с 18:00 до 00:00, и того 6 часов.

   за время игры синими было потеряно в силу погодных условий и грамотных действий партизан примерно 6 вайпаутов и 1 бузард, и того 7 ударных самолётов.

   при нынешнем времени респа самолёта порядка 40 минут, силы синих находились без авиаподдержки более четырёх с половиной часов.

   учитывая что пилот тоже человек Двенадцатый отходил передохнуть приблизительно на час.

   итого авиация синих вела эффективные контрпартизанские действия за всё время игры менее получаса.

   за это время было выявлено что авиация с тепловизором способна вести избыточно точный огонь по одиночным пехотным целям.

выводы из инцидента были сделаны верные, но не совсем полные.
сейчас, после отключения тепловизора в светлое время суток, на базе у синих всё ещё нехватает вайпаута с мнгновенным респом после уничтожения.

**Comment by 12st** [comment]
4 вайпаута, 3 бузарда, 3 хелкета.

**Comment by ToxaBes** [comment]
>пару дней назад на сервере произошёл инцидент приведший к нерфу тепловизора у авиации.

Это тянется уже больше 2х месяцев. Проблема в том что радар видит все в определенном радиусе - например стоящий пустой квадрик он отмечает серым квадратом на радаре, а железную бочку или металлический забор - нет. Соответственно для хорошего пилота нет проблемы нагибать все вокруг, как партизан так и ботов на основе. Магический радар это дисбаланс, но и сделать с ним толком ничего нельзя. Отключение теплака в дневное время - обходной путь который хоть как-то поможет балансу. До нерфа теплака партизаны в среднем уходили от 12го 1 раз из 40-50 попыток. Я хочу найти такой баланс чтобы партизаны уходили от 12го 1 раз из 10-15 попыток. Ессно это прикидки на случай когда партизаны еще не успели налутать ПВО-титан.

>за время игры синими было потеряно в силу погодных условий и грамотных действий партизан примерно 6 вайпаутов и 1 бузард, и того 7 ударных самолётов.

Только потому что против очень опытного пилота (12st) был очень опытный партизан (zed) который не занимался ничем другим как охотой на него. Это пограничный случай - дуэль.
Если бы не zed - синие потеряли бы только 1 самолет (и то по ошибке пилота была насколько я помню).

Далее, никаких мгновенных респов. У ботов вражеская поддержка тоже не респится мгновенно после уничтожения.  Или хотите кайман каждые 60 сек после уничтожения предыдущего на основе? У нас упор на пехотные бои и авиация является вспомогательным средством.

Вообще я могу сказать так, самолеты у синих есть только потому что у ботов тоже появляется вражеский самолет. Т.е. это контрмера против воздуха противника которую опытный пилот может использовать против всего.

**Comment by Vilein** [comment]
> Если бы не zed - синие потеряли бы только 1 самолет

страшно представить сколько бы самолётов потеряли синие, если бы не Двенадцатый.
> Вообще я могу сказать так, самолеты у синих есть только потому что у ботов тоже появляется вражеский самолет. Т.е. это контрмера против воздуха противника которую опытный пилот может использовать против всего.

да да, а техника у синих есть только потому что у ботов тоже появляется техника, которую грамотный экипаж тоже может использовать против всего.
>  У нас упор на пехотные бои

ок.
вопрос снят.

**Comment by ToxaBes** [comment]
>а техника у синих есть только потому что у ботов тоже появляется техника, которую грамотный экипаж тоже может использовать против всего.

не смотря на сарказм отвечу на полном серьезе - ты прав. Бронетехника у синих есть только потому что она есть у ботов. Даже несмотря на то что большинство запрыгивает в mrap/lsv/транспортный верт и мчит в зону БД у синих должна быть возможность использовать сопоставимые контрмеры при  желании/необходимости.
