### ISSUE TITLE
Слоты пилотов

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#196]
У нас 4 слота пилота больше чем реально необходимо. Я в принципе с этим согласен - можно оставить 2 слота. В связи с этим возникает вопрос: на какой класс поменять высвободившиеся 2 слота? У кого какие идеи/предложения? Кого не хватает по классам у синих (с кратким обоснованием пожалуйста)?

**Comment by 12st** [comment]
Инженеры, не обязательно те которые будут с возможностью БПА использовать. Часто были ситуации когда использовали сразу несколько единиц техники, но 1 инженер использовал БПА и оставался только один на 2-3 машины.

**Comment by ToxaBes** [comment]
Механик? Тогда получится немного урезанный класс. Надо будет добавить ему какое-то умение в специализацию. Либо забрать у инженера возможность починки (только разминирование/беспилотники например).

**Comment by ToxaBes** [comment]
Как вариант можно попробовать сделать механиков которые не могут использовать БПЛА но могут управлять Hummingbird при любом количестве народа на сервере. Только вот не слишком ли круто будет.

**Comment by ToxaBes** [comment]
Пришел в вопросу: а действительно ли +2 инженера будут нужнее чем + 2 пилота?

**Comment by Noart537** [comment]
Убери их и все. будет не 30 игроков а 28.

**Comment by ToxaBes** [comment]
Убирать их тем более не нужно. Пусть тогда остается как есть. В будущем если понадобятся слоты на что-то - будем иметь их ввиду.
