### ISSUE TITLE
Мосты

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#198]
Нужно добавить 1 мост на Алтис и 3 на Таноа чтобы исключить постоянное перемещение партизан через базу синих.

**Comment by Noart537** [comment]
Мосты ставишь в 3d редакторе, потом координаты в скрипт копируешь?

**Comment by ToxaBes** [comment]
В консоли отладки пишу скрипт и добавляю строчки в массив с координатами. Т.к. позиция задается относительно уровня моря а не земли то z координата у всех секций кроме съездов одинакова. Направление у всех секций одно, т.е. после первых пары секций видно смещение по _x и _y. Дальше просто копипаста строк с координатами и изменения их на delta_x и delat_y. Вся внешнаяя обвязка секций (фонари, отбойники) имеет относительные координаты, т.е. просто выбираются все секции в цикле по ним присоединяются элементы.
