### ISSUE TITLE
Список необходимых скриншотов для описания миссии

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#199]
Т.к. от скриншотов с моего ноута можно заработать катаракту прошу помочь с оформлением сайта. Нужны скриншоты в хорошем качестве. Список в постах ниже. Заранее спасибо.

**Comment by Noart537** [comment]
Может будет удобней создать в гугл диске папку, с доступом по ссылке. И в ней создать дерево папок, в которые нужно залить скрины. 

А тут список с описанием скринов и кодовым названием файла. 
например: 
_Основное задание - AO_01.jpg (AO_01_1.jpg, AO_01_2.jpg - несколько вариантов)
Дополнительное задание - SM_01.jpg 
..._

**Comment by ToxaBes** [comment]
Достаточного двух архивов (Алтис и Таноа) в котором скриншоты разбиты по папкам с номерами из списка, например 5/Протоип или 6/Заложники. Просьба в скриншотах не выкладывать метки поставленные вручную в том числе и шифт-клик. Все скриншоты будут изменены до 800px по ширине. Т.е. если что попадет по краям лишнего - ничего страшного.
Вот список того что нужно:

1. Разное: меню скрипта прорисовки, лобби сервера со слотами синих и зеленых, шлем пилотов с функцией отображения цели (HMD Laser Target)
2. Основное задание - вид на карте, КП - вышка, КП - бункер (снаружи и изнутри + терминал данных/ящики), Радиовышка с минами и без, Аванпост снаружи и внутри до взятия и после, разрушенный аванпост, патрули, вражеский вертолет в воздухе, техника.
3. Оборона: вид на карте, десант
4. Приоритетнце цели: вид на карте и внешний вид (здесь и далее сверху/сбоку как зевсом) Артиллерия, Зенитная батарея, Узел связи
5. Допки: вид на карте, внешний вид - Радар, Прототип, Склад, Шпионаж, Пусковые Установки, Лагерь, Тайник. Важные объекты геймплея если есть (ноутбук в будке и тд)
6. Спецоперации: вид на карте, внешний вид и важные объекты геймплея (терминалы данных, машина с ядерным зарядом и тд) - Прерванный Полет, Заложники, Конвой, Угон, Рыба-меч, Желтый Туман, Гроздья Гнева
7. База синих: места арсеналов, вид на карте, внешний вид, главные секции - респ, ангары, взлетка, перевооружение самолетов, вертолетные площадки, лодки, охрана базы, ПВО базы
8. База партизан: вид на карте, внешний вид, вызов техники, ящики партизан, лодки на карте
9. Сервис техники: вид на карте и внешний вид
10. Фракции: группа синих в форме синих, красные в форме красных, партизаны в своей базовой форме и партизаны через часик другой игры (форма красных с надетым броником синих), гражданские - просто водитель в джипе в гражданской одежде.
11. Классы синих и зеленых которые есть на сервере - внешний вид.
12. Дополнительные мосты - вид на карте и внешний вид.

Спасибо за помощь!

**Comment by Noart537** [comment]
Антон, давай вечером спецоперации и допки позагружаем разные. Пофоткаю. Долго выцеплять все.

**Comment by ToxaBes** [comment]
Ок, только у нас вечера сильно разнятся.

**Comment by 12st** [comment]
Я тоже могу пофоткать, зовите если что.

**Comment by ToxaBes** [comment]
Ок, спасибо за предложение. Я через часик другой появлюсь в ТС и позову тебя и Noart'a

**Comment by ToxaBes** [comment]
Всем спасибо. Скриншотов достаточно для оформления сайта.
