### ISSUE TITLE
Агресивное кеширование объектов

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#20]
Агресивное кеширование - отключение AI у ботов если в радиусе X метров нет игроков. При этом AI у лидера группы не отключается что позволяет сохранить перемещение по маршруту (если он есть). Это сильно экономит ресурсы сервера и повышает fps.

Но есть 2 минуса:
1. Переход из неактивного состояния в активное может занять 1-2 сек
2. Пилоты, ПТ-шники и Снайпера не смогут не убить ботов/технику если будут находится дальше X м от них т.к. при отключении AI отключается в том числе и уязвимость.

Стоит ли это включать и на какое расстояние?

**Comment by Noart537** [comment]
Что если удалять пехоту на расстоянии 3 км?  А технике отключать аггресивность. 
_Доп условие (на усмотрение): Если на точке никого нет в течение 5-10 мин._

Боевая авиация в основном работет только по технике. А если вертолет, то с 3-х км ему не поработать пушкой.

**Comment by ToxaBes** [comment]
При кешировании пехота не удаляется, она просто перестает реагировать на окружение. Удалять полностью не вариант, т.к. потом надо ее создавать по событию и эта нагрузка перекроет все преимущества. 
Пока я пришел к следующему: у нас вражеской техники не так много (<10 шт) и ее можно вообще не кешировать, пусть катается. Этим мы снимем вопрос по самолетам/вертолетам, ПТ-шникам и стационаркам.
Главная нагрузка это пехота (~100 ботов на основе и до 150 на обороне). Если кешировать всех ботов кроме командиров групп то все группы продолжат действовать (идти по точкам маршрута например) но при этом будет работать 1 AI на группу.
Главный вопрос - какая эффективная дальность работы по пехоте?
Самые дальние у нас снайпера и ПТ-шники с AP ракетами. Обычно дальше 1.5км они не стреляют. Можно взять это за основу, т.е. _отключаем AI всех ботов кто не в технике и не командир группы и не ПВО-шник если в радиусе 1.5км нет ни одного игрока_.
Какие могут возникнуть проблемы в игровом процессе?

**Comment by malashin** [comment]
Расстояние нужно ставить минимум 3 км, чтобы авиация видела нормально действующих ботов.
Боты без АИ, просто, стоят на месте? То есть лидер группы ушел по своим делам, а остальные стоят далеко от него?

**Comment by ToxaBes** [comment]
Нет, вся группа идет как шла, просто боты не реагируют на внешние события и воздействия. Соответственно не обращают внимание ни на что и не убиваемы.

**Comment by AlexVDem** [comment]
Я отстеливаю ботов с 2.5 км. из линкса легко. Из миномета тоже. 3 км. это уже предел. Вообще, для ПТ и снайперов можно ничего и не отключать.

**Comment by 12st** [comment]
У линкса максимальная пристрелка 2200, дальше ни о какой простоте стрельбы речи не идёт(если конечно не тратить в каждого бота по 5 и более выстрелов), миномёт дальше 2,5 км имеет слишком большой разброс, стрельба становится не эффективной. Только зенитка, авиация и арта могут работать на дистанции свыше 3 км, при этом не теряя свою боеспособность и без перерасхода бк.

**Comment by AlexVDem** [comment]
Соглашусь, только не "максимальная пристрелка" нет такого термина в стрельбе. Просто пристрелка, с прицелом LRPS - 300 метров. На 2.5 стрелять можно, кучность правда на такой дистанции уже не та, разброс конечно большой, но с 2-3 выстрелов в стоящего бота попасть довольно большая вероятность.
С минометом та же картина, БК тратиться больше, безусловно, но иногда оно того стоит. 
Можно попробовать (если это скриптово возможно) включать AI ботов на максимум если у них есть потери или был взрыв или выстрел в пределах 3-5 км.

**Comment by 12st** [comment]
Суть в том, что не стоит жертвовать производительностью ради 1-2 снайперов, эффективность которых сводится к нулю, команде такие снайпера не помогают, а лишь отстреливают ботов ради статистики.

**Comment by AlexVDem** [comment]
Это да, а также ПТ-шников (титан тоже на 2.5 км. стреляет) или стрелков из стационарных орудий.

**Comment by 12st** [comment]
Стационарные орудия дальше 2000 м, стреляют с слишком большим навесом, пуля летит слишком долго эффективность в ноль. ПТ редко стреляют дальше 3, но мы говорим про пехоту, у техники AI не отрубает.

**Comment by ToxaBes** [comment]
Речь идет только о пехоте. Также я заметил еще один момент - если игрок (в пехоте) ставит прорисовку 6-8 км то это создает доп. нагрузку на сервер даже если у игрока мощное железо. 
Возникли вопросы:
Какова эффективная дальность ПВО-шника/боевых пилотов? 
С какого расстояния работают пилоты противника?

Появилась идея органичить настройки прорисовки для пехоты в 2.5-3 км (но что делать с пво шниками?)
Для техники в 4-5км (?)
Для авиации в ?

Это должно добавить фпс всем игрокам, причем чем больше будет народу на сервере тем больше будет выигрыш в фпс.

**Comment by AlexVDem** [comment]
Поскольку серверу без разницы, игрок в самолете, танке или пешком, а на 5 км. видимость всетаки иногда нужна, можно ограничить всем видимость в 5 км. если нужно серверу повысить производительность.

**Comment by 12st** [comment]
Самая дальняя арта и РСЗО, с них можно стрелять и на 7000, была бы высота с которой видно цель. Танки до 5000. Авиация: боевые вертолёты по пехоте не более 3500, по технике не более 6500. Самолёты: по пехоте не более 3000, по технике не более 6000. Зенитка по штурмовику до 12000.

**Comment by ToxaBes** [comment]
Тогда такой вариант:
пехота - 3 км
техника - 5 км
авиация - 6 км

остался вопрос по ПВО-шникам, хватит ли им 3 км?

**Comment by ToxaBes** [comment]
В данном случае узкое место не сам сервер а сетевая подсистема армы.

**Comment by 12st** [comment]
ПВО около 5000, с перерасходом стреляют часто. Но зенитные снаряды пехоты по идее не более 3500.

**Comment by Noart537** [comment]
Антон глянь, может можно поиграться с сетевыми настройками. Может как-то поможет в разгрузке трафика https://community.bistudio.com/wiki/basic.cfg

**Comment by ToxaBes** [comment]
Ок, тогда пробуем схему прорисовки 3-5-6. Пехотных ботов кешируем если в радиусе 2х км нет игроков.
@Noart537  - спасибо, это уже сделано.

**Comment by Noart537** [comment]
Поидее если у тебя прорисовка 12000 то и работать ты можешь на 12000 (это с вооружением которое лочит цели)

**Comment by 12st** [comment]
Ракеты ПТ и ПВО взрываются на 6500-7000 м. В случае с зениткой там просто идёт спам ракет с базы, и штурмовики идут атаковать её и погибают на дистанции примерно в 6000.

**Comment by ToxaBes** [comment]
>По идее если у тебя прорисовка 12000 то и работать ты можешь на 12000 (это с вооружением которое лочит цели)

и при 10 игроках у всех остальных может быть просадка на 8-10фпс. Вне зависимости от мощности сервера. Исключение только если у сервера и у игроков гигабитные линки. 
Суть в следующем - арма видит что одному из клиентов нужно больше инфы по большему количеству объектов и выделяет его поток в приоритет . В итоге это косвенно влияет на всех игроков с меньшей прорисовкой и получаем ситуацию когда у большинства идет просадка и они еще больше уменьшают дальность прорисовки чтобы "вписаться" в ограничения своего потока, а тот у кого 10км всем рассказывает что "у меня 10км и ничего не тормозит, покупайте нормальное железо )". В данном случае проблема не в железе сервера или игроков а в корявости сетевой подсистемы армы (она управляет потоками исходя из заданного размера канала в basic.cfg).

**Comment by AlexVDem** [comment]
> и при 10 игроках у всех остальных может быть просадка на 8-10фпс.

Если делать ограничение на прорисовку, до думаю будет разумно делать её дифференцированной.
Т.е. при числе игроков до 5 (к примеру) максимальная прорисовка может быть до 10 км., при числе игроков от 5 до 10 она принудительно выставляется до 7 км, при числе игроков больше 10 она принудительно выставляется до 5 км.
Значения могут быть не обязательно такие, но принцип надеюсь понятен.

**Comment by ToxaBes** [comment]
Не имеет смысла.  Во первых,  на 10км видимость просто не нужна в игре,  это лишняя нагрузка.  Во-вторых,  резкий выход части игроков может спровоцировать лаг по типу применения погоды связанный с резким изменением видимости у всех.

**Comment by AlexVDem** [comment]
Выход игроков автоматом не увеличивает прорисовку, т.к. вход доп.игроков просто автоматом её снижает. Большую прорисовку иногда  использую когда в самолете или вертушке, или на высоте и надо обстановку оценить.

**Comment by ToxaBes** [comment]
опечатка в предложении -  я имел ввиду что при заходе игроков будет принудительно меняться прорисовка с 10км на 3км что даст лаг. разделения прорисовки по количеству игроков не будет -  этот вопрос закрыт.

**Comment by ToxaBes** [comment]
Кеш применен, на локальном сервере дает +2..5 FPS. Тестируем что даст на выделенном.

**Comment by ToxaBes** [comment]
Тесты прошли успешно:
На сервере: до +10-20fps (стабильно)
На клиенте: до +15fps (со временем падает из-за утечек памяти на клиенте - помогает перезаход в игру)

Чем слабее клиентская машина и тем больше дополнительных фпс дает кеширование.

**Comment by malashin** [comment]
В миссии задания даются по очереди. То есть в любом случае кто-то будет делать задание и все боты будут включены. Стоит ли экспериментировать с большим количеством ботов разбросанных по острову или давать одновременные задачи?

**Comment by ToxaBes** [comment]
Кеширование включается если в 2км нет ни одного игрока. Когда начинаем брать основу, то ввязываемся в бой на подход к зоне и кешированными остается примерно 20-30% (я замерял вчера несколько раз на основе и на допках). По мере уничтожения противников и продвижения вперед все новые боты размораживаются и вступают в бой (также боты размораживаются если их командир замечает противника, командиров отделений не морозим).
Т.к. у нас единицы стреляют на 1600+ по пехоте (даже не каждый снайпер/ПТ-шник) то я думаю уменьшить расстояние с 2км до 1.6км. Это позволит держать до 40% ботов в заморозке при взятии основы без потери играбельности.
Кстати, разморозка 100 ботов происходит за ~5 сек. Интервал проверки необходимости разморозки/заморозки 15 сек.

В итоге мы получили:
* увеличение fps на базе и во время пути до зоны операции
* увеличение fps во время боя с группами дальше 2км от зоны (как с блуждающими отрядами ботов так и синие vs партизаны)
* увеличение fps при взятии зоны снаружи (без десанта в центр) - плавная разморозка ботов по мере продвижения внутрь
* большую часть времени серверный fps стал 40-50, был 20-30. Больше fps на сервере, меньше странных хедшетов, дерганья ботов, висения тушек ботов после смерти и прочих непоняток

**Comment by malashin** [comment]
Снижать до 1.6км не стоит. Техника работать может по пехоте из далека. Плюс учитывая, что проверка не такая уж и частая, на наземной и воздушной технике можно достаточно близко подъехать к противнику за это время.

**Comment by ToxaBes** [comment]
Ну вот я и стараюсь подобрать оптимальное расстояние. Может 1.8 км? Я не помню на сколько техника бьет по пехоте (пулеметы/фугасы).

**Comment by 12st** [comment]
@ToxaBes может и до 5 км, авто наводка же.

**Comment by ToxaBes** [comment]
В принципе, техника вполне может подъехать на 1.5км до цели и отработать. Это безопасное расстояние. 
У нас не стоит задача обеспечить максимальное расстояние для техники которая бьет по пехоте. Что с 5км, что с 1.5 км - все равно техника в безопасности (ПТ-шники вражеские не бъют на 1.5 км наскоько я помню).

**Comment by 12st** [comment]
@ToxaBes они примерно на 2 км стреляют(вражеские пт).

**Comment by AlexVDem** [comment]
А разморозка-заморозка ботов как происходит? Я почему спрашиваю: то-ли и в самом деле так, то-ли глюк и мне показалось, я когда с дартера смотрел на бой, то пока в зоне были игроки - то и ботов бегало больше, как только всех убили - то ботов вроде стало намного меньше. Часть просто исчезла?

**Comment by ToxaBes** [comment]
Надо будет замерить эффективную дальность вражеских ПТ-шников.

**Comment by ToxaBes** [comment]
>А разморозка-заморозка ботов как происходит?

Берется группа ботов, командир отделения остается бдить, остальных в заморозку (полностью отключается симуляция и объект убирается - ботов просто нет в зоне) т.е. ресурсы AI не задействованы, арма не обсчитывает коллизии/поражение с ними и тд. Как только появляется игрок в радиусе 2км или командир отделения замечает противника - все отделение размораживается. У нас отделения могут быть от 2х до 10 ботов.

>как только всех убили - то ботов вроде стало намного меньше

Если ты про то что убили всех игроков - то да. Если в радиусе 2км не осталось живых и боты не заметили твой дартер то остаются только командиры отделений и водители техники, остальные исчезают.
