### ISSUE TITLE
Изменения в наградной

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#200]
После сбора и анализа всех предложений от игроков пришел в следующему варианту:

1. Разделяем наградную технику по типу задания: наградная за основу, за допки/спецоперации, за endless game. 
2. У синих также появляется награда за основу. Условие - захват КП и уничтожение радиовышки синими. Если хоть один из пунктов сделают партизаны то синие будут без награды.
3. Нужно убрать маркеры наградной у синих и поставить там банкомат (как у пилотов для вызова конейнеров). В нем можно будет вызвать необходимую технику. Также уберем лимит на 10 мин перед использованием техники и сделаем вызов доступным только синей стороне. Партизаны больше не смогут прокрадываться и угонять наградную, одиноко стоящюю на бетонке.
4. В случае начала обороны на основе будем блокировать вызов наградной из банкомата (чтобы не вызвали всю наградную до окончания обороны). Если оборона провалена - список наградной у синих очищается (наказание за провал).
5. Списки наградной разделены по уровню: за основу будет даваться более простая награда, за допку/спецоперацию - более серьезная. За победу в endless game раунде будет даваться спецподразделение (1-2 взвода) ботов с возможностью командования ими. Боты будут умными, на уровне вайперов (с правильной формой и тд). Отряд будет полноценным, т.е. все нужные классы, в том числе ПТ и ПВО. Также боты-медики из этого отряда могут поднимать павших игроков.
6. Отдельной наградной за приоритетную цель не будет, т.к. то что она перестанет портить жизнь своим существованием уже награда.

Вот примерный список:

**Регулярная армия**

* Наградная за основное задание:

    * ["Qilin с пулеметом", "O_T_LSV_02_armed_F"],
    * ["Страйдер с пулеметом", "I_MRAP_03_hmg_F"],
    * ["Ифрит с пулеметом", "O_T_MRAP_02_hmg_ghex_F", false],
	* ["Беспилотник KH-3A Fenghuang", "O_T_UAV_04_CAS_F"],
    * ["Беспилотник MQ-12 Falcon", "B_T_UAV_03_F"],	
	* ["AH-99 «Блэкфут»", "B_Heli_Attack_01_F"],		
	* ["ПО-30 «Касатка»", "O_Heli_Light_02_F"],
	* ["AFV-4 «Горгона»", "I_APC_Wheeled_03_cannon_F"],
	* ["БТР-К «Камыш»", "O_APC_Tracked_02_cannon_F"],
	* ["ЗСУ-39 «Тигр»", "O_APC_Tracked_02_AA_F"],
	* ["IFV-6a «Гепард»", "B_APC_Tracked_01_AA_F"],			
	* ["FV-720 «Мора»", "I_APC_tracked_03_cannon_F"],
	* ["MSE-3 «Марид» с НУРС", "O_APC_Wheeled_02_rcws_F"],

* Наградня за допку/спецоперацию:

    * ["То-199 «Неофрон» (штурмовик)", "O_Plane_CAS_02_F"],
    * ["А-164 «Вайпаут» (штурмовик)", "B_Plane_CAS_01_F"],
    * ["Ми-48 «Кайман»", "O_Heli_Attack_02_black_F"],
    * ["Y-32 Xi'an", "O_T_VTOL_02_vehicle_F"],
    * ["T-100 «Варсук»", "O_MBT_02_cannon_F"],
    * ["MBT-52 «Кума»", "I_MBT_03_cannon_F"],
    * ["M5 РСЗО «Сэндсторм»", "B_MBT_01_mlrs_F"],
    * ["M2A1 «Сламмер»", "B_MBT_01_cannon_F"],	
    * ["M2A4 «Сламмер» UP", "B_MBT_01_TUSK_F"],
    * ["V-44 X Blackfish", "B_T_VTOL_01_armed_F"],
    * ["M4 «Скорчер»", "B_MBT_01_arty_F"],

* Наградня за endless game:
    * Спецподразделение "CTRG".

**Партизаны**

* Наградная за основное задание:

    * Оружие BLUFOR:
        ["Ящик со снаряжением BLUFOR", "Box_NATO_Equip_F", false],
        ["Ящик с основным оружием BLUFOR", "Box_NATO_Wps_F", false],         
        ["Ящик со специальным оружием BLUFOR", "Box_NATO_WpsSpecial_F", false],       
    * Припасы BLUFOR:
        ["Ящик поддержки BLUFOR", "Box_NATO_Support_F", false],
        ["Ящик с припасами BLUFOR", "B_supplyCrate_F", false],
        ["Ящик с боеприпасами BLUFOR", "Box_NATO_Ammo_F", false], 
    * Оружие OPFOR:
        ["Ящик со снаряжением OPFOR", "Box_CSAT_Equip_F", false],
        ["Ящик с основным оружием OPFOR", "Box_East_Wps_F", false],
        ["Ящик со специальным оружием OPFOR", "Box_East_WpsSpecial_F", false],         
    * Припасы OPFOR:                
        ["Ящик поддержки OPFOR", "Box_East_Support_F", false],
        ["Ящик с припасами OPFOR", "O_supplyCrate_F", false],       
        ["Ящик с боеприпасами OPFOR", "Box_East_Ammo_F", false],
    * Оружие партизан:
        ["Ящик со снаряжением партизан", "Box_AAF_Equip_F", false],        
        ["Ящик с основным оружием партизан", "Box_IND_Wps_F", false],
        ["Ящик со специальным оружием партизан", "Box_IND_WpsSpecial_F", false],  
    * Припасы партизан:   
        ["Ящик поддержки партизан", "Box_IND_Support_F", false],    
        ["Ящик с припасами партизан", "IG_supplyCrate_F", false],
        ["Ящик с боеприпасами партизан", "Box_IND_Ammo_F", false],
    * Снаряжение Синдиката:
        ["Ящик с оружием Синдиката", "Box_Syndicate_Wps_F", false],    
        ["Ящик с боеприпасами Синдиката", "Box_Syndicate_Ammo_F", false], 
    * ["Спортивный хэтчбек", "C_Hatchback_01_sport_F", false],
    * ["Вертолет M900", "C_Heli_Light_01_civil_F", false],   
    * ["Самолет Caesar BTT", "C_Plane_Civil_01_F", true], 
    * ["Дартер AR-2", "I_UAV_01_F", false],     

* Наградня за допку/спецоперацию:
    
    * Минно-взрывные средства  
        ["Ящик со взрывчаткой BLUFOR", "Box_NATO_AmmoOrd_F", false],
        ["Ящик со взрывчаткой OPFOR", "Box_East_AmmoOrd_F", false], 
        ["Ящик со взрывчаткой СВУ", "Box_IED_Exp_F", false],        
    * Пусковые установки
        ["Пусковые установки BLUFOR", "Box_NATO_WpsLaunch_F", false],  
        ["Пусковые установки OPFOR", "Box_East_WpsLaunch_F", false],
        ["Пусковые установки партизан", "Box_IND_WpsLaunch_F", false],
        ["Пусковые установки Синдиката", "Box_Syndicate_WpsLaunch_F", false], 
    * ["Qilin с пулеметом", "O_T_LSV_02_armed_F"],
    * ["Страйдер с пулеметом", "I_MRAP_03_hmg_F"],
    * ["Ифрит с пулеметом", "O_T_MRAP_02_hmg_ghex_F", false],
    * ["Беспилотник MQ-12 Falcon", "B_T_UAV_03_F", false],
    * ["Беспилотник KH-3A Fenghuang", "O_T_UAV_04_CAS_F", true],    
    * ["Стомпер с гранатометом", "I_UGV_01_rcws_F", false],
    * ["Вертолет Pawnee", "B_Heli_Light_01_armed_F", false],
    * ["Вертолет Хеллкет (вооруженный)", "I_Heli_light_03_F", false],
    * Техничка с ПВО средством
        "I_G_Offroad_01_F" + "I_static_AA_F"
    * Техничка с ПТ средством
        "I_G_Offroad_01_F" + "I_static_AT_F"
    * Техничка с гранатометом
        "I_G_Offroad_01_F" + "I_GMG_01_high_F"
    * Техничка с минометом
        "I_G_Offroad_01_F" + "I_G_Mortar_01_F"
    * Мобильный постановщик электронных помех
        "I_Truck_02_transport_F" + "Land_SatelliteAntenna_01_F"
    * Аванпост зеленых
        "I_Truck_02_covered_F" => 4x "Land_TentDome_F" + 1x "Campfire_burning_F" + 1x "Land_Communication_F"
    
* Наградня за endless game:
    * Спецподразделение "Viper".

**Comment by Noart537** [comment]
* MSE-3 «Марид» с НУРС - увеличить кол-во НУРСов в 2 раза. (на усмотрение).
https://github.com/ToxaBes/ADR-Spec-Ops/blob/master/co30_ADR_Spec_Ops.Altis/functions/fn_SMhintSUCCESS.sqf#L81
* Для разнообразия, танкам можно добавить по 4 ПТУР-а стрелку и второй комплект дымов командиру. _(Предлагаю рассмотреть возможность стрельбы дымами, водителями.)_
* M5 РСЗО «Сэндсторм - предлагаю временно убрать. **(пока не починят)** т.к. ракеты не эффективны, даже когда падают рядом с игроком в 5 метрах. Раньше они сносили целый квартал в кавале.

**Comment by Noart537** [comment]
Qilin, ифрит и страйдер (боевые), можно давать за захват аванпоста, с шансом 50% Прямо рядом спавнить. Для большинства игроков в награду обидно получать такую технику. (на усмотрение).

**Comment by ToxaBes** [comment]
>MSE-3 «Марид» с НУРС - увеличить кол-во НУРСов в 2 раза

Cделаю.

>Для разнообразия, танкам можно добавить по 4 ПТУР-а стрелку и второй комплект дымов командиру. 

ПТУРы в танк делают немного бесполезным его главный калибр - отклоняю пока. Второй комплект дымов добавлю сразу водителю.

>M5 РСЗО «Сэндсторм - предлагаю временно убрать. 

Уберу.

>Qilin, ифрит и страйдер (боевые), можно давать за захват аванпоста, с шансом 50% 

Награда за аванпост - возможность на нем ресаться и вызывать квадрики. Помимо этого вражеская авиация постоянно сжигает даже квадрики которые пытаются отъехать от аванпоста. 

>Для большинства игроков в награду обидно получать такую технику

Проблема в том что у синих не так много действительно стоящих наград потому что на базе дофига техники по-умолчанию и если мы что-то будем давать за основу то MRAP/LSV как раз и будут в списке наградной.

**Comment by ToxaBes** [comment]
Осталось сделать по награде партизан:
* Мобильный постановщик электронных помех
* Мобильный Аванпост
