### ISSUE TITLE
Исключить дартеры из листа целей Зенитной батареи

### ISSUE THREAD

**Issue by Noart537** [ToxaBes/ADR-Spec-Ops#201]
Нужно поменять поиск цели у **зенитной батареи**. А именно - исключить из листа целей дартеры. Зенитки работают по дартерам ракетами, но не попадают по ним. (ракета проходит под дартером (в 3-10 метрах). Теоретически можно повесить несколько дартеров вокруг зениток и уничтожить ЗСУ с воздуха, с дальней дистанции. (не проверял)

https://github.com/ToxaBes/ADR-Spec-Ops/blob/master/co30_ADR_Spec_Ops.Altis/mission/priority/missions/priorityAA.sqf#L177

**Comment by ToxaBes** [comment]
Спасибо, исправлю.

**Comment by Noart537** [comment]
Грейхоки (с ракетами и бомбами) тоже относятся к UAV. Может лучше конкретный объект "B_UAV_01_F" ?  или через typeOf

**Comment by ToxaBes** [comment]
Не стоит писать код ночью. Еще раз в этом убедился. Ты прав, сегодня исправлю.
