### ISSUE TITLE
Задать координаты спавна Артиллерии

### ISSUE THREAD

**Issue by Noart537** [ToxaBes/ADR-Spec-Ops#203]
Частые, самопроизвольные возгорания артиллерийских установок.
Наверно для Алтиса лучше оставить рандом, т.к. там больше местности для спавна. А на Таноа, уже в ручную задать места или области.

**Comment by ToxaBes** [comment]
Проблема не только в арте, проблема во всех приоритетных целях (и на Гроздьях Гнева), на Алтисе - реже, на Таноа - чаще. Возгорание происходит из-за того что техника спавнится всегда мордой на север а затем поворачивается на нужный угол. Спавн следующей техники рядом предыдущей может происходить так что часть объекта окажется в другом объекте  и произойдет взрыв до того как техника будет развернута и коллизия исчезнет.
Решил пока кучу точек не делать, вместо этого сделал технику бессмертной до окончания спавна всех объектов в миссии.
