### ISSUE TITLE
Спецоперация "Газ-Батюшка"

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#207]
... Передовой завод по производству СПГ перешел под контроль противника. Необходимо вернуть завод под нашу юрисдикцию избегая серьезных разрушений. Завод должен продолжать работу несмотря ни на что. Командование назначило пехотную спецоперацию ...

Для реализации задумки нужно как-то проверить что игрок без Apex видит объекты Apex на карте Алтис. Например можно просто зайти на сервер и поехать по мосту - если все ок и мост виден то тест пройден. Осталось найти такого игрока.

**Comment by 12st** [comment]
Как-то зевсом спавнил объекты с Apex, игроки без него их видели, так что проблем с этим возникнуть не должно.

**Comment by ToxaBes** [comment]
О! Спасибо за инфу, тогда все должно получиться.

**Comment by ToxaBes** [comment]
2 варианта штурма:
* отстрел издалека "неудобных" ботов с последующим десантом с воздуха
* стандартный штурм пехотой ножками по земле

**Comment by Noart537** [comment]
* тихий режим. С глушителями. На мертвых ботах сделать действие - спрятать тело. (действие на 5 сек) или таскать как раненого куда-нибудь в кусты)
Если стрелять без глушителя или находят тело - тревога. Подкрепление спавнится на машинах и вертолетах. Можно предусмотреть посадочную площадку, чтобы верт приземлялся и выгружал пехоту.

**Comment by ToxaBes** [comment]
Тихий режим это очень интересно.
Для часовых (тех кто стоит на мест и смотрит в разные стороны) я могу добавить [BIS_fnc_ambientAnimCombat](https://community.bistudio.com/wiki/BIS_fnc_ambientAnimCombat) и добавить отслеживание события [FiredNear](https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#FiredNear). Это событие срабатывает когда рядом стреляли и возвращает кто на каком расстоянии стрелял, из чего и главное с глушителем или без. Это событие срабатывает если стреляли не дальше 69 метров от бота.
Если стреляли без глушителя в радиусе 69 метров то можно прерывать анимацию часового через BIS_fnc_ambientAnim__terminate.

Патрули. Территория завода большая (будет реально большая) и патрули будут обходить внутренний периметр. На них мы можем поставить [setBehaviour](https://community.bistudio.com/wiki/setBehaviour) со значением "CARELESS", т.е. им по идее будет пофиг на стрельбу и через FiredNear менять это значение.

Главная проблема во всем этом: FiredNear работает не дальше 69 метров. Т.е. тихий ражим будет нормально работать только в этом радиусе. Если стрелять дальше, хоть подкалиберными без всяких глушителей, боты не будут поднимать тревогу т.к. у часовых зациклена анимация а патрулям поставлено беззаботное поведение. Если знаешь похожую миссию, скинь мне на изучение, возможно есть другой вариант сделать это.

**Comment by ToxaBes** [comment]
upd: вместо FiredNear можно попробовать использовать [Fired](https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#Fired) и отлавливать его на игроках на время миссии, а не на ботах. Если игрок выстрелил ближе 1.5 км без глушителя - все боты на спецоперации переходят в режим тревоги, все обработчики у игроков убираются и тихий режим провален, штурмуйте как есть. 
Останетcя проблема с тем как прервать анимацию если бот действительно видит игрока рядом.

**Comment by 12st** [comment]
Стреляем из пистолета без глушителя на расстоянии 1.5 км, боты поднимают тревогу из-за этого, не перебор?

**Comment by ToxaBes** [comment]
Это был пример. Можно определять тип оружия и каждому типу задавать свою дистанцию. Например, снайперки - 1.5 км, винтовки 600м, пистолеты- 150м, и тд. Проблема в том что арма не приспособлена под такое от слова вообще и без такой проверки получим все что стреляет дальше 69 метров без глушителя - не тревожит ботов.
В любом случае тут без подобных жестких ограничений не получится тихий режим. Наверное потому  и нет настоящих стелс миссий в воркшопе.

**Comment by ToxaBes** [comment]
Нашел вот такую инфу по среднему расстоянию на котором слышно выстрелы:
Стрельба из крупнокалиберных пулемётов	 - 3000м
Стрельба из автоматов	- 2000м
Одиночный выстрел из винтовки	- 1200м
По пистолетам не нашел но явно меньше.

Остается вопрос по гранатам, рпг.

**Comment by ToxaBes** [comment]
Переношу задачу в след. релиз т.к. не получается сделать тихий режим, а без него смысла особого и нет в этой спецоперации.

**Comment by ToxaBes** [comment]
Расковырял логику как информация о противнике передается между ботами. Нормальный стелс в арме сделать невозможно.
