### ISSUE TITLE
Вертолеты на спецоперации угон

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#213]
Нужно сделать все вертолеты со спецоперации Угон доступными для партизан.

**Comment by kovt** [comment]
А нельзя сделать так, что бы ради выполнения этой операции, можно было бы садиться за верт который нужно угнать любому игроку, а не только пилоту? А, после взлёта. по прошествии некоторого времени, например 5 минут(до базы долететь хватит), это функция выключалась если за штурвалом не пилот. А то когда на сервере нет пилота приходится перезаходить и ехать на точку за вертом. Ну это так, просто мысль. ))

**Comment by ToxaBes** [comment]
Очень толковая мысль. Синие тоже смогут садится на место пилота при условии что: на сервере нет пилотов синих. При первой посадке вертолета вне круга спецоперации не-пилот будет автоматом высаживаться с места пилота и не сможет его более занять. В этом случае не-пилот сможет полетать до первой перезараядки.
