### ISSUE TITLE
Количество патронов в модулях Тару

### ISSUE THREAD

**Issue by malashin** [ToxaBes/ADR-Spec-Ops#217]
> Tweaked: The CRV-6E Bobcat and Mi-290 Taru supply variants now also have a near infinite supply of ammunition, fuel and repair resources, just like the other supply vehicles in the game

Нужно поправить количество патронов в модулях Тару.

**Comment by ToxaBes** [comment]
Спасибо, буду фиксить.

**Comment by malashin** [comment]
> Added: A new "PlayerViewChanged" Event Handler

Вот еще полезный хэндлер, можно заменить луп в проверке вида от третьего лица. Пока на вики не появился.
