### ISSUE TITLE
Развитие баз

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#218]
В 9 версии будем пересматривать механизм наградной техники, на основе наградой будет развитие базы победившей стороны, а вся наградная уйдет на допки/спецоперации (+ поубираем ненужные награды). 
Элементы и варианты развития баз обсуждаемы. Есть определенные наброски но пока нет цельной картины. Ближе к 9й версии добавлю сюда что есть.

**Comment by ToxaBes** [comment]
**Общие изменения в наградах и игровой логике:**

1. За успешное выполнение основной задачи дается наградная техника
2. За успешное выполнение допки/спецоперации дается +1 пункт развития базы при условии перемирия сторон. 
При войне сторон игроку "выполнившему" задание (имеется ввиду непосредственное нажатие кнопки и тд) дается на выбор: 
+1 пункт развития своей базы либо -1 пункт развития базы противника (если уровень базы противника выше 0). 
Если за 60 сек выбор не сделан, то дается +1 пункт развития своей базы.
3. Все не вызванные награды у синих и зеленых - сохраняются при перезапусках сервера (для каждой карты свое сохранение).
4. Если одна из баз полностью развилась - появляется последнее задание (основное или дополнительное). Если сторона у которой полностью развита база
проиграет - у базы отберется 2 пункта развития. Если выиграет - основы и допки перестают появляться, а база противника (ящик у партизан и прапор-арсенал у синих) становится полностью уничтожаемой (пункт меню). При уничтожении базы миссия завершается. Все списки наградной/пункты развития базы обнуляются и миссия начинается заново.

**Общие изменения на базе синих:**

1. Возрождение доступной техники: раз в 10 мин прилетает blackfish и совершает посадку около базы. Если он сел то в течении 10 сек вся доступная по уровню базы техника появляется на своем месте. После чего blackfish улетает. Если он по какой-либо причине не приземлился у базы (был сбит например) то техника не возрождается.

2. При вызове наградной техники прилетает Huron с контейнером на подвесе (1-2мин лета после вызова) и сбрасывает контейнер около базы. Если контейнер доставлен (на земле и не уничтожен) - вместо контейнера тут же появляется вызванная наградная техника. Если контейнер был уничтожен - техника не появляется и награда "сгорает". Если вертолет был подбит но отцепил контейнер который благополучно приземлился - наградная техника появится на месте приземления.
- - -
**Уровни развития баз:**

Уровень 0:

* База синих - квадрики, килины + праулеры без оружия, хеминберд, бобкет, стомпер с пулеметом, вызова дартеров нет. Арсенал - основное оружие: только все виды MX + M320 для снайперов. Забора нет, вышек нет, охраны базы нет.
* База партизан - доступен вызов квадрика, пикапа или лодки, снаряжение на базе пустое (нет SDAR, гидрокостюма, ребризера и тд). Партизаны появляются с пистолетами (+небольшой шанс получить пистолет-пулемет и еще более небольшой шанс на обвес к нему)

Список следующих уровней без указания очередности представлен ниже:

**Регулярная армия:**

* База 1: забор и вышки со стационарами по умолчанию
* База 2: вызов охраны базы
* База 3: появление аванпоста на основе
* База 4: сервисы техники, самолетов, вертолетов, бпла на базе
- - -
* Арсенал 1: все оружие синих с учетом разделения по классам
* Арсенал 2: все оружие зеленых с учетом разделения по классам
* Арсенал 3: все оружие красных с учетом разделения по классам
* Арсенал 4: все оружие синдиката с учетом разделения по классам
- - -
* Машины 1: два страйдера без оружия, килин с праулером становится с пулеметом (+2 вооруженных охотника для Алтиса)
* Машины 2: хеммты: медицинский, перезарядка, топливозаправщик
* Машины 3: один из страйдеров получает пулемет, маршал
* Машины 4: пантера и +2 вооруженных охотника на Алтисе
- - -
* Вертолеты 1: Гостхок и Хурон
* Вертолеты 2: Тару грузовой, тару со скамейкой
* Вертолеты 3: Тару транспортный, хеллкет вооруженный
* Вертолеты 4: Касатка без оружия, VTOL Блэкфиш (автотранспорт)
- - -
* Самолеты 1: Буззард (АА)
* Самолеты 2: Буззард заменяется Неофроном (CAS)
* Самолеты 3: Неофрон заменяется Вайпаутом (CAS)
* Самолеты 4: Перезарядка авиации (самолеты), возможность выбирать между Буззардом, Неофроном и Вайпаутом в ангаре
- - -
* Командир 1: вызов снабжения если нет пилотов на сервере (раз в 40 мин)
* Командир 2: арта 2х видов + дымы (раз в 20 мин)
* Командир 3: поддержка с воздуха если нет пилотов на сервере (вооруженный blackfish в течении 3-5 мин нарезает круги на указанной точкой) (раз в 60 мин)
* Командир 4: десант с хурона (неуправляемые боты) на координаты, через 15 мин этот отряд отступает и исчезает (раз в 40 мин)
- - -
* Пилот 1: вызов контейнеров для подвески
* Пилот 2: перевооружение авиации
* Пилот 3: полевой ремонт
* Пилот 4: теплак на pod camera работает в любое время суток (сейчас он работает только ночью)
- - -
* Инженер 1: беспилотник MQ-12 Falcon
* Инженер 2: беспилотник MQ-4A Greyhawk (CAS)
* Инженер 3: беспилотник MQ-4A Greyhawk 
* Инженер 4: стомпер получет 2 ПТ и 4 ПВО выстрела Titan


**Партизаны:**

* База 1: снаряжение для подводных действий (гидрокостюмы, ребризеры, очки, SDAR)
* База 2: возможность вызова грузовичка, внедорожника (SUV), джипа и хэтчбека
* База 3: вызванные награды (ящики) в радиусе 50 м переезжают вместе с базой при эвакуации
* База 4: перенос базы в указанное место (из списка доступных мест)
- - -
* Арсенал 1: улучшенное вооружение при респе: пистолеты и пп заменяются на Mk-20, AKSU, TRG-21. 
* Арсенал 2: улучшенное вооружение при респе: пулеметчик - lim, пт-шник - PCML, снайпер - mk14, инженер - АКМ
* Арсенал 3: улучшенное вооружение при респе: пулеметчик - mk200, пт-шник - ПВО титан, снайпер - mk14 + MOS, инженер - рюкзак-дартер с пулеметом
* Арсенал 4: возможность одевать гилли всем классам партизан
- - -
* Командир 1: блокпост партизан по клику на карте (исчезает через 15 мин), раз в 30 мин, не может быть ближе 200 м до базы синих
* Командир 2: боевая собака. Ищет врага, набегает и загрызает (раз в 30 мин)
* Командир 3: очаг сопротивления - по клику на карте в любом месте появляются 20 партизан-ботов на время 15 мин (раз в 60 мин)
* Командир 4: минное поле в заданной точке на карте радиусом 50 м на 30 мин (раз в 60 мин)
- - -
* Патруль 1: пехота: 2 стрелка + 2 PCML (клик на карте, в радиусе 600 м появляются и идут на точку) (раз в 60 мин)
* Патруль 2: 2 стрелка + 2 PCML на внедорожнике (клик на карте, в радиусе 1000 м появляются и едут на точку) (раз в 60 мин)
* Патруль 3: 2 стрелка + 1 ПТ титан + 1 ПВО титан на внедорожнике (клик на карте, в радиусе 1000 м появляются и едут на точку) (раз в 60 мин)
* Патруль 4: партизанский блокпост - мешки с мусором на них боты партизан (клик на карте, через 20 мин исчезают) (раз в 60 мин)
- - -
* Общее 1: вызов грузовичка на указанную позицию каждому партизану (раз в 60 мин)
* Общее 2: на аэродромах можно вызвать самолет Caesar BTT (кроме аэродрома на базе синих) (раз в 60 мин)
* Общее 3: на аэродромах можно вызвать вертолет M900 (кроме аэродрома на базе синих) (раз в 60 мин)
* Общее 4: дебаф базы синих - если партизаны выполнят Гроздья Гнева (все 3 терминала) при войне с синими и если синих было минимум в 2 раза больше партизан, то база синих откатывается на уровень 0.
- - -
* ???
* ???
* ???
* ???
- - -
* ???
* ???
* ???
* ???
- - -
* ???
* ???
* ???
* ???

**Comment by 12st** [comment]
Арма не развалиться от всего этого?

**Comment by ToxaBes** [comment]
От этого - нет.

**Comment by 12st** [comment]
Кстати, а почему касатка выдаётся аж на 4 уровне? Это самый убогий вертолёт в игре, было бы логично поменять его с тару.

**Comment by ToxaBes** [comment]
Спасибо. Вот для таких замечаний я и накатал простыню текста. Поменял местами касатку с тару.

**Comment by 12st** [comment]
В арсенал 0 уровня стоит добавить все модификации SPAR, как никак оружие нато и явно не превосходит MX, а для Таноа вообще по стандарту идёт.

**Comment by 12st** [comment]
Также сервисы для самолётов, вертолётов и БПА появляются только на 4 уровне. Где их перезаряжать до этого? Подгонять машины очень не удобно, но и они появляются только на 2 уровне. Предлагаю альтернативу - на маленьких уровнях увеличить время перезарядки в 1.5-2 раза.

**Comment by ToxaBes** [comment]
>В арсенал 0 уровня стоит добавить все модификации SPAR, как никак оружие нато и явно не превосходит MX

На Алтисе будет MX, на Таноа - SPAR. Не дописал.

>Также сервисы для самолётов, вертолётов и БПА появляются только на 4 уровне. Где их перезаряжать до этого?

Можно просто с 4го перенести на второй.

**Comment by Noart537** [comment]
Посмотрите, может что приглянется, накидал, что в голову пришло.

База
- Летающий дартер-охранник, медленно летает по периметру базы, отстреливает противника.
- Патрули (по 2-4 бота) по периметру базы.
- Снайперская группа на башне диспетчеров или в другом высоком месте.
Инженер или командир.
- Доступно в арсенале снаряжение "Детектор мин". Если у игрока он есть, то - позволяет игроку быстрее захватывать терминалы, скачивание информации на допках и подобное. Все-равно не используется, тут пригодится.
Общее. (высокий уровень)
- Доступно в арсенале снаряжение "Тактические очки". Позволяющие видеть игроков в группе на небольшом расстоянии или лазерные метки, которые видит пилот вертолета в шлеме. Полезно для партизан, видеть что они помечены лазером. (на усмотрение игроков. 
Пилотам
- "Шлем пилота вертолета" показывает бойцов своей стороны, маленькими точками на ограниченном расстоянии (1км), чтобы исключить дружественный огонь. (Координаты, скрипту, можно запрашивать раз в 10-20 сек, чтобы уменьшить нагрузку на сервер).
- Не боевые вертолеты\самолеты имеют дополнительный набор ловушек.

**Comment by ToxaBes** [comment]
Взял только "летающий дартер-охранник с пулеметом патрулирующий базу. При вызове охраны появляется второй" для База 4. Спасибо.

Остальные не актуальны пока т.к. у синих все ок с вариантами улучшений. Проблема у партизан - нужно еще 12шт вариантов сгруппированных по 3 секции с 4 шт в каждой (смотри ??? в списке).

**Comment by ToxaBes** [comment]
Осталось 4 варианта для партизан

**Comment by ToxaBes** [comment]
Варианты заполнены, теперь нужно решить с очередностью.

**Comment by ToxaBes** [comment]
Время возрождения техники на базе синих:

* Квадрики, бобкет - 1 мин
* LSV (килин, праулер), хеммты, хемингберд, грузовой тару - 10 мин
* MRAP (охотник, страйдер), маршал, стомпер, хеллкет, касатка, пассажирский тару, гостхок - 20 мин
* Пантера, хурон, блэкфиш, грейхок - 30 мин
* Самолет - 40 мин

**Comment by Zedd1** [comment]
Дополнительная ветка:
Синие:Командир через банкомат вызывает до 6 ботов НАТО с выбором специализации (согласно уровню)
Боты:
        1. Стрелок; Медик; Сапер; Легкий пулеметчик; Инженер
        2. Тяжёлый пулеметчик;  Гренадёр; Стрелок ПТ; Меткий стрелок
        3. Ракетчик ПТ, Ракетчик ПВО; Снайпер
        4. CTRG 
Зелёные: Командир через ящик вызывает до 4 ботов ААF
Боты:
        1. Стрелок; Медик; Сапер; Легкий пулеметчик; Инженер
        2. Тяжёлый пулеметчик;  Гренадёр; Стрелок ПТ; Меткий стрелок
        3. Ракетчик ПТ, Ракетчик ПВО; Снайпер
        4. Viper
Уровни умений предлагаю ставить на макс.

**Comment by ToxaBes** [comment]
Спасибо, добавил.

**Comment by ToxaBes** [comment]
Будем менять уровень у партизан где боевая собака на что-то другое. В 50% случае собака набегает и успевает загрызть 1-2 противников, но в других 50% собака сваливает в закат и не реагирует на команды либо носится по округе с R ~ 150м.
