### ISSUE TITLE
Вид от 3-го лица иногда работает вне машины

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#22]
После фикса данного бага изредка продолжает работать вид от 3-го лица. Пока ищу закономерность.

**Comment by ToxaBes** [comment]
Перепроверил все - нет бага. Такой баг был с бпла но он пофикшен. Пока закрываю тикет.

**Comment by Horizon1959** [comment]
Да, подтверждаю, всё чотко.
