### ISSUE TITLE
Отображение имен противников

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#225]
При войне между регулярной армией и партизанами инженер регуляров довольно легко отлавливают партизан просто пролетая беспилотниками на над ними - при наведении отображается ник игрока. Это косяк стандартной реализации отображения имен при наведении от БИСов. Мало того что параметры затухания на расстоянии не работают (https://forums.bistudio.com/topic/191157-fadedistancestart-no-entry/) так эти альтернативно одаренные при включенном friendlyTags показывают ники всех живых игроков вне зависимости от стороны.
Придется отключать полностью и писать свой скрипт который будет показывать ники с учетом расстояния, стороны и взаимоотношений между фракциями.

**Comment by Horizon1959** [comment]
Ник светится, как только берёшь в лок. По ходу это недавно сделали, раньше просто писал название транспорта.

**Comment by ToxaBes** [comment]
>Если ты собрался изобретать свой велосипед

Я в принципе только этим и занимаюсь в арме.

>можешь сделать так, чтобы ники светились над головами рядом стоящих союзников? Метров 10-20, не больше.

Да. Только думал до 20м - четко видно, затем при удалении до ~40м плавно становится полностью прозрачным. Будет формат вида: Ник бойца (специализация)

Есть пожелания к цвету или размеру шрифта? Может есть смысл сделать надписи на регулярах синими а на партизанах - зелеными?

**Comment by Horizon1959** [comment]
@ToxaBes Мне кажется, что нужно смотреть на исполнение других решений, т.к сам я слабо представляю как это должно выглядеть в идеале. Но основной смысл в том, чтобы над головами висели читаемые на любом фоне ники с обозначением специальности (пиктограмма или тект) и они светились только на ближней дистанции.

**Comment by ToxaBes** [comment]
Готово. Пробовал над головами - получается слишком кукольно. Сделал на теле примерно там где стандартная армовская надпись выводилась. У синих ники подсвечены синем цветом, у зеленых - зеленым. При перемирии обе фракции видят надписи друг-друга. Видимость надписи примерно до 30м. Результат:
IceSemper (инженер)

Если игрок в технике, то данные выводят в формате: "Название техники: имя бойца (+кол-во остальных игроков в технике)". Логика выбора и отображения имени бойца в технике:
* водитель
* командир
* стрелок
* первый из списка пассажиров

Результат:
AMV-7 Marshall: ToxaBes (+4)
