### ISSUE TITLE
Больше боли партизанам

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#226]
По сценарию, партизаны это бывшие гражданские которые раздобыли оружие. Сейчас процесс добычи оружия не раскрыт, партизаны появляются сразу с легким автоматическим оружием.

* ~~Убираем у партизан SDARы из ящика, гидрокостюм, маску для ныряния и ребризер - оставляем.~~
* ~~при заходе на сервер партизаны появляются без оружия. Вообще.~~
* ~~если партизан больше одного и как минимум один из них - медик, то при возрождении на базу партизан теряет всю форму и оружия получая в замен базовую партизанскую экипировку~~
* ~~базовая партизанская экипировка включает в себя текущую гражданскую одежду партизан и рандомный выбор оружия из нового списка.~~
* ~~новый список оружия: все пистолеты и пистолеты-пулеметы~~
* ~~вероятность получения оружия из списка:
      - 70% пистолет с 40% шансом получения глушителя (если ставится на оружие) и с 40% пистолетного прицела (если ставится на оружие) + 4 доп магазина к нему
      - 30% пистолет-пулемет с 40% шансом получения глушителя (если ставится на оружие) + 3 доп магазина к нему~~

Получаем следующее - партизан появляется без оружия. Идет искать оружие и если погибает - возрождается на базе с оружием из списка (неопытные партизаны могут сразу нажать возрождение и пропустить процесс поиска оружия). Если партизан один на сервере - его оружие и снаряжение не исчезнет при возрождении на базу.

У многих возникнет вопрос - как вообще можно начинать без оружия? Отвечаю - у партизан есть как минимум 3 проверенных способа получить оружие в миссии не стреляя. А при наличии игроков регулярной армии на сервере процесс выслеживания и мародерства начинает играть новыми красками.

**Comment by Horizon1959** [comment]
@ToxaBes Всё прикольно, но я бы всё-таки оставил им ПП для начала, а потом если уж совсем весело пойдёт, то шаманить с пистолетами.

Как партизанам быть с SDAR во время подводных миссий?

**Comment by ToxaBes** [comment]
>всё-таки оставил им ПП для начала

Из 10 возрождений на базе ~3 будут с ПП. Если так нужно именно ПП - можно жать кнопку возрождение пока не выпадет. Ели серьезно то ПП это уже послабление т.к. с хорошей позиции достаточно до одного магазина чтобы снять противника.

>Как партизанам быть с SDAR во время подводных миссий?

Обе подводные миссии можно выполнить не ныряя. В дальнейшем SDAR будет добавлен партизанам в одном из первых перков по развитию базы.

**Comment by Horizon1959** [comment]
@ToxaBes тогда вопросов нет.

**Comment by ToxaBes** [comment]
Побегав без оружия понял что просто надоедает каждый раз сбивать патруль машиной и сразу получать катибу. Будут пистолеты и ПП по-умолчанию.

**Comment by Horizon1959** [comment]
@ToxaBes не понял, ПП и пистолеты зелёным или патрулям?

**Comment by ToxaBes** [comment]
>ПП и пистолеты зелёным или патрулям?

партизанам.

>получается если двое зелёный не медики, то их снаряжение сохраняется при респавном на базу?

да, т.к. в этом случае просто некому поднять павшего.

**Comment by Horizon1959** [comment]
@ToxaBes выходит, что в начале матча пара зелёный сможет достать всё необходимое зерг рашем?

**Comment by ToxaBes** [comment]
Нет, это значит что играя без медиков практически любое падение означает возвращение на базу и новую поездку до зоны операции. Партизаны сами решают - иметь медика который поднимет на месте, но терять все налутанное при возрождении на базу или играть без медиков для сохранения лута но каждый раз ездить с базы.
