### ISSUE TITLE
Нет охраны на базе НАТО на Таноа

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#227]
Уже не первый раз охраны нет на базе НАТО на Таноа и она не появляется даже по активации тревоги. Баг наблюдал лично за зелёных и синих ещё в прошлом году.

Есть идеи?

**Comment by ToxaBes** [comment]
После нескольких вызовов просто перестает работать. Ошибок в логах нет, отваливается что-то внутри армы на сервере. В это же время перестают удаляться боты с прошлых аванпостов, а также старые минные поля с радиовышек и барьеры с приоритетных целей. Я перепишу механизм появления охраны базы но не уверен что это полечит на 100%. Полностью лечит только перезапуск сервера.

**Comment by Horizon1959** [comment]
Улучшений не наблюдаю, охрана всё ещё не спавнится.

**Comment by ToxaBes** [comment]
Сегодня на Таноа буду тестить еще раз.

**Comment by Horizon1959** [comment]
@ToxaBes Я зайду  обоими фракциями вечером, прогоню туда-сюда.

**Comment by ToxaBes** [comment]
Пофискил координаты, завтра опять буду тестить.

**Comment by Horizon1959** [comment]
Охрана респавнится, кнопка активации охраны работает почти корректно. Иногда кулдаун кнопки охраны больше 10-ти минут.
