### ISSUE TITLE
Сервис вертолетов/самолетов

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#23]
Необходимо добавить сервис вертолетов/самолетов (только ремонт и заправка) на 3 пустующих аэродрома на острове.

**Comment by malashin** [comment]
На сколько я помню, этого не стали делать, чтобы летчики не перезарежались рядом с основой, а возвращались на базу.

Представь боевой вкртолет зависший рядом с основой, отстрелял БК , сел рядом на аэродром, продолжил стрелять.

Есть вариант, оставить только починку. Но и это достаточно странно в боевых услових где попало чиниться.

**Comment by Horizon1959** [comment]
Тоже не особо понимаю, это как VAS/VA раскидывать по карте.

**Comment by 12st** [comment]
На самом деле дополнительные 5-7 минут для хорошего экипажа особой проблемы не составляют, тем более садится рядом с основой всегда большой риск. В данный момент например такое иногда происходит с танками, бывают такие основы на которых сервис техники находится почти в тригере.

**Comment by ToxaBes** [comment]
Будет сервис в смысле ремонта/заправки, без перезарядки вооружений.

**Comment by AlexVDem** [comment]
Ващет я думаю, что как раз для вертушек такое не надо, пусть будет всего один сервис - только на базе. Единственное я бы отодвинул от него все машины и палатки, можно хвостом задеть при посадке.

**Comment by malashin** [comment]
Я тоже против сервисов авиатехники разбросанных по острову.

Единственное, что можно было бы оставить там, это топливо. Но лучше ну мудрить и не делать их вообще.

**Comment by ToxaBes** [comment]
Спасибо за мнения. Для игрового процесса это изменения принесет больше вреда чем пользы. Фича отклонена.
