### ISSUE TITLE
Быстрая смена навесных элементов текущего оружия

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#230]
Можно попробовать использовать хоткеи:

* Глушитель: <kbd>CTRL</kbd>+<kbd>S</kbd>
* Оптика: <kbd>CTRL</kbd>+<kbd>O</kbd>
* Сошки: <kbd>CTRL</kbd>+<kbd>B</kbd>
* ЛЦУ: <kbd>CTRL</kbd>+<kbd>L</kbd>

Действие выполнится только при наличии вызываемого/убираемого элемента и достаточного места в снаряжении. Если в снаряжении несколько подходящих элементов (например, оптические прицелы) то устанавливается первый найденный элемент.

**Comment by 12st** [comment]
Если делать, то только с возможностью переназначить клавиши т.к. стандартная раскладка может быть не всем удобна. 
P.S. CTRL + S уже используется в арме по умолчанию(смена позы бойца на более низкую)

**Comment by ToxaBes** [comment]
Проблема в том что я не нашел вариант добавления всем зашедшим пользователям кастомных комбинаций чтобы они были видны в настройках без модов. Только сам пользователь может добавить себе в настройках новые комбинации. Поэтому остановился на предустановленных вариантах, как это сделано в перепаковке магазинов (CTRL+R).
По CTRL+S нужно будет придумать другую комбинацию (либо во всех случаях заменить CTRL на ALT или SHIFT). Какие комбинации были бы более удобными?

**Comment by 12st** [comment]
Лично мне удобнее все комбинации через ALT.

**Comment by ToxaBes** [comment]
Ок, попробуем с ALT вместо CTRL и добавим второй вариант перепаковки магазинов по ALT+R.

**Comment by Grid-Sw** [comment]
Интересно, а в реальности также? снять установить прицел одной клавишей? Чтобы заменить прицел, нужна минута времени, также сошки и остальное навесное оборудование. Ставлю "+" в пользу реализма - открыть рюкзак - поискать в нем нужное устройство - прикрепить его на ствол. Ставлю "-" в пользу Аркадности.

**Comment by ToxaBes** [comment]
Лично для меня оба варианта равнозначны. Не вижу в этом какой-то сильной аркадности, скорее - удобство.

**Comment by ToxaBes** [comment]
Потестил локально - фигня получается: если больше одного прицела то они ставятся снимаются в произвольном порядке и получается что иногда ставится и снимается один и тот же прицел несколько раз подряд. Теряется смысл. Танцы с запоминанием последнего прицела дают свою странности когда игрок скидывает/подбирает прицелы + нужно отсеивать прицелы на ручное оружие. 
Фича отклонена.
