### ISSUE TITLE
Расширенное управление ботами

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#231]
Нужно попробовать что-нибудь вроде [Command & Control (C2)](http://www.armaholic.com/page.php?id=28040) и посмотреть есть ли в этом смысл для нашей миссии.

**Comment by ToxaBes** [comment]
Вариант выше реализован в виде мода. Интересует нечто похожее только в скриптовом варианте.

**Comment by Horizon1959** [comment]
Оно вообще надо? Я очень круто научился возится с ботами, но под мультиплеер сама концепция тонкой работы с ботинками не подходит, т.к. на руководство уходит много времени. Достаточно будет использовать стандартные методы типа посадки в технику, отправки на точку, смены построения.

**Comment by ToxaBes** [comment]
>т.к. на руководство уходит много времени

Именно для решения этой проблемы и есть расширенное управление. Простой пример -  возможность задания ботам маршрутных точек просто кликая на карте командирского планшета. Примерно так как это сейчас делается с беспилотниками.

**Comment by Horizon1959** [comment]
@ToxaBes в беспилотниках это реализовано плохо (в наземных), т.к. БПА начинает от этих точек тупить или вообще встаёт в ступоре. Т.е. с ботами будет больше возни.

**Comment by ToxaBes** [comment]
С ботами норм работает, тестил. Но опять же, это все в варианте обсуждения. Попробуй этот мод если есть время чтобы можно было разговаривать предметно.

**Comment by Horizon1959** [comment]
@ToxaBes Хорошо, погоняю.

**Comment by ToxaBes** [comment]
Похоже что расширенное управление просто не имеет смысла до тех пор пока поведение ботов не придет в норму. Сейчас их имеет смысл брать только в качестве экипажа (водитель/стрелок) в бронетехнику и вертолеты. Боты также перенесены из наградной в развитие баз. Тикет закрываю.
