### ISSUE TITLE
Отключить kill-чат при войне с партизанами

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#235]

**Comment by ToxaBes** [comment]
Отключил сообщения об убийстве. Позже добавлю сообщение о том что игрок без сознания не уточняя причину. Такие сообщения будут показываться только при перемирии.

**Comment by ToxaBes** [comment]
Нужно будет потестить.

**Comment by Horizon1959** [comment]
Работает исправно, но можно проверять статистику, где пишутся убитые игроки.
