### ISSUE TITLE
Добавить возможность уничтожения беспилотников для инженера

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#236]
Иногда, когда захожу на сервер, вижу несколько дартеров без топлива на земле (они не очищаются скриптом). Число поехавших дартеров тоже не меняется. Возможно ли замутить ручное уничтожение  дартеров/грейхоков инженерами?

**Comment by ToxaBes** [comment]
Подумаю как это можно сделать.

**Comment by Horizon1959** [comment]
@ToxaBes Сейчас вроде при заходе на беспилотник в контекстном меню есть строка про беруши. Может так можно уничтожать беспилотники? Неадекватов вроде нет, беспилотниками рулят единицы, так что не думаю, что стоит опасаться вандализма.

**Comment by ToxaBes** [comment]
Готово, нужно тестить.

**Comment by Horizon1959** [comment]
@ToxaBes оке, погляжу сегодня вечером.

**Comment by Horizon1959** [comment]
Инженеры говорят, что всё отлично работает. Большое спасибо!
