### ISSUE TITLE
Добавить спуск по тросам с вертолетов

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#239]

**Comment by Horizon1959** [comment]
@ToxaBes ты напишешь свой скрипт или будешь использовать васянские троссы-палки?

**Comment by ToxaBes** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=713709341

**Comment by Horizon1959** [comment]
Выглядит очень круто.

**Comment by Grid-Sw** [comment]
+1

**Comment by ToxaBes** [comment]
Попробуем добавить открытие дверей перед спуском как предложил @Grid-Sw.

**Comment by ToxaBes** [comment]
Почитал отзывы и потестил мод. В синглеплеере все шикарно, в мультиплеере периодически вылезают косяки. Пока отклоняю.
