### ISSUE TITLE
Вражеские БПА/БПЛА

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#24]
Добавить вражеские БПА/БПЛА на основном задании с небольшой (~30%) вероятностью.

**Comment by Horizon1959** [comment]
А бомбами AI умеет кидаться?

**Comment by ToxaBes** [comment]
Научим.

**Comment by Noart537** [comment]
Как считаете, можно ли замутить БПЛА вертолеты? Во второй арме такие были. Возможно и тут можно как-то заставить управлять ботами через Пульт управления БПЛА.

**Comment by Horizon1959** [comment]
@Noart537 ага, будем играть в военный симулятор в военном симуляторе.

**Comment by ToxaBes** [comment]
Не получится, т.к. сам вертолет должен иметь тип uav чтобы к нему моно было цеплять терминал управления, иначе бы можно было сделать так:
```sqf
_pos = position player;
_grp = createGroup WEST; 
_driver = _grp createUnit["B_UAV_AI", _pos, [], 0, "CAN_COLLIDE"];
_heli = createVehicle ["B_Heli_Transport_01_camo_F", _pos, [], 0, "FLY"];
_driver moveInDriver _heli;
player connectTerminalToUAV _driver;
player action ["SwitchToUAVDriver", getConnectedUAV player];
```

**Comment by ToxaBes** [comment]
Беспилотники не могут в атаку если на сервере выключены некоторые настройки (такие как автообнаружение противника). У нас отключены эти настройки потому вражеских БПЛА не будет.
