### ISSUE TITLE
Защита респа синих

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#242]
Нужно перенести в здание либо защитить высоким забором место респа синих для уменьшения бейзрейпа партизанами. Синие должны иметь возможность появится на базе и добежать до арсенала, возможно добежать до бобкета/маршала.

**Comment by ToxaBes** [comment]
Появилась еще одна идея как защитить синих если их расстреливают на респе в упор - первые 10 секунд или до первого выстрела синий игрок бессмертен. Это времени хватит чтобы уйти с линии огня. 
Т.е. если игрок после возрождение в первую секунду выстрелил, то  неуязвимость тут же снимается. Если не стрелял то первые 10 сек ему невозможно нанести урон.

**Comment by Horizon1959** [comment]
@ToxaBes Вот это уже действительно крутое предложение, я за. Этого времени хватит, чтобы убежать или расстрелять кого-то.

**Comment by ToxaBes** [comment]
База синих на Алтисе готова. Завтра будет на сервере. Нужно будет потестить на предмет мелких косяков в виде стыков в заборе, а также на защиту от партизан. Партизаны по-прежнему могут проникать на базу не не могут угнать технику без помощи синих, при включении обороны базы турели действуют более слажено. Пока что даже неуязвимость в первые 10 сек после спавна не нужна.
Базу синих для Таноа делает Grid. Жду его вариант, если не подойдет - будем свой делать.
