### ISSUE TITLE
Ограничение дальности видимости

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#244]
* Если оператор дальше чем 4км от дартера то управление им теряется. Для восстановления контроля необходимо попасть в 4км зону вокруг дартера.
* Возможно нужно уменьшать дальность видимости грейхоков. Сейчас стоит max 6км что якобы нужно для того чтобы уничтожать зенитку раньше чем она уничтожит беспилотник. Но этого не происходит, у нас зенитки на основе не лочат на такое расстояние. Как вариант можно снизить до 4-5 км.

**Comment by Horizon1959** [comment]
@ToxaBes Прорисовка БПА сейчас максимум 5 км. К зениткам действительно нужно подлетать издалека, т.к. они стреляют залпами ракет.

Не особо понимаю переделку дартеров, т.к. инженер в основном сидит на базе и дартеры спавнятся на наградной технике (грузить их в машину нельзя). К тому же беспилотники быстро сходят с ума и их приходится уничтожать и возить караванами с базы. Т.е. ты предлагаешь вызывать дартер, а потом сопровождать его вплоть до точки в 14-ти км?

**Comment by ToxaBes** [comment]
>К зениткам действительно нужно подлетать издалека, т.к. они стреляют залпами ракет.

 Взял грейхок и полетел на основу, дальше чем 2.5 км от центра ни одна зенитка по мне не работала. Проверил несколько раз. Да, у зенитке лок дальше чем на 2.5 км но боты не такие умные и не лочат на таком расстоянии.

>Не особо понимаю переделку дартеров, т.к. инженер в основном сидит на базе

Чтобы инженер не сидел тупо на базе, чтобы нельзя было мониторить сразу всю карту. Примерно также это сделано в warfare миссии.

>Т.е. ты предлагаешь вызывать дартер, а потом сопровождать его вплоть до точки в 14-ти км?

Запаковал в рюкзак, кинул в машину/верт. На месте развернул - полетел.

**Comment by 12st** [comment]
Зенитки работают до 4-5 км в случае если они обнаружили технику, ввиду того, что грейхок погибает от 1 прямого попадания ПВО ракеты любая ошибка будет приводить к потере БПА. Слишком жёсткое ограничение, надо оставлять как есть.

**Comment by ToxaBes** [comment]
Я не умея толком на них летать в 50% случаев пролетаю сквозь всю основу и грейхок остается в живых. Лечу на высоте ~1000м. В случае если грейхок летит в автоматическом режиме - его фиг собъешь тк бот мастерски владеет ловушками, да и количество ловушек достаточно велико.
Я не с пустого места это все взял, сначала я понаблюдал со стороны в качестве партизана, потом потестил сам - попробовла посбивать его с ПВО партизаном и полетал сам на нем за синих, в итоге посмотрел как это решено в других миссиях и решил сделать также.

**Comment by Horizon1959** [comment]
@ToxaBes ты тестил грейхок на обоих картах? Как только пускаешь ракету, то зенитки начинают тебя искать и делают это хорошо, в результате летит град ракет (на Таноа с этим легче). Бомбовоз эффективно попадает в цель при условии высоты в 500-700 метров, т.к. дальше начинается слишком большой разброс и в результате его полезность сводится к нулю.

Сейчас дартеры паковать нельзя (на прошлой неделе пробовал), они исчезают как запрещённый предмет. К тому же их можно взять ограниченное количество, а они из-за глюков быстро сходят с ума и выходят из строя. Может есть другой выход типа спавна квадрокоптеров возле инженера или выбор спавна на других площадках?

Концепцию инженера, который тусуется возле поля боя я знаю, в принципе это довольно хорошая реализация, но это не надо делать, пока на базе синих не появится нормальной обороны. Сейчас инженер сидит на базе только из-за обороны, т.к. боты за турелями почти не представляют угрозы для зелёных. А так выгонять инженера к полю боя надо, а то сидят себе на базе, а взрывать/разминировать/чинить некому.

**Comment by ToxaBes** [comment]
Тестил на Алтисе. Перед изменением протестирую еще раз на обеих картах. Тестил тот который с ракетами. Нужно будет второй проверить. Если все будет плохо - не буду применять.

По дартерам - можно обойтись без перепаковки, достаточно подьехать на 4км к базе чтобы подключится к дартеру и направить его куда нужно. Затем подъехать на 4км к месту где он должен быть и рулить им как хочешь. Инженер используя 8 дартеров и 2 грейхока мониторит практически всю карту что неправильно. У него есть теплаки на беспилотниках и автолок который веде цель даже после потери видимости (аналог магического радара в самолетах). Нужно нерфить немного инженера, пусть использует все что есть но для этого придется немного поездить - будет "окно" для партизан, также партизанам не будет смысла ехать на базу синих наказывать инженера просто потому что его там скорее всего не будет.

**Comment by Horizon1959** [comment]
@ToxaBes ты сможешь мониторить всю карту 8-ю дартерами, если они не будут сходить с ума. Как правило, едва хватает на точку и немного на базу. Их сбивают боты и игроки, они быстро начинают носится туда-сюда вокруг собственной оси и перестают слушаться команд. Наличие теплаков не такое уж и приемущество, ведь зелёные регулярно бегают в шлемах вайперов. Есть ещё финт в настройках цветов армы, который позволяет подсвечивать цели как в тепловизоре.

Этой мерой ты не зарегулируешь и не понерфишь инженера, а просто убьёшь его как класс. Инженер раньше был простым механиком/сапёром, а с нынешней злобой красных и атак в спину от зелёных он станет не нужен на боевой машине вообще. В качестве альтернативы предлагаю убрать грейхоки вообще и выдавать их за спецоперации, что позволит избавиться от читерского радара и сделает слот ракетчика снова нужным.

Про наказание инженера вообще не понял, у нас же война за задачи а не фраги. Какое инженеру дело до собственной смерти, если он дома?

**Comment by ToxaBes** [comment]
>а просто убьёшь его как класс

Я слышу это каждый раз когда что-либо меняю в классах ) 
Вы (инженеры)  - обленились. Все время сидите в одних и тех же местах. Инженер не только оператор БПЛА, он еще нужен для починки техники (в том числе и вражеской которую отжали на основе). А как он починит если он на базе? Сейчас инженер это такой паук который сидит на базе в бобкете. 

>Как правило, едва хватает на точку и немного на базу. 

Давай прикинем: 8 дартеров+2 грейхока = 10шт с макс дальностью видимости 5км и теплаком. Переключение между ними занимает пару секунд + еще несколько секунд на просмотр засветки на экране и вращение дартера/облет грейхока. 
Итого опытный инженер за несколько минут может просмотреть площадь 3.14*5км^2=78.5 км2 * 10 шт бпла => 785 км2 Это без учета высоты беспилотника над уровнем земли. Возьмем 1 км высоты для примера. это даст нам радиус видимости предметов на земле с беспилотника в 4.89км что даст для одного беспилотника 75 км2 обзора, соответственно для 10шт будет ***750 км2***.
Для высоты 2км площадь поурытия будет ~66 км2 и тд.

Для справки: площадь Алтиса ~270 км2. Таноа около 100 км2 (суша).

Я хочу уменьшить зону "покрытия" разведки синих или хотя бы чтобы были окна в виде "тут нас накрывают а если сделать крюк в 6км то возможно сможем проехать" а также заставить инженеров хоть как-то двигаться а не сидеть сиднем на базе. В идеале двигаться потихоньку за основным отделением, просматривая вокруг дартерами, помогая ударными БПЛА и чиня технику.

>В качестве альтернативы предлагаю убрать грейхоки вообще и выдавать их за спецоперации

Грейхоки синим нужны, будут как одно из улучшений базы.

>Про наказание инженера вообще не понял

Уже стандартная ситуация: инженер накидал партизанам с грейхока несколько раз подряд повесив дартером метку, им это надоело, они плюнули на задачу и пошли наказывать инженера. Найти его довольно легко сейчас - 90% что он на базе. В итоге партизаны забили на задание и набегают на базу синих, синие воют о бейзрейпе.

Про уменьшение дальности видимости: арма продолжает деградировать (если ты вдруг не заметил) сейчас практически на всех популярных серверах дальность видимости на все стоит не больше ~3-4км потому что дальше начинает часто лагать вплоть до отвала physX. И мы также будем потихоньку двигаться к этому, хотим мы или нет, вместе с уменьшением дальности ракет зениток и тд.

**Comment by 12st** [comment]
А можно показать мне видео, где инженер за пару минут полностью осматривает такую территорию? Одно дело когда он просто имеет возможность видеть на такую дистанцию и совершенно другое искать противника на такой большой площади.

**Comment by Horizon1959** [comment]
@ToxaBes 

> Вы (инженеры) - обленились. Все время сидите в одних и тех же местах. Инженер не только оператор БПЛА, он еще нужен для починки техники (в том числе и вражеской которую отжали на основе). А как он починит если он на базе?

Инженер не может совмещать роли мехвода/сапёра и оператора БПА, т.к. ему банально не хватает времени. В довесок перед переходом между ролями нужно менять прорисовку как в игре, так и в скрипте на сервере. Каждый беспилотник требует неустанного внимания, потому что:

- беспилотник может сойти с ума
- грейхоки нужно сажать, заправлять, поднимать в воздух руками
- дартеры приходится поднимать вручную, иначе они перестают слушаться команд и трясутся как эпилептики
- после активации беспилотника он ещё около 30-ти секунд не слушается команд и бот продолжает им рулить

Всё вот это просто приковывает инженера к терминалу и приходится выбирать между работой с беспилотниками и ролью мехвода/сапёра. Кстати, боевые машины сейчас не используют, т.к. с апексовыми обновлениями титаны стали прилетать от красных со всех сторон, а уж при наличии зелёных, стреляющих в спину, техника тяжелее MRAP потеряла всякий смысл. Т.е. мы дошли до такого абсурда, что пехотой действовать эффективнее, чем техникой.

> Сейчас инженер это такой паук который сидит на базе в бобкете.

Это он сидит на базе, т.к. рулит БПА (смотри выше) и двигаться ему никуда не надо. К тому же он нужен, чтобы включить оборону базы и в случае нападения авиации красных и зелёных (ты же сам регулярно упрекал синих. что они никого не оставляют на оборону базы).

> Давай прикинем: 8 дартеров+2 грейхока = 10шт с макс дальностью видимости 5км и теплаком. Переключение между ними занимает пару секунд + еще несколько секунд на просмотр засветки на экране и вращение дартера/облет грейхока.
Итого опытный инженер за несколько минут может просмотреть площадь 3.14*5км^2=78.5 км2 * 10 шт бпла => 785 км2 Это без учета высоты беспилотника над уровнем земли. Возьмем 1 км высоты для примера. это даст нам радиус видимости предметов на земле с беспилотника в 4.89км что даст для одного беспилотника 75 км2 обзора, соответственно для 10шт будет 750 км2.
Для высоты 2км площадь покрытия будет ~66 км2 и тд.

Давай возьмём в руки арму, а не калькулятор, т.к. в арме сам знаешь какая математика:

- Из-за особенностей прорисовки армы, на минимальном увеличении ты не увидишь засветов в паре-тройке км и в результате тебе придётся увеличивать камеру до максимума и быстро осмотреться ты не можешь. Чем дальше цель, тем больше приходится зумить камеру, а это снижает общий обзор. Т.е. чтобы посмотреть небольшой квадратный участок, тебе придётся поворачивать камеру и мучить увеличение-уменьшение и чем дальше он будет, тем больше придётся брать увеличение
- на сервере в большинстве случаев погода отвратительная, видимость очень плохая, что практически нейтрализует главное приемущество дартера
- дартер приходится держать на высоте 500 метров, иначе его сбивают боты и зелёные, из-за такой высоты, силуэты ломаются, и отличить своего от чужого достаточно проблематично
- дартер часто трясёт так, опознать что-либо меньше машины невозможно
- переключение между дартерами происходит отнюдь не в несколько секунд, т.к. игра часто подвисает, а управление может перейти от бота к инженеру через 30 секунд

> Грейхоки синим нужны, будут как одно из улучшений базы.

Тогда нужно делать их на более сильных этапах развития и чтобы у зелёных был достойный ответ. 

> В итоге партизаны забили на задание и набегают на базу синих, синие воют о бейзрейпе.

Это из-за твоего просчёта в концепции партизан и защиты базы синих. У партизан нет цели, вот они и занимаются собирательством и беспределом на базе синих из-за безнаказанности. Сделай счётчик побед и это будет мотивировать. 

Синие же не баттхёртят от набегов зелёных на базу синих, им абсолютно пофиг. Синие действительно недоумевают, как пара гражданских может вынести базу регулярной армии и спокойно кататься на их боевых машинах.

Вообще на счёт прорисовки ты прав 100%. Мне очень понравилось, что в end game есть динамика, дистанции обычной пехоты, беспилотники, боевые машины и всё это отлично работает с прорисовкой в 1600. Но у нас миссия завязана на прорисовку, при чём больше прорисовка, тем больше шансов доехать/долететь. Банальный пример - ты не видишь кайман/касатку/неофрон, а он видит тебя и посылает подарок твоей машине. Или зенитка может тебя засечь и выстрелить, а ты даже не будешь знать, что она там. Может перед перепилкой прорисовки подумать о деталях, а не тупо зажимать неудобные для зелёных классы?

**Comment by ToxaBes** [comment]
>А можно показать мне видео, где инженер за пару минут полностью осматривает такую территорию? 

Я думаю ты сам себе можешь снять такое видео, мой ноут не позволяет такую прорисовку.

>Инженер не может совмещать роли мехвода/сапёра и оператора БПА

Я вижу полное непонимание игроками назначения данного класса. Инженер это не человек сидящий на базе. Он не должен 100% времени быть подключенным к беспилотнику. Посмотри где находится оператор БПЛА в арме (группы в редакторе), он находится либо в составе подразделения либо идет двойкой с другим стрелком недалеко от подразделения. В обоих случая они также принимают участие в БД, а не сидят на базе. В том числе потому что инженер только и делает что рулит беспилотниками будут сделаны эти изменения. Пора потихоньку выходить с базы, размять ножки.

>Это из-за твоего просчёта в концепции партизан и защиты базы синих. У партизан нет цели, вот они и занимаются собирательством и беспределом на базе синих из-за безнаказанности. 

Не вижу просчета. У партизан всегда будет как минимум одна цель - набежать на базу синих потому что это "весело". Сейчас есть еще цели - угон техники и отстрел тушек синих с целью получения лута. Эти цели мы планомерно убираем. 

>Т.е. мы дошли до такого абсурда, что пехотой действовать эффективнее, чем техникой.

Это синие дошли до абсурда когда они разучились действовать в связке пехота+техника в том числе потому что удобнее сесть на базе за инженера и сносить грейхоками все.
Простой пример: пару дней назад у партизан и синих был мир, партизаны нашли танк на основе, перевренули/починили его и выполнили на не подряд 2 основы и 2 допки, потом просто стали влетать на задание от скуки и ессно сгорели. 
У синих вообще в последнее время периодические проблемы с тактикой и взаимодействием. Если есть командир, то он берет горстку людей и уходит в другой канал выстреливая сам себе в ногу. Только беспилотники и спасают...

>Синие же не баттхёртят от набегов зелёных на базу синих, им абсолютно пофиг. 

Ага, поэтому после набега синие мчатся за партизанами на полкарты на маршале или просто роняют беспилотник на голову чтобы сказать как мы им безразличны...

>ты не видишь кайман/касатку/неофрон, а он видит тебя и посылает подарок твоей машине. Или зенитка может тебя засечь и выстрелить, а ты даже не будешь знать, что она там.

С уменьшением прорисовки будет и уменьшение дальности ракет. Если я не смогу уменьшить дальность ракет без модов - уменьшения прорисовки не будет.

>Может перед перепилкой прорисовки подумать о деталях, а не тупо зажимать неудобные для зелёных классы?

Детали как раз продуманы, еще до меня, в других миссиях где этот баланс уже есть. Я просто смотрю где у нас перекосы, тестирую сам, смотрю как у других сделано и применяю под наши реалии. По поводу тупо зажимать неудобные классы - ты серьезно считаешь что оператор БПЛА прям таки неудобен? Партизаны недавно уделали синих на Гроздъях Гнева при том что им на голову сыпали бомбы и ракеты с беспилотников. Вот в записи партизаны выполняют Заложников при противодействии БПЛА и самолетов синих: https://www.youtube.com/watch?v=s7U1eEZCjC4
Мы уже научились жить с этим ) Гораздо страшнее для партизан столбы и маленькие сетчатые заборчики...


Еще раз, прочитайте внимательно. Инженер сидят на базе и руля беспилотниками - единственный класс который ничем не рискует, он не участвует в бою персонально даже периодически. Он может не брать стрелковое оружие вообще. Нет боли и унижения. Для нашей миссии это не норма.

**Comment by Horizon1959** [comment]
> Я думаю ты сам себе можешь снять такое видео, мой ноут не позволяет такую прорисовку.

Получается всё это утверждение базируется на теории математических вычислений без опытов?

> Я вижу полное непонимание игроками назначения данного класса. 

Ты присобачил роль оператора БПА мехводу/сапёру, т.е. это уже три класса в одном. Ты ожидал, что у людей есть многопоточность и они могут одновременно бежать, стрелять, ползать по минам, чинить технику и умудряться летать беспилотниками? Ты намеренно создаёшь неприятные условия и неудобства нашему несчастному инженеру (у которого и так много работы), чтобы он бросил одну из своих неудобных ролей, а потом можно было смело говорить, что у синих есть все ресурсы, но они не умеют ими пользоваться.

>Я вижу полное непонимание игроками назначения данного класса. Инженер это не человек сидящий на базе. Он не должен 100% времени быть подключенным к беспилотнику. Посмотри где находится оператор БПЛА в арме (группы в редакторе), он находится либо в составе подразделения либо идет двойкой с другим стрелком недалеко от подразделения. В обоих случая они также принимают участие в БД, а не сидят на базе.

Это маленькое подразделение, которое не лезет в бой и занимается наводкой артиллерии,  уничтожением различных объектов и обнаружением противника.. Ему необязательно торчать возле поля боя. В кампании "Восточный ветер", подразделение БПА красных, находится далеко в тылу и работает в зоне боевых действий только беспилотниками.. 

>Не вижу просчета. У партизан всегда будет как минимум одна цель - набежать на базу синих потому что это "весело". Сейчас есть еще цели - угон техники и отстрел тушек синих с целью получения лута. Эти цели мы планомерно убираем.

Не понял, какие цели у зелёных есть и будут? Грабить базу синих?

> Это синие дошли до абсурда когда они разучились действовать в связке пехота+техника в том числе потому что удобнее сесть на базе за инженера и сносить грейхоками все.

Напомню, что разъезжать машине, броня которой не выдерживает одного попадания, есть чистый абсурд и верная смерть. На танке и синие разъезжают. Попробуйте поездить на танке в режиме боя с красными и синими, увидите, что произойдёт.

> У синих вообще в последнее время периодические проблемы с тактикой и взаимодействием. Если есть командир, то он берет горстку людей и уходит в другой канал выстреливая сам себе в ногу. Только беспилотники и спасают...

У синих иногда (почти всегда) отсутствует желание побеждать. Горстка людей в отдельном канале - вполне эффективный отряд с очень хорошим взаимодействием и желанием. Те, кто не хотят побеждать, остаются в общем составе и контактировать с ними в большинстве случаев смысла не имеет.

> Ага, поэтому после набега синие мчатся за партизанами на полкарты на маршале или просто роняют беспилотник на голову чтобы сказать как мы им безразличны...

Беспилотник на голову роняют если он сошёл с ума, так сказать "последний поцелуй". Случаи с маршалом - дикость, я таких случаев лично не видел.

> С уменьшением прорисовки будет и уменьшение дальности ракет. Если я не смогу уменьшить дальность ракет без модов - уменьшения прорисовки не будет.

Если сумеешь сделать, то можно смело рубить прорисовку на 2-3 км.

> ты серьезно считаешь что оператор БПЛА прям таки неудобен? Партизаны недавно уделали синих на Гроздъях Гнева при том что им на голову сыпали бомбы и ракеты с беспилотников.

Да, это так. Беспилотники - головная боль, т.к. они без пилота, имеют тепловизоры, радар, грозное оружие и их можно комбинировать. Для простых гражданских с пушками, беспилотники являются опасным противником. Именно поэтому США сделали ставки на дешёвых беспилотных летунов, а не на дорогих разведывательных команчей. Группа держала партизан у границы триггера ровно до тех пор, пока половина не разошлась спать. Уж ты точно знаешь как оно было.

Давай завязывать с цитированием, много текста генерируем.

**Comment by ToxaBes** [comment]
> Давай завязывать с цитированием, много текста генерируем.

Согласен. 
Вся суть в том что ты считаешь управление беспилотниками главной, самой важной и **единственной** целью инженера в миссии. Я так не считаю. Поэтому и буду менять. Предлагаю продолжить обсуждение технических деталей, а не самой концепции.

**Comment by Horizon1959** [comment]
@ToxaBes Ты знаешь, я тут поразмыслил на выходных и пришёл к выводу, что ты в принципе прав, надо резать прорисовку. К какому значению ты в принципе движешься? Даст ли это какие-нибудь результаты в плане производительности сервера? Можешь ли ты в теории прийти к результату в 2 км?

Как будет выглядеть ограничение в дальности работы дартеров? Примерно как с узлом РЭБ?

**Comment by ToxaBes** [comment]
Будем делать это постепенно и снижать все до 3км макс со значением по умолчанию в 1км. Это увеличит серверный фпс и сгладит периодические лаги.

>Как будет выглядеть ограничение в дальности работы дартеров?

Будет сообщение для инженера о том что дартер вышел из зоны управления. При попытке подключится к нему будет сообщение о том что он вне зоны. Если дартер в зоне то управление/подключение будет происходить как обычно.

**Comment by ToxaBes** [comment]
* дартеры управляются до 4 км, затем связь обрывается с указанием причины. Если подъехать ближе 4км - можно опять подключаться.
* все остальные беспилотники - без ограничений по дальности управления
* максимальная дальность видимости: у ВСЕХ снижена до 3км. Дальность прорисовки объектов синхронизирована с дальностью видимости.
* все наводящиеся ракеты имеют дальность действия в 3км. Используя магический радар можно залочить цель и дальше - но ракета просто не долетит.
