### ISSUE TITLE
Запрещенное оружие и форма

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#245]
Сейчас при поднятии запрещенного оружия или формы оно исчезает. Нужно заменить на возвращение предмета в предыдущее положение (в ящик или на землю).

**Comment by malashin** [comment]
Для этого нужен https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#Take

Могут быть проблемы с нашим скриптом, который удаляет вещи из инвентаря, т.к. с арсеналом эвент хэндлер не работает. ```Take``` должен раньше срабатывать, но это ведь Арма и тут всё возможно.

**Comment by ToxaBes** [comment]
Спасибо за информацию. Буду тестировать.

**Comment by ToxaBes** [comment]
Еще вариант: брать в руки можно - стрелять нельзя и соответствующая надпись. Если не получится тогда будем на землю бросать.

**Comment by ToxaBes** [comment]
Сделал для основного и дополнительного оружия.
