### ISSUE TITLE
Не респавнятся охранники базы синих

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#248]
12:20, зашёл на Таноа, охраны снова нет. 
![107410_20170123122434_1](https://cloud.githubusercontent.com/assets/17685328/22198304/05642914-e167-11e6-9899-032da6984ca3.png)
![107410_20170123122504_1](https://cloud.githubusercontent.com/assets/17685328/22198309/066be84c-e167-11e6-9b09-4e6f476fdbce.png)

**Comment by ToxaBes** [comment]
Теперь мы не убираем стационары от доп охраны которая появляется при вызове обороны базы. Т.е. по умолчанию половина стационаров пустая. Если нажать оборону базы то все они заполнятся. Вызывал оборону базы?

**Comment by Horizon1959** [comment]
@ToxaBes вызывал. Стационары взлетели в воздух и благополучно приземлились, охрана не появилась.

Вот что увидел в 14:11:

![107410_20170123141237_1](https://cloud.githubusercontent.com/assets/17685328/22201757/1401242c-e176-11e6-98ba-7a2a8b8401d1.png)
![107410_20170123141254_1](https://cloud.githubusercontent.com/assets/17685328/22201760/14fd063e-e176-11e6-9b34-4e2c631859ea.png)

Не пойму, оно работает или нет?

**Comment by Horizon1959** [comment]
Кстати сегодня трупы лежали на земле больше 20-ти минут. может это как-то связано?

**Comment by ToxaBes** [comment]
Так на первом скрине тебя охрана как раз появилась - пулеметчик и ПТ-шник. 

>Кстати сегодня трупы лежали на земле больше 20-ти минут. может это как-то связано?

20мин это не нормально. Настройка уборки тел идет отдельным параметров description.ext :
corpseRemovalMaxTime = 180; <-- 3 минуты для ботов

Сейчас у нас перезагрузка раз в сутки. Видимо пора переходить на раз в 12 часов (5 утра и 5 вечера).

**Comment by Horizon1959** [comment]
@ToxaBes тогда на вечернюю перезагрузку надо прикрутить оповещение за 30 минут, дальше напоминание в за 20, потом за 10, потом за 5 и дальше каждую минуту.

**Comment by Horizon1959** [comment]
@ToxaBes Всё пашет?

**Comment by ToxaBes** [comment]
Потестил обе карты на всякий. Работает.

**Comment by Horizon1959** [comment]
@ToxaBes Сегодня погоняю на Таноа, потестим в боевом варианте.
