### ISSUE TITLE
Перезагрузка сервера дважды в сутки

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#249]
Добавить вторую перезагрузку сервера в 5 вечера по мск. Сделать сообщения за 30, 15 и 1 мин до рестарта сервера.

**Comment by malashin** [comment]
Возможно, стоит подумать над тем, делать ли перезагрузку до завершения текущей задачи или нет. Допустим, если игроков сейчас много на сервере то дождаться заверения задачи, если мало то делать перезагрузку по расписанию.

**Comment by ToxaBes** [comment]
Я не могу из армы послать команду на перезагрузку. Только получить реальное время на сервере и вывести сообщение что сейчас будет перезагрузка. Сам процесс перезапуска стартует по крону отдельно от армы и никак с ней не связан.

**Comment by Noart537** [comment]
- Есть ли возможность реализовать перезагрузку через веб интерфейс? Чтобы администратор мог зайти и перезапустить, при необходимости.
- Будет ли сохраняться наградная техника после рестартов?

**Comment by ToxaBes** [comment]
>Есть ли возможность реализовать перезагрузку через веб интерфейс?

Нет, даже программа Артема крашит сервер вместо перезапуска, т.к. через BE протокол не передать параметры запуска.

>Будет ли сохраняться наградная техника после рестартов?

Нет, иначе будут копить технику. Вчера синие за день собрали с десяток машин, от ифритов до танков. И это не считая наградной техники. Между рестартами будем сохранять развитие баз.
