### ISSUE TITLE
Основная миссия: взлом

### ISSUE THREAD

**Issue by Noart537** [ToxaBes/ADR-Spec-Ops#253]
Для ложных кп, добавить действие в терминал, как и на настоящем. Но при этом будет звук замыкания (есть в игре), красить в красный терминал и взрыв терминала через 5-10 сек. (взрыв можно с небольшим шансом сделать, чтобы не всегда взрывался).

**Comment by ToxaBes** [comment]
Спасибо за идею, добавил в релиз v0.1.0.

**Comment by Noart537** [comment]
Ещё хотелось бы добавить. Поиграв на выходных в кампанию apex, нашел там дейтвие, при котором нужно смотреть на объект и удерживать пробел, для действия. Что если для терминалов и для объектов дополнительных миссий, где нужно собрать данные с ноутбука, заложить заряд, нам сделать так-же? [Подробнее о функции ](https://community.bistudio.com/wiki/BIS_fnc_holdActionAdd)

```
[myLaptop,"Hack Laptop","\a3\ui_f\data\IGUI\Cfg\holdactions\holdAction_connect_ca.paa","\a3\ui_f\data\IGUI\Cfg\holdactions\holdAction_connect_ca.paa","player distance myLaptop < 3","player distance myLaptop < 3",{hint "Идет взлом терминала"},{},{hint "Терминал взломан"},{hint "Взлом прерван"},[],10,nil,true,false] call BIS_fnc_holdActionAdd;
```
Так выглядит действие при наведении на нужный объект, в данном случае _myLaptop_
![20170206140745_1](https://cloud.githubusercontent.com/assets/8770445/22641118/37517222-ec77-11e6-9f59-f45bee69cd92.jpg)
Начинаем взлом
![20170206140844_1](https://cloud.githubusercontent.com/assets/8770445/22641119/376d5f3c-ec77-11e6-92a7-8594f4e6c85b.jpg)
Так выглядит прерывание взлома, условие сделал не дальше 3-х метров от объекта. (заметил небольшой недочет, что действие продолжается при отведении взгляда от объекта.) Можно поправить, добавив во второе условие поддержание прогресса проверку, смотрит ли игрок на объект.
![20170206140850_1](https://cloud.githubusercontent.com/assets/8770445/22641121/37703e5a-ec77-11e6-9c0c-b959cb0893fe.jpg)
Так выглядит завершение действия.
![20170206141422_1](https://cloud.githubusercontent.com/assets/8770445/22641120/377002be-ec77-11e6-9266-ad5c0c13382e.jpg)

p.s. При взломе терминала можно сообщать всем сторонам, что начат взлом, думаю это заставит игроков пойти в атаку. (Это на усмотрение администрации, т.к. при сообщении, техника или авиация синих может работать по кп, если это вышка.) В этом случае, можно перенести терминал внутрь башни. 
Действие можно сделать 1 минуту.

**Comment by Noart537** [comment]
Для разных задач, разные значки. `"\a3\ui_f\data\IGUI\Cfg\holdactions\*"`
`holdAction_connect_ca.paa` 
![holdaction_connect_ca](https://cloud.githubusercontent.com/assets/8770445/22642286/f0f0a83e-ec7b-11e6-9bdc-859bbc0528a6.JPG) 
`holdAction_forceRespawn_ca.paa`
![holdaction_forcerespawn_ca](https://cloud.githubusercontent.com/assets/8770445/22642315/0dacf950-ec7c-11e6-8a57-cd6e188f3dec.JPG)
`holdAction_hack_ca.paa`
![holdaction_hack_ca](https://cloud.githubusercontent.com/assets/8770445/22642322/166d0b52-ec7c-11e6-97c0-0eb72bb3d450.JPG)
`holdAction_revive_ca.paa`
![holdaction_revive_ca](https://cloud.githubusercontent.com/assets/8770445/22642332/20d74f12-ec7c-11e6-9497-a9c636efc822.JPG)
`holdAction_reviveMedic_ca.paa`
![holdaction_revivemedic_ca](https://cloud.githubusercontent.com/assets/8770445/22642338/28e0ded0-ec7c-11e6-8907-83ec41dea0a8.JPG)
`holdAction_search_ca.paa`
![holdaction_search_ca](https://cloud.githubusercontent.com/assets/8770445/22642349/32337272-ec7c-11e6-8ec6-ae5ab0e93d67.JPG)
`holdAction_unbind_ca.paa`
![holdaction_unbind_ca](https://cloud.githubusercontent.com/assets/8770445/22642359/3826005a-ec7c-11e6-9f91-b962d4dd1e2d.JPG)

**Comment by ToxaBes** [comment]
Отличное предложение. Однозначно попробуем использовать. Еще бы в скрипт оживления/лечения добавить эти значки с обязательным условием не отводить взгляд от объекта...

**Comment by ToxaBes** [comment]
Протестил эту функцию еще раз. Работает хорошо только до тех пор пока сервер не выделенный. В режиме выделенного сервера часто вообще не появляется значок либо после выполнения не исчезает. Слишком ненадежная работает, пока остаемся на стандартных действиях через меню (хотя они тоже иногда исчезают и задваиваются).
