### ISSUE TITLE
Ручное управление сервисом техники

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#254]
Grid предложил перевести сервис перезарядки (ремонта) самолетов на ручное управление (пункт меню вместо триггера). Если менять то и наземные сервисы техники тоже. Т.е. вместо въехал в зону тригера даже случайно - жди пока закончится, будут пункты меню - починка, зарядка, топливо и тд. Имеет ли смысл это делать и в каком виде?

**Comment by Noart537** [comment]
Предложение интересное. Делать это, на мой взгляд, лучше одним пунктом. "Сервис" - то-же что и сейчас при въезде в триггер. В этом случае изменения будут минимальными, останется только вместо триггера добавить несколько действий на маркер: сервиса вертолетов, самолетов и техники, как на перевооружении самолетов. 
И ещё, предлагаю объединить место сервиса самолетов с перевооружением самолетов. А в месте починки вертолетов, туда сделать перевооружение вертолетов.

**Comment by ToxaBes** [comment]
Логично. Займусь этим примерно через версию.

**Comment by Grid-Sw** [comment]
Обосную свое предложение. Так как я предпочитаю больше всего в Арме 3 воздух, то сразу скажу, роль авиации на серверах довольно скучная, но перезарядившись один раз на перевооружении, я понял, это прекрасная возможнось добавить пилоту немного интереса для игры, а именно, не тупо приехать на полном газу триггер и он тебя сам починит, а подъехать (подлететь), остановиться и выбрать нужное действие:  
Самолеты
- перезарядить вооружение (оставить как и было)
- ремонт, заправка, перезарядка (добавить)
Вертолеты
- перезарядить вооружение 
- ремонт, заправка, перезарядка (добавить)
Автомобили, танки, БТРы
- ремонт, заправка, перезарядка

Этим мы уберем аркадность в переворужении техники

**Comment by ToxaBes** [comment]
Можно разделить "ремонт, заправка, перезарядка" на 3 действия. Например, заправка - нужно довольно редко.

**Comment by Noart537** [comment]
Скрипт же учитывает, что если полный бак, то заправка пробегает моментально 1-2 сек.

**Comment by Noart537** [comment]
Как вариант, если делить, то может приспособить на базе места визуально подходящие для действия "Заправить" - небольшой склад с топливом, бочками. "Отремонтировать" - тоже какой нибудь склад с инструментами и поломанной техникой, которую чинит бот. "Перезарядка" - ящики с оружием или что-то в этом роде.

**Comment by malashin** [comment]
Не вижу смысла их разделять. Лишняя возня если нужны все три действия.

**Comment by Noart537** [comment]
Согласен, если нужны все три действия, не актуально. А так поставил самолет на заправку, вышел чайку налить, пришел, все готово)

**Comment by ToxaBes** [comment]
В таком случае можно просто добавить "ремонт, заправка, перезарядка".

**Comment by Grid-Sw** [comment]
Разделять нельзя, просто добавить кнопку в которой все вместе будет

**Comment by malashin** [comment]
>[09-02-2017](https://forums.bistudio.com/topic/140837-development-branch-changelog/?page=39#comment-3150804)
>Added: Dynamic Loadout feature for airplanes and helicopters (more Intel / docs incoming)

Похоже, что БИСы решили сделать сменное вооружение для самолетов и вертолетов. Что логично учитывая следующий DLC про самолеты.

**Comment by ToxaBes** [comment]
Подождем тогда их реализации и посмотрим.

**Comment by malashin** [comment]
Список всей техники со сменным вооружением.
```sqf
"A-143 Buzzard (CAS)" ("I_Plane_Fighter_03_dynamicLoadout_F") ["PylonRack_1Rnd_LG_scalpel","PylonRack_1Rnd_AAA_missiles","PylonMissile_1Rnd_Bomb_04_F","PylonWeapon_300Rnd_20mm_shells","PylonMissile_1Rnd_Bomb_04_F","PylonRack_1Rnd_AAA_missiles","PylonRack_1Rnd_LG_scalpel"]
"A-149 Gryphon" ("I_Plane_Fighter_04_F") ["PylonMissile_Missile_BIM9X_x1","PylonMissile_Missile_BIM9X_x1","PylonRack_Missile_AGM_02_x1","PylonRack_Missile_AGM_02_x1","PylonRack_Missile_AMRAAM_C_x1","PylonRack_Missile_AMRAAM_C_x1"]
"A-164 Wipeout (CAS)" ("B_Plane_CAS_01_dynamicLoadout_F") ["PylonRack_1Rnd_Missile_AA_04_F","PylonRack_7Rnd_Rocket_04_HE_F","PylonRack_3Rnd_Missile_AGM_02_F","PylonMissile_1Rnd_Bomb_04_F","PylonMissile_1Rnd_Bomb_04_F","PylonMissile_1Rnd_Bomb_04_F","PylonMissile_1Rnd_Bomb_04_F","PylonRack_3Rnd_Missile_AGM_02_F","PylonRack_7Rnd_Rocket_04_AP_F","PylonRack_1Rnd_Missile_AA_04_F"]
"AH-9 Pawnee" ("B_Heli_Light_01_dynamicLoadout_F") ["PylonRack_12Rnd_missiles","PylonRack_12Rnd_missiles"]
"AH-99 Blackfoot" ("B_Heli_Attack_01_dynamicLoadout_F") ["PylonMissile_1Rnd_AAA_missiles","PylonMissile_1Rnd_AAA_missiles","PylonRack_12Rnd_PG_missiles","PylonRack_12Rnd_PG_missiles","PylonMissile_1Rnd_AAA_missiles","PylonMissile_1Rnd_AAA_missiles"]
"F/A-181 Black Wasp II" ("B_Plane_Fighter_01_F") ["PylonRack_Missile_AMRAAM_D_x1","PylonRack_Missile_AMRAAM_D_x1","PylonRack_Missile_AGM_02_x2","PylonRack_Missile_AGM_02_x2","PylonMissile_Missile_BIM9X_x1","PylonMissile_Missile_BIM9X_x1","PylonMissile_Missile_AMRAAM_D_INT_x1","PylonMissile_Missile_AMRAAM_D_INT_x1","","","PylonMissile_Bomb_GBU12_x1","PylonMissile_Bomb_GBU12_x1"]
"F/A-181 Black Wasp II (Stealth)" ("B_Plane_Fighter_01_Stealth_F") ["","","","","PylonMissile_Missile_BIM9X_x1","PylonMissile_Missile_BIM9X_x1","PylonMissile_Missile_AMRAAM_D_INT_x1","PylonMissile_Missile_AMRAAM_D_INT_x1","","","PylonMissile_Bomb_GBU12_x1","PylonMissile_Bomb_GBU12_x1"]
"K40 Ababil-3" ("I_UAV_02_dynamicLoadout_F") ["PylonRack_3Rnd_LG_scalpel","PylonRack_3Rnd_LG_scalpel"]
"K40 Ababil-3" ("O_UAV_02_dynamicLoadout_F") ["PylonRack_3Rnd_LG_scalpel","PylonRack_3Rnd_LG_scalpel"]
"Mi-48 Kajman (Black)" ("O_Heli_Attack_02_dynamicLoadout_black_F") ["PylonRack_4Rnd_LG_scalpel","PylonRack_19Rnd_Rocket_Skyfire","PylonRack_19Rnd_Rocket_Skyfire","PylonRack_4Rnd_LG_scalpel"]
"Mi-48 Kajman" ("O_Heli_Attack_02_dynamicLoadout_F") ["PylonRack_4Rnd_LG_scalpel","PylonRack_19Rnd_Rocket_Skyfire","PylonRack_19Rnd_Rocket_Skyfire","PylonRack_4Rnd_LG_scalpel"]
"MQ-12 Falcon" ("B_T_UAV_03_dynamicLoadout_F") ["PylonRack_12Rnd_missiles","PylonRack_3Rnd_LG_scalpel","PylonRack_3Rnd_LG_scalpel","PylonRack_12Rnd_missiles"]
"MQ-4A Greyhawk" ("B_UAV_02_dynamicLoadout_F") ["PylonRack_3Rnd_LG_scalpel","PylonRack_3Rnd_LG_scalpel"]
"PO-30 Orca" ("O_Heli_Light_02_dynamicLoadout_F") ["PylonWeapon_2000Rnd_65x39_belt","PylonRack_12Rnd_PG_missiles"]
"To-199 Neophron (CAS)" ("O_Plane_CAS_02_dynamicLoadout_F") ["PylonRack_1Rnd_Missile_AA_03_F","PylonRack_1Rnd_Missile_AGM_01_F","PylonRack_20Rnd_Rocket_03_HE_F","PylonRack_1Rnd_Missile_AGM_01_F","PylonMissile_1Rnd_Bomb_03_F","PylonMissile_1Rnd_Bomb_03_F","PylonRack_1Rnd_Missile_AGM_01_F","PylonRack_20Rnd_Rocket_03_AP_F","PylonRack_1Rnd_Missile_AGM_01_F","PylonRack_1Rnd_Missile_AA_03_F"]
"To-201 Shikra" ("O_Plane_Fighter_02_F") ["PylonMissile_Missile_AA_R73_x1","PylonMissile_Missile_AA_R73_x1","PylonMissile_Missile_AA_R77_x1","PylonMissile_Missile_AA_R77_x1","PylonMissile_Bomb_KAB250_x1","PylonMissile_Bomb_KAB250_x1","PylonMissile_Missile_AA_R73_x1","PylonMissile_Missile_AA_R73_x1","PylonMissile_Missile_AA_R77_x1","PylonMissile_Missile_AA_R77_x1","PylonMissile_Missile_AA_R77_INT_x1","PylonMissile_Missile_AA_R77_INT_x1","PylonMissile_Bomb_KAB250_x1"]
"To-201 Shikra (Stealth)" ("O_Plane_Fighter_02_Stealth_F") ["","","","","","","PylonMissile_Missile_AA_R73_x1","PylonMissile_Missile_AA_R73_x1","PylonMissile_Missile_AA_R77_x1","PylonMissile_Missile_AA_R77_x1","PylonMissile_Missile_AA_R77_INT_x1","PylonMissile_Missile_AA_R77_INT_x1","PylonMissile_Bomb_KAB250_x1"]
"UCAV Sentinel" ("B_UAV_05_F") ["PylonMissile_Bomb_GBU12_x1","PylonMissile_Bomb_GBU12_x1"]
"WY-55 Hellcat" ("I_Heli_light_03_dynamicLoadout_F") ["PylonRack_12Rnd_missiles","PylonRack_12Rnd_missiles"]
"Y-32 Xi'an (Infantry Transport)" ("O_T_VTOL_02_infantry_dynamicLoadout_F") ["PylonRack_4Rnd_LG_scalpel","PylonRack_19Rnd_Rocket_Skyfire","PylonRack_19Rnd_Rocket_Skyfire","PylonRack_4Rnd_LG_scalpel"]
"Y-32 Xi'an (Vehicle Transport)" ("O_T_VTOL_02_vehicle_dynamicLoadout_F") ["PylonRack_4Rnd_LG_scalpel","PylonRack_19Rnd_Rocket_Skyfire","PylonRack_19Rnd_Rocket_Skyfire","PylonRack_4Rnd_LG_scalpel"]
```

**Comment by ToxaBes** [comment]
Только нужно будет какие-то ограничения добавить. Чтобы не лепили такое:
![37ef7a7b80177d4f1e268337b900784c](https://cloud.githubusercontent.com/assets/3309152/26256953/628529d4-3cc7-11e7-9d57-ba352b4f5c70.jpg)

**Comment by zed142** [comment]
В текущей версии: БПЛА Грейхок (которые стоят на базе) не перезаряжаются на "сервисе БПЛА";
Наградные БПЛА Страж и Феникс произвольно отключаются и управление не вернуть.

**Comment by ToxaBes** [comment]
@zed142 - спасибо, перенес в отдельный тикет.

**Comment by ToxaBes** [comment]
Вся техника кроме БПЛА перезаряжается на маркере "Перевооружение авиации". Там же можно раздельно выбрать заправку/ремонт/перезарядку. Осталось:
* добавить перевооружение БПЛА
* сделать более вменяемое окно управления перевооружением

**Comment by ToxaBes** [comment]
У БПЛА теперь можно менять вооружение на подвесках.
