### ISSUE TITLE
Открытие/закрытие дверей в вертолетах

### ISSUE THREAD

**Issue by Grid-Sw** [ToxaBes/ADR-Spec-Ops#258]
Предлагаю внедрить скрипт открытия боковых дверей в вертолетах (а именно Huron и Black Havk) это   очень разнообразит геймплей для пилотов, и тем более это не сложно сделать

**Comment by 12st** [comment]
Совершенно не понимаю как это может разнообразить геймплей за пилота, просто лишний скрипт без смысловой нагрузки.

**Comment by ToxaBes** [comment]
С одной стороны -  я тоже не понимаю зачем это. С другой там реально 3 строчки. Пока 50/50. Подождем что еще пилоты напишут.

**Comment by Noart537** [comment]
Если будем делать спуск с вертолета по тросам. То для высадки пилоту нужно открыть двери, только тогда появится меню - спуститься по тросу (для пассажиров). Как вам такая идея?

**Comment by ToxaBes** [comment]
Идея хорошая. Этот титек закрываю. Займемся дверьми вместе с высадкой по тросам.
