### ISSUE TITLE
НУРС для пилота Y-32 Xi'an

### ISSUE THREAD

**Issue by Noart537** [ToxaBes/ADR-Spec-Ops#259]
Для каймана как-то рассматривался вопрос неуправляемых ракет. #177 Предлагаю ещё для новой наградной техники "Y-32 Xi'an" также сделать. Пилот управляет - ракетами Skyfire, стрелок - пушкой и управляемыми ракетами Scalpel.

`"O_T_VTOL_02_vehicle_F"` - Y-32 Xi'an (Vehicle Transport)

**Comment by ToxaBes** [comment]
Предлагаю пилотам обсудить здесь насколько это актуально.

**Comment by 12st** [comment]
Сейчас пилот наводит технику и даёт команду для стрельбы стрелку, после ввода этой фичи пилот будет стрелять сам. То есть пока стрелок будет вести огонь с пушки у пилота появиться возможность пострелять самому.

**Comment by Zedd1** [comment]
Нужно, полезно. Реализовано в King of the Hill.

**Comment by Noart537** [comment]
Для транспорта техники
```
if (_reward isKindOf "O_T_VTOL_02_vehicle_F") then {
    _reward removeMagazineTurret ["38Rnd_80mm_rockets", [0]];
    _reward removeWeaponTurret ["rockets_Skyfire", [0]];
    _reward addMagazineTurret ["38Rnd_80mm_rockets", [-1]];
    _reward addWeaponTurret ["rockets_Skyfire", [-1]];
};
```
Для транспорта пехоты
```
if (_reward isKindOf "O_T_VTOL_02_infantry_F") then {
    _reward removeMagazineTurret ["38Rnd_80mm_rockets", [0]];
    _reward removeWeaponTurret ["rockets_Skyfire", [0]];
    _reward addMagazineTurret ["38Rnd_80mm_rockets", [-1]];
    _reward addWeaponTurret ["rockets_Skyfire", [-1]];
};
```

**Comment by ToxaBes** [comment]
Спасибо, займусь после развития баз.
