### ISSUE TITLE
Завершение обороны

### ISSUE THREAD

**Issue by malashin** [ToxaBes/ADR-Spec-Ops#26]
Вчера когда играли с Ковтом, после взятия основы (какой-то терминал ткнуть надо было) началась оборона. Мы просто сидели в белом куполе, пока дроном наблюдали противника движущегося к точке. Минуты через 3-4 оборона была выполнена. Мы ничего не делали в это время, никто даже выстрелить не успел. Оба были в триггере (который на карте нарисован).

**Comment by ToxaBes** [comment]
Если в этом триггере меньше 20 чел то оборона считается успешной. Можешь примерно оценить, сколько оставалось ботов?

**Comment by malashin** [comment]
Мы ниодного не убили. Они до нас даже не дошли. Я не знаю сколько ботов было изначально.

**Comment by ToxaBes** [comment]
Проверю, спасибо.

**Comment by ToxaBes** [comment]
Проверил, в новой версии бага нет.
