### ISSUE TITLE
Сохранение добытой на основах/допках техники

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#261]
Есть идея сохранять между рестартами не только наградную технику которую не вызывали но и угнанную с задания вражескую технику для обеих сторон. Это также позволит возвращать в список наградной техники уже вызванную технику.
Механизм примерно следующий - подъехать на технике к банкомату для вызова наград (базе партизан/генератору на аванпосте) - у водителя появится пункт меню "поставить в гараж". При вызове данного действия все принудительно выходят из машины, сама машина исчезает и появляется в списке наград.
С одной стороны это может привести к накоплению техники и появлению танковых клиньев, с другой стороны техника у нас долго не живет в любом случае.

**Comment by 12st** [comment]
Сделать ограничение - не более 2 одинаковых видов техники в гараже(2 самолёта, 2 танка, 2 ЗСУ и т.д).

**Comment by ToxaBes** [comment]
Логично,  так и сделаем.
