### ISSUE TITLE
Скрипт отображения пассажиров

### ISSUE THREAD

**Issue by 12st** [ToxaBes/ADR-Spec-Ops#274]
Сдвинуть окно скрипта немного выше т.к. загораживает левый экран.
![20170519004336_1 2](https://cloud.githubusercontent.com/assets/18305023/26226372/bbf4434e-3c34-11e7-808f-ff3fd8c76dcc.jpg)

**Comment by malashin** [comment]
У меня всё в порядке на 1920х1200.
Я думаю у @12st не стандартное расположение экранов.

**Comment by ToxaBes** [comment]
Кстати, да. У меня 1920x1080 и первые 5-6 пассажиров не перекрывают.

**Comment by malashin** [comment]
![](http://i.imgur.com/cz8I031.jpg)

**Comment by 12st** [comment]
Разрешение у меня 1920X1080, но HUD поставлен на обычный а не мелкий.

**Comment by ToxaBes** [comment]
При "нормальном" HUD съезжает расположение чата (нужно вручную ставить). При "большом" HUD все еще хуже.
В общем, я приподнял список чуть выше, @12st - если все равно будет налезать, то опусти HUD чуть ниже.
