### ISSUE TITLE
Прорисовка для самолётов

### ISSUE THREAD

**Issue by 12st** [ToxaBes/ADR-Spec-Ops#282]
В Arma 3 Jets были добавлены реактивные истребители, для которых 1000 км нормальная скорость. С прорисовкой 3 км тяжело атаковать цели. Увеличить прорисовку до 5-6 км как раньше.

**Comment by ToxaBes** [comment]
неа

**Comment by ToxaBes** [comment]
Долго думал над тем что можно сделать и партизан не подставить. Вариант такой:
1. при перемирии **или** отсутствии партизан на сервере дальность для авиации - 5 км (больше нельзя ибо будет лагать у остальных)
2. при отсутствии перемирия - 3 км как сейчас.

**Comment by ToxaBes** [comment]
Арма не дает после инициализаии менять диапазон слайдера в диалоге. Тикет отклонен.
