### ISSUE TITLE
Штурм и зачистка зданий

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#287]
После тестов в реале новых мозгов для ботов нужно будет добавить полноценный штурм и зачистку зданий в котором засели игроки.

**Comment by ToxaBes** [comment]
Зачистка зданий в принципе готова, достаточно указать на дом маршрутную точку. Перед зачисткой нужно будет добавить штурмовую составляющую:

* простреливание закрытых дверей
* обязательные 1-2 офг и 1 дымовую в окна перед заходом
* подавление окон при заходе

для начала будет достаточно.

**Comment by Horizon1959** [comment]
@ToxaBes Что-то я не почувствовал штурма, может жёстче сделаешь?

**Comment by ToxaBes** [comment]
Этого еще нет. Потому и не почувствовал.

**Comment by Horizon1959** [comment]
@ToxaBes а, понял
