### ISSUE TITLE
Обучение AI тактике пехотного боя основанное на тактике игроков

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#289]
Наши AI уже ведут себя хорошо (благодаря 2м HC и VCOM AI с модификациями). Пришло время оптимизировать механизм принятия решения исходя из боевой обстановки.
На данный момент есть ~15 действий (в будущем их количество удвоится) из которых в боевой обстановке AI выбирает что делать. Начальный выбор зависит от некоторых условий (есть граната/нет гранаты, пулеметчик или просто стрелок и тд). Из 15 возможных действий остается ~5-8.
Окончательный выбор действия из этих 5-8 происходит на основе жестко заданных приоритетов. Можно попробовать сделать эти приоритеты гибкими. Для этого нужно создать небольшую нейронную сеть.
Входные параметры:
* 5-7 нейронов на класс AI (ПТ-шник, пулеметчик, и тд)
* 2 нейрона на наличие техники у противника (легко- и тяжеловооруженная)
* 3 нейрона на дистанцию до ближайшего противника (<100м, <300м, <600м)
* 1 нейрон на условие нахождение ближайшего противника в здании
* 5 нейронов на количество обнаруженных противников в радиусе контакта (1, >2, >5, >10, >20)
* 5 нейронов на количество союзников в группе (<2, <5, <10, <20, <50)
* 1 нейрон на наличие БК у бота к основному оружию

Выходной параметр - номер действия с самой большой вероятностью эффективности.
Максимальный критерий - после выполнения действия противник уничтожен и AI выжил.
Достаточный критерий - после выполнения действия оба противник и AI погибли (тут нужно осторожно, а то если сеть скатится в локальный максимум то получим ботов-камикадзе).
Минимальный критерий - AI жив.

Обучать будем на игроках :) Первый этап  - сбор текущих данных в БД из армы. Формат таблицы: по 1 колонке на каждый входной нейрон, + 1 колонка на номер выбранного действия без использования сети и 2 колонки для результата после выполнения действия (AI жив? Противник уничтожен?). После сбора хотя бы 1К строк попробуем первичное обучение сети.

Сеть делаем на основе [FANN](http://leenissen.dk/fann/wp/). Она довольна быстра, написана на C и имеет кучу биндингов на разные ЯП.

Вопросы с которым мне требуется помощь: 
1. оценка времени обучения сети и необходимого количества примеров.
2. как сделать постоянно обучающуюся сеть (есть возможность возвращать достигнутый результат на основе ее выбора)?
3. возможно есть более оптимальные типы сетей для этой задачи?

**Comment by 12st** [comment]
То есть боты будут рандомно выбирать 5-8 действий, которые соответствуют задаче и после грубо говоря ставить оценку эффективности этого действия? Не скатиться ли в итоге это к одной и той же тактике ботов, ведь данная сеть не предусматривает рельеф местности, а лишь наличие\отсутствие противника в здании. Может добавить ещё один критерий, такой как разница высот между ботом и целью?

**Comment by ToxaBes** [comment]
>То есть боты будут рандомно выбирать 5-8 действий

Нет. Действия выбираются из условия может ли бот его сделать. Например есть действие "выстрелить в здание с противником из РПГ", но он не будет в первичном отборе просто потому что у бота нет гранатомета. Также например может не быть действия "перебежать в  укрытие" если бот находится на соляном озере. Т.е. на первом этапе исключаются действия которые просто не подходят под текущие условия. Это уже реализовано.

Рельеф местности в данном случае не используется т.к. в арме не имеет смысла (нет в арме возможности сказать боту спрятаться за ближайший холм). Вместо этого используются укрытия (уже реализовано). Это одно из 15 действий. Нейронная сеть в данном случае подскажет стоит бежать за ближайший укрытие камень/дерево/другой объект высотой больше 0.5м или наоборот сократить дистанцию с противником.

**Comment by ToxaBes** [comment]
Грубо говоря, рельеф местности это карта, а мы оперируем объектами (дома, деревья, камни, заборы и тд).

**Comment by 12st** [comment]
Смотри, допустим у бота есть на выбор 2-3 действия которые он может выполнить

**Comment by 12st** [comment]
Смотри, допустим у бота 3 действия которые он может выполнить при штурме здания.
1. Кинуть гранату в окно.
2. Просто зайти и расстрелять.
3. Кинуть дым и зайти под него.
Если у нас учитывается два фактора такие как устранение противника и выживаемость AI, то боты станут использовать почти всегда первое действие, то есть даже если со стороны бота было бы разумнее зайти с тыла в здание и не палить свою позицию. Со временем 2 и 3 варианты сойдут на нет т.к в большинстве случаев граната будет убивать противника оставляя при этом живого бота. Соответственно похожую аналогию можно провести с другими ситуациями, боты станут предсказуемыми и в большинстве случаев выполнять действие которое работает лучше, однако это не означает, что оно тактически выгодное в данный момент. Зная это можно будет довольно легко просчитывать их действия, т.к на каждую ситуацию будет 1 наиболее используемое решение, иными словами мы столкнёмся с тем, что часть их логики станет мало используемой.

**Comment by ToxaBes** [comment]
Не на том уровне рассматриваешь задачу. В данном случае сеть решает идти на штурм или нет. Сам процесс штурма уже находится вне компетенции сети.

**Comment by 12st** [comment]
Ага, теперь понял. Спасибо за разъяснения.

**Comment by Horizon1959** [comment]
> то получим ботов-камикадзе
А если подробнее, то как они будут выглядеть? Будут просто бежать на смерть с боевым кличем или взрываться вместе гяурами?

**Comment by ToxaBes** [comment]
>Будут просто бежать на смерть с боевым кличем или взрываться вместе гяурами?

Если [переобучить](https://basegroup.ru/community/glossary/overtraining) сеть то такое возможно.
Также игроки своими неоднократно повторяющимися глупыми действиями могут испортить выборку с примерами и сделать сеть туповатой. На данном этапе сложно что-то конкретное сказать. Сначала нужно собрать выборку для первоначального обучения.

**Comment by Horizon1959** [comment]
> Также игроки своими неоднократно повторяющимися глупыми действиями могут испортить выборку с примерами и сделать сеть туповатой.

Пахнет грифферами из майнкрафта. Какой-нибудь заблудший Вася не сможет всё попортить?

**Comment by ToxaBes** [comment]
>Какой-нибудь заблудший Вася не сможет всё попортить?

Не сможет, это граничный вариант. Тут нужно целенаправленно, постоянно и не в одиночку делать глупости. Ну и добавлю наверное сообщение мол просьба в бою стараться действовать адекватно, а то от вас нейронная сеть тупеет...

**Comment by zed142** [comment]
Тоха может не надо терминаторов? Как насчёт того чтобы задать достижение выживаемости основым критерием. Причем выживаемость не единиц, а подразделения. Предполагается что потери более 40% не приемлемы.
К сожалению игроки бессмертны (поднимают друг друга под атакой) и поэтому  исходя из текущей задачи подразделения ботов (патрулирование, часовой, штурм) подбирать им граничные условия успешности для обучения.
Например. 
1) Идёт по лесу подразделение 10 ботов с задачей  патруль.
На них вылетает 2 партизана.
Партизаны круты и в течении 10 сек валят 4. Боты смогли быстро отступить(потеря целеуказания) больше без потерь. Успех.
2) Идёт по лесу подразделение 10 ботов с задачей  патруль.
На них вылетает 2 партизана.
Партизаны круты и в течении 10 сек валят 4. Боты при отступлении потеряли еще 3 (потеря целеуказания). Провал.
3) Идёт по лесу подразделение 10 ботов с задачей  патруль.
На них вылетает 2 партизана.
Партизаны круты (но не очень) и в течении 10 сек валят 1. В перестрелке боты берут 2-3 фрага (или продержались ?? мин) до наступления потерь в 40%.  Успех. 
4) Идёт по лесу подразделение 10 ботов с задачей  патруль.
На них вылетает 2 партизана.
Партизаны круты и в течении 10 сек валят 1 и бегут (потеря целеуказания). Успех.
И так далее.

**Comment by ToxaBes** [comment]
>Как насчёт того чтобы задать достижение выживаемости основным критерием.

В этом случае боты будут ВСЕГДА отступать и уклоняться от контакта т.к. это самая эффективная тактика выжить. Будем искать компромисс.

Терминаторов не будет. Я уже уменьшил им точность и скорость прицеливания в среднем на 15-20% из-за новой тактики. То что ты описал в примерах примерно и будет происходить с помощью нейронной сети.

**Comment by zed142** [comment]
кстати вот интересный проект по машинному обучению https://gym.openai.com

**Comment by ToxaBes** [comment]
>Причем выживаемость не единиц, а подразделения. Предполагается что потери более 40% не приемлемы.

Тут есть проблема. Боты уже умеют отступать перегруппировываться (2 отряда соединяются в 1), разделяться (отряд разделяется на два независимых отряда). Сейчас их любимые тактики:
1. клещи (разделиться на 2 отряда и зайти с 2х флангов)
2. эту тактику я называю "гаденыш" (1 бот отделяется от группы и по большому радиусу обходит игроков заходя им в тыл. Остальные в это время подавляют). В 50% он выкашивает всех игроков.

Из-за реализации на конечных автоматах они стараются постоянно использовать эти 2 варианта. Нейронная сеть нужна для того чтобы разнообразить их методы.

https://gym.openai.com не подходит. У нас будет обучение на реальных выборках (схватки игроки vs боты на конечном автомате будут записываться в бд вместе с результатом). Когда накопится достаточно строк скормим все это дел fann.

**Comment by ToxaBes** [comment]
@zed142 - напомни мне пожалуйста модель твоего ноута.  Я сейчас в раздумьях. Зефир провалился...

**Comment by zed142** [comment]
как по моему обучение с подкреплением интереснее для ситуации песочницы Arma будет чем обучение с учителем (хотя я только по верхам почитал). 
[Ноут](https://www.msi.com/Laptop/GT72VR-7RE-Dominator-Pro.html)
[тут](https://www.notebookcheck.net/MSI-GT72VR-7RE-Dominator-Pro-Notebook-Review.190406.0.html) и [тут](https://www.google.ru/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=0ahUKEwjRhNKgpNTVAhXHKJoKHatNBF0QFggrMAE&url=http%3A%2F%2Fwww.ixbt.com%2Fportopc%2Fmsi%2Fmsi-gt72vr-7re.shtml&usg=AFQjCNHgTgnhQLCQDzwB6kANH9o2qyg8Xg) разобрали. Зефир это демонстратор технологии. Они как обычно к сэилтайму (рождество и НГ) выкатят серийные нормальные модели.

**Comment by ToxaBes** [comment]
В нашем случае больше всего подходит классический вариант обучения с учителем с последующим периодическим дообучением. 

Делись впечатлениями от своего ноута.  Что не устраивает? как охлаждение? Я думаю взять ASUS G752VS-BA497T 90NB0D71-M07110. Что думаешь (походу ты его и советовпл постом выше) ? 
У зефира принципиальные для меня косяки в способе охлаждения и зарезании частот - их не рассматриваю.

**Comment by ToxaBes** [comment]
Результаты тестов по управлению группой (возврат номера действия из бд) с НС обученной подготовленными данными:
* 1 группа -> до 1.5 сек
* 5 групп -> 4 сек
* 10 групп -> 6-7 сек

В каждой группе от 3х (техника) до 8 ботов. При наличии живых игроков/взрывов и расчета прочих коллизий это время увеличится. С такими сроками реакции игроки успеют надругаться над каждым ботом в группе. 
Нужно сместить управление на уровень выше (взаимодействие групп). Т.е. тактика каждой единицы группы останется на конечных автоматах, т.к. они очень быстрые (только допишу пару приемов), а взаимодействие между группами будет отвечать НС, там нет необходимости в такой скорости, достаточно опроса 1-2 раза в минуту.  Сейчас между соседними группами идет обмен информацией об обнаруженном противнике. Никакой стратегии на уровне взаимодействия более 2х групп нет.

Будем пилить свой скайнет с командными цепями управления и основами стратегии. 
Цель: защита зоны определенного радиуса. Для основного задания зон будет 2 (вышка и КП). 
Не смотря на игру в защите нужно попробовать предусмотреть возможность контратаки на базу синих с помощью блуждающих патрулей и авиации.

Нужна информация по применении ИИ/экспертных систем в играх с упором на защиту.

**Comment by ToxaBes** [comment]
Другими словами, если раньше я пытался сделать чтобы ИИ решал, идти на штурм или нет, то теперь ИИ будет решать какие группы (пехота, танк, ифрит, вертолет - разные группы) и сколько групп отправить в точку обнаружения противника для его устранения.

**Comment by ToxaBes** [comment]
На этапе тестирования возникла проблема контроля расхода БК. С авиацией проблем нет, улетает и перезаряжается. Проблема с наземной техникой. Пример: Красная королева обнаружила угрозу (вражескую технику с пехотой) и отправила танк. А у танка закончились снаряды к основному орудию, остался только пулемет. В данном случае нужно было отправлять либо другую технику либо что-то классом выше (авиацию).
Просчитывать БК к каждому классу техники не вариант.

**Comment by ToxaBes** [comment]
C БК вопрос решился. После очередного обучения ИИ решил что вообще нет смысла гнать пехоту т.к. ее покосят и начал действовать исключительно тяжелой техникой под прикрытием авиации, а пехоту отводить к обоим КП и радиовышке, причем радиовышка в приоритете (видимо хочет чтобы аваиация не кончалась). Пытаюсь подогнать обучающую выборку так чтобы ИИ "поверил" в свою пехоту.

**Comment by ToxaBes** [comment]
Сегодня официальный день рождения Красной королевы (ИИ). Теперь она эффективно использует все доступные силы при любых вариантах при необходимости комбинируя варианты решения, а также способна ночью дополнительно обучаться на сыгранных за сутки битвах (сейчас доп. обучение занимает ~1.5-2 сек что с увеличением количества битв дойдет до 1-2 мин max). 
Возможность доп. обучения каждую ночь сводит на нет все попытки атаки "тупостью".

Технически характеристики ИИ: остаточная сеть с тремя скрытыми слоями (60, 30 и 15 нейронов соответственно). Входной слой содержит 10 нейронов, выходной - 5. Первичная обучающая выборка - 100 битв при 150 эпохах обучения и допустимой ошибке 0.0001.
Функции активации: вых. слой - линейная, скрытые слои - сигмоидальная.
Способна распознать и среагировать на ~3.6 миллиона вариантов развития событий на поле боя сведя их к одному из 120 вариантов решений. При этом весит 170 KB (ну это пока). Действует в рамках оборонной стратегии.

**Comment by 12st** [comment]
Ой ой. Скайнет близко...

**Comment by ToxaBes** [comment]
Красная королева добавлена на основу и оборону основы. Пока идет обкатка взаимодействия AI с армой и проверка структур данных. В данный момент сеть работает без самообучения (первоначально обучил "на себе"), да и ничему хорошему игроки пока ее научить не могут. Нужна адаптация с обеих сторон. После тестирования добавлю ее в допки / приоритетные цели и включу самообучение - вынес задачи в отдельный тикет.
