### ISSUE TITLE
ПВО у ангаров пилотов

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#29]
Добавить возможность включения ПВО у ангаров пилотов.

**Comment by Horizon1959** [comment]
Мне кажется этого все ждут.

**Comment by ToxaBes** [comment]
+ немного оживил место респа пилотов.

**Comment by ToxaBes** [comment]
Если игроков меньше 7 человек и нет ни одного пилота, то MH-9 Hummingbird доступен для всех.
