### ISSUE TITLE
Перенос миссии на Malden

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#290]
Логотип миссии:
![adr_specops_malden_loading](https://user-images.githubusercontent.com/3309152/27770579-c88a35a4-5f49-11e7-8809-419f564c6364.jpg)

**Comment by Horizon1959** [comment]
Перенос по аналогии с Алтисом или Таноа?

**Comment by ToxaBes** [comment]
Алтис. Только скорее всего уберем новые самолеты из DLC из наград и авиации противника.

**Comment by Horizon1959** [comment]
@ToxaBes Нармасик. Карты будут поочерёдно ставится?

**Comment by ToxaBes** [comment]
>Карты будут поочерёдно ставиться?

Скорее всего просто поочередно. 
Ну или разбивать на чет/нечет/простое число. Выйдет примерно также, но к началу и концу месяца так карта которая выпадает на простое число будет играться чаще (и понять какая карта будет завтра смогут не только лишь все, мало кто сможет это сделать).

**Comment by Horizon1959** [comment]
Никак нельзя организовать голосовалку за карту с кулдауном на N-часов? А то например я больше всего Алтис люблю, а его 2 дня ждать надо будет.

**Comment by ToxaBes** [comment]
я подумаю что можно сделать.

**Comment by ToxaBes** [comment]
Alpha-версия готова. Осталось перенести спецоперации.

**Comment by Horizon1959** [comment]
![default](https://user-images.githubusercontent.com/17685328/28057607-2c862672-6629-11e7-99ea-e5e5500ea06c.jpg)

**Comment by ToxaBes** [comment]
Текущий статус:

- [x] Прерванный полёт
- [x] Заложники
- [ ] Конвой
- [ ] Угон
- [ ] Рыба-меч
- [ ] Желтый туман
- [x] Гроздья Гнева
- [ ] Нефть-Матушка
