### ISSUE TITLE
Нет снаряжения при старте

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#293]
Зашёл за синего инженера, у него вообще инвентарь пуст. Арсенал не работает из-за очередного не доехавшего конвоя. Может ещё перепилить стандартное снаряжение? А то там обычно снаряга рассчитана с расчётом на бой отряд vs отряд где-то при тесном контакте в лесу.

![107410_20170711163029_1](https://user-images.githubusercontent.com/17685328/28070660-68f227b4-6656-11e7-8f27-487bed8643dd.png)

**Comment by ToxaBes** [comment]
Оружие можно найти в бронетехнике либо взять ее и поехать искать конвой/проводить его до базы. Т.е. в этот момент это главная задача синих.

**Comment by Horizon1959** [comment]
@ToxaBes Падажи, т.е. даже шмотки в начале иметь нельзя? В какой бронетехнике есть винтовки? Ты же вроде убрал их из машин?

**Comment by ToxaBes** [comment]
в верте был mx. В начале шмоток нет чтобы не перезаходили.

**Comment by Horizon1959** [comment]
@ToxaBes а, понял. Это т.е. надо лезть в авиацию и искать этот несчастный грузовик?
