### ISSUE TITLE
Глюки с спецоперацией "Заложники" на Malden

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#295]
Тусовался на базе, поехал на допку, по пути высплыло сообщение:

![107410_20170712114230_1](https://user-images.githubusercontent.com/17685328/28109344-7b32e5e8-66f7-11e7-9805-1a3f63bc55be.png)

Может это опять конвой ехал через зону боевых действий? Он как всегда куда-то делся и опять нет арсенала.

**Comment by ToxaBes** [comment]
Это не глюки. Как обычно кто-то из ботов наступил на ПП во внутреннем поясе, а командир в это время был на втором этаже (открытом). Также иногда заложники погибают, если их будка стоит около внутреннего пояса.

**Comment by Horizon1959** [comment]
Ок, рано закрыл. Заложники-то не лыком шиты! Взяли и убежали под шумок. Проверив 2 малые коробки, увидел их на высоте. Догнал, протыкал.

![107410_20170712123550_1](https://user-images.githubusercontent.com/17685328/28111988-119ae3e8-6700-11e7-87d3-ff22b5cb231c.png)

![107410_20170712124316_1](https://user-images.githubusercontent.com/17685328/28111990-13befe34-6700-11e7-8927-811ccee44b0e.png)

![107410_20170712124320_1](https://user-images.githubusercontent.com/17685328/28111992-15e71016-6700-11e7-8834-988c5977e6df.png)

**Comment by ToxaBes** [comment]
Да, они теперь пытаются найти свободный проход в заграждении и выйти за него метров на 50-100. На синих надейся, а сам не плошай. 
Так и задумано - командир красных убит, есть команда на их ликвидацию, сидеть ждать палача?

**Comment by Horizon1959** [comment]
@ToxaBes они могут уйти куда угодно или тусуются в зоне?

**Comment by ToxaBes** [comment]
Уходят до первого безопасного места, обычно это 50-100м от границы круга.

**Comment by Horizon1959** [comment]
Хорошо, я сдаюсь. Прошманал все коробки, накрыл весь город из миномёта. Со всех сторон перестрелял ботов, просмотрел всю округу тепловизором. Дошло до того, что вот эти китайцы никак на меня не реагировали и их невозможно было убить:
![107410_20170712161559_1](https://user-images.githubusercontent.com/17685328/28120031-87a90758-671f-11e7-8bf4-60f0965b478d.png)

Что делать-то? Как найти заложников или зафейлить миссию?

**Comment by ToxaBes** [comment]
>на меня не реагировали и их невозможно было убить

они улыбались при этом? )

**Comment by ToxaBes** [comment]
перезапустил сервер - безголовые клиенты зависли. Это арма.

**Comment by Horizon1959** [comment]
@ToxaBes да хер этих китайцев поймёт.

**Comment by ToxaBes** [comment]
суть в том что когда безголовые зависают - боты которые были на них начинают улыбаться. Я серьезно.

**Comment by Horizon1959** [comment]
@ToxaBes 
![-](https://user-images.githubusercontent.com/17685328/28120651-4e0efc62-6721-11e7-8550-7ef6289bb909.jpg)
