### ISSUE TITLE
Кривые конвои на Malden

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#296]
Катался, встретил по пути это:
![107410_20170712121621_1](https://user-images.githubusercontent.com/17685328/28110782-1741a7a4-66fc-11e7-9f9e-8b552ced7660.png)

![107410_20170712121635_1](https://user-images.githubusercontent.com/17685328/28110795-1ce82a52-66fc-11e7-985a-f7a9a12f1097.png)

![107410_20170712121643_1](https://user-images.githubusercontent.com/17685328/28110800-205e8208-66fc-11e7-8566-206fe4ec94cf.png)

![107410_20170712121650_1](https://user-images.githubusercontent.com/17685328/28110808-24a2a182-66fc-11e7-9434-e863518396c7.png)

![107410_20170712121658_1](https://user-images.githubusercontent.com/17685328/28110811-26e3e6b8-66fc-11e7-829a-0d22126cc4f4.png)

![107410_20170712121944_1](https://user-images.githubusercontent.com/17685328/28110896-69750ebc-66fc-11e7-972d-4053fa7eb9c9.png)

Все живые. Что с ними случилось? Из-за них нет арсенала?

**Comment by ToxaBes** [comment]
Опять проявился косяк с построением маршрута. Будем разбираться.

**Comment by Horizon1959** [comment]
Воооо, зацени, прям щас:

![clip2net_170712122404](https://user-images.githubusercontent.com/17685328/28111093-064b3630-66fd-11e7-8e3b-77b438adb9af.png)

**Comment by Horizon1959** [comment]
Ну что это такое:

![107410_20170714145342_1](https://user-images.githubusercontent.com/17685328/28211256-5a5df39a-68a4-11e7-9fa3-546be27fbc89.png)

**Comment by ToxaBes** [comment]
Беспощадный рандом ) нужно будет сделать проверку на текущую точку. Кстати проверь, там теперь машина сопровождения ставится вплоть до маршала.

**Comment by Horizon1959** [comment]
Видел охотник с конвоем. Регулярно выцепляем этих дебилов здесь:
![107410_20170714162948_1](https://user-images.githubusercontent.com/17685328/28214127-bb0d2cee-68b1-11e7-954b-93101b2caedf.png)

**Comment by ToxaBes** [comment]
Там камни на обочине на которых все время застревает конвой. Я постараюсь их удалить с карты.

**Comment by ToxaBes** [comment]
Если грузовик физически уничтожен или вообще не может двигаться то он считается уничтоженным. Невозможность движения проверяется командой canMove которая проверяет только физическую составляющую, например что выбиты ВСЕ колеса или пробит двигатель. Если техника по глупости водителя застревает где-либо то она по прежнему может двигаться (колеса то крутятся, движок работает). 
Сделано это для того чтобы ушлые синие не обездвиживали полностью конвой тем самым получая постоянно открытый арсенал.

**Comment by ToxaBes** [comment]
По инженеру: если грузовик потеряет 1-2 колеса - водитель может дать команду инженеру выйти и починить (а может решить что и так сойдет, конвой стоит - служба идет). А если уничтожить колеса то приказ просто не успеет выполнится, там проверка раз в несколько секунд.

**Comment by Horizon1959** [comment]
@ToxaBes я ему выбил не все колёса, но вот он сразу исчез, оставив меня в недоумении.

**Comment by ToxaBes** [comment]
Хм, обычно у колесной техники нужно выбить все колеса, у гусеничной - один трак, у вертолетов - несущий винт. Возможно этот грузовик настолько длинный что считаются не все колеса. Я неоднократно видел как красные боты с помощтю ГП сносили передние два колеса, расстреливали водителя и конвой просто стоял на месте никуда не исчезая.

**Comment by Horizon1959** [comment]
Привет от конвоя: 

![107410_20170818141905_1](https://user-images.githubusercontent.com/17685328/29456847-4d482788-8420-11e7-8b86-9ba77c3a2ddb.png)

Хорошо хоть арсенал не пропал.

**Comment by ToxaBes** [comment]
Ты же видишь что там соднце жарит. Вот он в тенек под кроны и спрятался. Вообще,  в этом месте косяк слоя дорог на карте. Даже если убрать там все объекты - техника будет останавливаться (та же причина почему гражданские останавливаются на мостах).

**Comment by Horizon1959** [comment]
:)

**Comment by Horizon1959** [comment]
В продолжение темы кривых конвоев - их убивает аид из-за проезд по спецоперации. Как-нибудь отключть это можно?

**Comment by ToxaBes** [comment]
Нет, т.к. захватив машину конвоя можно будет кататься внутри триггера. После внесения изменений предложенных сундуком по конвою это будет не важно.
