### ISSUE TITLE
Стомперы на Malden живут своей жизнью

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#298]
Стомперы конечно любят заниматься самодеятельностью, но на Malden они без участия инженера уже начинают разъезжать в гаражах. С этим есть методы борьбы или понять и простить?

**Comment by ToxaBes** [comment]
Нет, это не только на Малдене, это в любом гараже на любой карте. БИСы тоже опыты на ботами походу делают.

**Comment by Horizon1959** [comment]
@toxabes Ок, понял.
