### ISSUE TITLE
Не работает спавн наградной техники

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#299]
После нескольких взрывов в воздухе вертолёт таки долетел с контейнером, а потом улетел с этим самым грузом в неизвестном направлении. В результате наградную технику получить не можем.

**Comment by ToxaBes** [comment]
Проблема не в карте. БИСы ОПЯТЬ поломали построение маршрута с посадкой/отеплением груза для вертолета. Скорее всего буду заменять на наземную доставку из одного и того же места с нормальной дорогой.

**Comment by ToxaBes** [comment]
Заменил на блекфиш и добавил им отваги. Посмотрим как будут себя вести.

**Comment by Horizon1959** [comment]
Итого 2 утюга теперь летает?

**Comment by ToxaBes** [comment]
Да, они более устойчивы к атакам со стороны да и партизанам сложнее сбить будет.
