### ISSUE TITLE
Сокровищница зелёных

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#300]
Зашёл тут за зелёных, решил поглядеть на охрану базы синих. Ну там перенёс базу прям к синим, давай к ним кататься. Достал немного лута, пришёл его положить в ящик и увидел эти несметные богатства:

![107410_20170717130930_1](https://user-images.githubusercontent.com/17685328/28264032-c8aab0dc-6af1-11e7-8e70-9466077e3b1c.png)
![107410_20170717130937_1](https://user-images.githubusercontent.com/17685328/28264035-d066a038-6af1-11e7-83d4-a2022c463cf4.png)
![107410_20170717130942_1](https://user-images.githubusercontent.com/17685328/28264040-d1a7334a-6af1-11e7-9c73-b97fec26fb12.png)
![107410_20170717131037_1](https://user-images.githubusercontent.com/17685328/28264042-d2cf1ef4-6af1-11e7-9ead-b3c703f2c7b8.png)
![107410_20170717131044_1](https://user-images.githubusercontent.com/17685328/28264043-d3dc123e-6af1-11e7-97dd-de118c75aec3.png)
![107410_20170717131054_1](https://user-images.githubusercontent.com/17685328/28264044-d4a123da-6af1-11e7-8ba6-1d730d3991d9.png)
![107410_20170717131102_1](https://user-images.githubusercontent.com/17685328/28264045-d5993ff2-6af1-11e7-8b13-5bfcff70b454.png)
![107410_20170717131108_1](https://user-images.githubusercontent.com/17685328/28264046-d66eceec-6af1-11e7-9de0-5372a59fef2c.png)
![107410_20170717131114_1](https://user-images.githubusercontent.com/17685328/28264048-d944905c-6af1-11e7-9520-ecc68cdfaa79.png)
![107410_20170717131119_1](https://user-images.githubusercontent.com/17685328/28264050-daa0d01e-6af1-11e7-8dd1-edb917935543.png)
![107410_20170717131124_1](https://user-images.githubusercontent.com/17685328/28264051-dbb6b57c-6af1-11e7-8703-7f022faac1f7.png)
![107410_20170717131129_1](https://user-images.githubusercontent.com/17685328/28264052-dcb1b602-6af1-11e7-8348-9df13bc65148.png)
![107410_20170717131143_1](https://user-images.githubusercontent.com/17685328/28264055-ddad68a8-6af1-11e7-919e-21fa65b8c621.png)

База перенеслась сюда:
![107410_20170717131233_1](https://user-images.githubusercontent.com/17685328/28264061-e640f0fc-6af1-11e7-87e4-da5f4abbe16d.png)

Это нармасик или баг какой? 244 коллиматора это вообще эпик.

**Comment by 12st** [comment]
Норма. База зелёных не уничтожалась очень давно, но при этом её постоянно пополняли припасами.

**Comment by Horizon1959** [comment]
При переносе базы лут не теряется?

**Comment by ToxaBes** [comment]
>При переносе базы лут не теряется?

Нет. Лут остается и при переносе и при перезагрузке.

**Comment by Horizon1959** [comment]
@ToxaBes Ок, понял
