### ISSUE TITLE
Недоступность вещей на Таноа

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#301]
Давно уже недоступны вот эти два итема (хотя на Таноа они как раз должны быть:

![107410_20170719165606_1](https://user-images.githubusercontent.com/17685328/28370655-82875354-6ca3-11e7-886f-7b43ebf6ba99.png)
![107410_20170719165609_1](https://user-images.githubusercontent.com/17685328/28370654-82849f56-6ca3-11e7-9949-abf2c7bbca0c.png)

**Comment by ToxaBes** [comment]
Спасибо что сообщил.  Добавлю на таноа.

**Comment by ToxaBes** [comment]
G_Balaclava_TI_G_tna_F и G_Balaclava_TI_tna_F  находятся в списке разрешенных вещей и должны быть доступны.

**Comment by Horizon1959** [comment]
Уточнение: в арсенале итемы есть, но они пропадают после выхода из арсенала. Короче надо блеклист проверить.

**Comment by ToxaBes** [comment]
Исправил.

**Comment by Horizon1959** [comment]
@ToxaBes Отлично, спасибо.
