### ISSUE TITLE
Добавить пару БПЛА операторов на основу

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#306]

**Comment by Horizon1959** [comment]
Стомперы и их прихвостней мы находили, а вот дартеры не обнаружили. Может это из-за того, что оператор не запустил его в воздух (бегает с рюкзачищем)?

**Comment by ToxaBes** [comment]
Да, он сам решает стоит запускать дартер или эффективнее найти укрытие и начать отстреливаться.
Кстати, стомперы примерно не в центре зоны находили? Я заметил что вроде они тяготеют оставаться в центре охраняемой зоны. Можно случайность.

**Comment by ToxaBes** [comment]
Добавлю наверное 1-2 принудительно запускаемых дартера, а операторов спрячу по домам.

**Comment by Horizon1959** [comment]
@ToxaBes Они ездили вместе с прихвостнями не только в центре. Вроде нормально всё пашет, но эти стомперы тупые как блондинки-менеджеры. Мы их расстреливали с 500 метров, а они только турелью вращали.

**Comment by ToxaBes** [comment]
Попробую добавить им мозгов -> #308
