### ISSUE TITLE
Добавить мозгов вражеским стомперам

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#308]
Также добавить 1-2 принудительно запускаемых дартера, операторов спрятать по домам.

**Comment by Horizon1959** [comment]
Было бы круто ещё и синим стомперам мозгов добавить. Сейчас эти дауны не реагируют даже если по ним стреляют, а цели видят только в упор и только если они по фронту. Не делать им конечно дальность на 1000 метров и далее, но хотя бы чтоб они метров на 300-500 не тупили.

**Comment by ToxaBes** [comment]
Я подумаю что можно сделать.

**Comment by ToxaBes** [comment]
Кое-что сделал.

**Comment by Horizon1959** [comment]
@ToxaBes  Подробности есть?

**Comment by ToxaBes** [comment]
поймешь когда поиграешь. Зачем портить сюрприз.

**Comment by Horizon1959** [comment]
@ToxaBes Интриган.
