### ISSUE TITLE
конвой

### ISSUE THREAD

**Issue by SooNDooCK71** [ToxaBes/ADR-Spec-Ops#309]
Контролируемый конвой(арсенал) , который ведут сами игроки , охраняют сами игроки . Конвой не спавнится каждые 15 мин , а появляется после каждого закрытия точки . Забирать нужно с "охраняемой базы синих" (хорошо охраняемой ....неприступной ! сам сделаю !) , находящейся либо на северо-западе карты(р-н ореокастро) , либо на юго-востоке (р-н в/п полосы ) . если это возможно , карту нужно разделить на две половины , спавн "базы" происходит в противоположной половине от места спавна следующей точки , чтобы не гнать конвой(арсенал) через зону боевых действий . Маршрут необходимо сделать обязательным , при отклонении от маршрута спавнится вр. воздух (звено неофронов . кайманов , касаток ) и пт отделения . Потеря конвойной машины(арсенал) - потеря арсенала на базе на текущую точку , после закрития точки , для следующей спавнится следующий конвой . Так же предлагаю к конвойной машине(арсенал) добавить конвойную машину(награда) . Один заказ-одна машина . Так же предлагаю сделать ограниченным арсенал/б.к для техники . В данный момент точку можно сравнять с землёй с помощью опытного пилота и пары -тройки дозаправок , либо беспилотниками , либо артой , т.к бк не ограничен , соответственно цели не делятся по приоритетам и на одного бота можно с лёгкостью   отправлять гбу или дорогущий скальпель . Для этого необходимо убрать у гражданских сервисов возможность дозаправки б.к техники , это"дичь" , если это возможно , сделать визуальное отображение заполнения сервиса техники скажем в процентах . Для дозаправки с.т. на базе добавить конвойную машину"бензовоз" . Если скажем на сервере 3-4 игрока , то они могут отслеживать степень заполнения с.т. и решать , нужно ли им гнать " бензовоз" вместе с "арсеналом" .   А вообще идеально сделать сервис техники выборочным и анимированным , с командой механиков и техников ))) ИТОГО : у нас получается полноценная колонна с определённым маршрутом следования , не застревающая в деревьях , цель для зелёных , приоритет для синих .

**Comment by ToxaBes** [comment]
Идея интересная.

>спавн "базы" происходит в противоположной половине от места спавна следующей точки , чтобы не гнать конвой(арсенал) через зону боевых действий.

Почему нет? Есть мосты, всегда можно объехать зону. 

>Маршрут необходимо сделать обязательным 

Зачем ограничивать? Как синие доставят конвой на базу - их дело. К тому же оч. гемморно сделать контроль маршрута.

>Так же предлагаю к конвойной машине(арсенал) добавить конвойную машину(награда) . Один заказ-одна машина 

Она уже есть, это машина сопровождения - рандом от праулера до маршала. С ботами - водителем и стрелком. Если игрок хочет забрать эту технику он просто садится на пассажира и потом пересаживается на водителя. После этого можно приказать ботам остаться в машине или выйти.

>Для этого необходимо убрать у гражданских сервисов возможность дозаправки б.к техники , это"дичь"

Согласен. Можно еще добавить что если арсенал закрыт то на базе синих сервисы техники/перезарядки/перевооруженя также не работают.

>сделать визуальное отображение заполнения сервиса техники скажем в процентах .

Пока можно остановится на двух состояниях: работает/не работает.

Пока непонятно как быть если например на сервере 1-2 синих. Каждый раз им ехать за конвоем после точки - надоест оч. быстро.

**Comment by Horizon1959** [comment]
Конвой, стартующий в определённых укреплённых местах - хорошо и логично, даже для зелёных. Сейчас конвой часто едет через зону боевых действий, благополучно там взрывается и заслуженно получает овации с премией "ёптвоюмать".

Если начать выключать арсенал  чаще, чем сейчас, то это приведёт к собирательству снаряжения и отходу от концепции регулярной армии. Когда на втором был доступен только вооружённый охотник и бобкэт, то игроки просто коллекционировали ресурсы в виде техники. Если на арсенал нельзя будет положиться, то синим придётся запасаться награбленным с поля боя. Заходя за синих, играющий рассчитывает на минимум запар со снаряжением и вооружением в рамках своего класса; шатание этого принципа приведёт к очередному Wasteland.

С воздуха нагнуть всех невозможно, по причине всем известной ракетной атаки. Пилоты работают по схеме "покатался 10 минут - сбили"; полёты  и модель повреждений сейчас в разы сложнее с выходом jets dlc. Беспилотники отныне не являются долгожителями и их благополучно сбивают. В добавок боты в машинах стали умнее и научились выкидывать дымы, сбивающие ракеты с курса.

Рабочие сервисы техники сейчас находятся на значительном расстоянии от зоны боевых действий, поездки до этих сервисов отнимают время и создают паузу между атаками.

**Comment by SooNDooCK71** [comment]
не забирать машину сопровождения , а везти на базу хемт , который в последствии стане наградой в виде заказанной единицы техники

**Comment by ToxaBes** [comment]
Как вариант, если синие не приехали за конвоем в течении 10мин после появления то он выдвигается сам. Если по каким-то причинам он не доедет - арсенал закроется. Появление конвоя - строго после каждого задания как описал сундук. В этом случае можно не вспоминать о нем если на сервере нет партизан и конвой поедет не через новое задание.

Убрать БК с гражданских сервисов давно просилось и логично оставить только ремонт и дозаправку топливом. Чтобы был смысл гнать технику в отдаленные от базы уголки можно добавить ком. отделения возможность вызова контейнера с БК для техники на парашюте (1 раз в час).

>не забирать машину сопровождения , а везти на базу хемт , который в последствии стане наградой в виде заказанной единицы техники

Вы технику и так маринуете уже ) Куда еще награду? Награды за конвой - открытый арсенал и открытые сервисы на базе, машина сопровождения. Этого более чем достаточно.

**Comment by SooNDooCK71** [comment]
у регулярной армии ни когда и ни где нет неограниченного технического , материального , человеческого ресурса . задачи ставятся и планируются исходя из возможности подразделений

**Comment by SooNDooCK71** [comment]
не не , теперь если человек хочет танк , то не просто нажимает кнопку и ждёт , а едет за ним и держит булки в кулаке , т.к могут сжеч по дороге

**Comment by SooNDooCK71** [comment]
и десять минут мало . скажем мы только закрыли точку на другом конце карты и без транспорта

**Comment by ToxaBes** [comment]
Вызов нарадной остается как есть потому что в развитии баз у партизан будет навык "взлом системы связи синих". Там несколько уровней, от "прокрасться к банкомату и очистить список наградной" до "вызвать наградную из списка". Сам банкомат для пущего веселья возможно перенесем внутрь базы синих.

Про 10мин написал для примера. Время подберем опытным путем но не более 15 мин.

**Comment by SooNDooCK71** [comment]
вотч догс ))))))

**Comment by SooNDooCK71** [comment]
во , придумал , если нет партизан на базе нажимаешь кнопку "вызвать конвой" и он едет сам

**Comment by ToxaBes** [comment]
>во , придумал , если нет партизан на базе нажимаешь кнопку "вызвать конвой" и он едет сам

подходит.

**Comment by SooNDooCK71** [comment]
блин , вот перечитал описание фракций , то зелёные не могут преодолеть языковой барьер , но сложной турецкой техникой и натовской техникой они пользоваться могут , то они простые местные жители , но при этом они смогут "взломать системы связи синих" геройски проникнув на "хорошо охраняемую базу" . не проще им подорвать конвой при помощи сву ? как это и происходит . а по поводу сложности маршрута : после пасадки синего в хемт(арсенал) хемт(награда) хемт(бензовоз) по маршруту активируются тригеры , нам их видеть не обязательно , маршрут можно на карте показать жирной синей полосой . и тригеры активируются на отсутствие синих , если конвой жив , но синие не в одном из тригеров появляется противник в районе последнего посещённого тригера . а маршрут нужен для создания задачи зелёным и , соответственно , усложнения задачи синим . а так любой желающий может прыгнуть в машину и погнать её по " занятой противником территории" .

**Comment by ToxaBes** [comment]
>сложной турецкой техникой и натовской техникой они пользоваться могут

Почему могут? Боевые вертолеты и самолеты они не могут использовать. Этого достаточно.
Синие тоже поголовно могут танки водить и ничего, это условности игры. Не вводить же из-за этого отдельные слоты мехводов.

>то они простые местные жители , но при этом они смогут "взломать системы связи синих"

Комментирование этого параграфа с приведением примеров из жизни нарушает законодательство нескольких стран. Просто прими на веру что это возможно. Я уж молчу про "угон" БПЛА прямо в воздухе подменой GPS сигнала направленными излучателями.

>геройски проникнув на "хорошо охраняемую базу"

Легко. Вьетнам. Нападение на базу ДаНанг как пример.

Короче. Синие не текущая армия какой-либо страны. Это форпост армии одной из глобальных фракций в **будущем**. Это обоснование для любой нестыковки с реальной жизнью, просто потому что это а) игра б) нет задачи делать реальную армию образа 2017г.

**Comment by SooNDooCK71** [comment]
ну это всё понятно , просто по сути , кроме начального ограничения по вооружению , зелёные по возможностям и навыкам не простые местные жители , которым делать не чего , а командос в отставке . и вот посмотрел награду зелёных ...фалкон !!!???)))))) по поводу респа в машинах . если сделать время ожидания обязательным , то можно убрать иконку "возрождение" ну или как она там и проблема решена . и кстати бисы таки сделали миноискатель ! как радар правда , не понял только как по лягушкам будет

**Comment by SooNDooCK71** [comment]
и тох , цель проникновения зелёных на базу и несовершенство её охраны приведёт к тому что часть игроков будет тупо заниматься охраной
