### ISSUE TITLE
После смерти игрока оружие дублируется

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#31]

**Comment by Horizon1959** [comment]
Вчера заметил что-то похожее. Медик после того, как поднял меня, получил мою пушку себе в инвентарь. У меня всё осталось на месте.

**Comment by Horizon1959** [comment]
Сегодня меня поднимали и оружие появлялось на земле, помимо моего комплекта.

**Comment by ToxaBes** [comment]
Покопал инет на эту тему, это косяк от BIS-ов, появился в одном из последних серверных обновлений. Вот у ребят та же самая проблема: https://github.com/ArmaLife/Altis/issues/526
Постараюсь пофиксить его в коде миссии, хоть это и баг армы, а не миссии.

**Comment by ToxaBes** [comment]
Вроде пофиксил, проверьте на сервере.
