### ISSUE TITLE
Захват пленных

### ISSUE THREAD

**Issue by SooNDooCK71** [ToxaBes/ADR-Spec-Ops#310]
добавить возможность захвата в плен . Для этого ,в первую очередь , необходимо сделать время ожидания респа обязательным . медик должен поднимать как и раньше . Работать должно так зелёные/синие атакуют , находят тела , "колесом мыши" захватывают в плен , "связывают" , выбрасывают gps , "одевают мешок" на голову и дальше переносят либо как раненого на плечах , либо в машине . Использование бага с перепаковкой магазинов становится серьёзным преступлением ))) . Дальше доставка на базу/тюрьму . Тюрьма для пленных работает так же как для "преступников" только без времени . В дальнейшем либо обмен пленными , либо обмен на снарягу , технику , бк и тд . Необходимо так же добавить возможность "отпустить" после этого боец переносится в тюрьму своей фракции и досиживает срок . Как вариан синие могут прочёсывать местность и вести самостоятельный поиск своего бойца . Если синие/зелёные были убиты при транспортировке пленного бойцы своей фракции могут освободить его либо с помощью медика , либо как медик , в любом случае совершается действие , запускающее время до респа . Так же нужно убрать "волшебство телепортации" базы зелёных . 1-нажал кнопку 2-работает рация, время идёт , вещи собираются 3-появляется газель и на карте появляются места возможного развёртывания баз 4-газель подъезжает к месту возможного развёртывания , нажимается кнопка 5-звучит рация , идёт время , вещи распаковываются . если по дороге машина уничтожена-потеря лута . зелёным тюрьму делать не нужну , пусть пленные сидят как на оп. нефть-матушка . И ГЛАВНОЕ ! зелёные это зелёные , не красно-зелёные , не зелёно-красные , форма своя ! снаряга любая . спасибо за внимание )

**Comment by ToxaBes** [comment]
>необходимо сделать время ожидания респа обязательным

Что делать если на сервере 1 игрок? Если 3 игрока и ни один из них не медик?

>3-появляется газель

Пока она едет - нет возможности ресаться (допустим ресаться на пассажирское в газель). Если он уничтожена - game over. Где тогда база партизан?

Получается дисбаланс: у зеленых есть КШМ, а у синих стационарный аванпост. Модель КШМ нам не подходит.

>И ГЛАВНОЕ ! зелёные это зелёные , не красно-зелёные , не зелёно-красные , форма своя ! 

Нет, зеленые это партизаны. Они могут носит что угодно кроме формы синих.

**Comment by SooNDooCK71** [comment]
написал же , игрок запускает действие , после которого идет время до респа . а если медик , то поднимает . ресанье в машинах это вообще от лукавого . а зелёные могут одеть форму красных броник гранатомётчика и спокойно жить после попадания гп в лоб . если газель уничтожена то база партизан спавница в произвольном месте , не самом удобном и пустая

**Comment by ToxaBes** [comment]
>написал же , игрок запускает действие , после которого идет время до респа 

Не понял сути. Опиши детальнее.

>ресанье в машинах это вообще от лукавого

Баг армы. 

>а зелёные могут одеть форму красных броник гранатомётчика и спокойно жить после попадания гп в лоб

А если умрут то останутся с пистолетом без налутанного снаряжения. Вполне нормальный баланс.

**Comment by ToxaBes** [comment]
Да и броник гранатометчика они могут снять только с синего. Не все его носят, еще меньше удается найти такой труп. Легче вайпера найти чем такой броник но не суть.

**Comment by SooNDooCK71** [comment]
так про умрут и остаются без снаряги ...что то знакомое , где то уже было ))) перевозимые вещи теряются , это логично . для этого и нужно выбирать безопасные маршруты и скрытные места , а не поближе к точке или базе . сморти , я чайник , поэтому объясняю как могу) когда боец убит/тяж.ранен у него идёт время до респа . когда тяж.раненого бояца(колесом мыши) захватывают в плен время останавливается . когда подходит свой и освобождает(колесом мыши) время запускается . если свой-медик , то поднять можно как раненого

**Comment by ToxaBes** [comment]
Перевозка базы зеленых делает из нее КШМ, я против этого. Также в этом случае базу партизан можно уничтожить дистанционно (БПЛА/Самолеты и т.д.). Я против этого. Уничтожение базы партизан (очистка всей награды и сохранения) происходит только "вручную", т.е. пехотой. Это как со спецоперациями "техника запрещена".

**Comment by ToxaBes** [comment]
По плен смысл понял. Захват тяжелораненого бойца можно сделать лечением. Те если зеленый полечил синего то синий в плену. 
Тут не понятно что делать когда синие например переловили всех зеленых.

**Comment by SooNDooCK71** [comment]
тогда при поиске пленного , когда синие будут рядом нажимается кнопка и происходит вошебство . а вот по уничтожению авиацей и бпа поле обновления радаров не всё так просто . у бпа вообще нет активного радара

**Comment by SooNDooCK71** [comment]
ты думаешь такое будет ??? ))))да и кнопку "отпустить " предлагал ,

**Comment by SooNDooCK71** [comment]
либо при захвате всех зелёных те досиживают срок , время запускается одновременно , а у синих какая нибудь награда

**Comment by ToxaBes** [comment]
>когда синие будут рядом нажимается кнопка и происходит вошебство

И ящик партизан сгорает. С ним сгорает вся награда и лут (заодно иобнуляется развитие баз у партизан). Пустой ящик появляется в другом месте и партизаны ресаются на нем.

>ты думаешь такое будет ??? ))))да и кнопку "отпустить " предлагал

Да, я думаю что будет "сезон охоты". Тут нужно будет еще думать.

**Comment by SooNDooCK71** [comment]
не не , подожди , ящик сгорает если его находят синие , а если синие ищут своего пленного и приближаются к базе зелёных . то есть они нашли место захвата в плен , грамотно рассудили и вычислили место нахождения пленного и подходят к базе , зелёные нажимают кнопку заранее , убегают огородами , а база телепортируется сама

**Comment by ToxaBes** [comment]
зачем партизанам приводит пленных на свою базу, они могут унести их в любое место.

**Comment by ToxaBes** [comment]
И как партизаны нажмут на кнопку если будут лежать "убитые" пока счетчик тикает (достаточно техникой отработать домик где база и никто никуда не убежит и не нажмет).

**Comment by ToxaBes** [comment]
C пленными нужно будет решить вопрос по отображению на GPS. Летает по карте самолет и смотрит на GPS, не появятся ли пленные...

**Comment by SooNDooCK71** [comment]
да , согласен , здесь засада

**Comment by SooNDooCK71** [comment]
а принудительно оключить отображение одного игрока нельзя ?

**Comment by ToxaBes** [comment]
я подумаю как это сделать, там больше вопрос по скорости работы.

**Comment by SooNDooCK71** [comment]
а если этого игрока делать временно зелёным ? ведь пока война мы ж не видим их на джпис

**Comment by ToxaBes** [comment]
>да чтож так трудно то ))) идёт зачистка местности скажем двумя группами синих в пешем порядке , зелёные их замечают , не вступают в бой , а просто нажимают кнопку и убегают , так же может быть ?

Если партизаны не дураки то так и должно быть.

Синие не ищут базы партизан пешком. Они вычисляют это место по-тихому (наблюдая откуда партизаны выезжают и тд) - для этого  у них есть все средства разведки. После определения здания где находится база выдвигается группа зачистки. пехота под прикрытием тяж техники. Техника сносит все что есть и валит всех партизан. Пока они лежат пехота уничтожает ящик и берет в плен  тех кто остался.

**Comment by ToxaBes** [comment]
>а если этого игрока делать временно зелёным 

ограничения армы. Потом ему придется перезаходить. Лучше с GPS решать.

**Comment by 12st** [comment]
> C пленными нужно будет решить вопрос по отображению на GPS. Летает по карте самолет и смотрит на GPS, не появятся ли  пленные...

На скоростях которых летают самолёты пехота на GPS не отображается.

**Comment by ToxaBes** [comment]
Ок, не смолет, а БПЛА/Дартеры/мимо проезжающая машина синих и тд. Смысл думаю понятен.

**Comment by SooNDooCK71** [comment]
на самолётах нет , а вот тупо катаясь на технике можно легко найти . тоже не правильно

**Comment by SooNDooCK71** [comment]
только дартеры и машины , грейхоки меньше 90 не летают , и я тоже пехоту не наблюдаю

**Comment by ToxaBes** [comment]
есть еще одна проблема, рано или поздно синие додумаются до следующего:
1. Самолет летает, или пушка стреляет или еще что.
2. Пленный это слышит (черный экран можно сделать а вот звуки убрать - не уверен)
3. По тимспику говорит - слышал как самолет надо мной продетел/танк рядом бахнул.

Все, пленный найден.

**Comment by SooNDooCK71** [comment]
ну по тому как работают звуки в арме это легко не будет , а тут давай представим другое волшебство , скажем синий нашел телефон . либо спрятал его в жопе . всё правдоподобнее чем телепорт базы .

**Comment by ToxaBes** [comment]
Нет, зеленые проверяют все потаенные места )
Нужно будет со звуками что-то думать.

**Comment by SooNDooCK71** [comment]
а нельзя ему что нибудь включать . скажем ту же радейку при переносе базы , вобщем какие нибудь помехи создавать

**Comment by ToxaBes** [comment]
Буду думать что можно сделать. Вообще, тимспик и пленные несовместимы.

**Comment by SooNDooCK71** [comment]
в любом случае пленный это хорошая замануха для организованной засады с минами и ещё чем нибудь

**Comment by Horizon1959** [comment]
Зачем такие свистоперделки?

**Comment by ToxaBes** [comment]
Чтобы ты чуствовал боль и унижения не только при жизни (на сервере) но и после "смерти".

**Comment by Horizon1959** [comment]
Это пахнет нетрадиционным геймплеем на RF. Кто с включённым респавном будет заниматься таким мазохизмом? Это же не командир стороны какой-нибудь, тут тусуются или ниндзя или джигиты.

Хотя я думаю, что Банка мог бы одеться в свой костюм и ...

**Comment by ToxaBes** [comment]
После смерти есть 300 сек до принудительного возрождения (у партизан 150 сек). Сейчас в любой момент это времени можно нажать "на базу" и возродиться. Идея в том чтобы кнопка "на базу" появлялась только после (например) 120 сек. Т.е. 120 сек ты гарантрованно лежишь, потом можешь ресаться на базу либо ждать пока поднимут.

**Comment by ToxaBes** [comment]
@Horizon1959 - кажется ты начал забывать суть сервера:

![tg1](https://user-images.githubusercontent.com/3309152/29365807-e1eb28c6-82a0-11e7-85d9-32b1b51423ad.png)

**Comment by Horizon1959** [comment]
И пленного тогда переодевать для сессий:

![107410_20170816204852_1](https://user-images.githubusercontent.com/17685328/29377493-a4dc3712-82c4-11e7-99e1-44634dbc8240.png)

**Comment by SooNDooCK71** [comment]
ай ай ай , я забыл , появились , побежали , умерли , реснулись , побежали умерли ....так 15 раз , выполнили задачу-тактика...мать её!!!))))))))))))

**Comment by Horizon1959** [comment]
@SooNDooCK71 именно, зерг-раш.

**Comment by SooNDooCK71** [comment]
именно батла , фпс 100 . багов меньше , смысл играть варму ? к тому же в условиях не указанно как проходить точку , за какое время , при поддержке чего , авиации , арты , тяж бронетехники . а если честно ни одна из миссий и ни один из способов которых я видел не соответствуют названию сервера , нет спец опс

**Comment by Horizon1959** [comment]
Арма имеет ряд ключевых механик, отличающих её от батлфилдов, поэтому настоящим олдовым людям после армы уже скучно в батлфилдах. 

По тактике  - людей приведи, будут тебе спек опсы. Текущее разграничение классов делалось под онлайн не меньше 10-ти человек и создавалось всё это вынуждения действовать сообща. Сейчас для тактических действий банально не хватает стабильного онлайна.

Тактика родилась для того, чтобы при выполнении задачи сберечь свою жизнь и жизнь товарищей. Если жизни у тебя не ограничены, то и смысла использовать тактику нет. В свою очередь это и порождает зерг-раш и позволяет использовать методы наскока джигитов. Если же ограничить спавн, то можно будет сразу выходить с сервака. Патовая ситуация.

**Comment by SooNDooCK71** [comment]
зерг-раш это голимая бацила , чума , зараза , которая портит весь геймплэй армы . отсутсвие онлайн партнёров -да ! на все сто согласен и спорить будет глупо . но это не значит что нужно делать из недоработанного сервака армы батлу с расширенными возможностями . нуджно усложнять задачу исходя из возможностей текущего онлайна , а сходить покурить , попить , поесть ..передёрнуть из-за того что ты глупо погиб , на мой взгляд , не является ограничением , возможность попасть в плен из-за "самоотверженных" деиствий (зерг-раш) не является ограничением , неоходимость объединяться для сохранения арсенала не является ограничением , это всё побуждает к командной игре минимальным онлайном . а что же будет когда боты будут реально учиться ? когда зерг-раш станет прямой тупостью ? сейчас это просто фарт

**Comment by ToxaBes** [comment]
Нужно будет делать несколько вариантов состояния бойца:
1. Жив - 100% здоровья.
2. Легко ранен.
3. Тяжело ранен, лежит без движения, есть возможность попасть в плен или через 120 сек нажать возрождение.
4. Смертельно ранен. В этом случае боец сразу возрождается на базу (даже если есть аванпост).

Тут и в плен можно будет брать и достреливать....

**Comment by Horizon1959** [comment]
@toxabes в модной стильной молодёжной системе от BIS при сильных повреждениях игрок сразу отправляется в меню респавном, а поднять его можно только в течении 60 секунд. Вполне неплохая тема, но там используются модные действия с удерживанием пробела.

**Comment by ToxaBes** [comment]
>при сильных повреждениях игрок сразу отправляется в меню c респавном

будет сразу на базу

>а поднять его можно только в течении 60 секунд

время "истечения кровью" регулируются

>но там используются модные действия с удерживанием пробела.

это плюс т.к. будет возможность быстро прервать операцию.

**Comment by SooNDooCK71** [comment]
тох , а можно так ?:                                                                                                                                                1 лёгкое ранение , врезался на машине , упал с камней                                                                                     2 ранение средней степени тяжести (если вспомнишь , мы играли кооператив-миссию , за зелёных , против греков , там еще вышка большая была , так вот там при таком ранении экран начинал краснеть ,"глаза кровью заливает" , сильно шатает и нельзя вести прицельный огонь , можно доработать так : если при таком ранении в течении 60 сек не перебинтоваться ,"остановить кровь" , ранение переходит в следующую фазу - а именно потеря крови и как следствие потеря сознания , то есть то к чему мы привыкли , идеально ещё бы при ранении в обе ноги передвигаться только ползком , пока не перебинтоваться )                                                                                                                     3 тяжёлое ранение - мгновенная потеря сознания , красный пульсирующий экран , громкий звук пульса на заднем плане , так кстати для пленных можно и оставить , что бы не слышать происходящее вокруг , если , повторюсь , делать ожидание респа обязательным , то убрать иконку "возрождение" и тогда помочь сможет только медик , через транспорт не поднять .                                    4 смерть -либо критический урон (12,7 в голову , сожгли в танке , разбился на самолёте и тд) но при критическом уроне время ожидание так же должно быть обязательным . 300 сек это и не много и не мало .                                                                                                                                                                я просто помню момент когда в с кейзом играли за зелёных , я шёл по джунглям 700-800 метров до кп , так вот пока я дошёл вы успели 4 раза приехать туда , умереть и вернуться , это не нормально . но это опять тема о совместном задании противоборствующих  сторон

**Comment by ToxaBes** [comment]
Что-то подобное и будет с отличием в деталях т.к. мы буем использовать надстройку над стандартной "расширенной" системой лечения/возрождения армы.

**Comment by SooNDooCK71** [comment]
и , кстати , тох , я перерыл всю хронику вьетнамской войны , на "ДАНАНГ" нападения не было вообще , были на падения на различные авио в вертолётные базы , но совершались они целыми соединениями

**Comment by ToxaBes** [comment]
> я перерыл всю хронику вьетнамской войны , на "ДАНАНГ" нападения не было вообще , были на падения на различные авио в вертолётные базы , но совершались они целыми соединениями

Авиабаза "Дананг" (Da Nang) была **одним из основных пунктов базирования сил специальных операций США во время войны во Въетнаме**. Т.е. на месте обычного аэродрома сделали форпост куда прибывало подкрепление и тд. Ничего не напоминает? )

На русском ты вряд ли что найдешь, максимум вот: http://www.webpark.ru/comment/vetnamskaya-voyna

Оттуда: (подпись к фотографии) Сержант Алекс Адамс (с телефоном) и Рон Хупер на наблюдательном пункте возле авиабазы Дананг. 1 ноября 1965 года. **За неделю до этого вьетконговцы (партизаны) совершили нападение на базу и уничтожили около двадцати вертолетов.**

На эту авиабазу несколько раз серьезно нападали партизаны. На английском есть воспоминания очевидцев о другом нападении на эту базу: http://366th.blogspot.com/2012/01/attack-of-july-15-1967-on-danang.html
Если вкратце то партизаны обстреляли базу всем "тяжелым" что у них было, от гранатометов и минометов до "Катюш". Результат: https://www.youtube.com/watch?v=uo7c6rzwHIM

Также помню что читал воспоминания бойца который был на охранной вышке в ночь когда партизаны пошли в атаку (обстрел орудиями "с колес" и атака пехотой). Он выжил т.к. вырубил прожектор на своей вышке. Партизан  в итоге отогнали с базы артой и пулметами.

**Comment by ToxaBes** [comment]
Кстати, по поводу запрета переодевания в форму синих. В реальной жизни: http://www.bbc.com/russian/news-39675226

**Comment by ToxaBes** [comment]
Вообще, на тему Дананга, смежных (авиа)баз и набегов партизан на русском хорошо написано тут: http://www.bratishka.ru/archiv/2012/06/2012_6_14.php

**Comment by ToxaBes** [comment]
По поводу плена: я пока не нашел нормальных играбельных вариантов чтобы это было интересно:
а) самому пленному
б) исключало возможность пленного сообщать о том где он находится своей стороне

Если кто видел нормальный пример в какой-либо миссии - отпишитесь.
Все до чего додумался это не тащить пленных на базу, а сделать небольшой концентрационный лагерь (я знал что рано или поздно мы перейдем и на эту дрянь...). 
У синих это клетка-гауптвахта. У зеленых рандомное глухое место с похожей клеткой и парой ботов охранников. При захвате в плен (процесс описан выше - лечение или подход в плотную) у игрока пропадает все кроме формы и он оказывается в лагере.
Освободить его можно подойдя к клетке и нажав "освободить" - в этом случае у синих срабатывает сирена и идет сообщение о побеге. У зеленых просто сообщение.
Важное отличие - синий может попробовать сбежать (пока не придумал как). Никаких мешков на голову и т.д., все видно. Время нахождения в клетке 15-20 мин макс. Если не спасли за это время - он огибает и возрождается на своей базе (для случая когда одного партизана поймали в клетку и его некому спасти). Как-то так.

**Comment by ToxaBes** [comment]
В рамках текущих возможностей Армы не получится сделать так чтобы пленному было "интересно" сидеть 2 часа ждать освобождения. Тема закрыта.
