### ISSUE TITLE
Не даёт загрузить пресет из арменала

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#311]
Который раз замечаю, что на алтисе не горит кнопка "загрузить" в арсенале. Опытным путём выяснил, что это не работает, даже если снять с себя вообще всё снаряжение. Началось с недавних пор, при чём все мои старые комплекты работают.

**Comment by ToxaBes** [comment]
Началось это больше полугода назад с очередным обновлением армы. Замечено что баг возникает часто у тех кто использует моды. Появляется и исчезает сам по себе. На стороне миссии не пофиксить.

**Comment by Horizon1959** [comment]
@ToxaBes Ооооке, понял. Но у меня моды нигде не прописаны, на TvT я их подрубаю отдельно через ArmA Sync. Вообщем всё изолированно.

**Comment by ToxaBes** [comment]
Не изолированно, т.к. все на одном профиле внутри армы.
