### ISSUE TITLE
Оружие за спину ( holster )

### ISSUE THREAD

**Issue by Aveletsky** [ToxaBes/ADR-Spec-Ops#312]
Добавить кастомную комбинацию (клавишу) или контекстный пункт меню-спрятать оружие за спину.
https://www.youtube.com/watch?v=tkHeHmYTKyE для основного оружия
https://www.youtube.com/watch?v=JOl12VR9Db0 для пистолета

**Comment by Aveletsky** [comment]
http://www.armaholic.com/page.php?id=30571

**Comment by ToxaBes** [comment]
есть дублирование меню. поправлю позже.

**Comment by ToxaBes** [comment]
Поправил дублирование меню. Для пистолетов не делал т.к. для синих это не актуально, а у партизан практически никогда нет кобуры куда прятать пистолет. Пистолет можно убирать в рюкзак, пунктов меню и так слишком много.
