### ISSUE TITLE
Беруши доступны всегда

### ISSUE THREAD

**Issue by PlintuZz** [ToxaBes/ADR-Spec-Ops#313]
Хотелось бы доступность берушей всегда(как на картах westaland), а не только в технике.
К примеру на респауне "Оспри" очень сильно шумит, или когда пулеметчик стреляет тоже иногда хочется их вставить.

**Comment by ToxaBes** [comment]
Попробую сделать доступными везде.

**Comment by ToxaBes** [comment]
Готово.

**Comment by PlintuZz** [comment]
проверил работает, а нельзя ли сделать это не на прокрутку колесом а на горячие клавиши? к примеру 
H убрать оружие а END или WIN вставить беруши

**Comment by ToxaBes** [comment]
Дело в том что это плохая практика - у игроков может быть какой угодно набор используемых клавиш в игре. Переназначать их в миссии можно, но я использую рекомендуемый БИСами подход - через меню действий.
