### ISSUE TITLE
Медицинский аванпост

### ISSUE THREAD

**Issue by 12st** [ToxaBes/ADR-Spec-Ops#314]
Просили ввести в наградную CSAT'овский медицинский грузовик. Предлагаю альтернативу в виде медицинского аванпоста где и будет стоять эта машина. Ресается на основе с определённым шансом(25-50).

**Comment by ToxaBes** [comment]
Можно сделать так:
* мед пост,  (2 варианта, P=0.3)
* пост перезарядки техники (2 варианта, P=0.5)

Ремонтные и топливный посты в районе активных БД не ставим. Перезарядку техники добавляем т.к. с сервисов техники перезарядку уберем, оставим только ремонт и заправку.

**Comment by 12st** [comment]
Так даже лучше.

**Comment by ToxaBes** [comment]
Мед пост добавил. Перезарядку не стал добавлять т.к. сводит на нет грядущие изменения по сервисам техники.
