### ISSUE TITLE
Изменения по сервису техники

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#319]
У всех сервисов техники кроме сервиса на базе синих убрать возможность перезарядки БК. Только заправка и ремонт.

**Comment by Aveletsky** [comment]
Протестую. К чему такая фича?

**Comment by ToxaBes** [comment]
Покажи мне на реальной заправке БК к бронетехнике.

**Comment by Noart537** [comment]
Как вариант, сделать пару мест подходящих по смыслу, полевой ремонтный лагерь или лагерь с боеприпасами. Где будет ограниченное кол-во бк и ремонта (на 1-2 загрузки). А пополняться будет со временем или по приезду машинки с бк.

**Comment by ToxaBes** [comment]
У нас уже есть машина перезарядки на базе. Ее не используют вообще т.к. нет смысла, ведь есть же заправки. Если убрать из заправок БК то игроки начнут использовать эту машину - гонять ее с базы для зарядки своей техники и пригонять обратно чтобы зарядить на сервисе на базе. В итоге получается проводка конвоя туда-обратно, что более реалистично и порадует партизан.
