### ISSUE TITLE
Изменения по загробному миру

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#320]
Павших можно "достреливать", в этом случае он сразу отправляется на базу (выстрелил - противник лег, пострелял в него еще несколько раз - он автоматом реснулся на базу).

**Comment by Horizon1959** [comment]
Боты будут добивать раненых?

**Comment by ToxaBes** [comment]
>Боты будут добивать раненых?

Иногда они стреляют даже если игрок упал. В этом случае - да, будут достреливать. В большинстве случаев - не будут.

**Comment by ToxaBes** [comment]
Тесты показали что после поражения бойца стрелковым оружием в 90% него попадает еще 1-2 пули (критический урон). При поражении пулеметом танка/марида/ифрита - 4-5 пуль. Про попадания зенитки по пехоте даже говорить не хочется. В итоге недостреленными остаются только упавшие от снайперского огня/одиночном выстрела и подорвавшиеся на минах. 
Нет смысла вводить. Задача отклонена.
