### ISSUE TITLE
Добавить БПЛА "Пеликан"

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#321]
Предлагаю добавить в арсенал синих новый грузовой БПЛА "Пеликан". Эта хреновина представляет из себя аналог БПЛА "Дартер", но вместо модуля с оптикой и лазером, там установлен грузовой контейнер. Контейнер вмещает в себя 15 магазинов STANAG 5.56. 

Для того, чтобы не было злоупотребления этими дронами, предлагаю ограничить их количество от двух до четырёх штук. Если же добавить ограничение радиуса по аналогии с дартером, то беспилотник потеряет смысл, т.к. его придётся сопровождать на машине, куда помещается в разы больше. 

Основная задача - доставка мелких грузов. Экстренно необходимые жёлтые пакеты, дымы, потерянные/забытые инструменты или аптечки. 

Можно ли его добавить в арсенал, чтобы собрать и наполнить могли люди с базы, а не только инженер?

**Comment by 12st** [comment]
Также можно добавить БПЛА для разминирования.

**Comment by Horizon1959** [comment]
@12st да в нём особо нужды нет. Да и гражданский он, т.е. будет дополнительный гемор с высовыванием-всовыванием ботов в него. Вот нужда в пеликане есть, т.к. грузы нам никто не скидывает.

**Comment by ToxaBes** [comment]
В арсенал они добавлены не буду. Возможно я буду их использовать в качестве некоторых действий доступных командиру отделений (вызов мед. бпла). Пока не уверен что это необходимо.

**Comment by Horizon1959** [comment]
@ToxaBes почему бы и не добавить? Обзора они не дают, лазером не наводят, сбиваются первым агентом Смитом. Нужда иногда есть, ведь у нас нет людей, готовых заниматься мелкой логистикой. Супер линий поставок они наладить тоже не могут, т.к. с базы до Кавалы пеликан летит от 10-ти минут в одну сторону. Зато прикинь как людям приятно, когда сгоревшие инструменты могут прилететь через 10 минут, и не придётся их муторно искать на жмурах, как лут в таркове.

А вот медицинский дрон лучше не добавлять, это передвижная аптечка, частично снимая нужду в медиках.

**Comment by ToxaBes** [comment]
Я планирую использовать пеликаны немного в другом варианте.

**Comment by Horizon1959** [comment]
@ToxaBes В каком?

**Comment by ToxaBes** [comment]
Доставка командирами обеих сторон определенных наборов в указанную точку в автоматическом режиме. Грубо говоря, поддержа > вызвать пеликан > (набор). Открывается карта и по щелчку мыши дартер с базы летит в нудную точку с автоматической посадкой.

**Comment by ToxaBes** [comment]
У партизан возможно один из наборов будет "Пеликан смерти" с взрывчаткой внутри и возможностью подрыва.

**Comment by Horizon1959** [comment]
@ToxaBes это всё конечно круто, но сколько наборов придётся создавать, чтобы он мог выполнять все логистические задачи? Не превратится ли и так перегруженное контекстное меню в сложную древовидную структуру? Почему бы не сделать оба варианта - вызов пеликана командира с готовым снаряжением и пару пустых отдать на управление оператору?

Пеликан с взрвчаткой вполне ожидаем, тут ничего удивительного:)

**Comment by ToxaBes** [comment]
Будет не больше 3х наборов которые будут не сразу, а в развитии баз. Никто не будет гонять эти беспилотники по карте, т.к. чтобы его загрузить нужно быть на базе. И нет задачи повесить на него всю логистику.

**Comment by Horizon1959** [comment]
@ToxaBes Всю логистику на него не повесишь по причине уязвимости, низкой скорости доставки и малого грузового отсека. А грузить его на базе вполне будут. Чего там грузить, он вмещает 12 магазинов под MX.

Когда вообще ждать развитие баз? А то про него разговоров столько, сколько про свой end game.

**Comment by ToxaBes** [comment]
Когда вообще ждать развитие баз? 

В процессе. Базовые вещи готовы (сохранение уровня баз по картам/фракциям между рестартами). Развитие баз - огромный кусок работ который делается когда у меня есть время на это. Ждать его нужно в этом году )

**Comment by Horizon1959** [comment]
Ну валяй, ждём как ты всё это реализуешь. А то офигенный оригинальный контент в арме есть, а у тебя на сервере нет. Даже в TvT добавляют DLC'шное оружие и машины.

**Comment by ToxaBes** [comment]
Пеликан - говно без задач, как по мне. Из всего стоящего добавили автоукладчик мин и починили миноискатель. Оружия нового - нет. Новый фургон добавлен партизанами и гражданским. Не знаю какой офигительный контент ты имеешь в виду...

**Comment by Horizon1959** [comment]
Пеликан выполняет задачи мелкой логистики. Это давно назрело у гражданских и очень актуально у военных (в нашем случае синих). Мелкий пиздюк, который может привезти инструменты (в кампании забытые инструменты привозит именно он) или аптечку давно напрашивался в игру. Вот тебе несколько простых решений частых задач синих:

1. Из-за идиотских багов армы или кипиша, пропал рюкзак с инструментами/медициной. Вместо нудного и не антуражного мародёрства, прилетает жужжалка и счастливый специалист забирает своё добро в минимальной комплектации. Не надо кому-то перезаходить за пилота, чтобы ради одного предмета везти огромный ящик на тросах с возможностью его потерять из-за багов или вездесущих ПВОшников. Командир может приберечь ящик со снарягой для более подходящего случая. Хоть какая-то возможность не заниматься собирательством и лутанием в  условиях низкого онлайна.

2. Бойцы из последних сил дожимают кого-то или держат позицию, заканчиваются патроны. Ящик командира как назло улетел в неизвестном направлении, а пилота с контейнером сбили. Внезапно садится летун, которого отправил оператор с другого края поля боя, и довольные парни спокойно пополняют свой боекомплект, ждут основной подмоги.

3. Вместо того, чтобы нагружать себя 14-ю магазинами, дымами, взрывчаткой и прочим тяжёлым скарбом (спроси любого, так делают, т.к. не надеются на поддержку), бойцы могут одеться полегче, бегать дольше и при прицеливании не трястись как эпилептики. Игроки точно будут знать, что их ждут поставки от оператора.

4. Мелкий летун не обязательно может лететь с базы. Пилотам достаточно отвозить большой контейнер с припасами/машину с ништяками не только на аванпост, но и в другие безопасные места у поля боя (прямо на поле боя контейнер доставить практически не реально, т.к. агенты Смиты сразу сбивают вертолёт). В дальнейшем оператор принимает  груз и с помощью дронов начинает распределять грузы всем нуждающимся. В таком случае рисуется абсолютно новая цепочка действий и новые элементы геймплея - набег на логистический пункт, охрана логистического пункта, работа оператора поддержки с бойцами на линии огня, взаимодействия и координация с пилотами. В добавок инженер точно будет тусить у поля боя, что собственно и требуется от него. 

И это я только на вскидку придумал. Сейчас людям надоедают однообразные цепочки взаимодействия типа отстрела ботов или развоза пехоты вертолётами. Тут есть вариант родить абсолютно новые схемы и возможности, попутно никого не ущемляя и не уничтожая предыдущие устоявшиеся линии игры.

Что касается контента - помимо пеликана есть ещё дроны для медицины и разминирования. Бандосам можно всякие строительные шлемы и бронежилеты добавить. Автоукладчик запилил в арсенал или лишишь @SooNDooCK71 счастья?

**Comment by ToxaBes** [comment]
Могу добавить пустой пеликан (сами заполняйте на базе чем нужно), ограничений по дальности управления у него не будет (он больше чем AR-2 - значит и передатчика буде хватать). Ограничение по количеству будет не больше 2х шт одновременно.

Автоукладчик добавлю позже.

**Comment by Horizon1959** [comment]
@ToxaBes Давай попробуем двух пеликанов, может я всё это у себя в влажных мечтах придумал и на самом деле это говно без задач:) Спасибо!

**Comment by ToxaBes** [comment]
* Добавлено по 2 пеликана на синим и зеленым, вызывается через меню, ограничений на дальность управления - нет
* Миноискатель доступен для использования только инженерам
* В арсенал синих добавлен автоматический укладчик пп мин (зеленым организуем какую-нибудь награду позже)

**Comment by Horizon1959** [comment]
Отлично, благодарю!
