### ISSUE TITLE
Добавить в арсенал синих миноискатель

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#322]
В связи с выходом DLC "Сапёр", миноискатель вновь обрёл смысл. На данный момент его нет в арсенале и надо бы его добавить.

**Comment by ToxaBes** [comment]
В арсенал добавлю, но брать его сможет только инженер.

**Comment by Horizon1959** [comment]
@ToxaBes ок, спасибо

**Comment by ToxaBes** [comment]
Оказалось, что он там всегда был. А не показывается потому что баг, теперь официальный: https://feedback.bistudio.com/T126092

**Comment by Horizon1959** [comment]
![default](https://user-images.githubusercontent.com/17685328/30307732-141e21fc-9789-11e7-8e34-882592fbee58.gif)
