### ISSUE TITLE
Нужно больше минных полей

### ISSUE THREAD

**Issue by Horizon1959** [ToxaBes/ADR-Spec-Ops#324]
С выходом DLC "Сапёр" наконец-то сделали что-то похожее на миноискатель. Предлагаю делать модные минные поля в зонах боевых действий. Какие-нибудь важные объекты минировать или улицы. Только поменьше прыгающих мин, т.к. они сильно багованы.

Идея нармас или в топку?

**Comment by 12st** [comment]
Боты будут сливаться.

**Comment by Horizon1959** [comment]
Агенты Смиты сейчас не видят мины? Не обмениваются данными, как игроки?

**Comment by 12st** [comment]
Это ж арма,боты всё равно будут по минам бегать.

**Comment by Horizon1959** [comment]
Эх...

**Comment by ToxaBes** [comment]
Планы по минным полям есть, но не в ближайшем будущем.

**Comment by Horizon1959** [comment]
Ок.
