### ISSUE TITLE
Разрушения на карте

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#327]
Нужно прикрутить восстановление разрушенных зданий и прочих объектов после завершения миссии. Это одна из причин утечки памяти на клиентах.

**Comment by Horizon1959** [comment]
![default](https://user-images.githubusercontent.com/17685328/33432646-df14b616-d5e9-11e7-86f4-cdbbeb8994ba.gif)

**Comment by ToxaBes** [comment]
И вишенка на торте. Если сервер запустить с параметром -noLogs (не писать ошибки в логи), то он живет до падения в среднем в 2 раза дольше...

**Comment by Horizon1959** [comment]
Фантастика.
