### ISSUE TITLE
Барьеры и колючка вокруг вышки и башни кп

### ISSUE THREAD

**Issue by malashin** [ToxaBes/ADR-Spec-Ops#34]
Барьер и колючка которые появляются вокруг вышки, которую нужно взорвать, и башни командного пункта все повернуты в одном направлении. Скорее всего ориентация этих объектов не указывается при создании.

**Comment by ToxaBes** [comment]
Так и задумано. У армы большие проблемы с вычислением координат через BIS_fnc_relPos (погрешность до ~20см), нормально работает только с нулевым азимутом (расположение мебели внутри бункера и тд). Поэтому оставил нулевой азимут. На игру никак не влияет, а внутренние объекты расположены там где должны быть. Возможно в будущем добавлю рандомный азимут, пока не критично.
