### ISSUE TITLE
Заменить картинку миссии

### ISSUE THREAD

**Issue by malashin** [ToxaBes/ADR-Spec-Ops#35]
Если есть идеи или пожелания, готов выслушать.

Как я понимаю, нужно изобразить группу спецназа в боевой ситуации или при высадке из транспорта. Продемонстрировать командную игру.

**Comment by Horizon1959** [comment]
Лучше без спецназа. Нужны взрывы, бронетехника и огонь.

**Comment by Noart537** [comment]
Куски ботов намотанных на гусеницы. =)

**Comment by Horizon1959** [comment]
@Noart537 это уже брутал дет.

**Comment by ToxaBes** [comment]
Картинку менять не нужно, она меня устраивает. Достаточно прилепить текст "игровой портал tehgam.com" примерно так как на ADR: Blue Shark (чтобы не закрывало особо основную зеленую часть и оружие), возможно добавить чуть "мазков" с одной из сторон (не много). Сама картинка очень органично смотрится на фоне экрана загрузки (зеленые оттенки карты острова), нужно это сохранить. Никакого огня, взрывов и тд, нужен спокойный вариант (разведчик идет по лесу).

**Comment by Horizon1959** [comment]
@ToxaBes ну хотя бы не колхозную винтовку можно запилить? М14 там вообще такая древняя, как СВТ сейчас например.

**Comment by ToxaBes** [comment]
Нет, эта винтовка там потому что подходит по гамме к остальной картинке. На TEHGAM 1 никто не высаживается из транспорта по огнем (я пока не видел). Чаще высаживаются за зоной и не привлекая внимания стараются войти в нее,чтобы пройти к командному пункту/вышке. Картинка это более-менее отражает.

**Comment by Noart537** [comment]
Боец стоит на высоте, смотрит в бинокль. Время сумерки. Недалеко от него в присяди сидит боец, с опущенным оружием, смотрит в том-же направлении. В дали на заднем фоне город.

**Comment by ToxaBes** [comment]
>Боец стоит на высоте, смотрит в бинокль. Время сумерки. Недалеко от него в присяди сидит боец, с опущенным оружием, смотрит в том-же направлении. В дали на заднем фоне город.

Вот это очень интересный вариант, только нужно постараться оставить все в той же гамме, серо-зеленой (серое - вечернее время, зеленое - елки). Т.е. или дерево рядом или около города леса. За основу можно взять Зарос - там 2 больших холма с елками. Бойцы в MTP-расцветке формы. Как-то так.

**Comment by Horizon1959** [comment]
@Noart537 @ToxaBes и чтоб пушки у них были из семейства MX или что-то вроде Mk-1 EMR в соответствующих цветах. Ну М14 здесь реально не фракционная, т.к. разработчики пилили её для партизан.

**Comment by ToxaBes** [comment]
MX, MK-1 EMR, MAR-10 - подходит. Все равно новая картинка не будет отражать то что миссия от первого лица, в этом случае MK-14 не нужен т.к. на картинке оружие будет мелким.

**Comment by malashin** [comment]
![img](http://i.imgur.com/5gN1NIy.jpg)

**Comment by Horizon1959** [comment]
@malashin 
![default](https://cloud.githubusercontent.com/assets/17685328/14429940/3168211e-0008-11e6-98e3-78060ae95d50.jpg)

**Comment by ToxaBes** [comment]
Есть несколько предложений:
![example](https://cloud.githubusercontent.com/assets/3309152/14430349/e0347d2c-0009-11e6-9eb8-3c581a015b07.png)

сорри за качество.

**Comment by malashin** [comment]
Под мазками ты, что подразумеваешь?

**Comment by ToxaBes** [comment]
Мазки это различные кисти/эффекты:
![1](https://cloud.githubusercontent.com/assets/3309152/14431492/97d63a34-000e-11e6-993c-3e7a16880c94.jpg)
![2](https://cloud.githubusercontent.com/assets/3309152/14431493/97d80134-000e-11e6-9909-d417873c18ac.jpg)
![3](https://cloud.githubusercontent.com/assets/3309152/14431494/97d9019c-000e-11e6-97fe-a8780a143619.png)

В данном случае это просто пример, "огонь" и "разлитая краска" тут не подходят, надо подумать какой эффект будет выглядеть "спокойно".

**Comment by malashin** [comment]
![img](http://i.imgur.com/qPyVhid.jpg)

**Comment by ToxaBes** [comment]
То что надо! Огромное спасибо, сейчас применю в репозитарий, на сервер появится с ближайшим обновлением.

**Comment by malashin** [comment]
![img](http://i.imgur.com/nVoKlF8.jpg)
Еще чуть-чуть подправил. Силуэты лучше читаются.

**Comment by ToxaBes** [comment]
Применил
![20160411184405_1](https://cloud.githubusercontent.com/assets/3309152/14433113/aae072a0-0015-11e6-82c3-8db8370a361a.jpg)

**Comment by Horizon1959** [comment]
![default](https://cloud.githubusercontent.com/assets/17685328/14433563/693d0d16-0017-11e6-8866-25e9ac452d17.jpg)
