### ISSUE TITLE
Респавн внутри медецинского хемта

### ISSUE THREAD

**Issue by 12st** [ToxaBes/ADR-Spec-Ops#36]
Сегодня играя за пилота появился внутри хемта который стоит в ангаре.
![20160411133653_1](https://cloud.githubusercontent.com/assets/18305023/14424647/ec7bc03c-ffea-11e5-84f0-7022dd92c2f2.jpg)

**Comment by ToxaBes** [comment]
Похоже что у Армы точность респавна +/- 5м. Нужно будет перенести позиции возрождения еще больше вглубь ангара и постараться отключить рандомизацию по координатам.

**Comment by Noart537** [comment]
fn_respawnPilot.sqf

**Comment by ToxaBes** [comment]
Ближайший к хемту маркер респавна пилота находится на рсстоянии ~8м  )

**Comment by Noart537** [comment]
Тут хеммит не который стоит рядом с респом, а отдельный хеммит загнали прямо на маркер респавна.

**Comment by ToxaBes** [comment]
Вот из-за [этой](https://github.com/ToxaBes/ADR-Spec-Ops/blob/master/co30_ADR_Spec_Ops.Altis/functions/fn_respawnPilot.sqf#L14) строки все происходит:

```sqf
player setPosATL [(((_pos select 0) + random 3) - random 6), (((_pos select 1) + random 3) - random 6), 0];
```

т.е. +/- 6 метров. Плюс к этому накладывается рандомизация армы (BIS_enableRandomization) дает еще пару метров. Получаем как раз примерно 8 метров чтобы влететь в хемт.

**Comment by Noart537** [comment]
хм. за все время никогда не летал так далеко =) обычно всегда в ангаре.

**Comment by ToxaBes** [comment]
Стоп, на респавн пилотов загнали второй хемт?

**Comment by Noart537** [comment]
ага

**Comment by 12st** [comment]
Респавн выглядел вот так
![20160411140005_1](https://cloud.githubusercontent.com/assets/18305023/14425156/cabe6d0c-ffed-11e5-9bac-f9f75d9a34df.jpg)

**Comment by Noart537** [comment]
Этот хэммит, который стоял у ящиков? Или новый загнали.

**Comment by 12st** [comment]
Он там стоит по умолчанию.

**Comment by ToxaBes** [comment]
А ну второго хемта нет, значит я изначально правильно понял - рандом в скрипте складывается с рандомом самой армы. Добавлю проверку места перед перемещением игрока, это пофиксит и тот хемт который стоит и любую другую технику которую подгонят.

**Comment by Noart537** [comment]
Ясно) не знал что ты там интеръер поменял =)

**Comment by ToxaBes** [comment]
Решил немного оживить места респа.

**Comment by Noart537** [comment]
на фпс не повлияло?

**Comment by Noart537** [comment]
Мы брали сначала за основу миссию от annex, у них там тоже много разных объектов, при удалении всего лишнего, фпс подростает.

**Comment by ToxaBes** [comment]
Я тоже думал что повлияет но решил проверить - не повлияло вообще. Я им всем отключил симуляцию/урон поэтому они только немного занимают место в памяти.

**Comment by Noart537** [comment]
А ты через 3D редактор ставил?

**Comment by ToxaBes** [comment]
Через 2D. Eden пока слишком глючный.

**Comment by Noart537** [comment]
На 2-м со вчерашнего дня стоит сборка с Eden, вроде пока полет норм. Все объекты подредактировал чекбоксами из Eden, а в init-е удалил endbleSimulation, allowDamage. Разницы не заметил, но забинаренная миссия действительно грузится быстрее на 2-3 сек. не существенно но все-же.

**Comment by Horizon1959** [comment]
Разработчики сказали, что отключат 2D редактор. Надо переходить на 3D, надрочиться сражаться с его глюками.

**Comment by ToxaBes** [comment]
Я жду пока он не появится в stable статусе. Пока главный минус для меня: косяки с точностью. Eden часть float значений обрезает до int. Причем спонтанно. Нет желания ловить баги чтобы в итоге выяснить что фикс заключается в открытии миссии в 2D-редакторе и сохранении в нем..

**Comment by ToxaBes** [comment]
Перейти на 3D никакой проблемы не составит. Пусть сначала допилят его до вменяемого состояния. Также отключение 2D редактора никак не скажется на работе миссии.

**Comment by Horizon1959** [comment]
Главное не попасть в неловкую ситуацию, когда отключат 2D редактор.

Кстати, а ящик с VAS/VA убрали в ангар или он ещё есть на улице?

**Comment by ToxaBes** [comment]
В ангаре слева от входа стоит. Можно подъехать техникой и загрузиться при необходимости.

**Comment by Horizon1959** [comment]
@ToxaBes на втором у ящика иногда стояло от 2-ух до 4-ёх машин, поместятся ли они в ангар?

**Comment by ToxaBes** [comment]
3шт должно влезть. Этого достаточно.

**Comment by Horizon1959** [comment]
@ToxaBes ок.
