### ISSUE TITLE
Добавить технику в список наградной

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#39]
- [x] M2A1 Slammer
- [x] M4 Scorcher
- [x] M5 Sandstorm MLRS
- [ ] ~~IFV-6c Panther~~

**Comment by Horizon1959** [comment]
А зачем пантера? Она же сравнится на базе.

**Comment by ToxaBes** [comment]
Ты прав, она не нужна в наградной т.к. уже есть на базе. Убрал из наградной.

**Comment by 12st** [comment]
У скотчера нужно убрать все минные снаряды т.к. это очень лёгкий способ заминировать обширную территорию. На этих минах потом свои подрываются.

**Comment by ToxaBes** [comment]
Применил изменения Noart'a, добавил его в разработчики, теперь можно коммитить напрямую без форка.
