### ISSUE TITLE
 После зенитки не появляется основа

### ISSUE THREAD

**Issue by 12st** [ToxaBes/ADR-Spec-Ops#41]
После выполнения спец операции "Гроздья гнева", появилась зенитка, спустя ~30 секунд она сама выполнилась, при этом ни основа ни допка так и не появилась. Посмотрел зевсом по карте ничего не нашёл.

**Comment by ToxaBes** [comment]
Сейчас зашел на сервер - есть основа. Также кто-то отметил на основе расположение КП. Т.е игроки были и они видели эту основу. Уточни пожалуйста, сколько времени ждали после исчезновения зенитки?
Похоже что приоритетная цель стартанула раньше основы (они в неблокирующих потоках), т.к. основа еще не появилась то приоритетная цель завершается. Исправлю в след. обновлении.

**Comment by 12st** [comment]
Подождали примерно 7-10 минут, потом вышли. Через 30 минут сам зашёл проверить, ничего не было.

**Comment by 12st** [comment]
Нашёл купол в море, при этом на основе есть ещё один.
![20160419123929_1](https://cloud.githubusercontent.com/assets/18305023/14634763/26b5ea24-062c-11e6-9838-7e0ed6ded0bd.jpg)
![20160419123956_1](https://cloud.githubusercontent.com/assets/18305023/14634767/2a012626-062c-11e6-872a-6a87055e4a3d.jpg)

**Comment by ToxaBes** [comment]
Объекты в левом нижнем углу имеют координаты [0,0,0]. Обычно такие координаты возвращают БИС-овые функции поиска места для расположения объекта в зоне. Буду разбираться, спасибо.

**Comment by 12st** [comment]
kovt говорит, что основа так и не появилась, но появилась допка и после её выполнения стало всё нормально.

**Comment by 12st** [comment]
Выполнили основу, после неё допку, новая основа не появляется(прошло более 10 минут)

**Comment by ToxaBes** [comment]
проверь в левом нижнем углу карты, нет ли купола/пехоты. После этого я перезапущу сервер.

**Comment by 12st** [comment]
Появилось то, что должно быть в куполе, пехоты\техники\вышки нет
![20160419144546_1](https://cloud.githubusercontent.com/assets/18305023/14637989/98c704de-063d-11e6-9d1e-690bfc3d7bb4.jpg)

**Comment by Horizon1959** [comment]
У Тохи LOST какой-то, а не остров. Бункеры везде, даже под водой:)

**Comment by ToxaBes** [comment]
Перезапустил сервер армы, попробуй зайти. Ошибка где-то [тут](https://github.com/ToxaBes/ADR-Spec-Ops/blob/master/co30_ADR_Spec_Ops.Altis/functions/fn_getMainAO.sqf) судя по логам.

**Comment by 12st** [comment]
Основа реснулась, всё нормальнно

**Comment by ToxaBes** [comment]
Ошибку поймал, вечером исправлю. Спасибо за помощь.

**Comment by ToxaBes** [comment]
Исправил, нужно тестить.
