### ISSUE TITLE
Сделать метки лазерных целеуказателей видимыми для пилотов боевых вертолетов

### ISSUE THREAD

**Issue by malashin** [ToxaBes/ADR-Spec-Ops#43]
На мой взгляд, логичное дополнение для командной игры. У Longbow уже есть готовый скрипт, можно его за основу взять.

Ракеты это никак не наводит, просто дает понять пилоту где находится враг.

Ссылка на скрипт и видео примеры:
http://www.tehgam.com/showthread.php?t=1024
https://www.youtube.com/watch?v=TAgxe5sBiCQ
https://www.youtube.com/watch?v=7Uv_qFOCgBI

**Comment by Noart537** [comment]
На второй надо такой-же замутить)

**Comment by Horizon1959** [comment]
С учётом дополненной реальности, выглядит вполне реалистично. Мне нравится.

**Comment by Noart537** [comment]
Как дальнейшее развитие, добавить стрелкам Каймана\хелкета лазерный целеуказатель. для подстветки пилоту целей. Чтобы работать НУРСами.

**Comment by malashin** [comment]
Лазер сейчас у хеллкета есть. Это оружие второго пилота.

Кайману не добавлял. Не уверен, что он ему нужен.

**Comment by Noart537** [comment]
Чтобы стрелок пилоту подсвечивал цель для работы НУРСами. Но если лазер не будет выключаться при смене вооружения, то лучше не добавлять.

**Comment by malashin** [comment]
Я не проверял, но должен выключатся. Т.к. это оружие, при его смене оно работать не должно.

**Comment by malashin** [comment]
И в самом вертолете это не нужно, т.к. пилот и так видит куда смотрит пушка стрелка.

**Comment by Noart537** [comment]
А на втором у хелкета есть лазер?

**Comment by malashin** [comment]
Да, нужно переключить оружие чтобы его включить. Изначально ничего не выбрано.

**Comment by Horizon1959** [comment]
Можно пойти дальше - дать эту возможность обладателям шлема пилота, шлем выдавать только пилотам. Вполне вписывается в концепцию ArmA 3, т.к. командиры ходят с тактическими очками, где по идее должна выводится полезная информация. С учётом того, что ЛЦУ сейчас может переносить только командир отделения, это не даст сильных приемуществ, но улучшит взаимодействие пехоты и авиации.

**Comment by malashin** [comment]
В самом скрипте сейчас проверка идет на то, что ты в вертолете и в шлеме пилота.

**Comment by Horizon1959** [comment]
@malashin а можно было бы расширить проверку до самолётов и прочих вертушек?

**Comment by malashin** [comment]
Да как захотим так и будет.

Я предлагаю три шлема (две вертолетных, один самолетный), все вертолеты и самолеты. Расстояние до цели 3км, дальше не подсвечивать.

**Comment by Horizon1959** [comment]
@malashin да, круто. Что скажет маэстро?

**Comment by ToxaBes** [comment]
Добавлю в версию 0.0.4. Напишите мне название вертолетных и самолетных шлемов.

**Comment by 12st** [comment]
H_PilotHelmetFighter_B Шлем пилота истребителя(NATO)
H_PilotHelmetHeli_B Шлем пилота вертолёта(NATO)
H_CrewHelmetHeli_B Шлем пилота вертолёта(NATO)

**Comment by ToxaBes** [comment]
спасибо

**Comment by malashin** [comment]
Могу заняться этой задачей.

**Comment by ToxaBes** [comment]
Welcome on board!

**Comment by malashin** [comment]
Времено откладывается задача.

Сидел тупил, почему не работает eventHandler. А он оказывается в дев ветке еще. На этой неделе будет релиз.

Вместо того, чтобы ставить GetIn на всю технику. Можно будет поставить GetInMan на пилотов.

**Comment by ToxaBes** [comment]
Перенес в версию 0.0.4.

**Comment by malashin** [comment]
> Чтобы стрелок пилоту подсвечивал цель для работы НУРСами. Но если лазер не будет выключаться при смене вооружения, то лучше не добавлять.

Проверил, лазер висит при смене оружия. Поэтому только хэлкету стоит его давать.

**Comment by ToxaBes** [comment]
Как вариант можно отлавливать текущее оружие, например [вот так](https://community.bistudio.com/wiki/currentWeapon).
B cсравнивать с массивом классов вооружений для которых лазер разрешен.

**Comment by malashin** [comment]
Добавил сейчас данный функционал только на появляющийся на базе Хэллкэт. Можно пока протестировать на нём.

Самый простой вариант увидеть функционал это сесть в Хэллкэт на второго пилота и включить свой ЛЦУ.

----

**Условия:**
- Игрок сидит в воздушной технике.
- Игрок не пассажир.
- На игроке надет один из трех НАТОвских шлемов для пилотов.
- Расстояние до цели меньше трёх километров. (С 2.5км до 3 км прозрачность цели падает до нуля.)
- Цель ЛЦУ НАТОвская. Вражеские не видно.

Помимо иконки над целью видно и расстояние до неё в метрах.

**Что не понравилось**
Каждый кадр идёт проверка пассажир ли игрок или нет, т.к. в транспортных вертолётах можно пересесть с пассажира на бортовой пулемет. Для пулиметчика это полезный функционал. С другой стороны в дальнейшем это будет только у пилотов (сейчас достаточно шлема в хэллкэте), а они не будут сидеть за пулеметами.

Шлем во время полета можно снять и это ничего не отключит, решил проверят только при посадке в технику и не делать лишних расчетов.

**Comment by malashin** [comment]
> Как вариант можно отлавливать текущее оружие, например вот так.
B cравнивать с массивом классов вооружений для которых лазер разрешен.

А выключать лазер как? Удалять старый, добавлять новый? Это извращение какое-то. :)

**Comment by ToxaBes** [comment]
Зачем выключать лазер? Я про прорисовку метки цели.

**Comment by malashin** [comment]
Если дать ЛЦУ Кайману или Апачу, то стрелок сможет сам наводить свои ракета на цели корректируя их полет в процессе, т.к. ЛЦУ остается включенным когда выбрано другое оружие.

То, что он иконку увидит ничего не меняет, он и так её теплаком видит.

**Comment by ToxaBes** [comment]
Я имею ввиду немного другой подход. Возьмем например кайман. У него есть 30мм пушка, ракеты SCALPEL и Skyfire. Допустим мы хотим разрешить только SCALPEL для работы по подсвеченным целям.
Вот [тут](https://github.com/ToxaBes/ADR-Spec-Ops/blob/213eeeac4e5509b69548c1277bd5ad80a0908907/co30_ADR_Spec_Ops.Altis/functions/fn_HMDLaserTarget.sqf#L16) исправляем на:
```sqf
_allowedWeapons = ["missiles_SCALPEL"];
if ((headgear _player) in _pilotHelmets && currentWeapon _player in _allowedWeapons) then {
...	
```

и не нужно проверять где сидит игрок (в какой тенике и на каком месте), достаточно того что  у него нужный шлем и правильное текущее оружие. В массив _allowedWeapons набиваем все необходимые варианты того что хотим разрешить.

**Comment by ToxaBes** [comment]
Насколько я понимаю, ЛЦУ у нас только у хелкета?

**Comment by malashin** [comment]
> Как дальнейшее развитие, добавить стрелкам Каймана\хелкета лазерный целеуказатель. для подстветки пилоту целей. Чтобы работать НУРСами. Но при смене типа вооружения, лазер выключался, дабы стрелки не пользовались подсветкой в своих целях.

Я вот на это отвечал. И проверял отключается ли лазер у стрелка вертолета при смене оружия. В итоге ставить лазер на Кайман, Апач сейчас опасно, т.к. стрелок сам может наводить свои ракеты. Это никак не связано с отрисовкой иконки на экране. Ракеты всё равно будут наводится независимо от этого.

> Насколько я понимаю, ЛЦУ у нас только у хелкета?

Сейчас только у Хэлкэта. Я думаю, что не стоит никому другому его ставить. Он дан, чтобы второму пилоту было чем заняться и помогать другим игрокам, а не только пилоту.

> Я имею ввиду немного другой подход. Возьмем например кайман. У него есть 30мм пушка, ракеты SCALPEL и Skyfire. Допустим мы хотим разрешить только SCALPEL для работы по подсвеченным целям.

Работать по целям он в любом случае сможет, просто не будет видеть иконку, но видеть точку ЛЦУ в теплак.

Сейчас устроено так, что всем пилотам добавлена иконка, включая транспортники. Им можно указать куда сесть, куда не стоит суваться и т.д. Допустим метка стоит на зенитке и команда ждёт по ней удара, пилот транспортника видит, что там зенитка и облетает это место. Подход с проверкой оружия это уберет.

**Comment by malashin** [comment]
Как выглядит это дело в итоге
http://i.imgur.com/dDtTrLn.gifv

**Comment by Noart537** [comment]
А как-то можно ограничить видимость метки только на ИЛС шлема или вертолета?

**Comment by malashin** [comment]
> А как-то можно ограничить видимость метки только на ИЛС шлема или вертолета?

По горизонтали можно ограничить. По вертикали, по-моему, нет. Проверю сегодня.

**Comment by malashin** [comment]
Переделал скрипт.

Оказалось, что само присутствие Draw3D хэнделера на клиенте сжирает где-то 10 фпс (у меня) независимо от того отрисовывает он что-то или нет.

Скрипт ограничил только боевыми вертолетами и самолетами (не будет тормозить у транспортников). Если в трех километрах нет цели ЛЦУ, то хэндлер не создается, если цель была, но её больше нет, хэндлер удаляется.

**Comment by malashin** [comment]
Нашел в чем проблема. Внутри хэндлера каждый фрейм делается поиск целей ЛЦУ и тормозит именно из-за этого. Замедлить его внутри хэндлера нельзя, передать переменную внутрь хэндлера тоже нельзя. Единственный способ который я нашел это передавать netID объекта и по нему находить объект внутри хэндлера. В синглплеере, правда, это работать не будет.

https://github.com/ToxaBes/ADR-Spec-Ops/blob/master/co30_ADR_Spec_Ops.Altis/functions/fn_HMDLaserTarget.sqf#L39

```sqf
_laserTargets = player nearObjects ["LaserTargetW", 2000];
```

В итоге сейчас уменьшил расстояние поиска до 2км (было 3 км), nearestObjects заменен на nearObjects, в нём нет лишней сортировки списка.

**Comment by Noart537** [comment]
@malashin  Антон, на второй зальешь эту фичу в дев ветку? По голосованию проходит.

**Comment by malashin** [comment]
@Noart537 залил в dev, но не тестировал. Сядь вторым пилотом в хэллкет и проверь лазер.

**Comment by Noart537** [comment]
Я в ближайшее время не смогу потестить. Как минимум через 3-4 недели. Если будет время и желание, потестируй пожалуйста.

**Comment by ToxaBes** [comment]
@Noart537 -  задачей занимается @malashin ему и переносить. 
@malashin -  ты тестил на сколько падает фпс с текущей версией фичи и без нее? Есть у мня подозрение что нужно ее еще оптимизировать,  т.к. терять производительность из-за одной фичи для пилотов не разумно.

**Comment by malashin** [comment]
> ты тестил на сколько падает фпс с текущей версией фичи и без нее?

@ToxaBes у меня в редакторе когда вся логика миссия работает, фпс 30-40 где-то. Если включается эта фича, то падает где-то на 8 фпс. Что дофига всё равно.

Я думаю еще о варианте который будет искать одну ближайшую цель ЛЦУ, а не все сразу, с промежутком в секунд 5, потом костылями проталкивать её на отрисовку в эвент хэндлер. Каждые 5 секунд придется хэндлер удалять и создавать новый.

**Comment by ToxaBes** [comment]
8 fps это слишком,  будем искать другой подход или отключим эту фичу.

**Comment by Noart537** [comment]
В Зевсе видно лазерные пятна, создаваемые целеуказателями или БПЛА и т.д. Они являются объектами, может как-то работать с этими объектами, отлавливать их? Если зевсе они видны, может и отображать этот объект и для вертолетчиков но другим маркером. (если это будет наиболее простой вариант чем другие)

**Comment by malashin** [comment]
@Noart537 Я эти объекты и ищу.

```sqf
_laserTargets = player nearObjects ["LaserTargetW", 2000];
```

Проблема в том, что это затратная операция для таких расстояний и делается она каждый фрейм, нужно делать её реже.

**Comment by ToxaBes** [comment]
как вариант
https://forums.bistudio.com/topic/158256-stacked-event-handlers-oneachframe-onplayerconnected-etc/

https://community.bistudio.com/wiki/BIS_fnc_addStackedEventHandler

**Comment by ToxaBes** [comment]
наткнулся на: Order of CPU hog for object/unit collection with near.../nearest...:
1. nearestObjects
2. nearestObject
3. nearObjects
4. nearEntities (doesnt work for buildings, i believe only for units/vehicles)

Т.е. по идее замена 
```sqf
_laserTargets = player nearObjects ["LaserTargetW", 2000];
```
на
```sqf
_laserTargets = player nearEntities ["LaserTargetW", 2000];
```
должна дать какой-то выигрыш. Но нужно тестить.

**Comment by malashin** [comment]
nearEntities значительно быстрее, 0.0169ms против 2.9154ms.

Фпс на 1 кадр просидает в итоге если есть цель в двух километрах.

**Comment by ToxaBes** [comment]
В обновленной версии серьезных просадок фпс не обнаружено. Отличная работа.
