### ISSUE TITLE
Геноцид БПЛА/БПА вражеским штурмовиком 

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#44]
Очень часто после появления штурмовик бросает зону основы и переключается на наши беспилотники. Есть несколько вариантов:

~~1. Оставить все как есть.~~
~~2. Сделать какие-то капониры/ангары/маскировочные сети которые закроют стоящие беспилотники~~
3. Перенести стоянку беспилотников во второй большой ангар (соседний с респом пилотов). Т.к. он пустой, то 3 беспилотника туда влезут спокойно, после чего переместить боевой хелкет чтобы не мешал выезду из ангара и на его место поставить сервис беспилотников.
~~4. Можно их поставить как на втором, а именно перенести их в ангары где раньше стояла боевая вертушка, там же сделать и сервис.~~ (вариант от 12st)

У каждого варианта есть плюсы и минусы. Кто что думает?

**Comment by 12st** [comment]
Можно их поставить как на втором, а именно перенести их в ангары где раньше стояла боевая вертушка, там же сделать и сервис.

**Comment by Noart537** [comment]
Если самолет с юга заходит всеравно выносит)

**Comment by 12st** [comment]
Переносить их надо в любом случае т.к. там ресается наградная техника, мешает взлетать и опасность разбить сразу 2 техники.

**Comment by ToxaBes** [comment]
Я тоже так считаю, нужно выбрать между вариантами 3 и 4. Пока склоняюсь к третьему варианту.

**Comment by 12st** [comment]
Вот так они расположены
![toolwiz20164-20-15-7-10](https://cloud.githubusercontent.com/assets/18305023/14673958/a97cddf4-0709-11e6-8d4e-0046e937ee70.png)

**Comment by kovt** [comment]
Думаю 4-ый вариант самый лучший. Вариант 3 то же не плох, но, сервак рано или поздно станет пабликом, а это значит что всегда найдётся дятел который их повредит, разобьёт и т.д. Нужно будет переносить сервис БПЛА, а значит его нужно распложить близко, а это может привести к столкновением с вертушками, нужно будет убирать Хэлкэт. Так что предлагаю вариант 12s.

**Comment by malashin** [comment]
Тоже за 4-ый. Меньше нагрузки будет на базе, т.к. часть нужная единицам игроков стоит далеко.

**Comment by Horizon1959** [comment]
Вставлю свои 5 копеек. Когда ломают укрытия стомперов, то они потом спавнятся и ломаются. Их бы сдвинуть куда-нибудь.

**Comment by ToxaBes** [comment]
Ок, за основу берем 4й вариант. Что делаем с укрытием беспилотников?

1. Делаем как на втором сервере но добавляем укрытиям неубиваемость.
2. Ставим там же один большой ангар (как в респе пилотов), суем туда все беспилотниики поглубже и делаем ангар неубиваемым.

**Comment by ToxaBes** [comment]
Кстати на втором истребитель перестал жечь беспилотники после их переноса? Что-то мне подсказывает что скорее всего истребитель стал заходит четко с севера или с юга )
Я думаю их нужно прятать в глубь большого ангара, тогда с высоты их просто не будет видно.

**Comment by kovt** [comment]
![default](https://cloud.githubusercontent.com/assets/18574145/14674739/22ec27ae-070e-11e6-95c8-2e410bbd0bbf.png)

Вот моё виденье расстановки. Ну и конечно фонариков не много нужно будет добавить.

**Comment by kovt** [comment]
Ну и ангарам добавить неубиваемость. Думаю это лучше чем добавлять ещё ангар, лишняя нагрузка на сервер

**Comment by Noart537** [comment]
Осталось только неубиваемость добавить ангарам. Сервис БПЛА считаю лучше оставить рядом с тем местом где он сейчас стоит. Оно выбрано не случайно. Именно там на полосе Грейхоки останавливаются сделав круговую по полосе, после посадки. Также в файлик https://github.com/ToxaBes/ADR-Spec-Ops/blob/master/co30_ADR_Spec_Ops.Altis/scripts/misc/rearmUAV.sqf#L3  можно добавить и стомперов, чтобы не мешались на перезарядке техники.

**Comment by ToxaBes** [comment]
Эти ангары слишком короткие, поэтом позволяют бить по беспилотникам заходя с углом атаки 30-45 градусов, что штурмовик и делает. А чтобы достать технику в большом ангаре нужен угол атаки в 10-15 градусов что нереально, т.к. мешают другие ангары и штурмовик не летаяет в 10м над землей. Я хочу избежать вот этого:
![22ec27ae-070e-11e6-95c8-2e410bbd0bbf](https://cloud.githubusercontent.com/assets/3309152/14674951/2fea9bba-070f-11e6-8078-9b4f35718eda.png)

**Comment by ToxaBes** [comment]
Короче нужна статистика со второго, как сейчас происходит атака штурмовика? Или все ок?

**Comment by Noart537** [comment]
Грейхоки стали живучее после переноса их в ангарчик, но стомперы спрятаны под малую крышу, и горят чаще. И здания к сожалению убиваемые, поэтому после 2-3 взрывов, ангарчики невыдерживают, и рушатся. После чего респавн там не возможен, пока скрипт очистки не сотрет уничтоженные ангары. (это сейчас на 2-м)

**Comment by Noart537** [comment]
http://media.vorotila.net/items/9/4/0/t1@940da07a-5942-46f9-9fde-e66acb6db9ec.jpg

**Comment by Noart537** [comment]
=)

**Comment by Noart537** [comment]
Еще как вариант можно респавнить БПЛА без экипажа. Если нужен бпла, то подойти к компьютеру и активировать. Неудобно, но это один из выходов.

**Comment by ToxaBes** [comment]
ага, и заодно корабль запилить чтобы патрулировал ) 
По поводу неубиваемости, ангары это объекты карты, соответственно чтобы сделать их неубиваемыми нунжо убрать их (скрыть по id), на их месте заспавнить при старте сервера 3 новых ангара с тем же положением, азимтуом и уже им прописать неубиваемость (я так сделал с ангаром респа пилотов). И тут возникает вопрос, что лучше для сервера - 3 рукотворных средних ангара или один большой?

**Comment by malashin** [comment]
Можно еще не давать штурмовику летать над базой.

Если он рядом с базой, то давать вейпоинт в другом месте
setWayPointCombatMode "BLUE";

**Comment by Noart537** [comment]
Тогда зенитки без дела стоять будут)

**Comment by Noart537** [comment]
Антон, попробуй большой ангар тогда. Потестируем недельку, там и решим, как лучше, оставить или нет.

**Comment by ToxaBes** [comment]
зенитка будет сбивать вражескую авиацию с хвоста наших вертолетчиков

**Comment by ToxaBes** [comment]
в таком случае нужно решить куда ставить большой ангар, т.к. это новый объект на карте и туда влезут все беспилотники, то мы не привязаны к конкретному месту, возможно есть места удобнее, как считаете?

**Comment by Horizon1959** [comment]
@ToxaBes а что за ангар такой? Зелёный чтоль, как на базе у вертолётов?

**Comment by ToxaBes** [comment]
Да, обычный зеленый ангар, у нас сейчас два таких на базе у вертолетов стоят, в одном появляются пилоты, второй просто пустой рядом стоит.

**Comment by Horizon1959** [comment]
@ToxaBes т.е. в него два грейхока помещаются?

**Comment by ToxaBes** [comment]
2 грейхока + 1 стомпер - легко.

**Comment by Horizon1959** [comment]
@ToxaBes ок, получается, что если запихнуть технику в ангар, то штурмовик её не увидит?

**Comment by ToxaBes** [comment]
да, и даже если таки увидит, то уничтожить не сможет.

**Comment by ToxaBes** [comment]
После всех тестов вернулся к третьему варианту. Вроде норм.
