### ISSUE TITLE
Изменение спецоперации Гроздья Гнева

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#46]
- [x] Если в зоне меньше 5 ботов, то рисовать 3 маркера радиусом 50 метров внутри которых будут терминалы.  
- [x] Центр маркера не совпадает с позицией терминала. 
- [x] Терминалы могут быть уничтожены ядерным взрывом

**Comment by AlexVDem** [comment]
Можно и на втором тоже самое сделать, учитывая что сервер для новичков - это как раз для новичков облегчение и повышение динамики сюжета задания.

**Comment by ToxaBes** [comment]
Обкатаем на первом, потом применим на второй (если изменение пройдет голосование).

**Comment by RK3QRZ** [comment]
Я бы не стал изменять эту допка. Тем кому она не нравится пытаются выполнить ее  в 1-2 человека, отсюда и весь вайн что допка сложная. Мы отрядом в 8- 10 человек выполняли ее за 10-15 минут и все было прекрасно. Допка отличная, если ее упростить, то опять допку смогут выполнять в одно лицо.

**Comment by RK3QRZ** [comment]
P.S может просто убрать технику и ничего более не изменять?

**Comment by 12st** [comment]
@RK3QRZ, никто и не говорит, что она сложная просто если выполнять её в одиночку через час или два всё сводится к беготне по пустой зоне в поисках терминала. Естественно ничего интересного в этом нет, поэтому и стали взрывать ядерки, чтобы хоть как-то упростить этот процесс.

**Comment by RK3QRZ** [comment]
А никто и не говорил что эта допка для одного лица, собирайте команду и воюйте. Эта допка для команды/отряда и не над тут изображать ромбо которой в одно лицо хочет сделать допку, а потом ныть что она слишком замороченная.Тоха все правильно сделал, допка для выполнения ОТРЯДОМ/КОМАНДОЙ. В таком варианте она делается очень быстро. А вы привыкли допка выполнять за 5 минут, а тут вам облом.

**Comment by RK3QRZ** [comment]
Тоха придумай что-нибудь чтобы эту допку не могли взорвать ядерной.

**Comment by RK3QRZ** [comment]
Более того жалуются на это допку не более 5 человек, те кто ТС постоянно сидят.Новичком поприколу эта допка.

**Comment by 12st** [comment]
@RK3QRZ, если бы можно было никто бы и не стал выполнять в одиночку, но на первом допка и основа чередуются и тут уже ничего не сделаешь. Новички как и большинство игроков ни разу не искали эти терминалы более 10 минут(может просто мне не повезло и мне не попадались такие), большинство просто побегает некоторое время и сваливает на основу, или как делают часть старичков, посидят на горочке постреляют и ждут пока 1-2 человека обыщут город.

**Comment by RK3QRZ** [comment]
Я как администратор второго сервера веду речь только о втором сервере. И мне бы не хотелось чтобы на втором сервере эту допку как-то упрощали. Максимум можно технику убрать.На вас и там жалобы были что вы не даете отыграть эту допку подрывая ее ядерной.

**Comment by 12st** [comment]
@RK3QRZ, ещё раз повторяю сложность не в ботах и не в их количестве, просто никто не хочет тратить несколько часов на беготню по пустому городу, жалобы идут т.к получается примерно такая ситуация: Мы пойдём подрывать ядерку. -Но это не честно! Дайте пострелять вы убиваете весь смысл допки! -Будешь искать терминалы? - Конечно нет я же *подставьте нужный класс*, поэтому я и не должен искать!

**Comment by RK3QRZ** [comment]
Не хочешь искать терминалы иди на основу, тебя никто не заставляет их искать. Найдутся игроки которые пойдуи и выполнят эту допку. Подрывая ядерку ты лишаеш  других игроков честно выполнить эту допку. При мне не раз уже вам делали за это замечания.

**Comment by RK3QRZ** [comment]
Собирай отряд и за 15 минут эту допку можно сделать, если ты строишь из себя ромбо и один хочешь ее сделать то 3-4  часа это вполне нормально.

**Comment by 12st** [comment]
@RK3QRZ, пока не придут игроки которые постоянно этим занимаются допка будет висеть до рестарта, пройденный этап уже. Да туда будут приезжать игроки, да может быть они вскоре найдут один два терминала, но не найдя третий все будут просто сваливать, а новые игроки приезжать видеть отсутствие ботов и также сваливать. Были ситуации когда на неё собирались огромные толпы народу вплоть до 20 человек, но к концу допки остаются искать опять таки 2-3 человека, остальные либо бесцельно бегают в поисках ботов либо приезжают обыщут пару зданий и сваливают.

**Comment by RK3QRZ** [comment]
Темболее что у вас на первом допки и основы чередуются. И как-то странно жаловаться на эту допку. В последнее времени народу на первом играет предостаточно,и такие жалобы. Я в шоке!

**Comment by RK3QRZ** [comment]
Прям какие-то фантастические истории ты мне рассказываешь про 20 человек не могущих нот терминал. На втором мы с тобой же в 4-5 человек все всегда находили.

**Comment by RK3QRZ** [comment]
Короче я понял вашу позицию: вы хотите нагибать ботов побыстрому прикладывая минимум усилий и времени. Последнее самое актуальное видимо.

**Comment by 12st** [comment]
@RK3QRZ, искали, находили, однако остаются искать лишь не большое количество, не было такого когда народ нормально искал их такой большой толпой. И я не говорю про те ситуации когда везёт и все 3 находят быстро и ещё до того как всех ботов выкосят. То что хотят ввести должно убрать ситуации когда нашли 2 терминала, а 3 находится не известно где и поиск сводится к тупой беготне. Ботов выкашивали не более чем за два часа. Как только на первом стали помечать местонахождение терминалов, допка по сути не изменилась т.к чтобы до них добраться всё равно надо выкосить большую часть, это учитывая, что отмечают точно до метра, а тут будет 50 м.

**Comment by RK3QRZ** [comment]
На втором было такое и не раз, когда толпой заходили и выполняли эту допку за 10-15 минут. Я сам участвовал. Подсвечивать терминалы я считаю это упрощением.Может сузить триггер, убрать технику и поставить злых пехов  в домах и на улице чтобы мочили с развороту и убивали с первой пули? Так хардкорней будет!

**Comment by 12st** [comment]
@RK3QRZ, в маленьких городах проблем вообще не возникает. Их действительно проходят быстро, поэтому в пометке нет смысла. Однако в больших городах, метки всё же нужны из-за огромного количества зданий.
Как вариант на втором можно сделать так: Метки на терминалах появляются только в том случае если ботов меньше 10. Но убрать возможность подрыв ядерки и ввести систему Аид от Тохи.

**Comment by AlexVDem** [comment]
Друзья, давайте все-таки не забывать, что сервер для всех, а не для избранных. Народ голосует своим временем, и если эта допка не популярна по причине её монотонности, то надо повышать её динамику, т.е. хотя бы приблизительно указать места терминалов. Совет собирать команду и прочесывать город не катит, Техгам все-таки не Тушино.
Грамотный командир так и сделает: обозначит сектор для зачистки, найдет маркер, посетить зону как чистую и перейдет к следующему сектору. За неимением командиров это можно возложить на триггер с маркером, ничего криминального тут нет, это наоборот, повысит интерес, а сложность не понизит.

**Comment by AlexVDem** [comment]
Чтобы не подрывали ядерку достаточно выставить терминалам возможность урона, повредил терминал - миссия провалена.

**Comment by RK3QRZ** [comment]
А кто сказал, что она не популярная? Те кто в ТС постоянно сидят и ждут только допки? Не забывай о других игроках, если кого-то что-то не устраивает то идите воюйте на основе. И за всех не надо тут говорить. Народ с утра до вечера сидит в ТС и игре и о каком голосовании временем ты тут говоришь ? И как раз совет собрать команду на допку тут катит, Агларон бы быстро всех собрал и ответ туда куда надо. Просто вы обленились совсем, вам нужно все по быстрому и с минимум усилий.

**Comment by ToxaBes** [comment]
Мнения сильно разделились. Главная проблема (для первого сервера) в том что если играет 1-2 человека и в зоне 200 зданий, то проверить их немного муторно. Если же играет 5-10 чел, то никакой проблемы это не составляет. С учетом всего написанного выше я предлагаю новый вариант: 
* никаких маркеров на терминалах пока в зоне есть больше 5 ботов
* если 5 ботов или меньше то появляются маркеры-круги радиусом 50 м

В итоге получим следующее: ищем терминалы - выбиваем противника, в ходе выбивания нашли 1-2 терминала сами. Оставшиеся терминалы будут в зонах маркеров после окончательного захвата зоны и не нужно будет бегать проверять вообще все дома в зоне. Также это уберет необходимость в использовании ядерного заряда.

**Comment by RK3QRZ** [comment]
Тоха добавь туда еще супер ботов, в дома и на улицу.

**Comment by ToxaBes** [comment]
Я хочу оставить прохождение спецопераций доступным в одно лицо. Там боты и так добавлены (на первом спецоперации изменены по количеству ботов).

**Comment by AlexVDem** [comment]
Не популярная потому, что это уже много раз обсуждалось в ТС, и я сам часто заходил на сервер и видел недоделанную допку и народ воюющий только на основе. Именно потому, что людям не интересно бегать по пустому городу и обшаривать развалины. Тем более если там ядерный заряд взорвали, и терминал где то под обломками. Поэтому я и предложил сделать такие условия, при которых подрыв заряда миссию проваливает.
Почему за всех, да потому что если бы это было иначе этого бы обсуждения не было бы вообще. Никто же не обсуждает сценарий конвой или угон.
Хотим мы того или нет, но игра все-таки предполагает динамику со стрельбой, а если кому хочется бегать по городу и искать ачивки - вэлкам ту зе алтис лайф.

**Comment by AlexVDem** [comment]
Не популярная потому, что это уже много раз обсуждалось в ТС, и я сам часто заходил на сервер и видел недоделанную допку и народ воюющий только на основе. Именно потому, что людям не интересно бегать по пустому городу и обшаривать развалины. Тем более если там ядерный заряд взорвали, и терминал где то под обломками. Поэтому я и предложил сделать такие условия, при которых подрыв заряда миссию проваливает.
Почему за всех, да потому что если бы это было иначе этого бы обсуждения не было бы вообще. Никто же не обсуждает сценарий конвой или угон.
Хотим мы того или нет, но игра все-таки предполагает динамику со стрельбой, а если кому хочется бегать по городу и искать ачивки - вэлкам ту зе алтис лайф.

**Comment by RK3QRZ** [comment]
Тогда ядерку будут спицом подрывать чтобы провалить допку. Цель же не в этом, цель в сохранении допки ну и возможно наказании такого игрока.Да вообще кроме вас никто ничего не обсуждает, вы там сидите в ТС и придумывает как облегчить ту или иную миссию и только сеете панику у новичков, хаете допки и т.д. Даже Горизонт сказал что допка хорошая и не на что не жаловался. И не нужно говорить за всех. Не нравится допка? Великом на основу!

**Comment by AlexVDem** [comment]
> Да вообще кроме вас никто ничего не обсуждает, вы там сидите в ТС и придумывает как облегчить ту или иную миссию и только сеете панику у новичков

Я вообще ничего не обсуждаю с ТС, стараюсь больше слушать что другие говорят. Допка безусловно хорошая, спору нет. Вопрос вкуса, кто-то любит больше побегать и пострелять, кто-то вдумчиво шарить по домам в поисках клада. По моему мнению, духам больше свойственно первое, а дедам - второе. Дембеля вообще предпочитают на базе сидеть, и языком чесать... ))))

**Comment by 12st** [comment]
Сегодня появились только 2 терминала, причём тот кто активирует, после мог повторно его активировать бесконечное число раз. Пехота появилась только возле терминалов, техника не появилась вообще, тригеры показывающие терминалы также не появились.(допка появилась примерно в 20:00 по мск)

**Comment by ToxaBes** [comment]
Рассинхрон армы - не лечится.
