### ISSUE TITLE
Вооружение вертолётов на спец операции "Угон"

### ISSUE THREAD

**Issue by 12st** [ToxaBes/ADR-Spec-Ops#47]
Сейчас на данной спец операции могут появится следующие вертушки:
AH-9 Pawnee: 30 мм пушка системы гатлинга(вайпаут) и 2 ASRAAM
AH-99 Blackfoot: 30 мм пушка системы гатлинга(вайпаут) и 4 ASRAAM
UH-80 Ghost Hawk: 6.5 мм пулемёт системы гатлинга(правый стрелок), 35 мм автоматическая пушка(левый стрелок)
UH-80 Ghost Hawk(камуфляж): 6.5 мм пулемёт системы гатлинга(правый стрелок), 30 мм пушка системы гатлинга(вайпаут)(левый стрелок)
Mi-48 Kajman: 30 мм безгильзовая пушка, 8 ПТУР  "Скальпель", 4 ASRAAM
Po-30 Orca: 30 мм пушка(нефрон) и 12 DAGR
PO-30 Orca(чёрный и белый): 30 мм пушка системы гатлинга(вайпаут) и 12 DAR

Что хотелось бы изменить.
1. Основная претензия к вооружению каймана. Обменяли 38 ракет "Скайфайр" и 250 подкалиберных снарядов на 4 ASRAAM. Хотелось бы вернуть подкалиберы и как вариант добавить ОФ нурсы от вайпаута их там всего 7.
2. Гост хоки мало играбельны с пулемётом только с одной стороны. Их можно вообще убрать или добавить аналогичное вооружение с правой стороны. 
3. Блекфут лишили противотанкового вооружения дальнего действия, но взамен дали мощную пушку, которая легко сбивает авиацию. Убрать ASRAAM, а вместо них добавить 12 DAGR.

**Comment by ToxaBes** [comment]
Текущий вариант создавался по рекомендациям/просьбам игроков. Я могу изменить вооружение вертолетов на этой спецоперации, но нужно найти оптимальные варианты для каждой вертушки. Просьба к остальным игрокам, которые летают на этих вертушках высказать тут предложения/обсудить варианты.

**Comment by AlexVDem** [comment]
Лучше вернуть кайману (да и всем остальным вертолетам) нормальный вес и динамику если это возможно. Ну не может боевая ударная вертушка летать как беременная корова, Ка-52 в реальной жизни мертвую петлю делает, а у нас у каймана винты отрывает если крен на скорости больше 50 градусов. Ну бред же?

**Comment by ToxaBes** [comment]
@AlexVDem - БИСы не дали такой возможности. 
По поводу Mi-48 Kajman в арме: это не просто Ka-52, это сборная солянка из Ми-28н, Ка-52 и еще кого-то ) . Просто почитай про проблемы Ми-28н с перегревом главного ротора, проблемами со взлетом/поавдкой и тд. И получится что в игре этот мутант не так далек от реальных аналогов )

**Comment by AlexVDem** [comment]
Похоже не в БИСах дело, я не разбирался в сценарии, но похоже что-то в скрипте накосячили. Поставь в редакторе на чистой карте Кайман, полетай на нем, а потом попробуй то же в сценарии, совсем другая управляемость и интервалы допустимых перегрузок при продвинутой модели полета и включенных повреждениях от перегрузок. В редакторе Кайман летает как Тару - управлять одно удовольствие, а в сценарии ему как будто вес в два раза увеличили, я уж не знаю как и где.

**Comment by ToxaBes** [comment]
>Похоже не в БИСах дело, я не разбирался в сценарии, но похоже что-то в скрипте накосячили. 

После проверки оказалось что таки БИСы накосячили.

По вооружению вертолетов:
1. Он после этого не станет супер имбой?
2. Гостхокам пулеметы поправлю, будет 2 одинаковых
3. Блекфут оставлю как есть, помню что просили вертолет с авиапушкой часто. Вот это он и есть.

**Comment by 12st** [comment]
@ToxaBes Кайман который дают в награду сейчас на много слабее чем по умолчанию, нурсами мало кто пользуется, а эффективно вообще единицы поэтому нагибать такая вертушка точно не будет.

**Comment by ToxaBes** [comment]
Ок, вооружение Каймана и Гостхока исправлю на предложенный вариант.

**Comment by ToxaBes** [comment]
У Каймана только Skyfire заменен на ASRAAM, остальное вооружение - штатное. Гостхок пофикисл.
