### ISSUE TITLE
M5 Sandstorm MLRS

### ISSUE THREAD

**Issue by 12st** [ToxaBes/ADR-Spec-Ops#48]
Сегодня впервые выпал с допки данный агрегат, встал на расстоянии в 5 км привёз перезарядку, загрузился пво и просто выносил всю основу в одиночку, да так, что остальные 5 человек толком ботов не увидели. Через пару часов счёт стал таким.
Нужно убирать его, слишком мощная вещь.
![toolwiz20164-27-20-25-21](https://cloud.githubusercontent.com/assets/18305023/14861512/3d20d748-0cb6-11e6-8bbc-de47234438fc.png)

**Comment by Horizon1959** [comment]
Ара, это ты без БК так жаришь?

**Comment by malashin** [comment]
По идее, нужно тачку с патронами и бобкэт нерфить, чтобы патроны были конечными и нужно было ехать на ней в сервис. Либо кулдаун ставить на пополнение патронов, чтобы часто это делать нельзя было.

**Comment by Horizon1959** [comment]
@malashin бобкэт уже сейчас имеет ограниченый запас раздачи БК, не хватает даже на полную зарядку БТР. А вот про модули я давно говорил: берёшь камыш/зенитку/горгону/маршал, заезжаешь на холм с ящиком и начинаешь выносить всех бесконечными бопсами.

**Comment by malashin** [comment]
Тогда убирать этот модуль нужно. Делать свой скриптовой или цеплять грузовики с патронами.

**Comment by Horizon1959** [comment]
@malashin грузовик с БК ведь тот же самый эффект даёт.

**Comment by malashin** [comment]
У грузовика и бобкэта всегда был внутренний ресурс патронов, которые можно было забрать сидя в другой технике.

Всё это видно и можно менять этими коммандами.
https://community.bistudio.com/wiki/getAmmoCargo
https://community.bistudio.com/wiki/setAmmoCargo

Я этим уже давно не пользовался, поэтому, возможно, что-то БИСы снова сломали. Я, как, я понял из вашей речи, вертолетные модули дают бесконечный боезапас. Нужно проверить модули, грузовики и бобкэт через getAmmoCargo и всё станет ясно.

**Comment by Horizon1959** [comment]
Грузовик с БК сейчас вообще не спавнится, его убрали именно из-за такой читерской составляющей. Сейчас чуть-чуть заряжает бобкэт и ящик для вертолёта.

**Comment by Noart537** [comment]
@12st А ящик зевсовый или сам с базы привез?

**Comment by Noart537** [comment]
Если с базы, можно при спавне модуля прорисать ему ресурс.

**Comment by 12st** [comment]
Сначала обычный модуль вертолёта, потом просто поставил грузовик с бк, суть не поменялась.

**Comment by ToxaBes** [comment]
Нужно будет прописать модулю/грузовику какой-то ограниченный ресурс (какой?).

**Comment by 12st** [comment]
В нём 12 ракет, каждая ракета имеет радиус поражения пехоты 50-70 метров, попадание в радиусе 15-20 выносит лёгкую технику, 2 попадания танк. 30-50 ракет хватает, чтобы вынести почти всю основу.

**Comment by malashin** [comment]
Патроны в грузовике расходуются таким образом, что крумнокалиберные патроны тратят больше запаса грузовика, чем мелкокалиберные. У всех патронов прописаны значение в конфигах.

На мой взгляд одного грузовика должно хватать на полную перезарядку MLRS и всё, дальше он пустой. Стоит, конечно, проверить и другую технику.

**Comment by ToxaBes** [comment]
> На мой взгляд одного грузовика должно хватать на полную перезарядку MLRS и всё

Согласен, но как это сделать?

**Comment by malashin** [comment]
Либо в конфигах посмотреть сколько жрут запаса ракеты, либо имерическим путем побирать значение.

Найденное значение прописывать всем грузовикам и другой подобной технике.

**Comment by ToxaBes** [comment]
займешься?

**Comment by Horizon1959** [comment]
@malashin @ToxaBes если у вас получится, то вернёте грузовик с боеприпасами на место спавна?

**Comment by ToxaBes** [comment]
@Horizon1959  - пока не вижу необходимости.

**Comment by Horizon1959** [comment]
@ToxaBes не все могут летать и доставить модуль, а грузовик докатить не так уж и сложно. Если ограничить его ресурс, то было бы круто запилить машину обратно.
На втором его вырезали, т.к. Рысь, Я и куча других чуваков колесили с этим грузовиком и устраивали противнику дождь из 82мм мин, ведь всё это добро перезаряжалось от рядом стоящей машины.

**Comment by ToxaBes** [comment]
Хорошо, если @malashin сможет сделать грузовик "однозарядным" то вернем.

**Comment by malashin** [comment]
У Бобкэта 3000 патронов и 3000 на починку.
У грузовика и модуля Хурона 10 в 12-ой степени патронов, т.е. 1 000 000 000 000 патронов.

Одна ракета Сэндсторма стоит 1000. По идее Бобкэт должен заряжать три, но получается две, после этого он полностью пустой.

Путем  проб и ошибок я пришел вот к чему. Если грузовику поставить setAmmoCargo 0.000000012, то это ровно 12 ракет Сэндсторма. У него 12 полный заряд. То есть исправить это дело можно на сервере.

Вопрос в том, перезаряжает ли сервис техники грузовики с патронами. Нужно, либо добавить этот функционал, либо запретить ему заряжать грузовики полностью.

Позже этим займусь.

```sqf
_v = vehicle player; _v setAmmoCargo 0.000000012; _ammo = getAmmoCargo _v; systemChat str(_ammo);
```

**Comment by Horizon1959** [comment]
@malashin вот это да! А я думал грузовик бесконечен. Ставил его рядом с пулемётом, лочил стрельбу и отходил пиво пить - не кончался.
Получается, что бобкэт может чинить ограниченное количество раз?

**Comment by malashin** [comment]
> Получается, что бобкэт может чинить ограниченное количество раз?

Да, именно так. Не проверял на сколько его хватает.

**Comment by malashin** [comment]
Добавил грузовик с боеприпасами. Все грузовики и модули содержат 12000 патронов (12 ракет Sandstorm или 24 танковых снаряда). На наземном сервисе можно перезагрузить грузовики до 12000 патронов, модули нельзя.

Нашел еще один интересный момент. По умолчанию в HEMTT, Замаке и модуле Хурона 10^12 патронов, в Темпесте и модуле Тару 30000 патронов.

**Comment by malashin** [comment]
Я думаю, что всё таки Скорчер и Сэндсторм стоит убрать из наград.

**Comment by Horizon1959** [comment]
Оставьте артиллерию, она всё равно без баллистического калькулятора.
За машины спасибо, можно прям подвоз боеприпасов организовать.

**Comment by AlexVDem** [comment]
Не надо ничего изобретать, достаточно срок жизни контейнера с БК для техники сделать, например 20 минут. 5-10 минут на доставку, + 10-15 минут на стрельбу с перезарядкой.
Потом лететь за новым. Ну и тайм-аут по респу контейнера полчаса.
Вот вам и реализм настанет, все как в реальной жизни, когда снабжение техники опоздало, и пехота без поддержки осталась, сидим курим бамбук.

**Comment by ToxaBes** [comment]
@malashin - cкорчер и сэндсторм оставляем. Твои изменения по боеприпасам + отсутствие баллистического компьютера + грядующие изменения по дальности прорисовки сделают свое дело.

**Comment by ToxaBes** [comment]
Применил на сервер - протестируйте как будет возможность.
