### ISSUE TITLE
Зелёные боты на спец операции "Заложники"

### ISSUE THREAD

**Issue by 12st** [ToxaBes/ADR-Spec-Ops#49]
У зелёных ботов отсутствуют ПНВ, поэтому в ночное время суток они не могут действовать.

**Comment by Horizon1959** [comment]
Разве им не пофиг на ПНВ?

**Comment by ToxaBes** [comment]
Добавил ПНВ всем кроме пулеметчиков у партизан, они категорически не хотят им пользоваться.
