### ISSUE TITLE
Подкрепление на основе

### ISSUE THREAD

**Issue by malashin** [ToxaBes/ADR-Spec-Ops#50]
Для добавления разнообразия добавить следующий функционал к основной миссии.

В начале миссии рассчитывается сколько может быть подкреплений в зависимости от количества игроков на сервере. Пока детально не продумал как это сделать динамически, поэтому пока можно, просто, сказать, что подкрепление будет одно.

По ходу миссии делать проверку раз в 10 минут, если количество ботов в триггере меньше указанного и в триггере есть игроки, то с шансом в 25% вызвать небольшое подкрепление на расстоянии 3+ км и направить его внутрь триггера. При этом вычесть единицу из количества доступных подкреплений.

Варианты подкрепления:
- Грузовик с пехотой
- Марид с пехотой
- Десантный вертолет
- Боевой вертолет "Касатка"

Как вариант, можно сделать более сложные варианты подкреплений двигающихся по земле. В них будет идти колона техники, грузовиков. Но в таком случае игрокам будет об этом сообщено и на карте отмечена точка их появления, чтобы игроки могли их перехватить. Это можно в отдельную задачу в дальнейшем выделить.

**Comment by Horizon1959** [comment]
Всё круто, кроме пометки на карте едущих подкреплений.

**Comment by ToxaBes** [comment]
мне кажется тогда оборону вообще никогда не выиграют )

**Comment by malashin** [comment]
Мелкие подкрепления никак не отмечаются. Если же движутся серьезные силы противника, то нам докладывают о них и указано направление, чтобы мы могли подготовится или перехватить заранее.

Это геймплейное разнообразие добавит. Если не отмечать никак, то всегда поздно они будут обнаружатся и начнется сразу бой. Если нам сказали о них, то мы можем отвлечься от основы и пойти встретить противника, заминировать дорогу и т.д.

**Comment by malashin** [comment]
> мне кажется тогда оборону вообще никогда не выиграют )

Это до обороны происходит и шанс не так велик, что произойдет. Смысл именно в разнообразии.

**Comment by ToxaBes** [comment]
проблема в том что это разнообразие будет часто приводить к проигрышу обороны. Имеет смысл его вводить когда игроки уверено будут выигрывать большую часть оборон. Не забывайте что им придется уничтожить практически все силы противника чтобы выиграть оборону. И с подкреплениями это будет сделать нереально.

**Comment by AlexVDem** [comment]
Это имеет смысл делать при большом количестве игроков на сервере (больше 20 к примеру), когда будет такая посещаемость - тогда можно будет и оборону усложнить.

**Comment by ToxaBes** [comment]
Пока откладываем это обсуждение т.к. стабильного онлайна больше 20 пока не предвидится.

**Comment by malashin** [comment]
Тут же речь не про оборону идет, а атаку. Если не вывозят оборону, то лучше оборону упростить.

**Comment by ToxaBes** [comment]
Оборону сейчас как раз таки вывозят в случае если работают командно. Сейчас один из вариантов облегчения обороны - вынести как можно больше ботов во время атаки. С подкреплениями это перестанет иметь смысл.
