### ISSUE TITLE
Нарушение правил спецоперации

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#51]
Некоторые несознательные игроки используют технику на спецоперациях. Пора это исправлять.  Результат применить на второй север тоже )

**Comment by Horizon1959** [comment]
Сажать в обезьянник надо, только неотвратимость наказания заставляет правила работать.

**Comment by ToxaBes** [comment]
обезьянник это слишком гуманно )

**Comment by Horizon1959** [comment]
@ToxaBes обезьянник идеальное решение, оно заставляет сидеть и думать над своими поступками. Неадекватные сразу сваливают, адекватные размышляют и делают для себя выводы.

**Comment by ToxaBes** [comment]
только расстрел (молнией).

**Comment by Horizon1959** [comment]
@ToxaBes не поймут.

**Comment by ToxaBes** [comment]
Кто не понял тот поймет (с)
На сервере не нужны те кто нарушают правила.

**Comment by Horizon1959** [comment]
@ToxaBes кровавым тираном будешь, злым диктатором.

**Comment by Noart537** [comment]
Может тригер создать вокруг допки радиусом 2км, при въезде в него на технике, предупреждение. Если не понимает в радиусе 1 км, уже веником)

**Comment by malashin** [comment]
По идее на технике можно подъехать или на вертолете сбросить припасы, просто за её присутствие наказывать не должны.

Если делать ограничение на использование вооружения в технике, то тогда игроки смогут давить ботов, что часто и делают.

**Comment by AlexVDem** [comment]
Можно написать скрипт, что если в зоне действия триггера техника давит бота, то бот подрывает перед смертью подрывной пакет с криком "Аллах акбар!" )))

**Comment by RK3QRZ** [comment]
Эта проблема приобретает массовый характер, в отсутствии администраторов на сервере.
Даже старенькие игроки этим не гнушаются. Первое что нужно делать это банить таких игроков не взирая на то новичок это или старичок. Правила для всех одинаковые, а то я смотрю, что некоторые администраторы закрывают на это глаза. Впредь буду сам банить нарушителей, и без обид потом.

**Comment by ToxaBes** [comment]
Правило на убийство издалека из техники работает в мультиплеере, а триггер проверяющий заезд в зону - нет. Локально все как обычно - работает.

**Comment by RK3QRZ** [comment]
Круть, мож подрыв просто, а то так молний не напасешся? ;)

**Comment by ToxaBes** [comment]
молния в игре, особенно при ясном небе - индикация для знающих игроков что кто-то был наказан за что-то. Наказание должно быть публичным. А так кто-то там где-то взорвался и непонятно, боты подбили или наказали.

**Comment by Horizon1959** [comment]
@ToxaBes для инженеров, с терминалом БПА, достаточно уничтожения беспилотника и сообщения об этом. Цель ведь не допустить использование техники, а не карать игроков. Так?

**Comment by ToxaBes** [comment]
я еще думаю над этим. Тут есть явное нарушение - не просто так беспилотник пролетал мимо и уронил бомбу.

**Comment by RK3QRZ** [comment]
Беспилотник же не сам по себе полетел кидать бомбу? Его тут отправил игрок, пусть и отвечает за свои действия.

**Comment by ToxaBes** [comment]
Триггер заработал, только что проверил лично.
