### ISSUE TITLE
Криво расположен маяк на сервисе самолётов

### ISSUE THREAD

**Issue by 12st** [ToxaBes/ADR-Spec-Ops#52]
Маяк расположен сбоку от самого сервиса
![20160428162647_1](https://cloud.githubusercontent.com/assets/18305023/14887367/2a5d8e5a-0d5e-11e6-95e8-536f211b893b.jpg)

**Comment by ToxaBes** [comment]
Сделано специально т.к. zed врезается колесом самолета в него и взрывается )
