### ISSUE TITLE
Разрушаемый КП

### ISSUE THREAD

**Issue by 12st** [ToxaBes/ADR-Spec-Ops#53]
Ядерная бомба сносит КП и получается такая ситуация, без зевса достать терминал не получилось.
![20160430023906_1](https://cloud.githubusercontent.com/assets/18305023/14935420/bfe00fa8-0ed9-11e6-9ef8-20c4a1cf87bc.jpg)

**Comment by AlexVDem** [comment]
Тоха, новую тему открывать не хочу, поэтому пишу тут.
Сегодня делали РЭБ, есть пару мыслей:
1) Ночники и тепловизоры отключаются другим скриптом, нежели тот, что в моей изначальной миссии. Может это и неплохо, но нет никакого предупреждения, о том, что не работает. Надо бы поправить.
2) Наградные машинки, которые респяться рядом с антенной, не должны удаляться, это трофей. Надо убрать их из скрипта очистки при завершении задания.
3) При выполнении задания инженером танк не дается, эта часть кода куда то пропала.

**Comment by ToxaBes** [comment]
Как ты помнишь, я предупреждал что внесу изменения чтобы она подходила к тому что я задумал на сервере и стала приоритетной целью а не допкой.
1) твой скрипт не работал в мультиплеере, поэтому пришлось написать новый. Сообщение о том почему не работает - добавлю.
2) они будут удаляться т.к. и так слишком много объектов. Не такая ценная награда чтобы ее оставлять.
3) там есть ошибка, я в курсе и иправлю ее в следующих версиях, если правильно выполнить миссию то будет появляться танк.

По комментарию, он у тебя противоречит сам себе, потому и изменил.
>.... Пока **они не уничтожены**...
>... **захватить** узел связи и мобильнную установку РЭБ и **перехватить** информацию противника ...

**Comment by 12st** [comment]
Взорвали ядерку, кп уничтожился.

**Comment by ToxaBes** [comment]
Применил новый вариант, завтра утром применится.
