### ISSUE TITLE
Добавить возможность спуска по тросам для вертолетов

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#56]
Для PO-30 Orca, UH-80 Ghost Hawk, Mi-48 Kajman, CH-49 Mohawk, Mi-290 Taru, CH-67 Huron и WY-55 Hellcat рассмотреть возможность добавление опции десантирования по тросам (fastrope):
- [ ] опция доступна только пилоту через меню действий
- [ ] все пассажиры грузового отсека десантируются по тросам автоматически
- [ ] скорость вертолета не больше 5 км/ч, высота не больше 20м
- [ ] до окончания высадки скорость вертолета 0км/ч, высота 20м
- [ ] скорость спуска по каждому тросу 2-3 сек

**Comment by Horizon1959** [comment]
Раньше это было на втором, выглядело стрёмно. Парни без анимаций леветировпли с вертолёта до земли по каким-то палкам.

**Comment by malashin** [comment]
Мне, на самом деле, такой функционал никогда не нравился, т.к. он упрощает жизнь пилотам это раз, лишает смысла легкие вертолеты это два, т.к. тяжелому вертолету не нужно садится.

> все пассажиры грузового отсека десантируются по тросам автоматически

А если кто-то не хочет выходить и летит дальше?

**Comment by malashin** [comment]
Готовый скрипт
https://forums.bistudio.com/topic/187445-shk-fastrope

Можно посмотреть, как у него это реализовано. Сейчас еще в ACE, по-моему, сделали подобный функционал.

**Comment by ToxaBes** [comment]
>Раньше это было на втором, выглядело стрёмно

Постараемся сделать нормально. Если не получится, откажемся.

>лишает смысла легкие вертолеты это два, т.к. тяжелому вертолету не нужно садится

Эта фича позволит делать высадку в любой точке. Если пилот опытный и получает удовольствие от посадки то он будет использовать спуск по тросам только в очень сложных местах. Если не очень опытный - пусть хоть постоянно использует, все лучше чем разбиваться всей группой при посадке.

>А если кто-то не хочет выходить и летит дальше?

В таком случае пилот использует посадку вместо спуска по тросам.

>Готовый скрипт

Их много сделано но все они какие-то корявые. Попробуем свой вариант сделать.

**Comment by malashin** [comment]
Тут вариант ACE:
https://github.com/acemod/ACE3/tree/master/addons/fastroping

У них там анимация есть держания за веревку, её можно использовать при условии, что авторы указаны. Весит 12.4 KB всего лишь.

**Comment by ToxaBes** [comment]
спасибо,  посмотрю.

**Comment by AlexVDem** [comment]
Кстати, почему то сегодня не смог сесть в маленькую вертушку, хотя на сервере было всего 6 человек...

**Comment by ToxaBes** [comment]
Скорее всего в этот момент был JIP клиент (Join In Progress)

**Comment by ToxaBes** [comment]
Без модоа нормально не получится добавить нормальную анимацию спуска по тросу (ограничение армы). Тупое леветирование не устраивает. Задача отложена до момента когда арма позволит расширять секцию CfgMoves без модов.
