### ISSUE TITLE
Убийство с бпа

### ISSUE THREAD

**Issue by 12st** [ToxaBes/ADR-Spec-Ops#57]
Если убивать своих с БПА, то наказать обидчика нельзя т.к. наказывается бот, даже если игрок в этот момент подключён к нему.

**Comment by ToxaBes** [comment]
Утром миссия обновится на сервере, нужно будет потестить.

**Comment by ToxaBes** [comment]
Проблема осталась.

**Comment by malashin** [comment]
https://github.com/ToxaBes/ADR-Spec-Ops/commit/6ccdb0c508d92c17d259d4c43b52a46dde050711#commitcomment-17442431

**Comment by ToxaBes** [comment]
Проблема в правильной передаче отловленного игрока в  spawn {... }. Буду менять эту часть.

**Comment by ToxaBes** [comment]
Новый вариант, опять нужно тестить.
