### ISSUE TITLE
Стирание наградной техники

### ISSUE THREAD

**Issue by kovt** [ToxaBes/ADR-Spec-Ops#58]
Сегодня выполняли допку Радар, на наградном Т100. Находились в тригере, тыкнули ноут, допка кончилась, сразу стёрлись остатки, вместе с наградным Т100.... Так должно быть?

**Comment by ToxaBes** [comment]
Странно, Т100 точно наградной или отжали/починили на допке?

**Comment by kovt** [comment]
Именно наградной. Мы сидели в нём втроём, Норт, Пиги и я, допка стёрлась и вместе с ней наш танк.

**Comment by Noart537** [comment]
Хорошо хоть одежда осталась ^^

**Comment by ToxaBes** [comment]
Исправил, нужно тестить.
