### ISSUE TITLE
Вражеский воздух

### ISSUE THREAD

**Issue by kovt** [ToxaBes/ADR-Spec-Ops#59]
Антон, надо что то делать с вр.воздухом. Я понимаю что тебе на него по-барабану, так как ты в основном передвигаешься пешком или на лёгкой технике,понимаю что миссия заточена под пехоту. Но большая доля игроков любит и часто ездит на тяжелой броне, и мириться с таким респавном штурмовиков уже нет сил. До точки банально не доехать, так как только сбиваешь один самолёт через секунду появляется следующий. Так жить нельзя. Давай хотя бы тайм аут им увеличим, Ну или хотя бы сделать так что бы Неофрон не респился так часто.

**Comment by ToxaBes** [comment]
>Я понимаю что тебе на него по-барабану

нет

> Но большая доля игроков любит и часто ездит на тяжелой броне

На самом деле это очень небольшая часть игроков на сервере. Если тебе нравится ездить на тяжелой броне это не значит что таких большинство. Сходу могу назвать только тебя и soondook-a.

 
>До точки банально не доехать

Постоянно вижу как игрок soondook играя инженером на медленной пантере приезжает на основу и полностью ее зачищает. Есть ПВО (мобильные комплексы титан и ПВО базы), есть наша авиация, есть наградная техника (зенитки/верты/самолеты). 
Ты не написал самого главного - до точки банально не доехать **в одиночку** (хотя soondook все равно доезжает). И это логично.

По поводу изменений, я планировал увеличить время между респом вражеской авиации до 5-7 мин и добавить вражеских вертолетов. Т.е. будет случайный выбор из двух самолетов и 2-3х вертолетов. Но это не раньше 5й версии.

**Comment by malashin** [comment]
Сейчас проверка делается каждые 480-960 секунд. То есть новый самолет может появится через 0-960 секунд. По идее, нужно после падения штурмовика начинать отсчет времени, а не пока он жив.

**Comment by ToxaBes** [comment]
Сейчас новый самолет появляется через 1-30 секунд после того как появилось сообщение об уничтожении предыдущего.

**Comment by malashin** [comment]
Вот же цикл с проверкой. Плюс внутри функции 0-180 после падения, полюс 30 секунд после сообщения. Должно быть от 30 до 1170 секунд.

https://github.com/ToxaBes/ADR-Spec-Ops/blob/master/co30_ADR_Spec_Ops.Altis/mission/main/missions/AOattack.sqf#L177

**Comment by malashin** [comment]
Хотя 30 секунд не будет, они в spawn. 0-1140 секунд.

**Comment by ToxaBes** [comment]
Ага, а ты в игре понаблюдай, kovt не просто так написал. Действительно есть проблемы со временем спавна авиации.

**Comment by malashin** [comment]
Да явно бывает больше 30 секунд. Проблема в том, что сейчас минимум слишком низкий.

**Comment by ToxaBes** [comment]
Предлагаю минимум поднять до 5 минут (300сек).

**Comment by malashin** [comment]
Надо все проблемы по авиации обсудить сейчас, чтобы разом сделать.

Многим не нравится частая перезарядка штурмовиков. Сейчас каждые 180 секунд он полный боекомплект получает. То есть он на одном заходе может отстрелят два боекомплекта ракет если ему повезет с циклом.

- Сделать нормальный респаун
- Добавить вертолеты (Придется сообщение менять о штурмовике. Если назвать 'авиация', то не понятно, будет вертолет с основы или с вышки сбит).
- Увеличить время перезарядки

**Comment by ToxaBes** [comment]
соглсаен.
Респаун: минимум 300 сек, максимум оставляем как есть
Вертолеты: добавляем все вертолеты которые могут быть на основе в качестве поддержки. Сообщение меняем просто проверкой isKinfOf "Helicopter" или isKinfOf "Plane"
Время перезарядки: увеличить в 2 раза от текущего

**Comment by Noart537** [comment]
Хелкет только не ставьте, его будут игнорить)

**Comment by ToxaBes** [comment]
Только "O_Heli_Attack_02_F" и "O_Heli_Light_02_F"

**Comment by kovt** [comment]
Ну вообще то не только я и Сундук катаем технику. И именно из за такого спавна штурма многие игроки её и не катают, так как через пару смертей от этого начинает "бомбить". Не стоит забывать что на сервере редко когда больше 7-10 человек, я могу назвать минимум четырёх из тех кто любит катать коробки. А при таком онлайне, 3-4 человека это уже большая доля игроков. Упомянутого тобой Сундука то же не один раз "бомбило" от штурма, да так что он с психами бросал игру на несколько часов, что бы банально успокоиться. )) Не забывай что ты многого не видишь так как играешь реже.  
Да сложно доехать одному, но всеми ограничениями, убер ботами и прочим мы сами отсеиваем много игроков, и получается что собственно играть то и не кому. И именно из за штурма народ и перестал ездить на броне, тем более наградной, которую жалко быстро терять.А из тех кто играет только 3-4 человека пользуются тяжёлой техникой, Все остальные играют либо медиками(потому что они всегда нужны) либо пехотными, простыми снайперами и пулемётчиками, из за того что у этих классов есть хоть какое то более менее нормальное оружие, а не долбаные МХы с которых хрен кого убьёшь.
Я сегодня брал основу в Айос-Дионисосе, расстояние до неё без малого 11 км. Ехал на наградном Т100. За всю поездку мне пришлось сбивать 8 самолётов, 6 из которых были Неофронами. И мне на этот путь понадобилось 10 ПВО установок. Я не говорю что нужно убирать их бесконечный боезапас, но можно же наверно сделать так что бы Неофрон не респился так часто и буквально через секунду после уничтожения предыдущего.

**Comment by ToxaBes** [comment]
Интервал появления штурмовика увеличим.

>долбаные МХы с которых хрен кого убьёшь.

Ты серьезно? Очень странно такое слышать от тебя. Основное оружие ботов - Katiba, которая тот же 6.5мм что и MX. Все честно. И я не верю в то что ты не можешь никого убить из MX. Давай меньше эмоций и больше конкретики.

**Comment by Horizon1959** [comment]
Штурмовик бесит и отбивает желание кататься на технике. Когда уничтожают вышку, то техника уже не нужна. Самое обидное, что ты не видишь штурмовик, а он точно видит тебя. С новой прорисовкой для пехоты в 3 КМ эта проблема встанет острее, так что надо что-то менять с этой концепцией летающего нагибатора.
В то же время, когда мы без техники, то чувствуем себя инвалидами, т.к. пехота и техника должны поддерживать друг друга. Сейчас, вместо того, чтобы пригнать бронемашину и грузовик с боеприпасами, народ просто возит стационарки и не парится. 
Вообщем предлагаю нерфить концепцию летющей всевидящей имба-машины, отдать стационарки только специалистам по ПТРК или запретить их вообще. Эти меры будут стимулировать играть за операторов ПТРК и использовать бронетехнику.
А по MX Kovt прав, от 300-от метров требуется больше 3-ёх попаданий по корпусу бойца CSAT, даже в голову не меньше двух. Для боеприпаса близкого к винтовочному 7.62 это перебор.

**Comment by Noart537** [comment]
Поменяйте красных на зеленых, они убиваются с 1-2 попаданий 6.5

**Comment by ToxaBes** [comment]
а лучше только кроликов оставить, тогда претензий по пробиваемости ни у кого не будет.

**Comment by malashin** [comment]
- Респаун 5-15 минут.
- Добавлены два вертолета CSAT.
- Перезарядка в воздухе раз в 5 минут.
- Цель появляется не ближе чем в пяти километрах от игроков, базы, основы в случайной точке карты.

**Comment by ToxaBes** [comment]
Спасибо, сейчас применю на сервер и будем тестить.
