### ISSUE TITLE
Голосовые каналы и группы

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#6]
- [x] Добавить голосовые каналы в игре
- [x] Добавить разделение по группам

**Comment by Horizon1959** [comment]
В смысле отряды, работающие через скрипт, будут иметь индивидуальные каналы или будут общаться только в зелёном между собой?

**Comment by ToxaBes** [comment]
Там все немного сложнее, часть каналов будут обычными, например групповой, транспортный, прямой (до ~10м). В них будет разрешен чат и голос. Также будет оперативный канал, он будет доступен только командирам отделений и пилотам (тоже чат+голос), экстренный канал (доступен всем, только чат), командирский канал (только командиры отделений чат+голос) и т.д. Глобальных голосовых каналов на всех игроков не будет.

**Comment by Horizon1959** [comment]
@ToxaBes круто. А с лагучестью внутриигрового голосового чата можно что-то сделать или это фича богемии?

**Comment by ToxaBes** [comment]
Лаги появляются только при большом количестве адресатов (когда получатели большинство или все игроки). Сейчас при заходе у нас игроки автоматом делятся на 3 группы (2 взвода и пилоты как в лобби разделено). После введения голосовых каналов я думаю отключить управление группами (пока размышляю над + и -) в меню действий у игроков чтобы все не сбивались в одну группу и не трещали в зеленый канал. Тогда лагов вообще не будет.

**Comment by Horizon1959** [comment]
@ToxaBes я так понимаю это концепция Task Force Radio? Сейчас группы без шестигранников практически не нужны, только разве что для разделения эфира.

**Comment by ToxaBes** [comment]
>я так понимаю это концепция Task Force Radio?

да, только без обязательного мода, носимых радиостанций вместо рюкзаков и пшш-пшш при передачах (хотя над пшш-пшш я еще думаю).

**Comment by Horizon1959** [comment]
@ToxaBes пщ-пщщ офигенная хурма. Идею понял, хорошая затея.
