### ISSUE TITLE
Не дают очки за взятие КП

### ISSUE THREAD

**Issue by 12st** [ToxaBes/ADR-Spec-Ops#60]
При взятии КП вылезает надпись взял командный пункт +10. Но в статистику их не начисляют.

**Comment by ToxaBes** [comment]
Готово к тестированию.

**Comment by 12st** [comment]
Проверил, не начисляют

**Comment by ToxaBes** [comment]
Проблема глубже чем я думал.

**Comment by ToxaBes** [comment]
Новый вариант, проверяй.

**Comment by ToxaBes** [comment]
Надо переписывать под remoteExec

**Comment by ToxaBes** [comment]
Новый вариант
