### ISSUE TITLE
Не удаляются внедорожники

### ISSUE THREAD

**Issue by 12st** [ToxaBes/ADR-Spec-Ops#61]
На доп задании не удаляются внедорожники с пулемётами. Выполнили доп задание "Прерванный     полёт", примерно через 7 минут проехали по тому месту и встретили живой внедорожник.

**Comment by ToxaBes** [comment]
Нужно проверить минут через 15. Я заметил что в последнее время арма гораздо позже выполняет команды через spawn.

**Comment by ToxaBes** [comment]
Проверил, удалились примерно через 10 мин. Если такое еще раз заметишь - сообщи пожалуйста.
