### ISSUE TITLE
Уничтожение БПЛА

### ISSUE THREAD

**Issue by kovt** [ToxaBes/ADR-Spec-Ops#63]
Второй день наблюдаем картину как вражеский штурмовик игнорирует ангар и уничтожает все БПЛА.

**Comment by ToxaBes** [comment]
Да, я тоже наблюдал эту картину. После последних обновлений штурмовик периодически видит беспилотники сквозь любое здание. Это косяк армы. Если сделать их неубиваемыми внутри ангара (пока не покинули ангар), то штурмовик будет заходить на них снова и снова игнорируя все остальное (уже пробовал). Так что пока вариантов нет.
