### ISSUE TITLE
Проблема с ТЯЗ

### ISSUE THREAD

**Issue by 12st** [ToxaBes/ADR-Spec-Ops#64]
Если активировать таймер и нанести ядерке критический урон(такой чтобы взрывалась), она "кладёт" сервер, при этом сама ядерка стоит целая и не восприимчива к любому урону,боты продолжают действовать, спустя примерно 3 минут сервер падает.

**Comment by ToxaBes** [comment]
Пофиксил )

**Comment by ToxaBes** [comment]
Баг армы. Все что делает таймер - спавнит бомбу GBU12 под ядерку по завершению отсчета. Т.е. ядерный взрыв происходит только при разрушении ядерки. Если при этом она остается целая - значит на этом моменте какая-то из подсистем движка уже отвалилась и он пошел в разнос. Чобы пофиксить это мне нужен дробовик и билет в Прагу...
