### ISSUE TITLE
Пропадают подствольные гранаты

### ISSUE THREAD

**Issue by 12st** [ToxaBes/ADR-Spec-Ops#66]
При смерти если в подствольник была заряжена граната, то при ресе она исчезнет, баг наблюдается со всеми видами гранат.

**Comment by ToxaBes** [comment]
Если у игрока осталось место в форме/разгрузке/рюкзаке - граната будет добавлена. Если все забито - то добавлять некуда. Арма не умеет сувать гранату сразу в подствольник.

**Comment by malashin** [comment]
Если гранату положить в инвентарь до того, как будет добавлено оружие, то граната загрузится в оружие сама по себе.

**Comment by ToxaBes** [comment]
Я описал ситуацию для случая когда оружие никуда не девается. Если оно исчезает при смерти то потом появляется с заряженной гранатой. Также если у тебя полностью забито все то граната исчезнет раньше чем появится оружие.
