### ISSUE TITLE
Пт ракеты на бузард 

### ISSUE THREAD

**Issue by 12st** [ToxaBes/ADR-Spec-Ops#67]
Добавить 2 пт ракеты на бузард.

**Comment by Noart537** [comment]
Проще бузард поменять

**Comment by ToxaBes** [comment]
Суть в том чтобы выяснить, есть ли смысл ставить на него ПТ ракеты или нет.

**Comment by malashin** [comment]
Если добавлять ПТ ракеты, то какие-то другие нужно убрать.

**Comment by ToxaBes** [comment]
Какие будем убирать?

**Comment by malashin** [comment]
Это вопрос к тем, кто на нём летает. Если хотите, что добавить, то будете что-то терять. Просто плодить имбовую технику смысла не вижу.

**Comment by ToxaBes** [comment]
Именно поэтому у этого тикета статус "Обсуждение" а не "Фича". Т.к. я не пилот, то хочу получить аргументированную информацию от тех кто летает стоить ли добавлять ПТ ракеты и что в этом случае убрать. Если никому это не нужно либо внятной аргументации не будет - ракеты не будут добавлены.

**Comment by malashin** [comment]
Как вариант, можно сделать на базе место в котором можно будет менять навесное вооружение.

Актуально для Хэллкэта и Буззарда. Сделать 2-3 набора. Заезжаешь в триггер, в экшн меню выбираешь нужный набор, ждешь замены оружие и улетаешь.

**Comment by Noart537** [comment]
Аналогично хотел предложить, наборы вооружения, Антон опередил =)

**Comment by ToxaBes** [comment]
Хм, интересная идея. Кто хочет заняться?

**Comment by malashin** [comment]
Я позже, думаю, возьмусь. Нужно наборы продумать.

**Хэллкэт:**
```sqf
1x 5000Rnd_762x51_Yellow_Belt
1x 24Rnd_missiles
```
```sqf
1x 2000Rnd_65x39_Belt_Tracer_Green_Splash
1x 12Rnd_PG_missiles
```

То есть стандартный набор Хэллкэта и стандартный набор Касатки. Правда с наводящимися ракетами весь шарм теряется.

**Comment by Noart537** [comment]
Например такие: 
1) Стандартный CAS (пушка, 2 ракеты в-в, 2 ракеты в-п, 2 бомбы gbu-12);
2) Стандарный AA (пушка, 4 ракеты в-в, 2 ракеты в-в);
3) CAS-1 (пушка, 4 бомбы, 2 раеты в-в);
4) CAS-2 (пушка, 4 бомбы, 2 ракеты в-з);

**Comment by ToxaBes** [comment]
Ок, пока оставлю в шестую версию, если сделаешь раньше - перенесу в пятую.

**Comment by malashin** [comment]
@Noart537 классы можешь написать, я не в самолетном вооружении не разбираюсь.

**Comment by Noart537** [comment]
Да, сейчас

**Comment by Noart537** [comment]
**Описание вооружения:**
```
Twin_Cannon_20mm		300Rnd_20mm_shells		//Пушка
missiles_SCALPEL		2Rnd_LG_scalpel			//Ракеты воздух-поверхность
missiles_ASRAAM			2Rnd_AAA_missiles		//Ракеты воздух-воздух
missiles_Zephyr			4Rnd_GAA_missiles		//Ракеты воздух-воздух (Выглядят больше чем ASTAAM)
GBU12BombLauncher		2Rnd_GBU12_LGB_MI10		//Бомбы GBU-12
//---
Bomb_04_Plane_CAS_01_F	4Rnd_Bomb_04_F			//Бомбы GBU-12 (от вайпаута)
```

**Набор штурмовой стандартный**
```
Twin_Cannon_20mm		300Rnd_20mm_shells
missiles_SCALPEL		2Rnd_LG_scalpel
missiles_ASRAAM			2Rnd_AAA_missiles
GBU12BombLauncher		2Rnd_GBU12_LGB_MI10
```
**Набор против авиации**
```
Twin_Cannon_20mm		300Rnd_20mm_shells
missiles_ASRAAM			2Rnd_AAA_missiles
missiles_Zephyr			4Rnd_GAA_missiles
```
**Набор штурмовой GBU-12x4,ASRAAMx2**
```
Twin_Cannon_20mm		300Rnd_20mm_shells
GBU12BombLauncher		2Rnd_GBU12_LGB_MI10  x 2 	//Альтернатива Bomb_04_Plane_CAS_01_F		4Rnd_Bomb_04_F
missiles_Zephyr			2Rnd_AAA_missiles
```
**Набор штурмовой GBU-12x4,SCALPELx2**
```
Twin_Cannon_20mm		300Rnd_20mm_shells
missiles_SCALPEL		2Rnd_LG_scalpel
GBU12BombLauncher		2Rnd_GBU12_LGB_MI10 x 2		//Альтернатива Bomb_04_Plane_CAS_01_F		4Rnd_Bomb_04_F
```

_Можно ещё другие варианты сделать. Это как пример._

**Comment by Noart537** [comment]
[На страничке сделаю вооружения техники, чтобы к бисам постоянно не лазить, а все вооружение в одном месте.](https://github.com/TEHGAM/ADR/wiki/%D0%92%D0%BE%D0%BE%D1%80%D1%83%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-%D1%82%D0%B5%D1%85%D0%BD%D0%B8%D0%BA%D0%B8)

**Comment by malashin** [comment]
Всё сделал. Рядом с взлёткой стоит место для перевооружения.

У Хэллкэта нет радара, поэтому наводящиеся ракеты не работают. Их ставить не стал. У появляющегося на базе Хэллкэта теперь стандартный пулемет.

----

**Hellcat**

- M134 Minigun 7.62 mm[5000]; DAR[24]
- Gatling 6.5 mm[2000]; GMG 40 mm[200]
- Gatling Cannon 20 mm[2000];

**Buzzard**

- Twin Cannon 20mm[300]; Zephyr[4]; ASRAAM[2]
- Twin Cannon 20mm[300]; Skalpel ATGM[2]; ASRAAM[2]; GBU-12[2]
- Twin Cannon 20mm[300]; ASRAAM[2]; GBU-12[4]
- Twin Cannon 20mm[300]; Skalpel ATGM[2]; GBU-12[4]
- Twin Cannon 20mm[300]; Tratnyr AP[40]; ASRAAM[2]; GBU-12[2]
- Twin Cannon 20mm[300]; Tratnyr HE[80]; ASRAAM[2]

**Comment by malashin** [comment]
Тему пока не закрываем. У меня по поводу баланса всего этого дела есть сомнения.

**Comment by Noart537** [comment]
У бузарда 6 подвесов, старался за эти рамки не выходить. Последний набор возможно стоит проверить. Выпускаются ли кучей нурсы или по одному.

**Comment by malashin** [comment]
НУРСЫ по одному выпускаться будут. Оружие одно, обойм несколько.

**Comment by malashin** [comment]
Нужно сделать, чтобы нельзя было спамить кнопку смены вооружения.

**Comment by malashin** [comment]
Поправить орфографию на маркере.

**Comment by Noart537** [comment]
Если нурсы будут выпускаться по одной ракете из 20. То наверно стоит заменить на нурсы от пауни (ОФ) ? У него они кучей выпускаются, пока зажата кнопка стрельбы. (На усмотрение администрации).

**Comment by ToxaBes** [comment]
У меня вообще ощущение складывается что из хелкета сделали имбу, если еще и бузард сможет спамить нурсами.... Предлагаю то что есть активно потестить в игре.

**Comment by malashin** [comment]
Сегодня на Хэллкэте полетал.

20 мм гатлинг бесполезный, только если пытаться им технику выносить, что для вертолета скорее всего закончится смертью. В пехоту попасть трудно.

А вот гранатомет очень понравился. Легче выносить пехоту. Патронов больше, чем обычно ракет. За счет того, что подлететь нужно близко и попасть тяжело, баланс сильно не нарушен.

**Comment by malashin** [comment]
http://commi.narod.ru/txt/shirad/191.htm

Вот гранатомет 30 мм, вешается на Ми-8 и Ми-24. В одном подвесе 300 гранат. В DCS он есть.

**Comment by ToxaBes** [comment]
Ок, урежь до 96.

**Comment by malashin** [comment]
#### Изменения в наборах (жирным шрифтом):

**Hellcat**

- M134 Minigun 7.62 mm[5000]; DAR[24]
- Gatling 6.5 mm[2000]; GMG 40 mm[**96**]
- Gatling Cannon 20 mm[**1000**];

**Buzzard**

- Twin Cannon 20mm[300]; Zephyr[4]; ASRAAM[2]
- Twin Cannon 20mm[300]; Skalpel ATGM[2]; ASRAAM[2]; GBU-12[2]
- Twin Cannon 20mm[300]; ASRAAM[2]; GBU-12[4]
- Twin Cannon 20mm[300]; Skalpel ATGM[2]; GBU-12[4]
- Twin Cannon 20mm[300]; Tratnyr AP[**20**]; ASRAAM[2]; GBU-12[2]
- Twin Cannon 20mm[300]; Tratnyr HE[**60**]; ASRAAM[2]

___

При выборе наборе другой выбрать нельзя, пока процесс полностью не будет завершен.
Переделал все скрипты починки в сервисах техники. Теперь учитывается количество повреждений, патронов, топлива. Чем больше нужно зарядить, тем больше ждать. Если ничего заряжать не надо, то ждать не нужно вообще.

**Comment by ToxaBes** [comment]
Спасибо, сегодня применю на сервер.

**Comment by Noart537** [comment]
Добавьте еще набор. 
Twin Cannon 20mm[300]; Skalpel ATGM[2]; Tratnyr HE[20]; ASRAAM[2]

**Comment by Noart537** [comment]
После смены подвесов и заезда на сервис, загружается дополнительно стандартный набор бузарда АА. Итог: 2 набора (CAS и AA)

**Comment by ToxaBes** [comment]
Пока не применяю на сервер.

**Comment by malashin** [comment]
На Хэллкэте такой проблемы не было. Буду разбираться.

**Comment by malashin** [comment]
Да и у Буззарда всё в порядке. Заряжается только установленный набор.

**Comment by malashin** [comment]
В редакторе на винде проблемы я не увидел. На сервере у Хэллкэета всё в порядке было, несколько раз перезаряжался.

**Comment by Noart537** [comment]
Попробуй такую последовательность.
1. Сесть в самолет
2. Сменить подвесы
3. Потратить бк
4. Зарядиться на сервисе

**Comment by malashin** [comment]
Потратить до нуля всё, что висит? Я частично тратил, всё работало нормально.

Мы бк востанавливаем через setVehicleAmmo, он в расчет берем текущий обвес и количество магазинов. setVehicleAmmoDef востанавливал бы патроны из стандартного конфига техники.

Плюс setVehicleAmmo должен только патроны восстанавливать, но никак не добавлять новое оружие.

**Comment by ToxaBes** [comment]
Вчера один игрок добился чтобы на буззарде было чуть ли не по 4 комплекта всего вооружения. Я так понял добился он этого комбинацией нового перевооружения и сервиса самолетов.

**Comment by ToxaBes** [comment]
какой статус по этой задаче?

**Comment by malashin** [comment]
Пока времени не было заняться. Думаю переписать перезарядку на сервисе, если пустые магазины сохраняются в технике.

**Comment by ToxaBes** [comment]
ок.

**Comment by malashin** [comment]
Тохе уже писал, другим объясню.

Мне кажется, что пока на сервере стояла первая версия скрипта в которой можно было вызвать смену оружия в то время, пока уже идущая смена оружия не завершилась и появились эти проблемы. Так как сначала патроны и оружие удаляются (причем постепенно, а не все разом), а только потом добавляются новые, можно несколько наборов было загрузить и возможно не иметь часть патронов уже загруженых. Т.к. следующий вызов команды удалил новые патроны. Потом на сервисе догрузили все патроны. 

Я это уже давно исправил и не понимал в чем проблема.

Задачу закрываю. Если снова будут такие проблемы, то пишите.
