### ISSUE TITLE
Шлемы CSAT

### ISSUE THREAD

**Issue by 12st** [ToxaBes/ADR-Spec-Ops#68]
Убрать возможность одевать шлемы CSAT т.к. очень легко спутать с противником.

**Comment by malashin** [comment]
Шлем/шляпа удаляется при одевании или перетаскивании в инвентарь.

Список запрещенных головных уборов:
```sqf
[
"H_HelmetO_ocamo",
"H_Beret_ocamo",
"H_MilCap_ocamo",
"H_HelmetLeaderO_ocamo",
"H_PilotHelmetHeli_O",
"H_HelmetCrew_O",
"H_PilotHelmetFighter_O",
"H_CrewHelmetHeli_O",
"H_HelmetSpecO_ocamo",
"H_HelmetSpecO_blk",
"H_HelmetO_oucamo",
"H_HelmetLeaderO_oucamo"
]
```

**Comment by 12st** [comment]
Конкретно вчера был этот шлем: H_HelmetO_ocamo.
Бегал тот человек с ним более 10 минут, значит он не удаляется автоматом.

**Comment by malashin** [comment]
Это сегодня только сделано было. На сервере миссия не обновлена.

**Comment by ToxaBes** [comment]
Применил, после следующей перезагрузки применится на сервер.
