### ISSUE TITLE
Криво появляющийся буззард

### ISSUE THREAD

**Issue by 12st** [ToxaBes/ADR-Spec-Ops#69]
Если уничтожить ангар в котором стоит буззард, то при следующих респавнах он просто взрывается. 
![20160515205658_1](https://cloud.githubusercontent.com/assets/18305023/15275875/d2317130-1adf-11e6-8cb4-0f7ebbee789c.jpg)

**Comment by Noart537** [comment]
Переместите его просто на бетонку, вне ангара.

**Comment by ToxaBes** [comment]
Можно просто ангар сделать неуязвимым.
