### ISSUE TITLE
Не правильные оповещения

### ISSUE THREAD

**Issue by 12st** [ToxaBes/ADR-Spec-Ops#71]
Захватили точку, началась оборона успешно завершили её, в чате написало об успешной обороне, однако появилось окошко с надписью:"Точка ___ потеряна"(заскринить не успел). После  вышло стандартное окно с надписью "удержали".

**Comment by ToxaBes** [comment]
Спасибо, разберусь.

**Comment by malashin** [comment]
Это я накосячил. В Гите исправлено.
