### ISSUE TITLE
Режим Endless Game (Altis+Tanoa)

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#74]
На базе режима End Game предлагаю сделать режим Endless Game. Примерный вариант: если игроки успешно выполняют Основу-Допку-Основу-Допку, то вместо третьей основы включается режим Endless Game. После завершения этого режима опять начинается цикл основа-допка.

**Особенность режима:** пехотные бои в городах без использования техники со стороны игроков (может быть будут квадрики).

**Место проведения:** места с большим количеством городской застройки: Кавала, Зарос, Неохори, Атира, Парос и Харкия.

**Начальные условия:** С разных сторон города будет 2 временные точки респа: для синих и для партизан. На основных базах в это время будет залочена вся техника/арсенал. Игроки будут иметь возможность ТП в новую временную базу - без оружия. На временной базе есть только ящик с оружием. Оружие: для синих - MX, для партизан - MK20. + пистолеты, прицелы ACO, гранаты/дымы/аптечки.

**Суть режима:**
1. Захватить небольшую базу удерживаемую красными. У каждой стороны будет своя база для захвата. Захват этой базы дает доступ в арсенал с небольшим количеством доп оружие, прицелов и тд.
2. Захват базы из первого этапа разблокирует задачи для той стороны стороны которая захватила базу. Задачи общие для сторон (кто быстрее). Вторая сторона должна будет захватить свою базу чтобы разблокировать те же самые задачи иначе она не сможет их выполнить (просто прибежать) и нажать кнопку не получится если не захвачена база.
   После захвата базы игроки ресаются на этой базе а не на временной точке репа.
3. Все задачи рандомно выбираются из списка задач по 3 штуки на игру. Это может быть:
   проверить разбитый коновой противника не предмет важной инфы, забрать информацию у вражеского офицера, захватить инфу с компа дома у агента, улица которого захвачена красными, захватить блокпост и тд. Небольшие миссии на пехотный бой в городе. Скачивание информации производится одним игроком и занимает 3 минуты. В это время он не может находится дальше 5м от источника инфы и должен быть живым. Количество попыток неограниченно. Т.к. задачи общие - то можно устраивать засады синие на красных или наоборот, дожидаясь пока противник зачистит миссию от красных и начнет скачивание, после чего (рпг в дом) и скачивать самим пока противник собирается/добирается заново со своей базы (просто как пример).
4. Две из трех миссий - пустышки. Третья дает информацию о скрытом терминале данных (зона небольшим радиусом помечена на карте), который нужно захватить. Вторая сторона не знает где он находится и вынуждена наблюдать куда двигается противник/где идет бой (возможно они получат на карте зону радиусом в 3 раза больше чем сторона нашедшая инфу о терминале).
5. После захвата терминала необходимо будет доставить его (будет газель) в (еще одна зона боев) и подключив к устройству (то что в качестве ядерного заряда используется) - скачать с него данные. и переслать по спутнику. Скачка/пересылка такая же как и при скачивании инфы. 
   Т.е. та сторона у которой нет терминала может делать засаду на пути у противника чтобы отбить терминал и тд. Также обе стороны могут объединится (договорившись устно) и выполнять задания совместно, затем поделив награду.
6. Награда: 
   - каждое действие игрока которое позволяет команде продвинуться дальше приносит очки (уничтожение противника/лечение своих/скачивание информации). Тут все как обычно.
   - сторона, игрок которой выполнил последний шаг получает на базе награду в виде кастомной техники - на подобие той что делали evil_Cooke и Noart (аля Mad Max). Надеюсь, они помогут с этим. Предлагайте варианты награды.
7. После завершения все игроки перемещаются на свои основные базы, перевооружаются и отправляются на основу.

**Comment by ToxaBes** [comment]
Еще как вариант награды - возможность игроку который завершил последний пункт выбрать в каком городе будет следующая основа и какая после нее будет допка или спецоперация.

**Comment by AlexVDem** [comment]
Я не совсем понял, обе стороны воюют как с красными так и друг-с-другом или только с красными кто быстрее, а других игроков даже противоположной стороны убивать нельзя?
Мне кажется, что это миссия для сервера где регулярно воюют от 30 человек и выше. Задумка интересная, но где взять столько игроков? А без них дай бог найдутся игроки, кто выполнит хоть раз Основу + Допку, а до этой миссии может и не добраться. В принципе игроков можно привлечь, если перевести всю миссию на английский, но это уже другая история.
И еще, немного сложный сценарий, игрокам трудно будет въехать во все эти перипетии сюжета (если они новички), тут гораздо более логичным было бы делать цепочку основных заданий (захватить точку 1 - затем точку 2 - затем точку 3) рядом с которыми появляются параллельные миссии. Примерно так, как это сделано на сервере EUTW, там нельзя захватить следующую точку, пока не будет взята предыдущая.

**Comment by 12st** [comment]
@AlexVDem Сервер и не позиционируется как для новичков, тем более новички не задерживаются на первом больше чем на пол часа. Такой режим действительно интересно играть большой толпой, однако стороны изначально не равноправны(у партизан будет 4-5 слотов против 25 у синих). Грубо говоря менее опытные игроки воюют против опытных потому их и меньше, баланс также будет строится исходя из этого. И ни кто не отменял возможности временно объединиться.

**Comment by ToxaBes** [comment]
> Я не совсем понял, обе стороны воюют как с красными так и друг-с-другом или только с красными кто быстрее, а других игроков даже противоположной стороны убивать нельзя?

Все против всех. При этом синие с партизанами могут устно договариваться воевать вместе против красных.

> Мне кажется, что это миссия для сервера где регулярно воюют от 30 человек и выше

Эта задумка на любое количество игроков. У нас есть игроки которую основы/допки проходят в одно лицо спокойно. Я тестил режим EndGame в одно лицо - полностью играбельно.

>немного сложный сценарий

Зоны операций помечены на карте, описание в дневнике на карте, всегда можно спросить в чат/ТС, тупым тут не рады.

>тут гораздо более логичным

Нет, вообще никакой логики в твоих словах, зачем возвращаться к TG2 (основная + побочные миссии) либо делать клон EUTW, зачем? 

Пойми меня правильно, я предлагаю обсудить **детали** этого режима, ты же начинаешь растекаться мыслью по древу на что этот режим поменять.

**Comment by Horizon1959** [comment]
@ToxaBes ты всё-таки сумел выцепить всю технологию из End Game или всё сами писать-рисовать будете?

**Comment by ToxaBes** [comment]
Нет,  максимум получится вытащить процесс скачки данных с терминала с линией которая связывает игрока с терминалом и полосой загрузки.  Остальное сами напишем.

**Comment by Horizon1959** [comment]
@ToxaBes в End Game очень хитрый арсенал. Каждому классу доступны только определённые вещи, снаряжение и оружие. Можно ли такое сделать?

**Comment by Noart537** [comment]
Можно на каждого бойца отдельные делать. Как арсенал, так и обычное снаряжение.

**Comment by Horizon1959** [comment]
@Noart537 это сложно? Можно ли сделать доступное снаряжение на каждый класс? Скоро богемия сделает доступ к любым боеприпасам в арсенале и можно будет убирать VAS. Если это не сложно, но затратно по времени, то я могу написать списки.

**Comment by Noart537** [comment]
Один из простых вариантов это проверять класс и отправлять запрашивающего к файлу со списком снаряжения для его класса. Сложность лишь в том, чтобы составить список всего снаряжения. для каждого класса оно свое будет.

**Comment by Horizon1959** [comment]
@Noart537 список я могу составить, уже имел дело с составлением снаряги для ящика с припасами. Если главный не против, то можно вынести в отдельный issue и я запилю спискоту для классов. думаю к релизу патча всё будет готово и протестировано.
Данное изменение сильно поможет игрокам, т.к. вновь прибывшие много времени теряют на изучение таблицы снаряжения и сильно удивляются, почему LRPS и медика пропадает. Если BIS запилят всё как надо, то можно будет отказаться от VAS и перейти на арсенал. игроки же будут иметь весь ассортимент доступных ништяков в арсенале.
@ToxaBes что думаешь по этому поводу?

**Comment by Noart537** [comment]
Сложнее будет делить вещи, которые будут добавляться в арсенал по мере прохождения мисии.

**Comment by Horizon1959** [comment]
@Noart537 хм, вот тут не знаю. Как-то же это происходит в End Game?

**Comment by malashin** [comment]
Сейчас видно всё оружие в арсенале, чтобы игроку было понятно, что можно в нём взять. При попытке взять запрещенный предмет, ему говориться, почему он взять его не может. Если игрок хочет этот предмет, то меняет слот.

Если же арсенал не будет отображать всё доступное стороне, то игрок подумает, что этого оружия там нет вообще и не сразу поймет зачем нужны разные классы. Плюс это решение позволяет хранить один список, вместо десятка списков.

**Comment by Horizon1959** [comment]
@malashin не раз встречал, что запрещалка срабатывает не моментально. Человек садился в машину, а потом обнаруживал пропажу прицела.
С обзором доступных предметов получается двояко: прицел в списке есть, но у тебя его отнимают. Но вот Nightstalker'а или TWS нет вообще. Про мысли игроков ну даже не знаю, хоть исследования проводи. Как правило идёт многоуровневый отбор игроков: от прицела до сложности ботов, так что я не думаю, что это сильно должно повлиять. С другой стороны игрокам придётся меньше крутить списки.

**Comment by malashin** [comment]
> С обзором доступных предметов получается двояко: прицел в списке есть, но у тебя его отнимают. Но вот Nightstalker'а или TWS нет вообще.

Nightstaker и TWS нельзя взять вообще, не зависимо от класса. Если у игрока отобрали прицел, то пишут почему и что надо сделать, чтобы можно было его взять. Двояко потому, что один прицел нельзя взять в принципе, другой можно взять определенным классом. Мы доступным способом в минимальный отрезок времени даем понять игроку, что предмет взять можно, но другим классом.

Если показывать ограниченный арсенал, то игроку придется зайти за каждый слот, чтобы понять, что Nightstalker-а нет вообще. Не понятно будет, каким классом надо заходить за какой вещью и так далее.

> не раз встречал, что запрещалка срабатывает не моментально. Человек садился в машину, а потом обнаруживал пропажу прицела.

Т.к. факт передачи предмета через арсенал нельзя отследить (через инвентарь можно, арсенал нет), цикл проверяет каждый 2 секунды есть ли у игрока запрещенные предметы, каждые 10 секунд если игрок далеко от базы. Можно эти проверки делать чаще, нагрузка на клиент возрастет. Не знаю на сколько это критично.

**Comment by AlexVDem** [comment]
> Скоро интеллектуалы из BIS сделают доступ к любым боеприпасам в арсенале и можно будет  убирать VAS
> 
но только не раньше чем бис исправят глюк с загрузкой пресетов в арсенале, ибо VAS при всей его очевидной кривизне интерфейса полезен тем, что позволяет грузить пресеты без глюков...

**Comment by Horizon1959** [comment]
@AlexVDem пресеты из арсенала грузятся прекрасно, у меня вообще никаких сбоев. Скорректируй свои наборы на сервере.

**Comment by malashin** [comment]
Пресеты не грузятся (серым цветом отмечены), если хотя бы одного предмета из пресета нет в арсенале. Поэтому их собирать нужно на данном сервере и на данной карте, так как у нас они разные для каждой карты. Если потом разработчики миссии решат убрать один из предметов, а он был в пресете, то пресет снова станет серым.

Есть мод который позволяет загружать любые пресеты и сообщает, какие из предметов он не смог загрузить, вместо полного запрета. Можно было бы его разрешить, но им единицы будут пользоваться.

**Comment by AlexVDem** [comment]
Да, я в курсе причины, из-за одного предмета не грузится весь пресет, хотя логично было бы сделать так, чтобы он грузился за исключением одного предмета. Вот это я и называю глюк, т.к. все пользователи делают пресеты на разных серверах.

**Comment by ToxaBes** [comment]
>@ToxaBes что думаешь по этому поводу?

Я за то чтобы избавится от VAS, но @malashin прав - то что есть сейчас является оптимальным компромиссом, т.к. у нас разделение по классам и нужно чтобы игрок видел оружие всех классов. Захотел другое оружие - сменил класс. Я предлагаю сначала дождаться патча, чтобы не потратить кучу времени впустую из-за того что BISы опять накосячили. Будем смотреть по факту.

>Нашел косяк сейчас. Проверка идет по базе Синих, у партизан 10 секунд всегда сейчас.

Это не косяк, насколько я помню у партизан проверяются запрещенные прицелы, т.к. в трофеях иногда попадает ящик с припасами где лежит найтсталкер. Раз в 10 сек вполне норм.

**Comment by Horizon1959** [comment]
@ToxaBes @malashin  ок, вы правы. а то будет как с компасом:)

**Comment by 12st** [comment]
> не раз встречал, что запрещалка срабатывает не моментально. Человек садился в машину, а потом обнаруживал пропажу прицела.

Народ просто не обращает внимания на эту надпись, она появляется достаточно быстро. Так что проблема в невнимательности игроков.

**Comment by ToxaBes** [comment]
БИСы так и не открыли код режима end game (ebo файлы). Без них пытаться делать возрождение и динамические зоны заданий - неблагодарное занятие. Те модули что доступны в редакторе позволяют создавать режим только если зеленая сторона обороняет зоны, а у нас красная сторона должна быть. 
Пока делал несколько заданий и композиций к ним - наигрался в этот режим до чертиков и понял что для того чтобы сделать endless game на уровне наших основ и допок уйдет просто неприличное количество времени. Итог: режим endless game вводить не будем. Награду для этого режима добавим в награду по допкам, композиции созданные для этого режима будем использовать на основном задании (разные блок-посты на дорогах и тд).
