### ISSUE TITLE
Надписи во время смерти

### ISSUE THREAD

**Issue by 12st** [ToxaBes/ADR-Spec-Ops#76]
Заменить "No medics nearly", на надпись которая будет показывать расстояние до ближнего живого игрока.

**Comment by 12st** [comment]
Если игрок находится в машине, то его не будет показывать.

**Comment by ToxaBes** [comment]
Спасибо, сегодня применю.

**Comment by 12st** [comment]
Такая вот вещь.
![20160528202104_1](https://cloud.githubusercontent.com/assets/18305023/15629008/456b4c9c-2518-11e6-9c5d-dd5731937454.jpg)

**Comment by ToxaBes** [comment]
А что, все логично )
Скоро исправлю.

**Comment by 12st** [comment]
Вчера они срабатывали странно если рядом погибал медик, после этого игроки не отображались.

**Comment by ToxaBes** [comment]
Новый вариант.
