### ISSUE TITLE
КП во время ядерного взрыва

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#79]
Т.к. ядерный взрыв не щадит ничего (даже объекты с отключенным уроном), то логично будет при разрушении КП от взрыва считать что КП "взято".

**Comment by malashin** [comment]
Если объект _terminal разрушен, то MAIN_AO_SUCCESS ?

**Comment by malashin** [comment]
Хотя если железное зданием под терминалом будет разрушено, а терминал нет, то могут быть проблемы с доступом к терминалу.

**Comment by ToxaBes** [comment]
Да, 
```sqf
MAIN_AO_SUCCESS = true; publicVariable "MAIN_AO_SUCCESS";
```

В том то и дело что сложно достать становится. Займешься?

**Comment by malashin** [comment]
А если само здание проверять, живое оно или нет?

**Comment by ToxaBes** [comment]
Я так и думал, прикрутить к зданию MP event handler "MPKilled".

**Comment by malashin** [comment]
Поставил ```addEventHandler ["Killed"``` на терминалы, вышку и железную коробку внутри купола.

**Comment by ToxaBes** [comment]
Killed - не всегда работает в мультиплеере. Используй  addMPEventHandler["MPKilled"` и в нем все тоже самое что для "Killed".

**Comment by ToxaBes** [comment]
Сам поправил. Сегодня применю на сервер.

**Comment by malashin** [comment]
MPKilled на всех клиентах будет запускаться. Все клиенты будут объявлять глобальную переменную и от каждого клиента каждому клиенту нужно будет её передавать.

> Using publicVariable too frequently in a given period of time can cause other parts of the game to experience bandwidth problems. 

Тебе нужно, либо использовать Killed на севере, либо делать проверку на то, что это сервер в MPKilled (тогда не понятно зачем он вообще нужен).

Killed уже используется при подрыве вышки и поиске тимкиллов. Никто на них не жалуется.

Вот здесь еще пропустил:
https://github.com/ToxaBes/ADR-Spec-Ops/blob/master/co30_ADR_Spec_Ops.Altis/functions/fn_addFurniture.sqf#L21
