### ISSUE TITLE
Дартер с пулеметом на основе

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#8]
В одном из зданий в бункере или около вышки с вероятностью 50% появляется собранный дартер с легким пулеметом к которому инженер может подключиться и взять управление.

**Comment by Horizon1959** [comment]
Т.е. помимо ЛЦУ у дартера будет доступен Mk200? А отдача, влияние её на полёт?

**Comment by ToxaBes** [comment]
Отдача есть, т.е. как в тире будет не пострелять с него, также он сбивается с одного попадания, а как боты стреляют ты сам знаешь... Во время стрельбы включается автопилот, т.е либо висит на месте либо летит по маршруту. Это просто приятный бонус для инженера который можно использовать в каких-то случаях, но он не дает какого-либо серьезного преимущества.

**Comment by Horizon1959** [comment]
@ToxaBes тогда круто. Уже сейчас с получением терминала весь геймплей инженера поменялся, его хоть в техника переименовывай.

**Comment by ToxaBes** [comment]
Не в бункере, а в радиусе 200м от него иначе боты его сразу уничтожают.
