### ISSUE TITLE
Таймер возрождения

### ISSUE THREAD

**Issue by 12st** [ToxaBes/ADR-Spec-Ops#80]
Таймер возрождения отсчитывает 600 секунд, но каждую 2 секунду он пропускает цифру.

**Comment by Noart537** [comment]
Скорей всего эта секунда уходит на обновление информации на экране. Надпись исчезает и появляется. Во время исчезновения, эта секунда проходит.

**Comment by 12st** [comment]
Тут дело в другом, у нас таймер 10 минут или 5?

**Comment by Noart537** [comment]
10

**Comment by ToxaBes** [comment]
Этот баг относится к тикету Надписи во время смерти #76
