### ISSUE TITLE
Бочки спецоперации "Желтый туман"

### ISSUE THREAD

**Issue by malashin** [ToxaBes/ADR-Spec-Ops#82]
Эвентхэндлер на бочках погоду показывает. Срабатывает от всего подряд, например, броска гранаты (не взрыва, а броска гранаты в другое место стоя недалеко от бочки). Далеко не на все пули срабатывает и т.д.

Нужно менять поддон бочек на одну бочку или любой другой объект и использовать HandleDamage. На этой модели он не работает.

Создай бочку в редакторе таким образом и посмотри как она работает.
```sqf
_barrel = createVehicle ["CargoNet_01_barrels_F", getPos player, [], 0, "NONE"];
_barrel addEventHandler ["EpeContactStart", {systemChat str(_this);}];
```

Нормальный вариант. Помимо нормально логики еще и учитывает накопительный урон, и можно будет стрелка узнать.
```sqf
_barrel = createVehicle ["Land_MetalBarrel_F", getPos player, [], 0, "NONE"];
_barrel addEventHandler ["HandleDamage", {systemChat str(_this);}];
```

**Comment by ToxaBes** [comment]
Ок, давай поменяем. Займись этим пожалуйста. Сделай старые бочки статичными, а новые так как написал.

**Comment by malashin** [comment]
Стрелка указывать где-то? Логи или чат?

**Comment by ToxaBes** [comment]
Достаточно сообщения в чате о том что кто-то охранник или игрок с таким-то ником пробил бочку.

**Comment by ToxaBes** [comment]
Спасибо, применил. Появится после перезагрузки сервера.
