### ISSUE TITLE
Расширенная статистика

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#83]
Предлагаю обсудить, нужно ли вообще сохранять данные?
Для этого придется найти или создать самим быстрый вариант работы с внешней БД MySQL (пока что extDB2 довольно тормозной вариант в некоторых случаях).

Сейчас мы сохраняем только базовую инфу (сколько человек на сервере каждый 5 мин): http://mon.tehgam.com/?s=1

Что можно сохранять дополнительно:
- детальную статистику по игроку, а именно сколько раз и из чего убил/был убит, самый дальний выстрел, сколько убил своих и из них был наказан и т.д.
- ваш вариант

Сразу хочу обратить внимание что игровые очки хранить между рестартами смысла не имеет, только как доп. инфу в расширенной статистике.

**Comment by malashin** [comment]
Если этим серьезно заниматься, то нужно многие игровые моменты для разных классов как-то поошрять и записывать. Инженеры чинят, медики лечат, пилоты доставляют груз и людей и т.д.

**Comment by malashin** [comment]
Я статистику люблю в любых её проявлениях, поэтому я только за.

Пугает только то, что отслеживать нужно много чего будет и постоянно отправлять на сервер, Арме это может не понравится. Самое дикое это считать меткость, нужно каждый выстрел записывать и понять попал он или нет как-то.

**Comment by Horizon1959** [comment]
Статистика это прикольно, но не будет ли она дополнительно жрать ваше время? Почему именно mySQL, а не PostgreSQL например?

**Comment by ToxaBes** [comment]
> Если этим серьезно заниматься, то нужно многие игровые моменты для разных классов как-то поошрять и записывать. 

Именно. Нужно будет продумать в деталях что будем отслеживать.

>Пугает только то, что отслеживать нужно много чего будет и постоянно отправлять на сервер

Потому я и написал что extDB тормозной для наших задач, будем скорее всего пилить свой адаптер под Linux.

>Самое дикое это считать меткость

Я не собирался считать меткость если честно. Т.к. есть пулеметчики, есть те кто кроют с вертов/самолетов. О какой меткости у них может идти речь? Я думаю в этом случая достаточно считать K/D.

>Статистика это прикольно, но не будет ли она дополнительно жрать ваше время?

К этому моменту все основные задачи по миссии будут выполнены, останется полировка и исправления багов.

>Почему именно mySQL, а не PostgreSQL например?

Потому что для наших задач достаточно mySQL и потому что я знаю его от и до. Возможно возьмем MongoDB но уж точно не postgres.

**Comment by AlexVDem** [comment]
Прежде чем делать что-то, надо понять зачем. Ну как мне кажется, это имеет смысл делать только в том случае, если на основе этой статистики давать какие то ачивки. В любом ином случае игроку будет просто любопытно взглянуть на свои достижения на сайте, но не более, и ради этого тратить драгоценное время не стоит.
С другой стороны - этот сервер не кинг оф зе хилл, а построен на совсем ином принципе разделения по классам игроков. Делать апгрейд каждого класса конечно можно, но не отпугнет ли это вновь заходящих игроков, которые заходят в надежде поиграть в крутого снайпера, а им дают МХ с открытым прицелом. 
В общем, Тоха, расскажи для чего ты это замыслил, какие финальные задумки, тогда можно и обсудить.
Предполагается ли объединение статистики всех серверов TG, или хотя бы 1-го и 2-го по аналогии со статистикой админов?

**Comment by ToxaBes** [comment]
>В общем, Тоха, расскажи для чего ты это замыслил, какие финальные задумки, тогда можно и обсудить.

Вот тут обсуждаем что будет на сайт статистики: https://github.com/ToxaBes/ADR-Spec-Ops/issues/84

А в текущем тикете чисто технические момент реализации сбора статистики.

>Делать апгрейд каждого класса конечно можно

Этого пока нет в планах. Статистику будем собирать из того что есть: K/D, очки, из чего и сколько раз убил (оружие/техника), сколько взял КП или подорвал вышек, сколько авершил спецопераций и каких и т.д.

**Comment by AlexVDem** [comment]
> Вот тут обсуждаем что будет на сайте статистики: #84. А в текущем тикете чисто технические моменты реализации сбора статистики.

> Предлагаю обсудить, нужно ли вообще сохранять данные?

Я как раз про твой начальный пост писал. Я говорю в концептуальном смысле. Мне кажется, что сохранение данных - любопытная фича, но если она не привязана к конкретному геймплею (прогресс игроков, сохранение наградной техники, игровой прогресс выполнения задания) то возникает вопрос - для чего? Т.ч. на твой вопрос нужно ли вообще данные сохранять мне пока ответ не очевиден.
Хотя как упражнение в программировании этой функции - то почему бы и нет. Твой сервер - тебе и решать.

**Comment by ToxaBes** [comment]
Для чего вообще собирается статистика? 
* чтобы удовлетворить любопытство
* чтобы видеть обратную связь, оценивать результат, осознавать прогресс

Например кто-то будет мониторить свой K/D, кто-то будет сравнивать свою стату с другими, кому-то будет вообще пофиг и тд.

>Мне кажется, что сохранение данных - любопытная фича, но если она не привязана к конкретному геймплею (прогресс игроков, сохранение наградной техники, игровой прогресс выполнения задания) 

Подрыв радиовышки, захват КП, выполнение допки/спецоперации, подрыв ядерки, захват данных и их загрузка/отправка в endless game режиме (будет внедрен до статистики) - это по твоему не привязка к конкретному геймплею?

Вообще вся эта статистика добавит/продлит интерес к игре на нашем сервере (других арма серверов с такой статой я не знаю), т.к. перезагрузка сервера перестанет обнулять все достижения.

**Comment by Horizon1959** [comment]
А можно ли будет мониторить с помощью этой статистики онлайн, процентное соотношение по странам и регионам, различные игровые действия? Например разработчики всяких онлайн игрушек часто тупо смотрят на статистику, чтобы вносить правки в баланс и контент.

**Comment by ToxaBes** [comment]
Мониторить онлайн можно и сейчас ( http://mon.tehgam.com/?s=1 ) - это тоже будет на сайте.
Страны и т.д. сейчас могут мониторить админы в админской проге. На сайт пока не вижу смысла выносить эти данные.

**Comment by Horizon1959** [comment]
@ToxaBes я имею ввиду более серьёзную статистику, типа кто и сколько играет классом, популярность предметов, время выполнения миссий и т.д.

**Comment by ToxaBes** [comment]
* кто и сколько играет классом - да
* популярность предметов - не совсем понял о чем ты
* время выполнения миссий - не имеет смысла

**Comment by Horizon1959** [comment]
@ToxaBes на основе такой статистики можно проводить изменения и следить за тенденциями. Если без неё справляетсь, то она нафиг не нужна вместе со всем писькомерством.

**Comment by ToxaBes** [comment]
Следить за тенденциями мы сможем только косвенно.

**Comment by AlexVDem** [comment]
На сервере постоянно десяток человек,  я думаю это не больше 1% всех тех, кто заходит на сервер, остальные игроки никогда не возвращаются, или заходят ещё пару раз и все. Из 1% постоянных игроков статистика нужна тоже не всем.
Если ты просил совета делать ли её или нет, то моё мнение - не стоит, лучше сосредоточиться на повышении интереса сервера для увеличения его посещаемости. Когда ежедневно будут все слоты забиты - тогда и статистика будет актуальна. Ну это моё мнение, не претендуют на истину.

**Comment by ToxaBes** [comment]
Спасибо за мнение, я как раз и создал тему чтобы собрать отзывы об идее. Пока 60/40.

**Comment by malashin** [comment]
Было бы интересно знать какую технику берут на базе игроки. Можно будет выпиливать бесполезную.

**Comment by Horizon1959** [comment]
> Было бы интересно знать какую технику берут на базе игроки. Можно будет выпиливать бесполезную.

Я про это и говорил, BIS сейчас наблюдают, кто из чего стреляет, на чём ездит.

**Comment by ToxaBes** [comment]
Тот неловкий момент когда наши мысли совпадают с тем что делают БИСы....

**Comment by Horizon1959** [comment]
@toxabes это во многих проектах, ориентированных на мультиплеер, делается.

**Comment by ToxaBes** [comment]
Сохранение данных между рестартами вынесено в отдельный тикет.
