### ISSUE TITLE
Сайт статистики

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#84]
Если мы реализуем сохранение расширенной статистики, то возникает вопрос об ее удобном выводе. Предлагаю обсудить, нужен ли нам свой сайт с расширенной статистикой, примерно так как это сделано в bf3: http://battlelog.battlefield.com/bf3/soldier/ToxaBes/stats/378008218/pc/

Т.е. мы сможем показывать кто каким оружием/техникой был убит (либо убил), сколько вышек/кп подорвал/захватил и в качестве синего либо партизана и тд и тд  (посмотрите на страницу в баттлоге и мысленно перенесите ее в реалии армы с ее оружием и техникой...). Звания можно будет ввести за очки, т.е. мы сможем показать игрокам их прогресс, а также предоставить ачивки (в виде значков на сайте), сможем сделать таблицы лидеров и прочее. 

Многие хотят статистику и я тут подумал - а почему бы и нет.

**Comment by malashin** [comment]
Та на каждого бота хочешь эвентхэндлеры вешать? Как оружие иначе узнавать? Они обычно патроны возвращают, а одинаковые патроны есть у разных стволов и техники.

**Comment by 12st** [comment]
@malashin может тогда просто выводить класс бота? Они же оружие своё не меняют.

**Comment by malashin** [comment]
В статистике батлы есть статистика самого игрока, сколько он убил каким оружием и с какой меткостью.

**Comment by 12st** [comment]
Ну это же у игрока, а не у бота. Игроков всё же меньше.

**Comment by malashin** [comment]
Чтобы узнать что игрок попал в бота, нужно проверять каждого бота на повреждения. От игрока можно только сам факт выстрела взять, но не попадание.

**Comment by 12st** [comment]
А в таком случае мы не получим в некоторых ситуациях меткость больше 100 %? Например, попаданием пп ракеты в группу ботов.

**Comment by Noart537** [comment]
Если не попал = 0, Если ранил одного или больше двух ботов, считать это 1

**Comment by Noart537** [comment]
Помнится в Бателфилде 3 был такой сайт, где можно было посмотреть статистику. Хотел вам показать, но сайт уже закрыли, т.к. уже не актуальная игра... 

Возможно это будет лишней нагрузкой на сервер, писать статистику всех игроков, 2-3 из которых зайдут пару раз посмотреть.

Но если надумайте делать, то можно такие варианты. (Я предложу идеи, а решение делать или нет, за вами. Т.к. это не всегда просто осуществить).
- Меткость стрельбы из любого оружия\техники. Меткость можно считать попал\не попал. 
- Время, которое играл определенным классом (медик, снайпер...) . (сколько поубивал этим классом, кол-во смертей). 
- Время игры и меткость в технике, смертей в технике. 
- Медикам и инженерам считать кол-во отремонтированной техники и вылеченных персонажей.
- Кол-во убитых своих.
- Кол-во смертей и от какого оружия, здесь можно брать от какого класса бота, а у каждого класса свое оружие задать.
...

**Comment by Noart537** [comment]
А вот в шапке сайт ^^ у меня чет не пускало))

**Comment by malashin** [comment]
Нужно обязательно добавить количество взорваных бочек и убитых заложников ;)

**Comment by 12st** [comment]
и подрыва ядерки :D

**Comment by Noart537** [comment]
Сколько городов было разрушено)

**Comment by 12st** [comment]
Можно пойти дальше и как в батле добавить значения ОВМ(очки в минуту) и Уб\мин. Правда в реалиях армы такое нужно выводить за час иначе у всех меньше 1 будет)

**Comment by Noart537** [comment]
Это хорошо если в пвп мини игры и нагрузки , а в постоянный ко-оп, не актуально наверно будет.

**Comment by malashin** [comment]
Мне кажется, что в реалиях Армы вся эта статистика достаточно бесполезна, особенно если она играет роль в каких-то ачивках, званиях и т.д. В игре куда важнее игроки которые вообще очков не получают, но командуют, докладывают, корректируют и т.д.

Из примитивных статов, которыми никто мериться не будет это какими классами кто играет, с каким оружием бегает, на чем ездит и т.д.

**Comment by ToxaBes** [comment]
Ок, давайте сразу отсечем то что мы не будем считать чтобы не нагружать сервер:
* не считаем меткость
* не считаем из какого оружия был убит игрок ботами
* не считаем ранения ботов, только убийства

У нас max 150 ботов + 30 игроков, это ~180 обработчиков событий "MPKilled" + суммарно до десятка событий на объектах вышка, бункер (КП). Т.е. сильно не должно повлиять, но конечно будем тестить.
Самый затык будет при ядерном взрыве, возможно придется уменьшать радиус или исключать мелкие не нужные элементы из обработки нанесения урона.

**Comment by ToxaBes** [comment]
> в реалиях Армы вся эта статистика достаточно бесполезна

Как и в батле. Дело в том что командную работу нельзя отловить скриптами.

**Comment by ToxaBes** [comment]
>Возможно это будет лишней нагрузкой на сервер, писать статистику всех игроков, 2-3 из которых зайдут пару раз посмотреть.

Статистика по игроку начнет собираться с момента открытия им возможности играть за партизан т.е. через 100 часов игры на нашем сервере. В статистике будет разделение по стати игрока за сторону синих и за сторону партизан.

**Comment by AlexVDem** [comment]
> Мне кажется, что в реалиях Армы вся эта статистика достаточно бесполезна, особенно если она играет роль в каких-то ачивках, званиях и т.д. В игре куда важнее игроки которые вообще очков не получают, но командуют, докладывают, корректируют и т.д.

Из примитивных статов, которыми никто мериться не будет это какими классами кто играет, с каким оружием бегает, на чем ездит и т.д.

Полностью согласен. Но если есть желание и свободное время - чего бы не сделать?

**Comment by ToxaBes** [comment]
У меня такое чувство что вы не утруждаете себя размышлениями по теме а сразу пишите.

>В игре куда важнее игроки которые вообще очков не получают

Да ни в одной игре никакая статистика не покажет то что ты по тимспику дал азимут/удаление на противника! Или то что ты взял попутчиков с базы и на техничке/верте довез до основы.
О чем вы вообще??? Статистика может показать то что регистрируется в самой игре и именно детали этого мы и обсуждаем.

Статистики командной работы не будет т.к. это параметр нельзя определить в игре напрямую. Только косвенно, например при хорошем командире у всех бойцов улучшится K/D, и т.д.

>Мне кажется, что в реалиях Армы вся эта статистика достаточно бесполезна

Чем она бесполезна? Тем что ты можешь отслеживать изменения своих игровых параметров?
Я прекрасно понимаю что все эти значки/ачивки и тд - это просто антураж как и в большинстве других игр и сейчас сознательно разделяю статистику и прокачку.
Статистика интересна сама по себя но помимо этого она (собранные стат данные) дает в дудущем возможность реализации прокачки: открытие стволов из другого класса либо еще какой-то вариант. Я не говорю о том чтоб у нас будет какая-то прокачка, об этом рано думать нужна или не нужна. Я пытаюсь донести что со статистикой у большинства игроков интерес к игре будет дольше чем без нее. А с системой прокачки еще больше.

Посмотрите на батлу, на танки, на еще кучу игр. Статистика удерживает игроков, статистика + прокачка еще больше удерживает игроков. Неужели это не очевидно для вас?

**Comment by ToxaBes** [comment]
Еще раз, чтобы быть понятым: я предлагаю сделать не статистику всего а "боевую" статистику с теми параметрами которые мы сможем вытащить без серьезной нагрузки на сервер.

**Comment by ToxaBes** [comment]
Основа сайта статистики готова. Детали будем обсуждать в отдельном тикете про расширенную статистику.
