### ISSUE TITLE
Сайт с информацией о миссии

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#85]
Необходимо создать сайт с информацией о миссии:
- общая информация о миссии
- описание режимов игры в миссии
- описание сторон и их особенности
- описание баз сторон (где что находится, как использовать)
- описание классов и их возможностей/ограничений
- детальное описание всех миссий с некоторыми рекомендациями (на минном поле только один!)
- описание общих возможностей (например крепление подрывных пакетов, радио каналов и тд)
- возможно какие-то описания по тактике для различных операций от наших опытных игроков?

Все это с картинками/схемами и тд. И затем добавить в игре на карту + всплывающие сообщения первые 5 мин о сайте.

Для чего это все -  во первых, для самих себя, т.к. сейчас информация передается устно в тимспике. Во вторых - если игроку нравится играть на сервере, то он хочет получить больше информации о всем выше перечисленном. Вместо того чтобы рассказывать устно каждый раз уже довольно внушительный объем инфы можно будет просто посылать на ...сайт.

Этот же сайт модет выступать платформой для последующих этапов, таких как отображение статистики.

**Comment by Noart537** [comment]
Копию на форуме не хотите сделать?

**Comment by Horizon1959** [comment]
@ToxaBes а главный не будет против? А то вроде сайт с форумом есть, а тут такие чуваки внезапно отдельное место хотят.

**Comment by ToxaBes** [comment]
>Копию на форуме не хотите сделать?

Нет смысла, к тому же форум не предназначен для того что я собираюсь сделать. Сайт будет на том же сервере что и миссия крутится т.к. это облегчит вывод статистики. В будущем, возможно добавлю на сайт второй язык и переведу все тексты что тоже на форуме нормально не сделать и тд.

>а главный не будет против? А то вроде сайт с форумом есть, а тут такие чуваки внезапно отдельное место хотят.

У команды tehgam есть как свои сервера так и сторонние дружественные которые входят в проект. Первый сервер как раз и является таким дружественным сервером и не собирается куда-либо уходить если ты об этом. Текущий форум проекта им и останется, т.е. в меню на сайте первого сервера будет ссылка на форум tehgam и на главной будет написано о том что сервер является частью проекта. Этого вполне достаточно. 

Выглядеть все это будет примерно так:
![example](https://cloud.githubusercontent.com/assets/3309152/18744632/7cf49a1e-80c7-11e6-9b75-592cf81660ee.png)

**Comment by Horizon1959** [comment]
@ToxaBes 
![not bad](https://cloud.githubusercontent.com/assets/17685328/18744743/e4b16a9c-80c7-11e6-9fef-b0748cfbfcf8.jpg)

**Comment by ToxaBes** [comment]
Чтобы окончательно прояснить: на новом сайте не будет никакого общения или обратной связи с пользователями - для этого есть форум проекта. Этот сайт исключительно wiki по миссии первого сервера.

**Comment by Horizon1959** [comment]
@ToxaBes ок, расскажу чувакам. А там именно будет система вики или просто набор статей? если надо, то могу помогать править документацию.

**Comment by ToxaBes** [comment]
Рано еще рассказывать. Технически, сайт готов (на коленке с "дизайном" на выходных сделал) но еще не заполнен инфой, сейчас подготавливаю картинки и формулирую содержание. Будет больше похоже на набор статей последовательно описывающих что это такое и как в это играть. 
После написания того как напишу - дам тебе доступ посмотришь что где забыл описать или можно описать лучше.

**Comment by Horizon1959** [comment]
@ToxaBes ок.

**Comment by ToxaBes** [comment]
Нужны 1-2 добровольца из числа опытных игроков для вычитки и дополнения информации о миссии.

**Comment by ToxaBes** [comment]
Наконец-то руки дошли закончить текст для сайта. Собрать мысли в кучу оказалось сложнее всего. Наверняка там еще есть ошибки и нестыковки, но с этим уже можно работать (если что заметите - пишите).
Добро пожаловать на https://tehgam1.com

**Comment by ToxaBes** [comment]
Я боюсь что проблема может быть с содержанием. Писал несколько дней подряд в полубессознательном состоянии, мог напутать или ошибиться. Надо будет потом на свежую голову перечитать.

**Comment by 12st** [comment]
Как раз этим занимаюсь, пока всё написано довольно хорошо.

**Comment by malashin** [comment]
Оберни таблицы с оружием в
```html
<div class="table-responsive">
  <table class="table">
    ...
  </table>
</div>
```
Сейчас при низком разрешении по горизонтали они выходят за рамки страницы.
![image](http://i.imgur.com/GZFjSfd.png)

Скролл в самом низу, правда, не очень наглядный.

На телефоне таблицы жутко выглядят.

**Comment by malashin** [comment]
Можно убрать первую ячейку с картинкой. Сейчас картинки пропадают, а ячейки нет.

```html
<th scope="row" class="hidden-xs hidden-sm"><img src="https://tehgam1.com/assets/media/weapons/protector.png" width="200" class="img-responsive no-border"></th> 
<td class="text-left hidden-xs hidden-sm">Protector 9 mm</td> 
<td class="text-left hidden-md hidden-lg" colspan="2">Protector 9 mm</td>
```

**Comment by malashin** [comment]
> Автоматическая смена карты миссии каждый день в 5:00 утра.

Стоит указать часовой пояс.

**Comment by malashin** [comment]
Косяк в таблице оружия партизан:
```html
<thead>
    <tr>
        <th colspan="2" class="center">Оружие</th>
        <th class="center">Снайпер / Инженер</th>
        <th class="center">Пулеметчик / Ракетчик ПТ</th>
        <td class="center"><strong>Медик / Инженер</strong></td>
        <td class="center"><strong>Медик / Пулеметчик</strong></td>
    </tr>
</thead>
```

Должно быть:
```html
<thead> 
    <tr> 
        <th colspan="2" class="center">Оружие</th>
        <th class="center">Снайпер / Инженер</th>
        <th class="center">Пулеметчик / Ракетчик ПТ</th>
        <th class="center">Медик / Инженер</th>
        <th class="center">Медик / Пулеметчик</th>
    </tr> 
</thead>
```

**Comment by malashin** [comment]
Строки в большинстве списков начинаются с заглавной буквы, но есть пару списков выбивающихся из общей логики. Ниже ссылки и правленый код.

https://tehgam1.com/wiki/classes/partizans

```html
<ul>
    <li><b>Ракетчик/пулеметчик</b>
        <ul>
            <li>Доступно управление ботами</li>
            <li>Доступны все пулеметы</li>
            <li>Доступны все носимые ПТ и ПВО средства</li>
        </ul>
    </li>
    <li><b>Медик/инженер</b>
        <ul>
            <li>Может поднимать павших игроков с помощью перевязочного пакета</li>
            <li>Может лечить до 100% здоровья с помощью большой аптечки</li>
            <li>Может разминировать мины/взрывчатку</li>
            <li>Может управлять БПЛА/БПА, а также взламывать беспилотники противника</li>
        </ul>
    </li>
    <li><b>Снайпер/инженер</b>
        <ul>
            <li>Доступно управление ботами</li>
            <li>Доступны все снайперские винтовки</li>
            <li>Может разминировать мины/взрывчатку</li>
            <li>Может управлять БПЛА/БПА, а также взламывать беспилотники противника</li>
        </ul>
    </li>
    <li><b>Медик/пулеметчик</b>
        <ul>
            <li>Может поднимать павших игроков с помощью перевязочного пакета</li>
            <li>Может лечить до 100% здоровья с помощью большой аптечки</li>
            <li>Доступны все пулеметы</li>
        </ul>
    </li>
</ol>
```

https://tehgam1.com/wiki/bases/regular

```html
<ul>
    <li>Основная зона возрождения - тут появляются все игроки кроме пилотов. В данной зоне есть несколько важных элементов которые будут рассмотрены ниже</li>
    <li>Посадочная площадка - место загрузки пехоты в вертолеты</li>
    <li>Техника - грузовики и MRAP/LSV различного назначения</li>
    <li>Бронетехника - место появления тяжелой техники</li>
    <li>Вертолеты - место появления различных вертолетов (рядом находится ангар с местом появления самолета)</li>
    <li>Ангар пилотов - место появления игроков класса пилот. В ангаре продублированы все элементы находящиеся на основной зоне возрождения</li>
    <li>Сервис техники - место починки всей наземной техники. В отличие от остальных сервисов техники данный сервис работает только для <span class="blue">регулярной армии</span></li>
    <li>БПЛА ангар - место появления БПЛА и БПА машин</li>
    <li>Модули - место вызова пилотами различных грузовых модулей и модулей поддержки (БК и пехотное снаряжение) для вертолетов</li>
    <li>Сервис вертолетов - место полного восстановления вертолетов включая заправку и перезарядку</li>
    <li>Сервис самолетов - место полного восстановления самолетов включая заправку и перезарядку</li>
    <li>Сервис БПЛА - место полного восстановления БПЛА включая заправку и перезарядку</li>
    <li>Перевооружение авиации - место смены типов вооружения</li>
    <li>Наградная техника - банкомат для вызова наградной техники (появится на площадке перед ним)</li>
    <li>Морская техника - станции морской и подводной техники</li>
    <li>Охрана базы - оборудованные места со стационарными пулеметами и гранатометами с ботами-операторами</li>
    <li>ПВО - место появления зенитной установки в автоматическом режиме защищающей базу</li>
    <li>Гауптвахта - большая клетка в которые отбывают наказание бойцы <span class="blue">регулярной армии</span> за различные нарушения. Принимает решение о наказании и применяет его система Аид в автоматическом режиме.</li>
</ul>
```

**Comment by malashin** [comment]
https://tehgam1.com/wiki/info/rewards

Есть смысл добавить в css:
```css
.tab-content {
  border-bottom: 1px solid #dddddd;
  border-left: 1px solid #dddddd;
  border-right: 1px solid #dddddd;
  padding: 10px;
}
```

![img](http://i.imgur.com/7mP5oiv.png)

**Comment by malashin** [comment]
https://tehgam1.com/stats
```html
<button id="show_stat" type="button" class="btn btn-default disabled">Найти</button>
```

**Comment by ToxaBes** [comment]
Спасибо, все поправил.

**Comment by malashin** [comment]
```css
.tab-content {
  border-bottom: 1px solid #dddddd;
  border-left: 1px solid #dddddd;
  border-right: 1px solid #dddddd;
  padding: 15px;
  padding-top: 0px;
}
```

Похерил таблицу, она тоже в .tab-content.

**Comment by ToxaBes** [comment]
Не понял что ты имел ввиду - этот класс добавлен в стили и таблицы выглядят нормально. Почисть кеш браузера и проверь.

**Comment by malashin** [comment]
Вот к этой таблице он тоже применился:
https://tehgam1.com/wiki/info/weapons

**Comment by ToxaBes** [comment]
Ну да, и в чем проблема? Я не фронтендщик - я смотрю на таблицу и мне кажется что все ок. Поясни пожалуйста, что с ней сейчас не так (или скриншот того что не так покажи)?

**Comment by malashin** [comment]
![img](http://i.imgur.com/nczEwdu.png)

Проблема в том, что мы и добавили.
Пад 15px и серая граница в 1px слева, сверху и снизу.

Либо вернуть всё обратно и забить на это, либо делать еще один `<div>` со своим классом внутри `.tab-content` на https://tehgam1.com/wiki/info/rewards.

**Comment by ToxaBes** [comment]
Теперь понял, спасибо.
>либо делать еще один < div > со своим классом

Так и сделал.

**Comment by kovt** [comment]
Круто выглядит, Тошан молодец. ))
Ошибочку поправь на главной странице. В последнем блоке, где об игроках.
"пилоты возят, а **команиры** - командуют." А то ошибка на главной странице, как то не комильфо ))

**Comment by ToxaBes** [comment]
Спасибо, исправил.
