### ISSUE TITLE
Повторение места основного задания

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#88]
Нужно добавить сохранение последнего места проведения основы и исключать его из выборки следующего места.

**Comment by malashin** [comment]
Есть смысл сделать то, что я говорил для наград на втором сервере.

Основа будет удаляться из списка доступных основ, после обнуления списка он полностью восстанавливается.

**Comment by ToxaBes** [comment]
Тут другая идея: использовать места которые слишком далеко либо находятся в чистом поле в два раза реже чем остальные места. Т.е. рандомно получили место основы, если она в списке основ которые должны быть реже то с 50% вероятностью мы перевыбираем место основы.
Это уже реализовано, забыл закрыть задачу.
