### ISSUE TITLE
Дозорные расчеты ПТ/ПВО

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#9]
Примерно на середине пути между базой и основой появляется один расчет ПВО и один ПТ расчет (2-4 пеха) которые патрулируют местность. Вероятность появление 50%. По завершению основы они исчезают.

**Comment by Horizon1959** [comment]
Плюсую несколько расчётов, чтобы водители/стрелки/пилоты в пути не расслаблялись, а были готовы получить ракету в бок.
