### ISSUE TITLE
Изменения по арсеналу

### ISSUE THREAD

**Issue by malashin** [ToxaBes/ADR-Spec-Ops#92]

**Comment by malashin** [comment]
@ToxaBes сейчас логика самой работы Арсенала изменилась. Теперь все шмотки добавлены только ящику в ангаре, а Арсенал с этими шмотками вызывается из ангара и на респе пехоты. То есть без ящика в ангаре Арсенал у пехов сломается.

Два одинаковых арсенала нет смысла создавать.

**Comment by Noart537** [comment]
А они не починили черный список в арсенале?

**Comment by malashin** [comment]
@Noart537 нет, у них так и задумано.

При создании арсенала с переменной true, создается полный арсенал, но сам список входящих в него объектов нигде не указан. При попытки удаления чего-то из него, удалять нечего. Если же добавлять в него свои объекты, то он будут добавляться в список и из него уже можно удалить.
