### ISSUE TITLE
Ремонтные машины

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#94]
Ремонтные хемт и бобкет не ремонтируют другую технику.

**Comment by malashin** [comment]
Может это у БИСов что-то? Они же по умолчанию должны ремонтировать.

**Comment by ToxaBes** [comment]
Возможно они что-то изменили, нам нужно разобраться в чем дело и можем ли мы это как-то починить?

**Comment by Noart537** [comment]
Добавить бобкету ауру восстановления =)

**Comment by malashin** [comment]
У меня есть подозрение, что это проблема с командой damage, о которой я раньше говорил, и у меня она почти всегда 0 показывала. Я поэтому в сервисах техники расчет урона по-другому делал.

**Comment by malashin** [comment]
Проверил сейчас, проблема именно в damage.

Если повредить технике через setDamage, то починка пойдет как надо. Если самому пострелять колеса, то чиниться они не будут, т.к. damage возвращает 0 (техника целая).

Если самим это править, то нужно свой экшн починки вешать на ремонтную технику и модули.

**Comment by ToxaBes** [comment]
Ждем патча от БИСов.
