### ISSUE TITLE
Перезарядка из контейнеров

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#96]
Нужно проверить контейнеры, т.к. игроки жалуются на то что зенитка заряжается примерно на 10%.

**Comment by malashin** [comment]
Я расчет делал на одну зарядку Сэндсторма. Зенитке, скорее всего, нужно больше патронов. В итоге сэндсторм можно будет заряжать больше.

**Comment by malashin** [comment]
Я прошлом тикете писал:

> По умолчанию в HEMTT, Замаке и модуле Хурона 10^12 патронов, в Темпесте и модуле Тару 30000 патронов.

Проверю хватает ли 30к патронов на зенитку. Если хватит, то поставлю везде по 30к, раз это значение по умолчанию.

**Comment by malashin** [comment]
30000 не хватает чтобы зарядить зенитку. Заряжает весь пулемет, дымы у командира и одну из четырех ракет.

**Comment by malashin** [comment]
Грузовики и модули с патронами полностью перезаряжают зенитку #96

**Comment by malashin** [comment]
Поставил 32 562 патронов. Хватает чтобы полностью перезарядить зенитку, включая командирские дымы.
