### ISSUE TITLE
Отключить сервисы техники рядом с текущей основой

### ISSUE THREAD

**Issue by malashin** [ToxaBes/ADR-Spec-Ops#97]

**Comment by Horizon1959** [comment]
Вот шайтаны, последние поблажки убираете!

**Comment by malashin** [comment]
На расстоянии 2.5 км от центра основы сервисы наземной техники отключаются. Те, что на базе всегда работают.

При отключении маркер сервиса техники окрашен в серый цвет. Если в него заехать в это время  напишет _"Сервис техники не работает. Регион захвачен противником."_.

**Comment by ToxaBes** [comment]
Спасибо, вечером применю.
