### ISSUE TITLE
Проблемы с БПА

### ISSUE THREAD

**Issue by 12st** [ToxaBes/ADR-Spec-Ops#98]
- [x] Инженер попадая в клетку не лишается терминала, что позволяет спокойно продолжать погром на базе(счетчик не обновляется).
- [x] БПА могут перезаряжаться на сервисе самолётов.
- [x] Через БПА можно пользоваться арсеналом(который встроен в арму).

**Comment by malashin** [comment]
Оказалось, что условия появления действий связанных с арсеналом и снаряжением не работали вообще. Они стояли в месте где указывается быстрая клавиша для вызова действия, а не в условии.

Сейчас они работают и теперь нельзя пользоваться этими действиями **из техники**, из БПА, на расстоянии выше 8 метров.

**Comment by malashin** [comment]
Сделал на всех сервисах проверку на все типы БПА. Т.к. они есть  и в Planes, и в Helicopters, и в LandVehicles.

Сообщения на сервисах теперь идут в системный чат, а не чат техники. Игрок управляющий БПА не находится в одном чате техники с БПА.

**Comment by ToxaBes** [comment]
Добавь после строки https://github.com/ToxaBes/ADR-Spec-Ops/blob/f0c43a9daab643985123a2c84a74817f081d1273/co30_ADR_Spec_Ops.Altis/scripts/%3DBTC%3D_TK_punishment/Prison.sqf#L31 :

```sqf
player connectTerminalToUAV objNull;
player unassignItem "B_UavTerminal";
player removeItem "B_UavTerminal";
```

и первый пункт готов.

**Comment by Horizon1959** [comment]
@malashin 
> Сейчас они работают и теперь нельзя пользоваться этими действиями из техники, из БПА, на расстоянии выше 8 метров. То есть теперь обязательно нужно выходить из техники.

Нельзя вообще, проверь.

**Comment by ToxaBes** [comment]
>Сообщения на сервисах теперь идут в системный чат, а не чат техники.

Вот это плохо, эти сообщения видят все игроки (включая партизан). Используй прямой канал вместо системного, тогда будет видно всем в радиусе 10-15м.

**Comment by malashin** [comment]
@Horizon1959 это перечисление. В технике нельзя, в БПА нельзя, пешком на расстояние выше 8 метров нельзя. Если нужно, чтобы в технике работало, то нужно это обсудить.

@ToxaBes сообщение в чат локально, его видит только один игрок независимо от канала.

**Comment by ToxaBes** [comment]
Нет, сообщения видят все, сейчас тестили. Все чтоидет в системный чат всегда глобально, используй чат "прямое соединение".

**Comment by Horizon1959** [comment]
@malashin нахер так жить? Как грузить машину?

**Comment by malashin** [comment]
@ToxaBes этого не может быть. systemChat повсеместно используется. Я ни разу не видел сообщений о том как другого игрока выкидывает из вертолета, как он перепакует магазины, как пилот ремонтирует технику и т.д.

> Types text to the system radio channel. This function only types text to the list, it does not broadcast the message. If you want the message to show on all computers, you have to execute it on all of them.

Единственный вариант который я вижу тут, это если в триггер починки как-то все игроки передаются.

@Horizon1959 можно вернуть технику. Этот код там годами лежал уже, просто из-за ошибки не работал.

**Comment by malashin** [comment]
Судя по всему, триггер спаунит скрипт починки на всех клиентах и передает в него технику заехавшую в триггер. Поэтому чинится только нужная техника, но сообщения в чат передаются всем. По идее вся логика скрипта обрабатывается у всех, что влияет на производительность.

Можно сделать проверку сидит ли игрок в данной технике перед спауном скрипта.

**Comment by malashin** [comment]
Арсенал теперь доступен из техники. Сервисы локально должны запускаться только у водителя.

Кстати в серсиах идет проверка на сторону WEST, при добавлении партизан это нужно будет переделать.

**Comment by Horizon1959** [comment]
@malashin уточни пожалуйста, только арсенал или ещё ящик?

**Comment by malashin** [comment]
@Horizon1959 все действия связанные со снаряжением.

**Comment by Horizon1959** [comment]
@malashin отлично, спасибо!

**Comment by ToxaBes** [comment]
>@ToxaBes этого не может быть. systemChat повсеместно используется.

Пишу еще раз, проверено вчера неоднократно на сервере множеством игроков. Меняй на прямое соединение.

**Comment by malashin** [comment]
@ToxaBes я уже написал в чем проблема.

Если думаешь, что systemChat глобален, то перепакуй магазины или сядь на место пилота. Никто не увидит этих сообщений кроме тебя.

**Comment by Horizon1959** [comment]
@malashin я понимаю, что это невероятно, но вчера ради эксперимента я сломал колесо и поехал чиниться. Сообщения о починке видели все сокомандники. Работало на нескольких сервисах.

**Comment by malashin** [comment]
Я же сказал, что сервисы работали глобально. Речь идет не о сервисах, а о systemChat. Раньше эти сообщения не видели только потому, что они шли в чат одной техники на сервисе. Если использовать любой другой чат его все будут видеть у кого к нему есть доступ.

Сейчас скрипт сервисов вызывается только у водителя техники или оператора БПА.

**Comment by ToxaBes** [comment]
А ок, теперь понял. Вечером применю на сервер, потестим.
