### ISSUE TITLE
Пункт меню "Сохранение Снаряжения"

### ISSUE THREAD

**Issue by ToxaBes** [ToxaBes/ADR-Spec-Ops#99]
У нас при наведении на ящик арсенала есть пункт меню "Сохранение снаряжения". Этот пункт еще актуален? Мне кажется он ничего полезного больше не делает и его можно убрать. @malashin , @Noart537 - что думаете?

**Comment by malashin** [comment]
Я никогда им не пользуюсь, да и VAS тоже. Поэтому сказать ничего не могу.

**Comment by Horizon1959** [comment]
Раньше он лечил пропадание оружия и прочей снаряги при возрождении. Сейчас всё работает хорошо, не думаю, что эта фигня нужна.
